### ISSUE TITLE
(Suggestion) New issue template - remove the quoted title explanations (in parentheses)

### ISSUE THREAD

**Issue by darkred** [soscripted/sox#100]
The current new issue template has an explanation below each title (in parentheses) that is in quotes `>`.
Therefore if one starts typing immediately below the quoted text (without a newline in between)
then his text will be quoted too (together with the explanation).
This IMHO makes issues hard to read (to distinguish the title from text ), as I've noticed in most of the issues.

To avoid this (and because I think most of these explanations are self-explanatory)
I'd like to make this suggestion, please: to change the new issue template from 

```
**Installed Version: 1.X.X  |  Environment: Chrome/Tampermonkey**

**Expected Behavior**
>How do you expect the feature to work?



**Actual Behavior**
>How is the feature currently behaving?



**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.



**Steps to reproduce**
>What steps did you take to reproduce the issue?
```

to

```
### Installed Version: 1.X.X  Environment: Chrome/Tampermonkey 

...

### Expected Behavior

...

### Actual Behavior

...

### SOX Errors logged to the browser console (if available)

...

### Steps to reproduce

1. First step
2. Second step
3. Third step
```

PS. Also, after that, if you have these two great userscripts installed, you may collapse headers and long code and quote blocks :
[GitHub Collapse Markdown](https://greasyfork.org/en/scripts/20974-github-collapse-markdown)
[GitHub Collapse In Comment](https://greasyfork.org/en/scripts/20973-github-collapse-in-comment)

**Comment by shu8** [comment]
@darkred nice! This new layout does seem easier on the eyes, changing it now :) thanks!
