### ISSUE TITLE
Hide Community Bulletin Module

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#101]
### Installed Version: 1.X.X  Environment: Chrome/Tampermonkey 
Note: Firefox, not Chrome

...

###  Expected Behavior
Community Bulletin module should be missing on the right side of the main page.
...

### Actual Behavior
Sometimes it's missing, most of the time it's displayed.  Sometimes it's missing immediately upon loading the page, but gets inserted within a second or two.
...

### SOX Errors logged to the browser console (if available)
```
logs scrubbed to remove personal data  -enki
```
...

### Steps to reproduce
Load main page, look on right side.

I'm assuming the WorldBuilding image is is the Community Bulletin:

![su dvi1](https://cloud.githubusercontent.com/assets/10065766/17915522/4d2be090-6979-11e6-86af-339f481ecfe7.png)

This is on v2.0.1a (1st time I checked this feature).

Just realized that what this feature is deleting is the Hot Meta Posts.

**Comment by enki-code** [comment]
The logs you posted look normal, although a bit bloated with unneeded data. 

What site is this happening on? All of them? Looks like an ad to me, and, that might not be included in the actual Community Bulletin module.

A quick way to tell whether or not it is actually part of the Community Bulletin would be to run the following code in the console and see if it disappears.

`$('#sidebar .community-bulletin').remove();`

**Comment by shu8** [comment]
@fixer1234 I don't think that is a [community bulletin](http://meta.stackexchange.com/q/234453/260841), which looks like:

![](http://i.stack.imgur.com/z6Ucj.png) and ![](http://i.stack.imgur.com/WAOl2.png)

**Comment by fixer1234** [comment]
OK, what's being hidden by the feature is Hot Meta Posts.  Looks like that's the Community Bulletin.  So the feature is working.  Nevermind.
