### ISSUE TITLE
Chat links not working properly

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#105]
### Installed Version: 1.X.X  Environment: Chrome/Tampermonkey 
2.0.1G
...

###  Expected Behavior
When I go to the menu and hover over a site, a chat link will appear. That link will take me to the chat for the respective site.
...

### Actual Behavior
When I click on the chat button for any site, it only takes me to the chat rooms of the site I'm currently on. For example, if I am currently on Physics SE, and I click the link in the menu to go to Math SE's chat, it will only show me the Physics chatrooms.
...

### Proposed solution
The chat links currently direct to chat.stackexchange.com, so you'll only see the chatrooms for the site you're on. The problem can be fixed by directing the links to https://chat.stackexchange.com/?tab=site&host=(site address), with the respective site's address.

For example, https://chat.stackexchange.com/?tab=site&host=physics.stackexchange.com would direct to Physics chatrooms.
...

**Comment by shu8** [comment]
Thanks, especially for the fix as well! ;)

The fix will be with you ASAP! :+1:

**Comment by shu8** [comment]
@IStoleThePies Sorry for the long wait, again. I've used your fix to solve this problem.

Please could you install [v2.0.1m from this link](https://github.com/soscripted/sox/raw/fix/sox.user.js) and confirm whether it has been fixed for you now? Thanks!

**Comment by IStoleThePies** [comment]
Works perfectly :)

**Comment by shu8** [comment]
@IStoleThePies Thanks for that! Will fix ASAP :)

**Comment by shu8** [comment]
@IStoleThePies also fixed in [v2.0.2 dev](https://github.com/soscripted/sox/blob/dev/sox.user.js)
