### ISSUE TITLE
SOX doesn't work when viewing the list of chatrooms

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#106]
### Installed Version: 1.X.X  Environment: Chrome/Tampermonkey 
2.0.1G
...

###  Expected Behavior
When going to chat.stackexchange.com, SOX will continue to work (mod diamonds will still appear, blog/chat/meta buttons would show up in the SE menu for each site, etc.)
...

### Actual Behavior
SOX seems to disappear on that page. Even the options button in the topbar is gone, along with all of the script's features and effects.
...

### SOX Errors logged to the browser console (if available)

...

**Comment by shu8** [comment]
@IStoleThePies Hmmm I think we disabled most of SOX on chat, however I see no reason why not to enable the blog/chat/meta buttons, but maybe not the mod diamond, because it would be unsure which site to check the meta for.. I'll also look into the cogs icon going missing, which (I think) was unintentional...

**Comment by IStoleThePies** [comment]
@shu8 Regarding the mod diamond, we could probably detect which site the user is on based on its url. As I mentioned before in my chat link issue, site chats can be specified by a longer link.

However, I'm not sure why simply going to chat.stackexchange.com only shows the chatrooms for the site the user was just on. Maybe if you guys figure out how that works, you can make the mod diamonds work the same way?

**Comment by shu8** [comment]
AFAIK there's some sort of hidden parameter (something like a 'referral' thing) that tells the site which site it's coming from.

I'll see if I can somehow get that information, and if I can then I'll look into enabling the mod diamond on chat :)

**Comment by IStoleThePies** [comment]
@shu8 Just wondering, do mod diamonds normally show up on that page for moderators? I've never been a moderator, so I'm not sure if it should actually be there.

**Comment by shu8** [comment]
@IStoleThePies lol not a clue either! neither me nor @enki-code have ever been mods... I doubt they see it on chat, but I see no problem in enabling it for SOX, *if it's possible*...

**Comment by IStoleThePies** [comment]
@shu8  Never mind, just asked a moderator. They do see mod diamonds on the chat lists, after all.

**Comment by IStoleThePies** [comment]
@shu8 Also just realized, Area 51 lacks any SE features

**Comment by shu8** [comment]
@IStoleThePies fixed in the [latest dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js) :) still broken in main chat though (#126)
