### ISSUE TITLE
Hide vote buttons on own posts

### ISSUE THREAD

**Issue by somebody1234** [soscripted/sox#107]
Note: I think `visibility: hidden` is better than `display: none` for this

**Comment by shu8** [comment]
@somebody1234 sorry for the delay in getting back to you... it's been really busy :/

Which feature are we talking about here? Do you mean the 'gray out deleted vote buttons' feature?

**Comment by geekyi** [comment]
I think this would be, when you click, the ones that show "You can't vote for your own posts!"
Right now, this includes both questions and answers posted by self

**Comment by shu8** [comment]
@geekyi that's not currently a 'feature' in SOX, I think @somebody1234 is referring to something else...?

**Comment by geekyi** [comment]
I think this is a feature request :p

**Comment by somebody1234** [comment]
@geekyi Yeah, whoops

**Comment by enki-code** [comment]
@somebody1234 So, just to be clear, you're requesting a feature that would hide any vote buttons on your own posts, correct? :+1:

**Comment by shu8** [comment]
Ahhh... That explains the confusion :P

**Comment by somebody1234** [comment]
@enki-code yeah

**Comment by enki-code** [comment]
@somebody1234 Something like this should do the trick.

```
$('.answer, .question')
    .find('.user-details:last a')
    .filter('a[href*=' + StackExchange.options.user.userId + ']')
    .closest('.question, .answer')
    .find('.votecell')
    .css('visibility', 'hidden');
```

However, I'm not a big fan of hiding the vote buttons, perhaps just completely disabling them would be better?

**Comment by somebody1234** [comment]
Yeah, that would be fine as well

**Comment by enki-code** [comment]
Alright sounds good, I will attempt at getting this implemented here shortly. I haven't been available much lately due to medical reasons, I am waiting to have back surgery and cannot sit for very long.

**Comment by enki-code** [comment]
The problem with the version I posted above, hiding the entire vote cell, it removes the post score and the ability to see vote counts. 

Here is what I've come up with instead. It unbinds the click events for *only* the vote buttons on your own posts and changes the tooltip as well to indicate that you cannot vote for your own posts.

```
$('.answer, .question')
    .find('.user-details:last a')
    .filter('a[href*=' + StackExchange.options.user.userId + ']')
    .closest('.answer, .question')
    .find('.votecell .vote a[class*="vote"]')
    .off()
    .css('cursor', 'default')
    .attr('title', 'You cannot vote on your own posts.');
```

Should be able to implement this by the weekend.

**Comment by shu8** [comment]
@somebody1234 I've added this feature [in the latest dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js) :) (it's the last one in the Appearance section)
