### ISSUE TITLE
Noticed a few bugs/minor issues

### ISSUE THREAD

**Issue by DJDavid98** [soscripted/sox#11]
- [x] **#<i></i>1** Misspelling in the **Editing** section:
   >[![][1]][1]

- [x] **#<i></i>2** The `Always show the 'Link from the web' box when uploading an image` option seems to be broken
   >[![][2]][2]

- [x] **#<i></i>3** When changing a tag's favourite/ignored/neutral status using the icon in the tag info tool tip, the highlights are reset back to the defaults (same thing happens when going to a different page, which could be related to the new navigation)
   >[![][3]][3]

- [x] **#<i></i>4** Clicking a tag name in a comment seems to do nothing despite the icon and link formatting
   >[![][4]][4]

- [x] **#<i></i>5** The `Parse titles to links cross-SE-sites` option can make posts illegible (probably should only activate when the link text is just the start of the URL itself)
   >[![][5]][5]

  [1]: http://i.stack.imgur.com/f8PpX.png
  [2]: http://i.stack.imgur.com/nx5Lb.gif
  [3]: http://i.stack.imgur.com/4sjJh.gif
  [4]: http://i.stack.imgur.com/ksDNP.gif
  [5]: http://i.imgur.com/mKQ9Ndv.gif

**Comment by shu8** [comment]
I'll work on all these over the weekend. Thanks for reposting over here @DJDavid98 :)

**Comment by shu8** [comment]
@DJDavid98 I've done 1,2,4 and 5 (as you can see ^^ ;), but no.3 seems slightly harder... it may be that I just leave that as-is if I can't find a way to fix it :/

**Comment by DJDavid98** [comment]
You could try creating a style tag somewhere on the page with `!important` rules preventing the style change by the site?

**Comment by shu8** [comment]
@DJDavid98 yeah I guess I could override the class. I'm currently trying to use a mutationobserver to detect the class being re-added so I can re-remove it...

**Comment by shu8** [comment]
@DJDavid98 done :) it's been pushed to dev.
