### ISSUE TITLE
Display comment scores for pages after the first one

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#111]
### Installed Version: 2.0.1  Environment: Chrome/Tampermonkey 
Don't know how/where to input feature requests, so posting here (please advise for future reference).  Also couldn't spot how to add the feature request tag.

---
###  Expected Behavior
Current feature appears to work as intended, but only for comments of the first page of comments in the profile

---
### Requested Behavior
I do a ton of commenting, and use them as bookmarks to go back and check updates on threads.  In cases where there have been multiple commenters and the poster isn't familiar with "@" addressing, there is no inbox notification of responses.  A common technique I use is to post a temporary comment, which the author can upvote to flag that they've seen it, and then I delete the comment.  So a useful feature would be a way to be aware of responses to comments up to at least two days old (the period I typically review old comments/threads).

Potential solution 1:
For me, two days of comments is typically four pages, six pages isn't unheard of.  One solution would be to extend the display comment scores feature to pages beyond the first (either unlimited, or up to say 6 pages, or governed by a time cutoff, like two days).

Potential solution 2:
It looks like the current comments list is 20 comments per page.  Modify the page so that up to 100 comments are displayed per (really long) page.

Potential solution 3:
This is a completely different approach, perhaps a new feature (which would supplement the comment scores, not replace them): add some form of indicator/flag on comments, maybe next to the score, that shows whether the post's author posted any comment after mine.  This wouldn't be perfect because such a comment could be a reply to someone else, but it would still be useful, even just as an indicator that the author is still responding on the post.

Potential solution 4:
Provide a way to bookmark/flag comments for later revisiting.  Even better, have a filter that can be turned on to view just the bookmarked comments, or even another screen where only the bookmarked comments are displayed.  Many SE users could benefit from a way to bookmark posts.  Currently, some people use Favorites as bookmarks, but that mixes ones you want to archive for reference with ones you just want to temporarily track for revisiting.

Actually, Solution 4 should probably be a totally separate feature request.  Solution 3 could be either a supplement to that or the comment score feature.

---
### SOX Errors logged to the browser console (if available)

---

**Comment by shu8** [comment]
@fixer1234 I think I'll implement solution 1.

Solution 4 sounds like a good idea, which could be considered in later versions. BTW, I have previously made this userscript: [Favourites Enhancer: Tag favourites and add personal notes](http://stackapps.com/q/6215/26088), which you might find useful for bookmarking posts :)

**Comment by fixer1234** [comment]
@shu8 Can't figure out why my last paragraph is shouting (no bold or heading markup).  Your Favorites Enhancer sounds pretty much like what I described.  Where have you been hiding that gem, and why isn't it in SOX?  :-)  The link appears to go to the raw script.  What's the procedure for installing it?

**Comment by shu8** [comment]
@fixer1234 click the 'raw link' at the top of the gist.

**Comment by fixer1234** [comment]
@shu8  Very nice!  I really like it!  That's solution 4, already packaged with a nice bow.

**Comment by shu8** [comment]
@fixer1234 Glad you like it! :D

**Comment by enki-code** [comment]
@fixer1234  @shu8 Can we close this?

**Comment by shu8** [comment]
@fixer1234 no, solution no,1 needs to be implemented for this issue.

**Comment by fixer1234** [comment]
@shu8 If you want to tackle solution 1, I won't complain.  :-)  I plan to check out what other goodies you're keeping hidden.  BTW, I've seen lots of posts over time of people looking for something like Favorites Enhancer.  That would be a great addition to SOX.

**Comment by shu8** [comment]
@fixer1234 solution 1 implemented in [v2.0.2 dev](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by fixer1234** [comment]
@shu8 I loaded v2.0.2dev and just started testing.  I thought this wasn't working, but it turns out it is just a little buggy.  Page 1 loads with the comment score buttons displayed.  The subsequent pages don't.  However, hitting the reload button next to the URL box in the browser displays all of the comment score buttons on the page.  This needs to be repeated on each page.  And once this has been done on subsequent pages, page 1 then works the same way.  Going back to page 1 requires reloading the page to see the comment score buttons again.  I'll leave it up to you whether you want to reopen this.  I discovered a workaround, but it might not be obvious to other users.

**Comment by shu8** [comment]
@fixer1234 hmm that's not how it's supposed to be working -- it *should* show the 'show comment score' button on all pages, even without refreshing.

Reopening this so I can look at it a bit more (next weekend!)

**Comment by shu8** [comment]
@fixer1234 fixed (again :P) in [the latest dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 Confirmed.  Looks like it's working.
