### ISSUE TITLE
Regarding blog links

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#114]
I'm not sure if this is an SOX problem, but blog links still slipped through (look near "log out"):
<img width="447" alt="screen shot 2016-10-05 at 7 19 08 pm" src="https://cloud.githubusercontent.com/assets/5375326/19135164/afaef47c-8b30-11e6-99c8-e373b216e0f4.png">

**Comment by shu8** [comment]
@IStoleThePies No, AFAIK that's SE itself which add the blog link when you're on sites with a blog. SOX isn't adding that.

**Comment by IStoleThePies** [comment]
@shu8 Huh. Now that I just figured that out, I'm thinking about the whole "removing blog links" change. I'd say if it wasn't worth the trouble of fixing them, then blog links were worth removing, but if it weren't too difficult to fix, then keeping them on certain sites would make it more like regular Stack Exchange. Your call.

**Comment by shu8** [comment]
@IStoleThePies TBH I think it's not worth the effort of maintaining this feature for the little gain...

The SE links only show up for current sites, and seeing as there are <20 (?) sites with blogs, it wouldn't be *that* useful.

I this ever pops up again in the future, I'll probably reconsider it, but till then IMHO I don't think there's any point... :/
