### ISSUE TITLE
Settings button

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#115]
This is just me being a *very* picky idiot, but I saw a small difference in the HEX colors of the gears in the settings button (#A1A1A1) and that of the regular buttons (#858c93). Also, the title of the button (which shows up when hovering over it) capitalizes "settings" in "Change SOX Settings", while the other buttons only capitalize the first word.

If you guys care enough, these might be worth changing. Otherwise, sorry for wasting your time.

**Comment by shu8** [comment]
@IStoleThePies nah! this is a perfectly valid annoyance!

I'll fix this ASAP. One question though: what do you mean about the capitalisation? I'm not sure I completely understand :/

---

Please keep posting issues like these! They look minor, but they really do help SOX get that bit better for everyone! :D

**Comment by IStoleThePies** [comment]
@shu8 For example, the title when hovering over the inbox is "Recent inbox messages", while the title for the SOX settings button is "Change SOX Settings". For consistency with the other buttons, I'd make the word "settings" lower-case, so it'd appear as "Change SOX settings".

**Comment by shu8** [comment]
Ah I see. Yeah that makes sense :). Will fix :-)

On 11 Oct 2016 9:40 p.m., "IStoleThePies" <notifications@github.com> wrote:
>
> @shu8 For example, the title when hovering over the inbox is "Recent
inbox messages", while the title for the SOX settings button is "Change SOX
Settings". For consistency with the other buttons, I'd make the word
"settings" lower-case, so it'd appear as "Change SOX settings".

**Comment by IStoleThePies** [comment]
@shu8 Also, I just spoke to a few mods. The title on the moderator button should be "Moderator inbox".

**Comment by shu8** [comment]
Right. Thanks :)

**Comment by shu8** [comment]
@IStoleThePies fixed in [v2.0.2 dev](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by IStoleThePies** [comment]
@shu8 The settings button is now a bright silver until I hover over it.

**Comment by shu8** [comment]
@IStoleThePies could you post a screenshot if possible?

**Comment by IStoleThePies** [comment]
@shu8 Yeah, here.
<img width="1440" alt="screen shot 2016-10-16 at 9 36 20 am" src="https://cloud.githubusercontent.com/assets/5375326/19417812/14a6e168-9384-11e6-9638-65f25a85119c.png">

Once I hover over the button, it becomes the correct color.

**Comment by shu8** [comment]
Hmmm weird... Thanks for that. I'll look into it a bit more in a while :)

**Comment by IStoleThePies** [comment]
@shu8 After messing around a bit, what I found to work was to remove any color you put on the button, and just add style="color: #a1a1a1;" to the SOX button element.

**Comment by shu8** [comment]
@IStoleThePies not 100% sure why that happens for you, but can you try reinstalling [with this link](https://github.com/soscripted/sox/raw/dev/sox.user.js) and see if it's fixed for you? :)

**Comment by IStoleThePies** [comment]
@shu8 Yep, seems fixed. :)
