### ISSUE TITLE
Hide certain questions

### ISSUE THREAD

**Issue by somebody1234** [soscripted/sox#119]
I'd like an option (or several) to hide on hold, closed and duplicate questions, and also deleted answers/questions (it's probably faster to turn deleted question hiding on only for users above the rep threshold)

**Comment by shu8** [comment]
I like the idea. this will be done sometime between v2.0.2 and v2.0.4 (there's a bit of a backlog atm 😞)

**Comment by somebody1234** [comment]
@shu8 Never mind, I don't have enough rep to see deleted questions on any site and didn't realize they didn't show on normal question pages (but an option to hide deleted answers posted by others would probably be helpful)

**Comment by shu8** [comment]
@somebody1234 done in [dev p](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

You can find the settings in the dialog itself. It's the last one in the Unsorted section -- just click the `>` next to the feature name. Make sure you click the small `save` underneath the checkboxes when you change the specific options -- I'm going to make the entire settings section look prettier...  soon....
