### ISSUE TITLE
Add experimental branch(es) for unfinished features

### ISSUE THREAD

**Issue by somebody1234** [soscripted/sox#12]
I think it would be nice to have an branch for each unfinished feature, as it would make it possible for others to help implement/port a feature.

**Comment by shu8** [comment]
@somebody1234 I think that's basically the dev branch -- anyone can help.

**Comment by somebody1234** [comment]
But I mean there should be an experimental branch for unfinished/currently broken features.

**Comment by enki-code** [comment]
That's not a bad idea! I would be completely okay with doing that.   @somebody1234 You work for SO, correct?

**Comment by shu8** [comment]
really!?? btw who are you on SE @somebody1234? I thought you were http://meta.stackexchange.com/users/289645/somebody... :/

**Comment by shu8** [comment]
and @somebody1234 yeah fair enough. It can be a branch where we push *our* latest versions with in-progress features. Any ideas for the branch name? `experiment`??

**Comment by enki-code** [comment]
@shu8  I think he means create a branch for **each** individual feature.

**Comment by shu8** [comment]
@enki-code ahh! ok sorry. didn't see that at first. That makes eve

**Comment by enki-code** [comment]
@shu8 There might be benefits to having separate branches, we should discuss this in chat.

**Comment by shu8** [comment]
@somebody1234 we've created a branch: https://github.com/soscripted/sox/tree/experimental. 

We'll have separate folders for each new feature so it's nice and easy to manage :)
