### ISSUE TITLE
SOX doesn't work on Area 51/Dialogs need to be positioned relatively

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#120]
I mentioned this before, but it probably deserves its own post. All the features drop dead on Area 51. SOX _does_ work on Area 51 Discussions, though.

PS: If you get SOX to work, make sure the meta button checks for new posts at discuss.area51.stackexchange.com instead of meta.area51.stackexchange.com.

**Comment by shu8** [comment]
Thanks. I forgot about that comment you'd left about this!

I'll look into this on the weekend, and see if it wouldn't be too hard to make it work with area51.

the problem with area51 is that everything's different behind-the-scenes, including the HTML markup, so it could be that I need to add extra html selectors.

I'll get back to you ASAP to tell you whether it would be too much effort to implement or not, and if not it'll hopefully be fixed for the next version :)

**Comment by shu8** [comment]
@IStoleThePies ok... I had a look at Area51, and it seems the way the StackExchange object (which we pretty much need to run SOX atm) exists is completely different (it doesn't exist, for starters)...

So, seeing as this *does* work on Area51 discussions, I'm not going to spend too much time fixing it for Area51 itself **right now**.

I'll leave this open to remind me sometime later, but I don't think it's going to be fixed anytime soon, unless it's a really easy solution I just can't see right now! :)

**Comment by somebody1234** [comment]
I have no idea how much just including `//cdn.sstatic.net/Js/stub.en.js` would help, but it would definitely add the `StackExchange` object (probably with a lot of errors) :P

**Comment by shu8** [comment]
@IStoleThePies I was wrong; the StackExchange object *does* exists, it's just really empty, and the stuff SOX wants doesn't exist. I've added a check to the dependency that broke the script and it works, in [latest dev i](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**but**, I've had to disable quite a few features because they rely on certain StackExchange objects... if you see a feature you particularly like and it doesn't seem to work, please tell me and I'll try my best to change it a bit :)

**Comment by IStoleThePies** [comment]
@shu8 Well the meta button is evidently absent :(

Also, just as an idea, maybe you can add the rep to Area 51 in the menu? Right now Area 51 Discussions shows the Area 51 rep, but not Area 51 itself. It's not an SOX problem but it shouldn't be too hard to fix.

**Comment by shu8** [comment]
@IStoleThePies what could the meta button show in area51?

also, is area51 discussions rep the same as area51 rep? (I don't know much about area51 :/)

**Comment by IStoleThePies** [comment]
@shu8 Oh, I meant the diamond stopped working on every site :P

And yeah, Area 51 Discussions rep is the same as Area 51 rep.

**Comment by shu8** [comment]
@IStoleThePies wait what...? you don't see the diamond at all?

And I'll see what I can do about area51... :)

**Comment by IStoleThePies** [comment]
@shu8 Yep

<img width="842" alt="screen shot 2016-11-03 at 1 53 36 pm" src="https://cloud.githubusercontent.com/assets/5375326/19978323/f22d6ace-a1cc-11e6-88b6-44336702e20c.png">

**Comment by shu8** [comment]
@IStoleThePies do you see anything in the console? (FN)+F12

**Comment by IStoleThePies** [comment]
@shu8 All I'm getting is:

<img width="1440" alt="screen shot 2016-11-03 at 1 55 36 pm copy 2" src="https://cloud.githubusercontent.com/assets/5375326/19978521/a524b9de-a1cd-11e6-852f-6bc8713b8475.png">

**Comment by shu8** [comment]
@IStoleThePies hmm that's weird. can you try going on another site you're registered on (that's not a meta) and see if you see it there? because I can see it... so I don't see why you shouldn't! :/

**Comment by shu8** [comment]
@IStoleThePies oh wait, never mind, it's broken for me as well :(

Fixing.

**Comment by IStoleThePies** [comment]
@shu8 Yeah, seems like tons of features are broken :/

**Comment by shu8** [comment]
@IStoleThePies yeah, told you enabling it on SE.com and Area51 would break it :P 

It's an easy fix.. I'm just trying to do what I tried to do before which broke it in a different way atm. It'll be ready in max 15 mins I hope :)

**Comment by IStoleThePies** [comment]
@shu8 Also, now that "notify on edit" works in Area 51, it is kind of squeezed together with the flag button:

<img width="777" alt="screen shot 2016-11-03 at 2 17 08 pm copy" src="https://cloud.githubusercontent.com/assets/5375326/19979362/92a83364-a1d0-11e6-86a1-3134cb87f4aa.png">

You should probably have the span tag that usually separates these buttons.

**Comment by shu8** [comment]
@IStoleThePies done! can you [reinstall please](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

**Comment by IStoleThePies** [comment]
@shu8 Could you also take a look at that picture I sent?

**Comment by shu8** [comment]
@IStoleThePies yeah, that feature doesn't actually work on Area51, so it should be disabled.

I'm working on a 'disable on area51 and se.com' flag right now... but that feature (and quite a few others) won't work on area51/se.com :(

**Comment by IStoleThePies** [comment]
@shu8 It doesn't? Are you sure it doesn't just track changes to proposals?

By the way, the notify button is a bit too far to the right on Area 51 Discussions:

<img width="357" alt="screen shot 2016-11-03 at 2 38 50 pm" src="https://cloud.githubusercontent.com/assets/5375326/19980242/aab04b06-a1d3-11e6-8737-8c7b366963e4.png">

**Comment by shu8** [comment]
@IStoleThePies nah, it can't work -- I haven't said to do that in the code!! (because it's not actually possible -- area51 doesn't have an API, and scraping the page is a bit too much effort IMO).

I'm not sure it even works on area51 discussions, but I'll have to check that -- I need to get that feature completely working first! #98 

---

Also, please reinstall [to dev version l](https://github.com/soscripted/sox/raw/dev/sox.user.js) to disable the incompatible features -- I've finally got that flag working :D

**Comment by IStoleThePies** [comment]
@shu8 The notify on edit button still appears on Area 51 proposals :/

**Comment by shu8** [comment]
@IStoleThePies hmm I'll look into it, but school's started again 😞, so it might not be till the weekend now

**Comment by IStoleThePies** [comment]
@shu8 Also, now the background image on Area 51's header is disappearing. 😕

**Comment by shu8** [comment]
Right. I'll fix it on the weekend :)

**Comment by shu8** [comment]
@IStoleThePies header issue fixed in [dev aa](https://github.com/soscripted/sox/raw/dev/sox.user.js).

I don't think it's worth the effort atm to fix the dialog issue, because it's isolated to A51 only and isn't too annoying IMHO...

**Comment by IStoleThePies** [comment]
@shu8 Now it seems the header was pushed down, making the moon a lot bigger:

<img width="1440" alt="screen shot 2016-11-27 at 10 47 09 am" src="https://cloud.githubusercontent.com/assets/5375326/20647231/1538403c-b48f-11e6-8d3e-da17a23733d7.png">

Compare without SOX:

<img width="1440" alt="screen shot 2016-11-27 at 10 46 57 am" src="https://cloud.githubusercontent.com/assets/5375326/20647232/1c7814d0-b48f-11e6-8630-74f8b3de7f1f.png">

**Comment by shu8** [comment]
@IStoleThePies hmm I'm not sure how I missed that! Should be fixed in [dev ac](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by IStoleThePies** [comment]
@shu8 Regarding the dialog thing, it seems to be happening on other sites too:

<img width="1008" alt="screen shot 2016-11-28 at 5 10 16 pm" src="https://cloud.githubusercontent.com/assets/5375326/20688162/b1b58eac-b58d-11e6-8499-fb13f8b662fe.png">

Your call if it's worth it though.

**Comment by enki-code** [comment]
The dialog positioning needs to be dynamic, we've been using hard coded positions via CSS but I've drafted up something that will position it relative to it's parent in the topbar.

**Comment by IStoleThePies** [comment]
@shu8 @enki-code Is it really necessary to make the dialogues relatively positioned? Couldn't you instead just set their absolute left positions to `$('#soxSettingsButton').position().left` and `$('#downvotedPostsEditAlertButton').position().left` for `#soxSettingsButton` and `#downvotedPostsEditAlertButton`, respectively?

**Comment by shu8** [comment]
@IStoleThePies you're right! thanks, again! :)

done in [dev al](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
