### ISSUE TITLE
Show when author was seen in "xxx ago" form

### ISSUE THREAD

**Issue by MarcinOrlowski** [soscripted/sox#122]
I'd be very useful to extend "Show when the post's author was last seen and whether they are registered in the comments section" feature to show the when author was seen in form "xxxx ago" instead of "raw" datestamp.  i.e. instead of

    	last seen: Sat, 20 Oct 2016 11:38:50 GMT | type: registered

it could be either

	last seen: 2 days ago (Sat, 20 Oct 2016 11:38:50 GMT) | type: registered

or just (perhaps configurable)

    last seen: 2 days ago | type: registered

**Comment by shu8** [comment]
@MarcinOrlowski this was my plan after doing #113, just didn't get round to it.

thanks for making a 'formal' request, and I'll try getting this done ASAP :)

**Comment by shu8** [comment]
@MarcinOrlowski I've added this feature in the [latest dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
