### ISSUE TITLE
Percentages don't show next to retracted flags

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#123]
When I have "Show flagging percentages for each type in the Flag Summary" enabled, every type of flag shows a percentage except for retracted votes:
<img width="315" alt="screen shot 2016-10-22 at 10 11 39 pm" src="https://cloud.githubusercontent.com/assets/5375326/19623731/c81ff070-98a4-11e6-8ebd-c057c2240dde.png">
As you can see, retracted votes are still considered into the percentages, but they don't show any numbers.

**Comment by enki-code** [comment]
I've never seen a retracted flag or even knew that was possible, thus, no percentages available.

Should be a fairly easy fix, however, you might have to help with the testing.

I have back surgery in 7 days, I will do my best to get to it before then.

**Comment by fixer1234** [comment]
@IStoleThePies I also wasn't aware that flag retraction was possible.  Do you have any idea how to accomplish that?

**Comment by IStoleThePies** [comment]
@fixer1234 Retracted flags appear if you flag an answer, and then try to unflag it. You can undo every type of flag except comment flags.

**Comment by shu8** [comment]
@IStoleThePies @enki-code This should be fixed in the [latest DEV version](https://github.com/soscripted/sox/raw/dev/sox.user.js).

I just added `RETRACTED: 'retracted'` to the:

```
             var type = {
                TOTAL: 'flags',
                WAITING: 'waiting',
                HELPFUL: 'helpful',
                DECLINED: 'declined',
                DISPUTED: 'disputed',
                AGEDAWAY: 'aged away',
                RETRACTED: 'retracted' //added this
            };
```

which should have fixed it, unless I overlooked something... so please confirm it works @IStoleThePies

**Comment by IStoleThePies** [comment]
@shu8 Works perfectly! 👍

**Comment by enki-code** [comment]
I apologize, I should've got this done.  I haven't been able to spend much time at the computer lately.

Thanks @shu8 for getting this done.
