### ISSUE TITLE
Whack-a-mole settings in SOX setup

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#131]
### Installed Version: 2.0.2DevC  Environment: Firefox/Greasemonkey 

---
###  Expected Behavior
Hover or click on "i" for additional information

---
### Actual Behavior
Hovering anywhere on a setting inserts information.  This makes trying to click on selection boxes a Whack-a-mole game.  Clicking on a selection inserts one or more lines of information, relocating the next item.  Moving to the next item removes the previous item's information, so the item isn't at the same location when you get there.  On the way back to where the item now is, passing another setting moves things again.  The items are constantly moving around, making it a challenge to go through the extensive features list.

For users who are already familiar with the features, this can make you seasick, and for testing a lot of new versions, it takes significant time to remove the old version, restart the browser, load the new version, get the token, go through the settings, and reload all of the pages.

Suggest limiting the help display to hovering on or clicking just the "i".

---
### SOX Errors logged to the browser console (if available)

---

**Comment by shu8** [comment]
Fair enough. I'll make it so it only appears when you hover over the i sign

**Comment by shu8** [comment]
@fixer1234 done in [latest dev version f](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by fixer1234** [comment]
@shu8 Nice.  No more need for Dramamine.  Works good.  :-)
