### ISSUE TITLE
Find&Replace/Autocorrect added repetitively to Your Answer edit window

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#133]
### Installed Version: 2.0.2 Dev G  Environment: Firefox/Greasemonkey 

---
###  Expected Behavior
Previously working.

---
### Actual Behavior
Question and answer posts appear normal (haven't checked the review queue).  However, every time a Q or A post edit window is opened, the Find&Replace/Autocorrect buttons are added again to the Your Answer edit window:

After editing the Question:

![su edit window](https://cloud.githubusercontent.com/assets/10065766/19917156/fbe0e398-a096-11e6-91d1-42d8c924bbe6.png)

Then after opening the edit window on the question and an answer to verify the appearance:

![su edit window1](https://cloud.githubusercontent.com/assets/10065766/19917218/9e6fb418-a097-11e6-9c88-a516241afedf.png)

The extra buttons disappear when the page is refreshed.

---
### SOX Errors logged to the browser console (if available)
I'm assuming this will be some obvious code bug, but I'll capture console output if you need it.

What the heck.  I had the console open on the same thread as #134 so I cleared it, opened an edit window on the question, and grabbed what transpired while adding an extra set of buttons on Your Answer.  Not sure if you're logging anything useful for this issue.

```
SOX:  observe: #wmd-redo-button-1141420 sox.common.js:8:13
GET 
http://superuser.com/content/img/progress-dots.gif [HTTP/1.1 304 Not Modified 37ms]
GET 
XHR 
http://superuser.com/posts/1141420/edit-inline [HTTP/1.1 200 OK 42ms]
SOX:  fire: #wmd-redo-button-1141420 sox.common.js:8:13
SOX:  fire: li[id^="wmd-redo-button"] sox.common.js:8:13
SOX:  fire: li[id^="wmd-redo-button"], textarea[id^="wmd-input"] sox.common.js:8:13
SOX:  fire: [id^="wmd-redo-button"] sox.common.js:8:13
SOX:  fire: #wmd-redo-button-1141420 sox.common.js:8:13
GET 
http://cdn.sstatic.net/Js/tageditornew.en.js [HTTP/1.1 200 OK 0ms]
GET 
XHR 
http://superuser.com/api/tags/langdiv [HTTP/1.1 200 OK 31ms]
POST 
XHR 
http://superuser.com/posts/validate-body [HTTP/1.1 200 OK 29ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
```
---

**Comment by shu8** [comment]
Fixed in [latest dev h](https://github.com/soscripted/sox/raw/dev/sox.user.js)
