### ISSUE TITLE
Animated meta and chat buttons

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#135]
I wrote a little something to try and make the meta and chat buttons fancier:

       metaChatBlogStackExchangeButton: function() {
            // Description: For adding buttons next to sites under the StackExchange button that lead to that site's meta and chat
            // NOTE: this feature used to have a 'blog' button as well, but it wasn't very useful so was removed

            var link, chatLink;

            $(document).on('mouseenter', '#your-communities-section > ul > li > a', function() {
                var href = $(this).attr('href');
                chatLink = 'http://chat.stackexchange.com?tab=site&host=' + href.substr(2);

                if (href.indexOf('stackapps') > -1) {
                    link = undefined;
                } else if (href.indexOf('area51') > -1 && href.indexOf('discuss.area51') === -1) {
                    link = 'http://discuss.area51.stackexchange.com/';
                } else if (href.indexOf('meta.stackexchange.com') > -1) {
                    link = undefined;
                    chatLink = 'http://chat.meta.stackexchange.com';
                } else if (href.indexOf('meta') > -1 || href.indexOf('discuss.area51') > -1) {
                    link = undefined;
                    chatLink = undefined;
                } else {
                    link = 'http://meta.' + href.substr(2, href.length - 1);
                }

                if (href.indexOf('stackoverflow.com') > -1 && href.indexOf('meta') === -1) {
                    chatLink = 'http://chat.stackoverflow.com?tab=site';
                }
                if (link || chatLink) { //only hide rep if we're actually going to add anything
                    $(this).find('.rep-score').stop(true).delay(135).fadeOut(20);
                    $(this).prepend('<div class="related-links" style="float: right; display: none;">' +
                        (link ? '<a href="' + link + '">meta</a>' : '') +
                        (chatLink ? '<a href="' + chatLink + '">chat</a>' : '') +
                        '</div>');
                    $(this).find('.related-links').delay(135).css({opacity: 0}).animate({opacity: 1, width: 'toggle'}, 200);
                }
            }).on('mouseleave', '#your-communities-section > ul > li > a', function() {
                $(this).find('.rep-score').stop(true).fadeIn(110);
                $(this).find('.related-links').remove();
            });
        }

It's a bit unclean, but tell me if you think this is a good idea. :)

**Comment by shu8** [comment]
@IStoleThePies I like the effect! I'll get this added in the next dev version :)

**Comment by shu8** [comment]
I've added this in [latest dev h](https://github.com/soscripted/sox/raw/dev/sox.user.js), keeping the opacity changes. 

But if they aren't needed then we could remove them :)

**Comment by IStoleThePies** [comment]
@shu8 I actually wanted to have the buttons fade into the rep score, kind of like when you hover over other SE sites on a profile:

![untitled-1](https://cloud.githubusercontent.com/assets/5375326/19979816/2d56ad36-a1d2-11e6-930e-d03865aa6407.gif)

This works very differently and doesn't append anything, but I was trying to replicate the effect overall. But since the buttons and rep score have relative positions, I wasn't really able to work with that, so this is the closest thing I could do in the time I had.

**Comment by shu8** [comment]
hmm I'll see if I can manage to make that effect :)

**Comment by shu8** [comment]
@IStoleThePies SE use this:

```
.sidebar-element .list li:hover .rep-and-badges.rep-hover {
    right: 0;
    opacity: 1;
    width: auto;
    transition: right .1s ease,opacity .3s ease,width .3s linear
}
```

with this HTML:

```
<span class="rep-and-badges rep-hover">
     <span class="reputation-score" title="1,234 reputation">1.2k</span>
     <span title="5 silver badges"><span class="badge2"></span><span class="badgecount">5</span></span>
     <span title="21 bronze badges"><span class="badge3"></span><span class="badgecount">21</span></span>
</span>
```

so we *should* be able to tweak that a bit to get the same effect.

**Comment by IStoleThePies** [comment]
@shu8 You'd probably need to give the meta and chat buttons absolute positions, which I didn't have the energy to go through.
