### ISSUE TITLE
SOX doesn't work on regular Stack Exchange

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#136]
SOX drops dead on https://stackexchange.com/, so it won't work when viewing network profiles, checking the front page, checking the full inbox, etc.

It does work on https://meta.stackexchange.com/, though.

**Comment by shu8** [comment]
@IStoleThePies Seems to be another Area51-like problem: the StackExchange object :/

I'll see what I can do... :)

**Comment by shu8** [comment]
Fixed in [latest dev version i](https://github.com/soscripted/sox/raw/dev/sox.user.js).

I'm pretty sure more bugs are going to arise on SE.com now, so please tell me if something dodgy happens... :)

**Comment by IStoleThePies** [comment]
@shu8 Yeah, I found a bug when opening the SOX settings

<img width="1027" alt="screen shot 2016-11-03 at 1 42 53 pm" src="https://cloud.githubusercontent.com/assets/5375326/19977910/9a090b1a-a1cb-11e6-9fc4-e82653ca6664.png">

**Comment by shu8** [comment]
@IStoleThePies lol, just noticed that as well; fixing as we 'speak' :P

**Comment by shu8** [comment]
@IStoleThePies fixed :)
