### ISSUE TITLE
Searching for options is pretty buggy in dev g

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#137]
If you try searching for an option, you'll probably encounter something like this:
<img width="552" alt="screen shot 2016-11-02 at 8 36 47 pm" src="https://cloud.githubusercontent.com/assets/5375326/19952496/33e8e42a-a13c-11e6-9d9e-79ecbce03754.png">

**Comment by shu8** [comment]
@IStoleThePies lol I noticed this yesterday and hoped I would push a fix before anyone noticed... :P

**Comment by shu8** [comment]
Fixed in [latest dev h](https://github.com/soscripted/sox/raw/dev/sox.user.js)
