### ISSUE TITLE
Edited Posts menu doesn't shift when the mod diamond is enabled

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#138]
Here's the "Edited Posts" menu when the mod diamond is disabled:

<img width="737" alt="screen shot 2016-11-03 at 2 51 08 pm" src="https://cloud.githubusercontent.com/assets/5375326/19980769/b217b6ac-a1d5-11e6-81d6-a0fccd68a7c5.png">

And here's it with the mod diamond enabled:

<img width="737" alt="screen shot 2016-11-03 at 2 51 08 pm copy" src="https://cloud.githubusercontent.com/assets/5375326/19980773/b8bb6256-a1d5-11e6-9dcc-8aaaaf440b58.png">

You can see that the icon for the Edited Posts menu moves, but the left side doesn't line up with the left end of the box anymore.

**Comment by shu8** [comment]
repro'ed. not going to be as easy a fix as I would have liked, but should be doable :)

**Comment by shu8** [comment]
@IStoleThePies fixed in [dev o](https://github.com/soscripted/sox/raw/dev/sox.user.js)... it was as easy as I thought it originally would be :P
