### ISSUE TITLE
Edited posts menu opens whenever you view a list of chatrooms

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#139]
When I go to any lists of chatrooms (chat.stackexchange.com, chat.stackoverflow.com, etc.), the edited posts menu opens up for some reason.

**Comment by shu8** [comment]
@IStoleThePies fixed in [dev o](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 Didn't realize this had already be reported.  I can confirm that it is fixed in Dev P.
