### ISSUE TITLE
Show comment score added twice on subsequent pages

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#143]
### Installed Version: 2.0.2 Dev P Environment: Firefox/Greasemonkey 

---
###  Expected Behavior
Previously working properly.

---
### Actual Behavior
The Show comment score prompt is added properly to the first page of comments.  On subsequent pages, the prompt appears twice in succession on each comment:

![su 2x comment](https://cloud.githubusercontent.com/assets/10065766/20122298/bca0c9fc-a5e4-11e6-81ab-53349aae72e9.png)

Both buttons are operational.  After viewing subsequent pages of comments, selecting the first page exhibits the double buttons there, also.

Refreshing any page showing the double button clears the issue and shows a single button.

---
### SOX Errors logged to the browser console (if available)
Let me know if console output would be useful.

---
### Steps to reproduce
Open the comments history page in the user profile.  At the bottom, select page 2 (or any subsequent page).

**Comment by shu8** [comment]
@fixer1234 fixed in latest [dev version q](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 Looks like you fixed it.
