### ISSUE TITLE
Topbar bugs in Stack Exchange Data Explorer

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#145]
If you go to data.stackexchange.com and wait a few seconds, you'll notice there are multiple logos in the top bar. A closer inspection revealed this:

<img width="1440" alt="screen shot 2016-11-15 at 1 47 26 am" src="https://cloud.githubusercontent.com/assets/5375326/20295841/7f1379f4-aad5-11e6-9e4b-3336f5c54f6c.png">

The second logo and the space between the two logos replace the SOX buttons, like the settings button and "notify on edit" button.

**Comment by shu8** [comment]
@IStoleThePies hmm I can't repro what you're saying, but instead I just see no cogs at all (which is still a bug)

Did SOX not auto-add your environment and enabled features?? If they didn't, could you try creating a new one and pasting the details into this issue (rather than creating a new one)?

**Comment by IStoleThePies** [comment]
@shu8 Yeah, here:

### Installed Version: 2.0.2DEVp  Environment: Tampermonkey 

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-betterCSS","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-grayOutVotes","Appearance-hideHireMe","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Appearance-disableOwnPostVoteButtons","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Flags-flagOutcomeTime","Flags-flagPercentages","Unsorted-downvotedPostsEditAlert","Unsorted-parseCrossSiteLinks","Unsorted-replyToOwnChatMessages"]

**Comment by shu8** [comment]
thanks! That should help me find the problem :) I'll be looking at this as
well on the weekend.

**Comment by shu8** [comment]
@IStoleThePies This should be fixed in [dev x](https://github.com/soscripted/sox/raw/dev/sox.user.js). Although I've treated this site just like I did with A51 -- most features are disabled, and you probably won't see much of SOX working on it...

Please can you confirm whether it is actually fixed? :)

**Comment by IStoleThePies** [comment]
@shu8 Now I get this:

<img width="1440" alt="screen shot 2016-11-19 at 7 49 30 pm" src="https://cloud.githubusercontent.com/assets/5375326/20459498/551ba86e-ae91-11e6-8b24-4f4869ac8bc4.png">

**Comment by enki-code** [comment]
@IStoleThePies I believe it was originally, we just need to add it back into the excludes of the userscript itself. Easy fix. :+1:

**Comment by shu8** [comment]
@IStoleThePies @enki-code disabled on data.SE in [dev y](https://github.com/soscripted/sox/raw/dev/sox.user.js)
