### ISSUE TITLE
Fixed topbar feature messes with sites with designs at the top

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#146]
If you go to worldbuilding.stackexchange.com, you'll probably see the the image on the bottom of the page overlapping the image on the top of the page.

<img width="1440" alt="screen shot 2016-11-15 at 1 39 59 am" src="https://cloud.githubusercontent.com/assets/5375326/20323392/7d962a70-ab4a-11e6-8fdf-fa9997948ac7.png">

This happens on any page, including meta pages. Disabling SOX entirely fixes the problem.

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-betterCSS","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-grayOutVotes","Appearance-hideHireMe","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Appearance-disableOwnPostVoteButtons","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Flags-flagOutcomeTime","Flags-flagPercentages","Unsorted-downvotedPostsEditAlert","Unsorted-parseCrossSiteLinks","Unsorted-replyToOwnChatMessages"]

**Comment by shu8** [comment]
I'm beginning to hate the fixed topbar feature... 😢 

I'll look at this on the weekend, because I don't think I'll have any time this week :(

**Comment by shu8** [comment]
@IStoleThePies Fixed in [latest dev t](https://github.com/soscripted/sox/raw/dev/sox.user.js)

But, this will almost definitely have broken it on another site, because I got rid of a CSS rule which I can't remember why it was there, so if you notice being weird on any other site, please comment back here! :)

**Comment by IStoleThePies** [comment]
@shu8 Also strangely, the logo and upper parts of the Worldbuilding site seem to jump up after SOX loads.

**Comment by shu8** [comment]
Yeah I just noticed that after I pushed it. I'll try fix it by the next
version

**Comment by shu8** [comment]
@IStoleThePies Seems like a complicated issue, and I'm *really* bad with CSS -- @enki-code's the expert in that :P So I think we'll need to wait for him to be back to get this one fixed :(

Sorry!

**Comment by IStoleThePies** [comment]
@shu8 Yeah, just realized it happens with lots of sites. In beta sites it cuts off the blue part of the header.

**Comment by shu8** [comment]
@IStoleThePies @enki-code had a look at it and worked out a fix. Done in [dev v](https://github.com/soscripted/sox/raw/dev/sox.user.js)
