### ISSUE TITLE
Replying to comments

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#147]
If I go into the comment section and hit reply, it brings up the name of the user in the comment. However, if I remove that name (or make any modifications to my comment, for that matter), the reply buttons will no longer work. I can't even reply to other comments.

![untitled-1](https://cloud.githubusercontent.com/assets/5375326/20458140/1d0ea8da-ae6a-11e6-8dbf-42485c249058.gif)

Also, clicking the reply button multiple times on different comments (if I don't type anything into the comment box) will put down multiple names:

![untitled-2](https://cloud.githubusercontent.com/assets/5375326/20458151/b4899468-ae6a-11e6-80ff-886591dd21ea.gif)

Since SE doesn't allow replies to multiple users (if you try to send it, it won't work and will warn you), could you make it so that clicking the reply button multiple times will just change the person you are sending it to, like in the chat:

![untitled-4](https://cloud.githubusercontent.com/assets/5375326/20458158/121867f8-ae6b-11e6-8f1b-8983f5fe3430.gif)

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-betterCSS","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-grayOutVotes","Appearance-hideHireMe","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Appearance-disableOwnPostVoteButtons","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Flags-flagOutcomeTime","Flags-flagPercentages","Unsorted-downvotedPostsEditAlert","Unsorted-parseCrossSiteLinks","Unsorted-replyToOwnChatMessages"]

**Comment by shu8** [comment]
@IStoleThePies bug fixed and feature added in [latest dev u](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

**Comment by IStoleThePies** [comment]
@shu8 The feature request wasn't entirely put in. :/

I can't click multiple reply buttons, which means I have to completely erase the user if I want to change who I'm replying to. The gif of the chat should help if what I'm saying isn't clear.

**Comment by shu8** [comment]
@IStoleThePies whoops! Sorry, I've added what you've actually said now in [dev w](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by IStoleThePies** [comment]
@shu8 Works now 👍
