### ISSUE TITLE
Mod Election UI breaks with the sticky header.

### ISSUE THREAD

**Issue by calebkleveter** [soscripted/sox#150]
### Installed Version: 1.X.X  Environment: Chrome/Tampermonkey 

TamperMonkey: 4.1.10
SOX: 1.0.3
Google Chrome: 54.0.2840.98 (64-bit)
OS X 10.11.6

---
###  Expected Behavior

I should be able to see the '1st choice' label above the Mod candidate that I have for my first choice.

---
### Actual Behavior

Sticky header hides the label:

[![enter image description here][1]][1]

---
### SOX Errors logged to the browser console (if available)

Nothing

---
### Steps to reproduce

Go the [election page](http://stackoverflow.com/election) and vote for the candidates of your choice, scroll down the page and the label is hidden.

  [1]: https://i.stack.imgur.com/IxN4y.png

**Comment by shu8** [comment]
Thanks for the bug report! I'm sorry but I don't have time to actually push a fix until the weekend :(

I'll get it fixed ASAP!
Note to self: Adding `.module#vote-picks { margin-top: 35px}` fixes it -- just need to find time to edit the files and push them!

**Comment by shu8** [comment]
@calebkleveter fixed in [dev aa](https://github.com/soscripted/sox/raw/dev/sox.user.js). I realise the election is over now, so sorry for not getting it fixed sooner! :/
