### ISSUE TITLE
Notify on edit acts a bit weird on the tour

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#151]
### Installed Version: 2.0.2DEVy  Environment: Tampermonkey 

---

On a site [tour](https://astronomy.stackexchange.com/tour), the "notify on edit" button actually appears in the "Improve posts by editing or commenting" section. Oddly, clicking it won't allow you to unclick it, and it doesn't actually notify you about updates (see [here](https://astronomy.stackexchange.com/questions/18039/is-the-sun-visible-from-proxima-centauri-to-human-eyes/18054#18054) for example).

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-betterCSS","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-grayOutVotes","Appearance-hideHireMe","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Appearance-disableOwnPostVoteButtons","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Flags-flagOutcomeTime","Flags-flagPercentages","Unsorted-downvotedPostsEditAlert","Unsorted-parseCrossSiteLinks","Unsorted-replyToOwnChatMessages"]

**Comment by shu8** [comment]
@IStoleThePies fixed in [dev aa](https://github.com/soscripted/sox/raw/dev/sox.user.js) -- it won't show up on the tour anymore.
