### ISSUE TITLE
Helpful flag percentage bar in addition to percentage break-down

### ISSUE THREAD

**Issue by calebkleveter** [soscripted/sox#155]
A while back, @enki-code posted a [question](http://meta.stackoverflow.com/questions/310881/overall-percentage-of-helpful-flags) on MSO about adding a helpful flag percentage bar to the flags page.

I liked the idea so much that I took the script and added it to tamper monkey.

I think it might be a good idea to add it to SOX.

**Comment by enki-code** [comment]
@calebkleveter Thanks for the interest! I was unsure how many people really liked the progress bar so I ended up writing the current version we have in SOX. However, we can gladly add this in.  I am currently recovering from back surgery and my wife just gave birth to our son so my hands are a little full at this time but I will do my best to get this implemented ASAP.

**Comment by shu8** [comment]
@calebkleveter As @enki-code's a bit busy, I've gone ahead and added the version from his meta post to the script.

It is available in [dev as](https://github.com/soscripted/sox/raw/dev/sox.user.js), and is treated as a **separate feature** (for now at least), so you'll need to enable the new `Show the total percentage of helpful flags as a coloured bar on the Flag Summary Page` feature under `Flags` :)
