### ISSUE TITLE
Move the quickAuthorInfo details to the right of the comments section

### ISSUE THREAD

**Issue by darkred** [soscripted/sox#156]
### Suggestion

Because the 'last seen date and registered status' entries (e.g. `last seen: 2 days ago | type: registered`) 
refers to the relevant question/answer poster, 
I'd suggest them to be aligned to the right, i.e. `text-align: right `  
in order not to be confused with being another comment.

Mockup:
![2016-12-14_001205](https://cloud.githubusercontent.com/assets/723651/21161658/28f06310-c192-11e6-850e-001185f5d0ba.jpg)

_This is a continuation of issue #117._

**Comment by shu8** [comment]
@darkred thanks! I like the idea and will have it done in the next dev version :)

I'll ping you when it's ready

**Comment by shu8** [comment]
@darkred done in dev af](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

**Comment by darkred** [comment]
Thank you!

PS. I just filed #158  about dev af.
