### ISSUE TITLE
Draggable bounty box creates problems

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#157]
### Installed Version: 2.0.2DEVae  Environment: Tampermonkey 

---

When you open the bounty box, you see this:

<img width="480" alt="screen shot 2016-12-14 at 5 55 10 pm copy" src="https://cloud.githubusercontent.com/assets/5375326/21204769/e0c72192-c226-11e6-9b1c-45ae8cb8d07c.png">

However, when you drag it, you'll have multiple problems. First, the word "question" is moved to the next line:

<img width="480" alt="screen shot 2016-12-14 at 5 55 16 pm copy" src="https://cloud.githubusercontent.com/assets/5375326/21204777/e63daa9c-c226-11e6-8053-2b247616b4fe.png">

This is minor. But if you click "next", the box whole will be messed up:

<img width="705" alt="screen shot 2016-12-15 at 2 14 56 am" src="https://cloud.githubusercontent.com/assets/5375326/21214999/53098fc0-c26c-11e6-8869-6ac0cb5d943e.png">

Finally, clicking next again makes the text box and buttons lie beyond the popup's borders:

<img width="636" alt="screen shot 2016-12-15 at 2 16 32 am" src="https://cloud.githubusercontent.com/assets/5375326/21215024/8590ce0e-c26c-11e6-9c1d-caf15a1ca355.png">

This all only happens if you drag the first box. Dragging the box after clicking "next" produces no problems on its own.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-addEllipsis","Appearance-answerTagsSearch","Appearance-betterCSS","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-grayOutVotes","Appearance-hideHireMe","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Appearance-disableOwnPostVoteButtons","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Flags-flagOutcomeTime","Flags-flagPercentages","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-downvotedPostsEditAlert","Unsorted-parseCrossSiteLinks","Unsorted-replyToOwnChatMessages"]

**Comment by shu8** [comment]
@IStoleThePies [fixed in dev af](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
