### ISSUE TITLE
Browser hang after updating to 2.0.2 dev af (I get 'Warning, unresponsive script: sox.common.js:136  ')

### ISSUE THREAD

**Issue by darkred** [soscripted/sox#158]
### Installed Version: 2.0.2 dev af,  Environment: Firefox 50.1.0 x64/Greasemonkey 3.9 in win10

After updating the script from 2.0.2 dev ae to 2.0.2 dev af
whatever StackOverflow page I may try to open
I constantly get high CPU usage in Firefox (browser "Not responding") to the point that I get this message:
![2016-12-17_005226](https://cloud.githubusercontent.com/assets/723651/21281135/2e974f14-c3f3-11e6-83ea-11f4df3300de.jpg)

I have to press <kbd>Stop script</kbd> every time
for the browser hang to stop.

I also tried it in a fresh Firefox with only Greasemonkey installed
and the issue occurs every single time, whatever SO page I may try to load.

**Comment by shu8** [comment]
@darkred sorry, that was me being stupid...

should be fixed in [dev ag](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

**Comment by darkred** [comment]
I updated to [dev ag](https://github.com/soscripted/sox/blob/66b4eaaa9e83c4972f8e39084ca7ea3e9fdb2b78/sox.user.js) as well as the latest, dev ah, 
but the hang still exits.

I get the Unresponsive script warning for sox common.js,
at either line 137, 138 or 145.

**Comment by shu8** [comment]
@darkred you're right!

I'm really sorry, I'm sure the hangs will have been really annoying. It's definitely (I'm 99% sure :/) fixed in [dev ai](https://github.com/soscripted/sox/raw/dev/sox.user.js) now.

It was a side effect to #152's solution and I messed up on the mutationobserver. Weirdly it only hangs on FF and not Chrome (which is also why I didn't realise this before I released it to dev!)...

**Comment by darkred** [comment]
Unfortunately it still hangs in dev ai.

**Comment by shu8** [comment]
@darkred urghh!!!

I don't have too much time atm so I've pushed a quick-fix [in dev aj](https://github.com/soscripted/sox/raw/dev/sox.user.js) that fixes it for now.

It makes the script actually usable again but kind-of breaks the fixed topbar feature for now -- you may need to disable that feature temporarily

**Comment by shu8** [comment]
@darkred all of the issues surrounding this should be fixed in [dev ak](https://github.com/soscripted/sox/raw/dev/sox.user.js) now :)

Please could you confirm this is the case? :) (you can re-enable fixed topbar now!)

**Comment by darkred** [comment]
Yes, it's fixed now. Thank you

**Comment by shu8** [comment]
*takes a big sigh of relief :P*
