### ISSUE TITLE
SOX buttons act weirdly when logged out on Area 51

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#159]
### Installed Version: 2.0.2DEVaf  Environment: Tampermonkey 

---

When logged out on Area 51, clicking the SOX settings button or the "notify on edit" button causes the popup to be shifted:

<img width="1440" alt="screen shot 2016-12-16 at 11 46 35 pm" src="https://cloud.githubusercontent.com/assets/5375326/21284475/19fc0a4e-c3ea-11e6-9614-b3836eb9e5bd.png">

<img width="1440" alt="screen shot 2016-12-16 at 11 46 46 pm" src="https://cloud.githubusercontent.com/assets/5375326/21284476/1c532f0c-c3ea-11e6-992f-e31ea673df27.png">

Additionally, you can't click on the "notify on edit" button to close its popup box (you have to click somewhere else). The SOX button doesn't have that problem.

All of this still happens if you disable the fixed topbar.

EDIT: The "clicking on notify on edit" bug actually seems to be on all sites, whether or not you log in. The "popup box shifting" problem only happens when logged out of Area 51, though.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-addEllipsis","Appearance-answerTagsSearch","Appearance-betterCSS","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-grayOutVotes","Appearance-hideHireMe","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Appearance-disableOwnPostVoteButtons","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Flags-flagOutcomeTime","Flags-flagPercentages","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-downvotedPostsEditAlert","Unsorted-parseCrossSiteLinks","Unsorted-replyToOwnChatMessages"]

**Comment by shu8** [comment]
@IStoleThePies The notify on edit button slipped through to A51 *again*, so I've got rid of that on A51 in [dev ag](https://github.com/soscripted/sox/raw/dev/sox.user.js). So that should get rid of all the A51 issues.

I can reproduce the other bug about the dialog not closing and I'll get that fixed ASAP

**Comment by shu8** [comment]
@IStoleThePies Fixed the dialog not closing bug [in dev ah](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by IStoleThePies** [comment]
@shu8 The Area 51 bug still seems to happen :/

**Comment by shu8** [comment]
@IStoleThePies Do you mean the dialog positioning one? If so, that's going to be fixed in enki's code that calculates positions relative to the parent's soon.
