### ISSUE TITLE
sox breaks the winter bash hats page.

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#160]
See https://meta.stackexchange.com/questions/288278/winter-bash-login-bug for the details ...

**Comment by shu8** [comment]
Confirmed. Working on it now. Sorry it made you go to meta for it!

**Comment by shu8** [comment]
@DavidPostill Can you check whether this is fixed for you in [dev al](https://github.com/soscripted/sox/raw/dev/sox.user.js)? :)

**Comment by DavidPostill** [comment]
Confirmed as fixed :)
