### ISSUE TITLE
Add "sign up" description to "notify on edit" button

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#161]
If you are logged out on all SE sites and click the inbox or rep topbar buttons, you'll get these messages:

<img width="439" alt="screen shot 2016-12-19 at 1 31 44 am" src="https://cloud.githubusercontent.com/assets/5375326/21303256/1cf61ba2-c58b-11e6-98b4-49bb7c5da513.png">

<img width="523" alt="screen shot 2016-12-19 at 1 30 42 am" src="https://cloud.githubusercontent.com/assets/5375326/21303257/1e215924-c58b-11e6-9e57-48a71f030a05.png">

Perhaps you could add one for the "notify on edit" button, since it is essentially the only SE button that is irrelevant if you're logged out?

**Comment by shu8** [comment]
@IStoleThePies I'm not sure about this one actually

It is possible for you to receive an edit notification even if you're logged out -- the script just uses the API and has a `sitename` so it doesn't need logging in...
