### ISSUE TITLE
Highlighting should be disabled on topbar buttons

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#162]
### Installed Version: 2.0.2DEVak  Environment: Tampermonkey 
---

When you double click on the SOX topbar buttons, you can highlight some of the elements:

![untitled-1](https://cloud.githubusercontent.com/assets/5375326/21303673/f6721d02-c58d-11e6-814b-3e9abff0f3fa.gif)

whereas double clicking on the regular SE buttons (including the site menu and winter bash) won't highlight anything. On that note, the notify on edit button also seems to highlight my gravatar whenever I click on the button to close its dialog box.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-addEllipsis","Appearance-answerTagsSearch","Appearance-betterCSS","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-grayOutVotes","Appearance-hideHireMe","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Appearance-disableOwnPostVoteButtons","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Flags-flagOutcomeTime","Flags-flagPercentages","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-downvotedPostsEditAlert","Unsorted-parseCrossSiteLinks","Unsorted-replyToOwnChatMessages"]

**Comment by shu8** [comment]
@IStoleThePies fixed in [dev al](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by IStoleThePies** [comment]
@shu8 Still seems to do it on the meta button.

**Comment by shu8** [comment]
@IStoleThePies sorry, forgot about that one! 

done in [dev ao](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
