### ISSUE TITLE
"Disable vote buttons on your own posts" disables accepting own answer

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#165]
### Installed Version: 2.0.2 Dev AD  Environment: Firefox/Greasemonkey 

---
###  Expected Behavior
Disabling vote buttons should not include the acceptance checkmark

---
### Actual Behavior
Tried to accept a self-answer on SU Meta and found that this feature had also disabled the acceptance checkmark.  Not much opportunity to see if it's limited to that site.

---
### SOX Errors logged to the browser console (if available)
I can collect console output if it's helpful, but this one has the flavor of a programming oversight rather than a bug.  Let me know.

---

**Comment by shu8** [comment]
@fixer1234 fixed in [dev au](https://github.com/soscripted/sox/raw/dev/sox.user.js)
