### ISSUE TITLE
error description: unexpected domain on proxy url

### ISSUE THREAD

**Issue by c-stauffer** [soscripted/sox#168]
### Installed Version: 1.X.X  Environment: Chrome/Tampermonkey 

---
###  Expected Behavior

---
### Actual Behavior

---
### SOX Errors logged to the browser console (if available)

---

**Comment by shu8** [comment]
I only just fixed this a few hours ago [in the latest dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js) (#164). Please can you make sure you are using at least `dev aw` (just install using this link)? Once installed, when you go to any SE site, a window should be opened (no alert this time!) to ask you to authorize the application, and finally an alert should say 'access token was saved, you can close this window now :)'.

Sorry this even happened in the first place, but it shouldn't happen in the latest dev version anymore!

**Comment by c-stauffer** [comment]
That worked, I had installed stable when encountering the error. Thanks for the quick reply!

**Comment by shu8** [comment]
No problem :)
