### ISSUE TITLE
Error authenticating against SO

### ISSUE THREAD

**Issue by tdwright-itg** [soscripted/sox#170]
### Installed Version: 1.X.X  Environment: Chrome/Tampermonkey 

---
###  Expected Behavior

SOX should be authorised by SO

---
### Actual Behavior

The authentication pop-up appears every time I try to access the SOX settings menu. The first time it appeared, I was prompted to authorise SOX, which I did. Then (and every time since) I got the following error:

> Application Login Failure
> 
> An error occurred while login into an application.
> Error Details
> 
> error description: unexpected domain on proxy url

---
### SOX Errors logged to the browser console (if available)

---

**Comment by shu8** [comment]
I only just fixed this yesterday [in the dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js) (#164). Please can you make sure you are using at least `dev aw` (just install using this link)? Once installed, when you go to any SE site, a window should be opened (no alert this time!) to ask you to authorize the application, and finally an alert should say 'access token was saved, you can close this window now :)'.

Sorry this even happened in the first place, but it shouldn't happen in the latest dev version anymore!

**Comment by tdwright-itg** [comment]
Thanks for the speedy response. That works like a charm. Great script by the way!

**Comment by shu8** [comment]
Thanks! I'm glad it's working for you now! :)
