### ISSUE TITLE
SOX settings search bar requires you to delete everything

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#171]
### Installed Version: 2.0.2DEVaz  Environment: Tampermonkey

If I make a typo when searching for features, the options won't reappear if I simply delete the last character. I have to completely delete everything in the search bar and retype what I was looking for.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Editing-titleEditDiff","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Voting-betterCSS","Unsorted-alwaysShowImageUploadLinkBox"]

**Comment by shu8** [comment]
@IStoleThePies fixed [in dev 2.0.3 b](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by IStoleThePies** [comment]
@shu8 Almost perfect, but doesn't seem to work on [Area 51 Discussions](http://discuss.area51.stackexchange.com/questions/26104/douplication-of-another-board).

**Comment by shu8** [comment]
@IStoleThePies yeah the API doesn't work on area51, so I don't think I'll be able to get that to work :(
