### ISSUE TITLE
New feature request: Review queue page indicator for Meta site reviews

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#173]
### Current Behaviour
All of the review queues for the site, itself, show a count of posts in each queue available for review.  The Meta site has a link at the bottom for its review queues, but no indication of whether there is anything to review.  It's fairly rare for there to be anything in the Meta site review queues, so clicking on the link is usually a waste of time.  Any form of indicator that there is something there to review would be useful.  Possibilities:

- Add the count of available posts like the other queues (in this case, it could be the sum of the counts in the Meta site queues).

- Display an icon if there are posts (sum of queue counts > 0).

- Grey out the Meta link if there is nothing there (sum of queue counts = 0).

- Use bold, color, or some other change to the Meta site link text if there are posts there.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

**Comment by shu8** [comment]
@fixer1234 added in [dev 2.0.3 b](https://github.com/soscripted/sox/raw/dev/sox.user.js) :) It's the last one in the Unsorted section.

**Comment by fixer1234** [comment]
@shu8 Nice.
