### ISSUE TITLE
Edit comment sometimes not working

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#174]
### Installed Version: 2.0.3 Dev A  Environment: Firefox/Greasemonkeymonkey
This feature was working earlier.  First noticed in one of the last 2.0.2 Dev versions (maybe ~AZ; I skipped some of the last flurry, so the relevant change could have been earlier)
Different issue from #87

### Current Behaviour
Hovering over the right side of the edit history link, shows the date/time as expected.  Hovering over "edited" sometimes show the edit comment as it's supposed to.  But it sometimes shows the instructional tooltip: "show all edits to this post"

---

### SOX Errors logged to the browser console -- F12 (if available)

[How do I setup Ceph-like storage system in Windows Server 2016? [on hold]](http://superuser.com/q/1158886/364367) is an example where it is working correctly.

[how to calculate download speed from total bandwidth?](http://superuser.com/a/1159189/364367) is an edited answer this is currently happening on.  I went to capture console output and when I refreshed the page to capture clean output, the feature started working correctly.

If this is one of the problems that changes after a page refresh, this will be hard to capture console output when it's acting up.  Ideas?

---

**Comment by shu8** [comment]
@fixer1234 for your second link where it didn't work originally -- did you hover over it directly after editing it yourself? 

Because this feature, right now, only runs on page load, so anything that happens after the page has loaded won't be detected.

I'm open to looking into changing that though, but it'd help if I was sure this is actually the problem so I don't end up fixing something completely different!

**Comment by fixer1234** [comment]
@shu8 I'm pretty sure I returned to both sample pages for the test, so it wasn't immediately after the edit, but I can't bet the farm on it.  I just went to the "bad" link and it's working properly now.  Since there's a possibility that I'm wrong, why don't you delay spending time on this one.  I'll keep my eye out for it and try to verify and report back.

**Comment by fixer1234** [comment]
@shu8 I'm now on Dev E and testing various features.  I retested this issue on a bunch of random posts and they all worked properly.  I guess it's possible that I hadn't refreshed that bad example, and the previous instances might have been the same situation (never made a note of the conditions, only remembered encountering them).  Since this can't be reproduced anymore, I'll close it.  We can always reopen if the problem shows up again under known, reliable conditions.
