### ISSUE TITLE
Installation needs access token

### ISSUE THREAD

**Issue by Gloin1313** [soscripted/sox#175]
### Current Behaviour

I am trying to use SOX, following these instructions, I clicked 'install' (development version) and the gears appear at the top of the page, but every time I open a page on SO, I get this message: 
![screen shot 2016-12-22 at 12 25 29](https://cloud.githubusercontent.com/assets/22625968/21425983/4af51e34-c844-11e6-8723-438211dda61b.png)
Message:
To complete the SOX installation please follow the instructions in the window that has been opened for you to receive your access token.

I am pretty sure that now window has been opened, so how to I get the access token?

**Comment by shu8** [comment]
I haven't tested this script on safari (I wasn't even aware that you could
get tampermonkey on safari) so I can't say for certain, but do you have a
pop-up blocker enabled?

Try disabling it which should let the window open. Once that window opens,
you'll get an alert that the access token has been saved and it is safe to
close the window

If that doesn't work, please comment back and I'll see if I can figure
something else out :)

**Comment by Gloin1313** [comment]
Thank you!
Safari has a default pop-up blocker which I turned off using [this tutorial](http://www.bestbuy.com/site/tech-tips/disable-popup-blocker/pcmcat748301880694.c?id=pcmcat748301880694).
All works fine now!

**Comment by shu8** [comment]
Great! I'm glad it's working for you now! And thanks for showing me you can
get tampermonkey for safari! :)

**Comment by Gloin1313** [comment]
It is available for Chrome, Microsoft Edge, Safari, Opera Next, and Firefox in case you are interested. Ninjakit appeared to be the recommend user script manager for safari according to the SOX [installation guide](http://stackapps.com/questions/6091/stack-overflow-extras-sox), but following the link to the GitHub page, then the safari install button on the GitHub page did nothing. Just a page of ads.
Hence why I used tamper monkey instead!  :)
Maybe you could change the recommended tool on the SOX installation guide?

**Comment by shu8** [comment]
Oh wow! I never knew it was available for so many browsers! I will change
the installation guide in a bit because I love tampermonkey and it's always
reliable! :)
