### ISSUE TITLE
Clicking on 'share' link copies the `[post-name](url)` to the clipboard

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [soscripted/sox#177]
In the spirit of the "Unsorted-shareLinksMarkdown" feature (Change 'share' link to format of `[post-name](url))`, that would be great to have an option that would cause clicking on 'share' link to copy the `[post-name](url)` to the clipboard (my JavaScript knowledge is fuzzy, but that seems feasible: [How do I copy to the clipboard in JavaScript?](http://stackoverflow.com/a/30810322/395857))

**Comment by shu8** [comment]
@Franck-Dernoncourt done in [dev c](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
