### ISSUE TITLE
Fixed top-bar overlaps with scrolling review queue options

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#180]
### Current Behaviour

When reviewing content, one can scroll down to view an entire post. The review queue options follow the scrolling, always staying at the top. However, with the fixed top-bar active, the top-bar and the review queue options overlap:

![](https://i.stack.imgur.com/neJb3.gif)

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

Review something in the closed review queue (say) where you can scroll down. Note how the review queue options go underneath the fixed top-bar.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-linkedPostsInline","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]

**Comment by shu8** [comment]
@wgrundlingh thanks for the bug report! fixed in [dev f](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
