### ISSUE TITLE
Extra CSS voting/favourite button animation works beyond Android.SE

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#182]
### Current Behaviour

Option under Voting mentions "Add extra CSS for voting signs and favourite button" is "currently only on Android SE". However, this seems to work on other sites on the network as well. Here's a view on [Meta.SE](http://meta.stackexchange.com):

![tex-se](https://cloud.githubusercontent.com/assets/1776164/21447698/4ad6c21a-c88d-11e6-9f54-61f4acc8d5b9.gif)

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]

**Comment by shu8** [comment]
@wgrundlingh By `currently only on Android SE`, I meant that this feature is currently only implemented by SE on the Android site.

However, I can see how that could be confusing now... do you have any ideas on how I could concisely rephrase that? :)

**Comment by wgrundlingh** [comment]
@shu8 I think one can remove the reference `currently only on Android SE` from the main list so it just reads (suggestion; note the change):

    Add extra CSS for animation actions on voting and favourite buttons

The expandable information bullet can reference the fact that it's currently only available on Android.SE. Something like

    Pulse effect when hovering over the upvote/downvote/favourite buttons. Currently only implemented natively on Android.SE. [meta]

**Comment by shu8** [comment]
@wgrundlingh thanks! changed in [dev f](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
