### ISSUE TITLE
Improved listing of answers are misaligned horizontally

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#183]
### Current Behaviour

The improved listing of answers are horizontally misaligned; the arrows are left-of-centre compared to "Score: X":

![image](https://cloud.githubusercontent.com/assets/1776164/21448328/51a7c0ea-c896-11e6-885e-5204c0b245b4.png)

Additionally, a 0-score (or perhaps unvoted) answer seems to have an extra coloured vote "button" due to the misalignment.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

Happened here:

[How do people find out about new questions?](http://meta.stackexchange.com/q/288644/168244)

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]

**Comment by shu8** [comment]
@wgrundlingh thanks again! fixed in [dev h](https://github.com/soscripted/sox/raw/dev/sox.user.js)
