### ISSUE TITLE
quickAuthorInfo CSS applies to first comment if it fails finding author info

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#187]
### Current Behaviour

The first visible comment on a post (question or answer; highlighted below) has a lighter colour, matching that of the `share edit close flag notify on edit` buttons:

![image](https://cloud.githubusercontent.com/assets/1776164/21465916/cefa400c-c96a-11e6-9cec-faacaff4f1fa.png)

---

### SOX Errors logged to the browser console -- F12 (if available)

(unknown) soup injecting fixes
VM5423:30 soup init complete
VM5423:30 soup setup complete
VM5428:563 SOX:  undefined
VM5428:563 SOX:  Object
VM5423:30 soup JS fixes applied
VM5428:563 SOX:  DEBUGGING SOX VERSION 2.0.2
VM5428:563 SOX:  ----------------saved variables---------------------
VM5428:587 SOX:  logging sox stored values --- 
VM5428:587 SOX:  SOXSETTINGS
VM5428:587 SOX:  ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]
VM5428:587 SOX:  editReasons
VM5428:587 SOX:  [["formatting","Improved Formatting"],["spelling","Corrected Spelling"],["grammar","Fixed grammar"],["greetings","Removed thanks/greetings"]]
VM5428:587 SOX:  access token set
VM5428:587 SOX:  metaNewQuestionAlert-lastQuestions
VM5428:587 SOX:  {"meta.tex":"How to including multimedia files in beamer [Work in progress, please ignor for the moment]"}
VM5428:587 SOX:  downvotedPostsEditAlert
VM5428:587 SOX:  {}
VM5428:587 SOX:  SOX-debug
VM5428:587 SOX:  true
VM5428:563 SOX:  ----------------end saved variables---------------------
VM5428:563 SOX:  initializing SOX dialog
VM5428:563 SOX:  injecting features into dialog
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  addAuthorNameToInboxNotifications
VM5428:563 SOX:  Object
VM5428:563 SOX:  running addAuthorNameToInboxNotifications
VM5428:563 SOX:  observe: .inbox-dialog
VM5428:563 SOX:  undefined
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  alignBadgesByClass
VM5428:563 SOX:  Object
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  answerTagsSearch
VM5428:563 SOX:  Object
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  bulletReplace
VM5428:563 SOX:  Object
VM5428:563 SOX:  running bulletReplace
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  colorAnswerer
VM5428:563 SOX:  Object
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  fixedTopbar
VM5428:563 SOX:  Object
VM5428:563 SOX:  running fixedTopbar
VM5428:563 SOX:  observe: #notify-container,#notify--1
VM5428:563 SOX:  undefined
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  highlightQuestions
VM5428:563 SOX:  Object
VM5428:563 SOX:  running highlightQuestions
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  isQuestionHot
VM5428:563 SOX:  Object
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  markEmployees
VM5428:563 SOX:  Object
VM5428:563 SOX:  running markEmployees
VM5428:563 SOX:  SOX Access Token: SET
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  scrollToTop
VM5428:563 SOX:  Object
VM5428:563 SOX:  running scrollToTop
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  spoilerTip
VM5428:563 SOX:  Object
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  standOutDupeCloseMigrated
VM5428:563 SOX:  Object
VM5428:563 SOX:  running standOutDupeCloseMigrated
VM5428:563 SOX:  observe: #user-tab-questions, #question-mini-list
VM5428:563 SOX:  undefined
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  tabularReviewerStats
VM5428:563 SOX:  Object
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  topAnswers
VM5428:563 SOX:  Object
VM5428:563 SOX:  Appearance
VM5428:563 SOX:  unspoil
VM5428:563 SOX:  Object
VM5428:563 SOX:  Comments
VM5428:563 SOX:  autoShowCommentImages
VM5428:563 SOX:  Object
VM5428:563 SOX:  Comments
VM5428:563 SOX:  commentReplies
VM5428:563 SOX:  Object
VM5428:563 SOX:  Comments
VM5428:563 SOX:  commentShortcuts
VM5428:563 SOX:  Object
VM5428:563 SOX:  Comments
VM5428:563 SOX:  confirmNavigateAway
VM5428:563 SOX:  Object
VM5428:563 SOX:  Comments
VM5428:563 SOX:  copyCommentsLink
VM5428:563 SOX:  Object
VM5428:563 SOX:  Comments
VM5428:563 SOX:  moveBounty
VM5428:563 SOX:  Object
VM5428:563 SOX:  Comments
VM5428:563 SOX:  showCommentScores
VM5428:563 SOX:  Object
VM5428:563 SOX:  Comments
VM5428:563 SOX:  hiddenCommentsIndicator
VM5428:563 SOX:  Object
VM5428:563 SOX:  Editing
VM5428:563 SOX:  addSBSBtn
VM5428:563 SOX:  Object
VM5428:563 SOX:  running addSBSBtn
VM5428:563 SOX:  observe: li[id^="wmd-redo-button"]
VM5428:563 SOX:  undefined
VM5428:563 SOX:  observe: .wmd-preview.sbs-on
VM5428:563 SOX:  undefined
VM5428:563 SOX:  Editing
VM5428:563 SOX:  editComment
VM5428:563 SOX:  Object
VM5428:563 SOX:  running editComment
VM5428:563 SOX:  Editing
VM5428:563 SOX:  editReasonTooltip
VM5428:563 SOX:  Object
VM5428:563 SOX:  Editing
VM5428:563 SOX:  enhancedEditor
VM5428:563 SOX:  Object
VM5428:563 SOX:  running enhancedEditor
VM5428:563 SOX:  observe: li[id^="wmd-redo-button"], textarea[id^="wmd-input"]
VM5428:563 SOX:  undefined
VM5428:563 SOX:  Editing
VM5428:563 SOX:  kbdAndBullets
VM5428:563 SOX:  Object
VM5428:563 SOX:  running kbdAndBullets
VM5428:563 SOX:  observe: [id^="wmd-redo-button"]
VM5428:563 SOX:  undefined
VM5428:563 SOX:  Editing
VM5428:563 SOX:  titleEditDiff
VM5428:563 SOX:  Object
VM5428:563 SOX:  Editing
VM5428:563 SOX:  inlineEditorEverywhere
VM5428:563 SOX:  Object
VM5428:563 SOX:  Editing
VM5428:563 SOX:  downvotedPostsEditAlert
VM5428:563 SOX:  Object
VM5428:563 SOX:  running downvotedPostsEditAlert
VM5428:563 SOX:  downvotedPostsEditAlert posts to check
VM5428:563 SOX:  Object
VM5428:563 SOX:  downvotedPostsEditAlert notifications
VM5428:563 SOX:  Object
VM5428:563 SOX:  Flags
VM5428:563 SOX:  flagOutcomeTime
VM5428:563 SOX:  Object
VM5428:563 SOX:  running flagOutcomeTime
VM5428:563 SOX:  Flags
VM5428:563 SOX:  flagPercentages
VM5428:563 SOX:  Object
VM5428:563 SOX:  running flagPercentages
VM5428:563 SOX:  Flags
VM5428:563 SOX:  flagPercentageBar
VM5428:563 SOX:  Object
VM5428:563 SOX:  running flagPercentageBar
VM5428:563 SOX:  Sidebar
VM5428:563 SOX:  hideHireMe
VM5428:563 SOX:  Object
VM5428:563 SOX:  running hideHireMe
VM5428:563 SOX:  Sidebar
VM5428:563 SOX:  linkedToFrom
VM5428:563 SOX:  Object
VM5428:563 SOX:  Sidebar
VM5428:563 SOX:  hotNetworkQuestionsFiltering
VM5428:563 SOX:  Object
VM5428:563 SOX:  running hotNetworkQuestionsFiltering
VM5428:563 SOX:  Chat
VM5428:563 SOX:  chatEasyAccess
VM5428:563 SOX:  Object
VM5428:563 SOX:  Chat
VM5428:563 SOX:  replyToOwnChatMessages
VM5428:563 SOX:  Object
VM5428:563 SOX:  Chat
VM5428:563 SOX:  renameChat
VM5428:563 SOX:  Object
VM5428:563 SOX:  Voting
VM5428:563 SOX:  betterCSS
VM5428:563 SOX:  Object
VM5428:563 SOX:  Voting
VM5428:563 SOX:  grayOutVotes
VM5428:563 SOX:  Object
VM5428:563 SOX:  Voting
VM5428:563 SOX:  stickyVoteButtons
VM5428:563 SOX:  Object
VM5428:563 SOX:  Voting
VM5428:563 SOX:  disableOwnPostVoteButtons
VM5428:563 SOX:  Object
VM5428:563 SOX:  Unsorted
VM5428:563 SOX:  parseCrossSiteLinks
VM5428:563 SOX:  Object
VM5428:563 SOX:  Unsorted
VM5428:563 SOX:  quickAuthorInfo
VM5428:563 SOX:  Object
VM5428:563 SOX:  Unsorted
VM5428:563 SOX:  shareLinksMarkdown
VM5428:563 SOX:  Object
VM5428:563 SOX:  Unsorted
VM5428:563 SOX:  warnNotLoggedIn
VM5428:563 SOX:  Object
VM5428:563 SOX:  running warnNotLoggedIn
https://api.stackexchange.com/2.2/users/?site=tex&key=lL1S1jr2m*DRwOvXMPp26g((&access_token=vZsS2UgjQzEGpTnma517VA)) Failed to load resource: the server responded with a status of 400 (Bad Request)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]

**Comment by shu8** [comment]
@wgrundlingh that actually seems to be that the quickAuthorInfo feature isn't fully working.

Please could you enable debugging (from the settings dialog) and paste the console log here? :)

**Comment by wgrundlingh** [comment]
@shu8 I've added the error log. Hope this is what you're looking for. And yes, the quickAuthorInfo CSS isn't loading.

**Comment by shu8** [comment]
@wgrundlingh thanks, but it seems you might have the 'network' option disabled in your console -- please could you enable the network option and post the log again? Sorry for the late reply!

**Comment by wgrundlingh** [comment]
I'm unfamiliar with working under the console. How do I do that?

**Comment by shu8** [comment]
@wgrundlingh no problem, here's what to do:

![this](https://cloud.githubusercontent.com/assets/8850830/21486656/35331fc8-cbb0-11e6-9ebd-b98d6c9ecc66.png)

(just follow the steps and make sure everything looks the same :)

**Comment by wgrundlingh** [comment]
I have exactly that:

![image](https://cloud.githubusercontent.com/assets/1776164/21487904/43cd0bc6-cb8c-11e6-9d21-1e343384a192.png)

**Comment by shu8** [comment]
@wgrundlingh oh, I'm sorry! I didn't see the very last line of your console that you posted last time, which shows the error! 

It looks like the problem is that your access token is no longer valid -- did you request a new access token on a different browser/computer? You can get a new token by going to this link: https://stackexchange.com/oauth/dialog?client_id=7138&redirect_uri=http://soscripted.github.io/sox/. It will save automatically.

Please could you confirm whether getting a new access token fixes this? 😃 

---

In [dev o](https://github.com/soscripted/sox/raw/dev/sox.user.js), I've added a new key icon at the bottom of the dialog. This allows you to paste in an access token if you want to use SOX on multiple browsers/computers. I've written the steps you could do if you want to paste it in [over here](https://github.com/soscripted/sox/issues/191#issuecomment-269243020) :)

**Comment by wgrundlingh** [comment]
Indeed, a new token fixed the issue and I can now see the quickAuthorInfo again (and the colour has been restored).

I didn't request a new access token on a different browser. The only other device I use for browsing SE is the iPhone app.

**Comment by shu8** [comment]
Glad to know it's fixed.

I've added a little check in Dev P that'll warn you if it happens again.
Not sure why it happened this time though...

**Comment by wgrundlingh** [comment]
I seem to be losing my key very regularly. Do you know of anything that might clear this key so frequently? Perhaps include a "Get new key" icon?

http://fontawesome.io/icon/key/

**Comment by shu8** [comment]
Yeah that seems to be happening to @fixer1234 as well. I need to look into
it

Until then, if you click the little key icon at the bottom of the dialog
and then press CANCEL, a link will be added to the console which you can
click to get a new key. Not ideal, but it should work for now! :/

**Comment by fixer1234** [comment]
@shu8 Any way for SOX to self-check for a valid token (periodically, or triggered by a failure of a feature that requires it, or have features that need it check before executing, or a user option, like a button in the menu, to check)?  It could then raise a message telling the user to get a new token (or self-trigger getting a new token) if needed.

**Comment by fixer1234** [comment]
@shu8 Just tested what you described.  The system didn't do anything related to tokens.  Pasting the new token in the key window also didn't work.
