### ISSUE TITLE
Trimming before applying kbd

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [soscripted/sox#189]
### Current Behaviour

If I select `A ` (A followed by a whitespace) in the text editor, then click on `kbd`, I get `<kbd>A </kbd>`. It would be nice to trim before adding the kbd tag, e.g. getting `<kbd>A</kbd> ` instead.  The main motivation is that double-clicking on a word often selects  the following whitespace:

![image](https://cloud.githubusercontent.com/assets/15331/21468361/2ce95106-c9db-11e6-8726-9a2b381ddbeb.png)

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-tabularReviewerStats","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-linkedPostsInline","Unsorted-parseCrossSiteLinks","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]

**Comment by shu8** [comment]
@Franck-Dernoncourt done in [dev l](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

**Comment by Franck-Dernoncourt** [comment]
It works, thanks! :+1:
