### ISSUE TITLE
Enhanced Editor Feature

### ISSUE THREAD

**Issue by shu8** [soscripted/sox#19]
### Feature Request

Add:

- post fixer ([original](https://github.com/nathan-osman/Stack-Exchange-Post-Editor))
- better tab key ([original](https://bitbucket.org/balpha/se-tab-edting/))
- keyboard shortcuts
- ace editor
- find + replace
- kbd+list

for editing.

**Comment by enki-code** [comment]
Find and Replace should toggle, as of right now it just keeps adding toolbars.
![ace-editor-fr-fail](https://cloud.githubusercontent.com/assets/12533449/13556276/8f00feb2-e38a-11e5-9c73-dcf6b1546bb4.png)



Insert Code button opens an empty dialog for me.


![ace-editor-insert-fail](https://cloud.githubusercontent.com/assets/12533449/13556290/c098f75e-e38a-11e5-8f73-de69688267ba.png)

**Comment by shu8** [comment]
@enki-code ah yes, upgoat told me about the first one. weird about the second. Anything in console?
