### ISSUE TITLE
"Get token" repeat quirk

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#190]
### Current Behaviour
(This started with Dev J, I think): I often have at least three SU tabs open concurrently--the main page, the review queues, and my profile page so I can jump to bookmarked threads.  After installing the new SOX, I refresh whichever SU page I land on (that's determined by the last page I was on before installing SOX; can't bet the farm on which tab that was each time), and go through the get-token routine.  Then I use whatever SU page I end up on to re-enter the SOX preferences (that has been the second SU tab in both cases, which was the review queues).  

I then go to the main page, which was the first SU tab both times, and refresh the page.  That executes the get-token action again.  It takes only a few seconds to successfully complete.  Subsequently going to the third SU tab, which was the profile page both times, and refreshing that, did not trigger the get-token for a third time.

---

### SOX Errors logged to the browser console -- F12 (if available)
Since the action isn't repeatable without reinstalling SOX, and I'm guessing that this is a program logic flaw that you might be able to spot,  I'll skip console output unless you really need it.

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-linkedPostsInline","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn","Unsorted-showMetaReviewCount"]

**Comment by fixer1234** [comment]
@shu8 Just loaded dev M and it didn't do this, so maybe whatever triggered the problem was fixed.  I'll close it.

**Comment by fixer1234** [comment]
@shu8 The quirk returned in dev N.

**Comment by shu8** [comment]
@fixer1234 is the problem the fact that it asks you to get the token again?

if so, it seems like it's because you didn't refresh the 2nd page, so TM/GM doesn't know the token was already saved on the previous tab before refreshing (AFAIK, TM/GM retrieve saved values on page load)...

If not, please could you clarify it a bit? :)

**Comment by fixer1234** [comment]
@shu8 I typically have several SE tabs open, so when SOX is installed, the cogs icon appears on several tabs.  I go to one of the SE tabs (random), and refresh the page.  That triggers the get-token routine, after which I close the token page (used to be an SO page).  I believe I end up back on the SE page from which I launched the get-token action.

My recollection is that the SOX menu is already pre-opened.  I set the preferences and save.

The next step might even have varied a little between versions.  I recall that on at least some versions, other tabs would also display the get-token message.  On other versions, I think, they would just display the open SOX menu still in its virgin state (not reflecting the just-saved preferences).  

However, except for a couple of recent versions, just refreshing that page would clear whatever flotsam was displayed and update the topbar icons (e.g., adding additional SOX icons). .  SOX was "smart enough" to only go for a token the first time.  

The repeat of the get-token action has occurred on only a couple of recent versions (including N).  In the case of N, it wasn't even the get token prompt on another page that triggered the action.  I got the token and then set the preferences on that page, at which point the updates to that page were complete.  I assume other tabs probably displayed the get token message or the open SOX menu at that point.  However, I refreshed the completed page, and that triggered another action that quickly reported that there was already a token.  

On Dev K, my recollection is that after the first tab was in final form, I selected another SE tab, which was displaying either the get token message or the open SOX menu (forget which).  Typically, just refreshing that page would clear it and update the topbar.  However, refreshing that page triggered another token check in K.

I've updated a lot of SOX versions, and there have always been multiple SE tabs open at the time.  K was the first that made a second attempt for a token.  I think M was the next version I loaded and that didn't do it.  I just loaded N and this version did it again.

It's harmless and not a big deal.  If it's an artifact of the way features need to work, it's not a problem.  I thought that worst case, it might be unexpected behavior that might point to a programming hole you could want to check out.  Otherwise, fixing it is just polish.  It's always reassuring and nice when things are tight and don't do "sloppy" actions.  And it seems like the kind of thing that would be fixable by simply checking for the existence of a token before running the routine (or suppressing the associated screen activity until SOX recognizes that action is required to get a token).

**Comment by shu8** [comment]
Oh ok I think I understand now.
I think I know which line might be causing it. I'll push a fix tomorrow
when I get a bit more time :)

**Comment by shu8** [comment]
@fixer1234 does it happen in [dev p](https://github.com/soscripted/sox/raw/dev/sox.user.js)?

**Comment by fixer1234** [comment]
@shu8 Didn't experience it with Dev P.
