### ISSUE TITLE
Fixed topbar no longer works

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#192]
### Installed Version: 2.0.3DEVl  Environment: Tampermonkey

The fixed topbar no longer seems to work in this version.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-enhancedEditor","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-quickAuthorInfo","Unsorted-showMetaReviewCount"]

**Comment by fixer1234** [comment]
I thought you were referring to the text positioning issue relative to the topbar, so I tested it on my own system.  It looks like you're referring to the topbar, itself.  This looks like another feature that has mysteriously disappeared.  The topbar is no longer fixed at the top (it scrolls out of view).  Jumping to a post or comment via a link, the topbar isn't visible at all.

**Comment by shu8** [comment]
@IStoleThePies @fixer1234 me being stupid again... fixed in [dev m](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 Dev M, confirm: works on threads, Q/A post links, comment links, and inbox links.

**Comment by IStoleThePies** [comment]
@shu8 Checking "enable on Ask Ubuntu" doesn't seem to do anything. In fact, it seems to uncheck itself every time I leave the page I'm currently on.

**Comment by fixer1234** [comment]
@shu8 Using Dev N.  Went to this link from a comment in my comment history:  http://superuser.com/questions/1159733/automatically-sorting-a-column-on-a-new-excel-spreadsheet-every-day#comment1670671_1159733.  The top of the comment was hidden behind the topbar.  Refreshing the page didn't change that.  I Enabled debugging in the SOX menu and it displayed properly.  Disabling debugging put it back to partially hidden.  I repeated this sequence several times to verify.  So it will be hard to capture console output of the problem in action.  But the silver lining is that activating debugging fixes it, which might be diagnostic in itself..

**Comment by shu8** [comment]
@IStoleThePies yeah I saw that happening -- it should be fixed in [dev o](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by shu8** [comment]
@fixer1234 can't repro, but can you try [dev p](https://github.com/soscripted/sox/raw/dev/sox.user.js)?

**Comment by IStoleThePies** [comment]
@shu8 Still doesn't seem to work :/

**Comment by fixer1234** [comment]
@shu8 I just tested Dev P.  The problem link reported above seems to work.  Random links to posts, comments from the comment history, and inbox comments seem to work.

**Comment by IStoleThePies** [comment]
@shu8 Replying to my own chat messages doesn't seem to work either :/

**Comment by shu8** [comment]
@IStoleThePies with the ubuntu checkbox... are you clicking the small save button underneath the checkbox or the main big one? it needs to be the small one!

![this](https://cloud.githubusercontent.com/assets/8850830/21527894/648e366e-cd26-11e6-9e56-2fa5b8021b64.png)

I realise that it looks reallllllly bad, and I'm completely open to any UI ideas! :) (I'll probably make that button bigger anyway though!)

---

also fixed the chat issue in [dev t](https://github.com/soscripted/sox/raw/dev/sox.user.js) -- it was completely broken on chat actually, so if anything else wasn't working on chat, it should now!

**Comment by IStoleThePies** [comment]
@shu8 Didn't realize you had to click that save button. 😆 

It works now, but #74 doesn't seem to be fixed on either AskUbuntu or Area 51. 😕
