### ISSUE TITLE
Move quickAuthorInfo closer to flair

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#195]
### Current Behaviour

The quickAuthorInfo is quite far from the post flair, perhaps as a result of the insertion of "start a bounty" and "show X more comments":

![image](https://cloud.githubusercontent.com/assets/1776164/21502801/59258022-cc07-11e6-9121-b62b526daec9.png)

Is it possible to move the quickAuthorInfo closer to the flair? It makes more sense there.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]

**Comment by shu8** [comment]
@wgrundlingh sure, I could make it look something like this:

![this](https://cloud.githubusercontent.com/assets/8850830/21508696/0a51bbb8-cc7b-11e6-888a-3aece640514d.png)

but then if I add the 'type: registered' text, it'll get too much. I could instead put an icon that shows whether they are registered or not, but can't think of *which* icon... do you have any ideas on what symbol could represent being registered or not?

**Comment by wgrundlingh** [comment]
I think the icon display should be subtle, perhaps with a tooltip if people are interested in more information. The following icons were taken from [FontAwesome](http://fontawesome.io/icons/) (search for "user"):

[Registered user](http://fontawesome.io/icon/user/):

![image](https://cloud.githubusercontent.com/assets/1776164/21509578/35e93d5a-cc3f-11e6-975f-356f35b43cc5.png)

[Unregistered user](http://fontawesome.io/icon/user-o/):

![image](https://cloud.githubusercontent.com/assets/1776164/21509589/516d80c2-cc3f-11e6-84e8-de36f765586c.png)

Perhaps one can do something similar for "last seen".

[Last seen](http://fontawesome.io/icon/clock-o/):

![image](https://cloud.githubusercontent.com/assets/1776164/21509628/9fc7ed7a-cc3f-11e6-886e-53da3bbc7761.png)

Or, perhaps use the same icon as is done by SE in the user profile:

![image](https://cloud.githubusercontent.com/assets/1776164/21509661/efe43b9c-cc3f-11e6-9d7a-3cae78fb2f37.png)

Here's a suggestion of the layout:

![image](https://cloud.githubusercontent.com/assets/1776164/21509818/f4ce5032-cc41-11e6-9a4a-c083802df047.png)

Hopefully the look won't be influenced by ugly wrapping of this kind:

![image](https://cloud.githubusercontent.com/assets/1776164/21509749/eecf32e2-cc40-11e6-9f6e-28f6487b315e.png)

And still work well around:

![image](https://cloud.githubusercontent.com/assets/1776164/21509777/50bf5400-cc41-11e6-8e35-4b30cb541420.png)

---

(Many options also showed when I [Googled `registered user icon`](https://www.google.ca/search?q=registered+user+icon&espv=2&biw=1366&bih=672&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiJ6aGcsZXRAhVP9mMKHdgGAZcQsAQIGg).)

**Comment by shu8** [comment]
Thanks. I think I'll change the last seen text to be the clock icon and
then add in the user icons you've shown from font awesome (which is ideal
because sox already uses that!). I'll try and make sure the wrapping
doesn't mess it up, especially on those ones like in your screenshot where
there are loads of badges!

**Comment by shu8** [comment]
@wgrundlingh done in [dev s](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

![this](https://cloud.githubusercontent.com/assets/8850830/21527644/870a5af8-cd24-11e6-8ab5-3d85ec6fa6b9.png)
