### ISSUE TITLE
Closing the Area 51 logged-out notification doesn't shift the rest of the page up

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#197]
### Installed Version: 2.0.3DEVr  Environment: Tampermonkey

If you have a fixed topbar and go onto Area 51 while logged out, then close the notification at the top, the rest of the page won't shift up (whereas it used to in earlier versions of SOX).

<img width="1440" alt="screen shot 2016-12-28 at 2 56 49 am" src="https://cloud.githubusercontent.com/assets/5375326/21517006/5453aac2-cca9-11e6-96a0-28ed347fee1e.png">

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-showMetaReviewCount"]

**Comment by shu8** [comment]
@IStoleThePies fixed in [dev s](https://github.com/soscripted/sox/raw/dev/sox.user.js)

not sure why it only started happening now though... it shouldn't have ever worked 😆

**Comment by IStoleThePies** [comment]
@shu8 Now the notification seems to disappear right after it loads 😕

**Comment by shu8** [comment]
@IStoleThePies sorry, how about now in [dev u](https://github.com/soscripted/sox/raw/dev/sox.user.js)?

**Comment by IStoleThePies** [comment]
@shu8 Works now :)
