### ISSUE TITLE
Hot Question filtering module will not load.

### ISSUE THREAD

**Issue by PsychicSmurf** [soscripted/sox#199]
### Current Behaviour

Cannot use the Hot Questions filtering module. Does not load.

---

### SOX Errors logged to the browser console -- F12 (if available)

VM672:581SOX:  There was an error loading the feature "Sidebar-hotNetworkQuestionsFiltering". Please raise an issue on GitHub, and copy the following error log:
TypeError: Cannot read property 'replace' of undefinedsox.error @ VM672:581
VM672:587SOX:  Deleting feature "Unsorted-duplicate"

---

### Steps to reproduce

Clean install. Accept token.
Uncheck "Hide the Hot Network Questions module"
Check the "Filter the hot network questions by their attributes" then click on arrow:
Enter values in the "Sites to block", click "save", then "Save Changes"

Options now highlighted it red with error "There was an error loading this feature"

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-displayName","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideHireMe","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-linkedPostsInline","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-sortByBountyAmount","Unsorted-warnNotLoggedIn","Unsorted-hideCertainQuestions","Unsorted-closed","Unsorted-migrated","Unsorted-deletedAnswers"]

**Comment by shu8** [comment]
@PsychicSmurf is it working now?

**Comment by PsychicSmurf** [comment]
Yes. The message is misleading, and instructed me to file an error, when in fact it was a simple case of "syntax error" for the content being added in the box. 

Without examples, I was unsure what format the "sites" needed to be, so I had just entered the SE domain prefix, instead of the entire URL, including the http bit.

**Comment by shu8** [comment]
@PsychicSmurf ahh ok. I'll get that fixed and make it give a more helpful error message :)
