### ISSUE TITLE
Upvote temporarily hidden when scrolling down

### ISSUE THREAD

**Issue by cullub** [soscripted/sox#2]
While scrolling down the page, the `vote` div gets scrolled up below the topbar, until it is mostly hidden, before jumping down to `position: fixed`.

Example:

![bug](https://cloud.githubusercontent.com/assets/7533931/13159314/b23f98de-d656-11e5-9403-fec679e2bf3d.gif)

**Comment by shu8** [comment]
Thanks for reposting this! :) I still don't have a solution though :(

Any ideas @enki-code?

**Comment by cullub** [comment]
I wonder if selecting the vote div using `find('div.vote')` instead of simply `find('vote')` would help....

And I don't see where you compensate for the topbar - do you?  (If you don't, you could just add 36px, the height of the topbar)

**Comment by enki-code** [comment]
I believe an adjustment to the top padding or margin on the body element when the topbar is fixed will fix this, I'll add it to my list of things to look into.

**Comment by cullub** [comment]
Awesome.  Honestly, it's not a huge deal, but fixing it will make it feel a lot more smooth.

**Comment by somebody1234** [comment]
Can't you just change the condition so it toggles position on `> 34` instead of `> 0`?

**Comment by cullub** [comment]
Yay! Just tested, and it's fixed.
