### ISSUE TITLE
Fixed Topbar breaks askubuntu

### ISSUE THREAD

**Issue by enki-code** [soscripted/sox#20]
### Expected Behavior

The navbar should be fixed to the top of the screen in the correct position and the ubuntu related links should be placed somewhere without blocking content.

### Actual Behavior

The navbar is pushed to the right and not aligned correctly.

The sidebar collection of links that were cloned from the top are now blocking page content when viewing on small screens.

![ask-ubuntu-jacked](https://cloud.githubusercontent.com/assets/12533449/13555440/54ffff34-e375-11e5-9bb1-9f654d9882c0.png)

### Suggested Fix

I would suggest moving the cloned ubuntu related links directly below the fixed top bar, like so:
![ask-ubuntu-unjacked](https://cloud.githubusercontent.com/assets/12533449/13555479/538a77d2-e376-11e5-8116-793683ef0a8f.png)

**Comment by shu8** [comment]
@enki-code does `$('.fixedTopbar-stickyToolbar').css('margin-left', '-545px');` in console fix the topbar being too much to the right?

**Comment by enki-code** [comment]
@shu8 lets talk in chat.

**Comment by shu8** [comment]
fixed :)
