### ISSUE TITLE
Feature request: user flag in comment history

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#201]
### Current Behaviour
I comment on a lot of posts to provide feedback to the author.  It often relates to issues that can be fixed to avoid a close vote or downvote, or things that can be improved to warrant an upvote.  I go through the comment history periodically to revisit those posts to see if anything has changed (typically going back 2 or 3 days, or more if there was a weekend).

Watching the post for an edit will go a long way once the bugs are fixed.  But authors often respond with a comment, frequently without @ addressing.  So revisiting posts is still the tool of choice for this.

The drawback is that a substantial portion of the comments are on posts I don't need to revisit.  The author might have already dealt with the post, or there isn't an expectation that the author will return within the revisit window and the comment was just in case they do, or for the benefit of other readers.

It would be a time-saver if there was a way to flag comments in the history that can be ignored.  I suppose it would also work to flag ones to revisit, instead.  For that matter, it could be a general purpose flag that can be toggled on or off for any purpose the user wants it for.  I supposed people could even use it as another form of "favorite", for example, if they wanted to temporarily follow or check back on a post, and the comment is what they mentally associate with the process.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-linkedPostsInline","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn","Unsorted-showMetaReviewCount"]

**Comment by shu8** [comment]
@fixer1234 this kind-of sounds like my other "Favourites Enhancer" userscript does this, in effect...? 

Sorry if I'm not understanding properly :/

**Comment by fixer1234** [comment]
@shu8 No, that is tied to the question.  Maybe if it could be tied to answers, also, it might be a stand-in.  But even there, you can get long comment threads, which would require figuring out what was the comment being referenced.  BTW, I do  use that to supplement the favorites.

For example, that includes a category to facilitate using it to revisit downvoted questions, and that is a big advantage over nothing at all.  But it can't compete with the SOX feature that sends a message when a watched post (of any kind), is edited.  There are cases where the comment is the direct link of value, so being able to flag the comment, itself, will be much more effective than starting somewhere else and working through a chain to find it.

I was envisioning a "dumb" icon, a "stand-alone" screen element, the appearance of which could be toggled, positioned somewhere next to each comment in the comment history (better in a uniform location).  Clicking it would just toggle it between some "inactive" placeholder indicator and some visible "active" indicator.  For example, "active" could just be a colored, filled circle, and "inactive" could be an empty circle.  Users could employ it to indicate whatever they want.

**Comment by shu8** [comment]
@fixer1234 hmm ok... so an indicator something like this:

![this](https://cloud.githubusercontent.com/assets/8850830/21583489/5e257f0a-d07b-11e6-98ea-295735de07b9.png)

?

Do you have any thoughts on what the toggle button icon could be? I was thinking a 'pin' icon (http://fontawesome.io/icon/thumb-tack/), but that might not be right for this...? I'm not sure :/

**Comment by fixer1234** [comment]
@shu8 I assume you're talking about the bars on the left?  That's the general concept, but discreet indicators per comment.  The bars are a little confusing because they span multiple comments.

I love the thumbtacks, but that would be confusing if the icon was used to indicate comments to ignore.  Better to use one that doesn't have an implied meaning.  Maybe a circle or square, or a snowflake/asterisk/star.  Some form of checkmark could also work; that can be taken either way ("check this" or "done"), but maybe not as good as something totally ambiguous.

**Comment by shu8** [comment]
Hmmm ok thanks :)

I'll see what I can do over the next few days

**Comment by shu8** [comment]
@fixer1234 how about adding a http://fontawesome.io/icon/thumbs-o-up/, http://fontawesome.io/icon/thumbs-o-down/ icon next to each one?

**Comment by fixer1234** [comment]
@shu8 Just an opinion, but I think the most universal symbol that would cover the most possible uses would be something that has no implied meaning; just a placeholder to click on when inactive, and and a visible indicator for the active state (like an indicator light to signify that a switch is on).  

People could want to use it for a variety of purposes--flag things to follow-up on, flag things to ignore, bookmark something for possible reference, etc.  So a specific use could imply a positive or negative connotation, or even just "information".  Any symbol that implies a positive or negative value, or is associated with a specific purpose, may seem counter-intuitive to the way somebody wants to use it.  So I would go as ambiguous as possible (even though that would lack pizzazz).

However, a variation on the idea would be the ability to select from a limited list of symbols (sort of like the smiley face selectors).  In that case, there could be dots of various colors that the user makes some association with.  It could also include some symbols like thumbs up/down, thumbtack, "halt hand", "idea lightbulb", etc.  For a given comment, the user would have a choice of marker and could then code the comments list for multiple purposes.

**Comment by shu8** [comment]
#215 will probably serve this purpose because you'll be able to watch comment on a certain post, so I'm closing this. I don't think there's any point writing this feature if the other will essentially do that.

**Comment by fixer1234** [comment]
@shu8 They're different use cases.  There are things that are comment-specific that you want to track or flag for information.  For those, the direct route there is at or from the comment.  The feature here is to help identify, at the comment, whether there is some action or meaning associated with the comment.

#215 provides information somewhere else if something happened with any watched post.  This could end up either more akin to a new tab on the main page or a vague indicator of something new.  You can hunt through the information there to see if the watched post has shown up.  If it's there, you might luck out if the most recent action on that post or thread is the particular thing you're looking for.  But that feature won't be useful for scanning through old comments in your profile to spot ones you wanted to follow-up on in some way or flag for information purposes.

Think of the feature here more like a favorite marker at the comment.  The fact that there may be some news about the thread somewhere else isn't useful when you're in the comments list trying to differentiate them.
