### ISSUE TITLE
Answer edit box has misaligned frame

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#203]
### Current Behaviour

![image](https://cloud.githubusercontent.com/assets/1776164/21578445/c6de8c1e-cf34-11e6-9f8a-8330ab5d7fd6.png)

Compare this to the edit/answer box when SOX is not loaded:

![image](https://cloud.githubusercontent.com/assets/1776164/21578449/e6a0deda-cf34-11e6-861b-ef8a6c131ad0.png)

---

### SOX Errors logged to the browser console -- F12 (if available)

soup injecting fixes
VM2117:30 soup init complete
VM2117:30 soup setup complete
VM2167:563 SOX:  undefined
VM2167:563 SOX:  Object
VM2117:30 soup JS fixes applied
VM2117:30 soup subscribed to realtime feed for question 288803 on site 4
VM2167:563 SOX:  DEBUGGING SOX VERSION 2.0.3DEVw
VM2167:563 SOX:  ----------------saved variables---------------------
VM2167:587 SOX:  logging sox stored values --- 
VM2167:587 SOX:  access token set
VM2167:587 SOX:  SOX-debug
VM2167:587 SOX:  true
VM2167:587 SOX:  SOXSETTINGS
VM2167:587 SOX:  ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]
VM2167:587 SOX:  downvotedPostsEditAlert
VM2167:587 SOX:  {}
VM2167:587 SOX:  editReasons
VM2167:587 SOX:  [["formatting","Improved Formatting"],["spelling","Corrected Spelling"],["grammar","Fixed grammar"],["greetings","Removed thanks/greetings"]]
VM2167:587 SOX:  metaNewQuestionAlert-lastQuestions
VM2167:587 SOX:  {"meta.tex":"How to including multimedia files in beamer [Work in progress, please ignor for the moment]"}
VM2167:563 SOX:  ----------------end saved variables---------------------
VM2167:563 SOX:  initializing SOX dialog
VM2167:563 SOX:  injecting features into dialog
VM2167:563 SOX:  Object
VM2167:563 SOX:  running addAuthorNameToInboxNotifications
VM2167:563 SOX:  observe: .inbox-dialog
VM2167:563 SOX:  Object
VM2167:563 SOX:  Object
VM2167:563 SOX:  Object
VM2167:563 SOX:  running bulletReplace
VM2167:563 SOX:  Object
VM2167:563 SOX:  running colorAnswerer
VM2167:563 SOX:  observe: .new_comment
VM2167:563 SOX:  Object
VM2167:563 SOX:  running fixedTopbar
VM2167:563 SOX:  observe: #notify-container,#notify--1
VM2167:563 SOX:  Object
VM2167:563 SOX:  running highlightQuestions
VM2167:563 SOX:  Object
VM2167:563 SOX:  running isQuestionHot
VM2167:563 SOX:  Object
VM2167:563 SOX:  running markEmployees
VM2167:563 SOX:  SOX Access Token: SET
VM2167:563 SOX:  Object
VM2167:563 SOX:  running scrollToTop
VM2167:563 SOX:  Object
VM2167:563 SOX:  running spoilerTip
VM2167:563 SOX:  Object
VM2167:563 SOX:  running standOutDupeCloseMigrated
VM2167:563 SOX:  observe: #user-tab-questions, #question-mini-list
VM2167:563 SOX:  Object
VM2167:563 SOX:  Object
VM2167:563 SOX:  running topAnswers
VM2167:563 SOX:  Object
VM2167:563 SOX:  running unspoil
VM2167:563 SOX:  Object
VM2167:563 SOX:  running autoShowCommentImages
VM2167:563 SOX:  observe: .new_comment
VM2167:563 SOX:  Object
VM2167:563 SOX:  running commentReplies
VM2167:563 SOX:  observe: .new_comment
VM2167:563 SOX:  Object
VM2167:563 SOX:  running commentShortcuts
VM2167:563 SOX:  Object
VM2167:563 SOX:  running confirmNavigateAway
VM2167:563 SOX:  Object
VM2167:563 SOX:  running copyCommentsLink
VM2167:563 SOX:  Object
VM2167:563 SOX:  running moveBounty
VM2167:563 SOX:  Object
VM2167:563 SOX:  Object
VM2167:563 SOX:  running hiddenCommentsIndicator
VM2167:563 SOX:  Object
VM2167:563 SOX:  running addSBSBtn
VM2167:563 SOX:  observe: #wmd-redo-button-288809
VM2167:563 SOX:  observe: #wmd-redo-button-288804
VM2167:563 SOX:  observe: #wmd-redo-button-288803
VM2167:563 SOX:  observe: li[id^="wmd-redo-button"], textarea[id^="wmd-input"]
VM2167:563 SOX:  observe: .wmd-preview.sbs-on
VM2167:563 SOX:  Object
VM2167:563 SOX:  running editComment
VM2167:563 SOX:  Object
VM2167:563 SOX:  running editReasonTooltip
VM2167:563 SOX:  Object
VM2167:563 SOX:  running enhancedEditor
VM2167:563 SOX:  observe: li[id^="wmd-redo-button"], textarea[id^="wmd-input"]
VM2167:563 SOX:  Object
VM2167:563 SOX:  running kbdAndBullets
VM2167:563 SOX:  observe: [id^="wmd-redo-button"], textarea[id^="wmd-input"]
VM2167:563 SOX:  Object
VM2167:563 SOX:  Object
VM2167:563 SOX:  running inlineEditorEverywhere
VM2167:563 SOX:  Object
VM2167:563 SOX:  running downvotedPostsEditAlert
VM2167:563 SOX:  downvotedPostsEditAlert posts to check
VM2167:563 SOX:  Object
VM2167:563 SOX:  downvotedPostsEditAlert notifications
VM2167:563 SOX:  Object
VM2167:563 SOX:  Object
VM2167:563 SOX:  running flagOutcomeTime
VM2167:563 SOX:  Object
VM2167:563 SOX:  running flagPercentages
VM2167:563 SOX:  Object
VM2167:563 SOX:  running flagPercentageBar
VM2167:563 SOX:  Object
VM2167:563 SOX:  running hideHireMe
VM2167:563 SOX:  Object
VM2167:563 SOX:  running linkedToFrom
VM2167:563 SOX:  Object
VM2167:563 SOX:  Object
VM2167:563 SOX:  Object
VM2167:563 SOX:  running betterCSS
VM2167:563 SOX:  Object
VM2167:563 SOX:  running grayOutVotes
VM2167:563 SOX:  Object
VM2167:563 SOX:  running stickyVoteButtons
VM2167:563 SOX:  Object
VM2167:563 SOX:  running disableOwnPostVoteButtons
VM2167:563 SOX:  Object
VM2167:563 SOX:  running parseCrossSiteLinks
VM2167:563 SOX:  Object
VM2167:563 SOX:  running quickAuthorInfo
VM2167:563 SOX:  quickAuthorInfo answerer IDs
VM2167:563 SOX:  Object
VM2167:563 SOX:  quickAuthorInfo API call parameters
VM2167:563 SOX:  users
VM2167:563 SOX:  278543;311398
VM2167:563 SOX:  meta
VM2167:563 SOX:  SOX Access Token: SET
VM2167:563 SOX:  Getting From API with URL: https://api.stackexchange.com/2.2/users/278543;311398?order=desc&sort=creat…site=meta&key=lL1S1jr2m*DRwOvXMPp26g((&access_token=*lbphlZ4KYXlrwnIv(qKqQ))
VM2167:563 SOX:  SOX Access Token: SET
VM2167:8 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ VM2167:8
VM2167:563 SOX:  quickAuthorInfo api dump
VM2167:563 SOX:  Object
VM2167:563 SOX:  quickAuthorInfor userdetailsfromapi
VM2167:563 SOX:  Object
VM2167:563 SOX:  current post
VM2167:563 SOX:  n.fn.init[1]
VM2167:563 SOX:  quickAuthorInfo addLastSeen(): current id
VM2167:563 SOX:  311398
VM2167:563 SOX:  quickAuthorInfo addLastSeen(): userdetailscurrent id
VM2167:563 SOX:  Object
VM2167:563 SOX:  current post
VM2167:563 SOX:  n.fn.init[1]
VM2167:563 SOX:  quickAuthorInfo addLastSeen(): current id
VM2167:563 SOX:  311398
VM2167:563 SOX:  quickAuthorInfo addLastSeen(): userdetailscurrent id
VM2167:563 SOX:  Object
VM2167:563 SOX:  current post
VM2167:563 SOX:  n.fn.init[1]
VM2167:563 SOX:  quickAuthorInfo addLastSeen(): current id
VM2167:563 SOX:  278543
VM2167:563 SOX:  quickAuthorInfo addLastSeen(): userdetailscurrent id
VM2167:563 SOX:  Object
VM2167:563 SOX:  observe: .new_comment
VM2167:563 SOX:  Object
VM2167:563 SOX:  running shareLinksMarkdown
VM2167:563 SOX:  observe: .share-tip
VM2167:563 SOX:  Object
VM2167:563 SOX:  running warnNotLoggedIn
VM2167:563 SOX:  SOX editReasonTooltip URL: http://meta.stackexchange.com/posts/288803/revisions
VM2167:563 SOX:  SOX editReasonTooltip text: deleted 2 characters in body; edited tags; edited title
VM2167:563 SOX:  SOX editReasonTooltip: adding to tooltip
VM2167:563 SOX:  SOX editReasonTooltip: finished adding to tooltip
VM2167:563 SOX:  SOX editReasonTooltip: tooltip is now: deleted 2 characters in body; edited tags; edited title
VM2167:563 SOX:  SOX editReasonTooltip URL: http://meta.stackexchange.com/posts/288804/revisions
VM2167:563 SOX:  SOX editReasonTooltip text: added 316 characters in body
VM2167:563SOX:  SOX editReasonTooltip: adding to tooltip
VM2167:563SOX:  SOX editReasonTooltip: finished adding to tooltip
VM2167:563SOX:  SOX editReasonTooltip: tooltip is now: added 316 characters in body
VM2167:563SOX:  SOX editReasonTooltip URL: http://meta.stackexchange.com/posts/288809/revisions
VM2167:563SOX:  SOX editReasonTooltip text: added 17 characters in body
VM2167:563SOX:  SOX editReasonTooltip: adding to tooltip
VM2167:563SOX:  SOX editReasonTooltip: finished adding to tooltip
VM2167:563SOX:  SOX editReasonTooltip: tooltip is now: added 17 characters in body
DevTools failed to parse SourceMap: http://meta.stackexchange.com/questions/288803/jquery.timeago.min.js.map

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]

**Comment by shu8** [comment]
Thanks. I think this was to do with the enhanced editor feature (find
replace) and I couldn't figure out which CSS was causing it.

This might make me a bit more determined now :P

**Comment by shu8** [comment]
@wgrundlingh fixed in [dev y](https://github.com/soscripted/sox/raw/dev/sox.user.js)
