### ISSUE TITLE
Update quickAuthorInfo to use the same time zone and format as regular SE

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#204]
### Current Behaviour

Current SE time stamps show as `YYYY-MM-DD hh:mm:ssZ` (with **UTC** reference). In contrast, quickAuthorInfo uses `DD/MM/YYYY, hh:mm:ss` (with **local** reference):

![tex-se](https://cloud.githubusercontent.com/assets/1776164/21579541/9c287db8-cf6b-11e6-9391-d646880d5629.gif)

Can these two be made similar? That is, quickAuthorInfo time stamps should match the zone & format of the regular SE time stamp?

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]

**Comment by shu8** [comment]
@wgrundlingh done in [dev y](https://github.com/soscripted/sox/raw/dev/sox.user.js)

the relative time is still local, but the tooltip is UTC to make it more consistent

**Comment by wgrundlingh** [comment]
The tooltips still show content differently:
  
![tex-se](https://cloud.githubusercontent.com/assets/1776164/21582747/8b99248a-d019-11e6-9987-acece6cd9627.gif)

Is this the intent? I thought it would look better if the formatting is similar: `YYYY/MM/DD hh:mm:ssZ`.

**Comment by shu8** [comment]
@wgrundlingh I have no idea how I missed that... :/ 

done in [dev z](https://github.com/soscripted/sox/raw/dev/sox.user.js)
