### ISSUE TITLE
Title toggle is having babies

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#206]
### Current Behaviour
It's always something; that's the rule.  The title toggle is interacting with the fixed topbar.  Every time scrolling on the Edit Review page passes the title toggle under the topbar, the icon replicates:

![sox title toggle](https://cloud.githubusercontent.com/assets/10065766/21598397/4e99804a-d12a-11e6-89f1-3c1c416889d8.png)

---

### SOX Errors logged to the browser console -- F12 (if available)
I can capture some console output if it will be helpful, but I suspect this is some obvious forehead smacker.  Let me know.

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-linkedPostsInline","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn","Unsorted-showMetaReviewCount"]

**Comment by shu8** [comment]
Thanks, I've reproduced it. I'll push a fix later today

**Comment by shu8** [comment]
@fixer1234 @wgrundlingh fixed in [dev ae](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
