### ISSUE TITLE
Incorrect migrated tooltip

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#210]
### Current Behaviour

![tex-se](https://cloud.githubusercontent.com/assets/1776164/21664256/43f2bb2c-d29a-11e6-88c7-79ea0c285db1.gif)

---

### SOX Errors logged to the browser console -- F12 (if available)

soup injecting fixes
VM346:30 soup init complete
VM346:30 soup setup complete
VM353:563SOX:  undefined
VM353:563SOX:  Object {debug: Object, initialized: Object, helpers: Object, _gps_track: Array[0], gps: Object…}
VM346:30 soup JS fixes applied
VM353:563 SOX:  DEBUGGING SOX VERSION 2.0.3DEVaf
VM353:563 SOX:  ----------------saved variables---------------------
VM353:587 SOX:  logging sox stored values --- 
VM353:587 SOX:  access token set
VM353:587 SOX:  SOX-debug
VM353:587 SOX:  true
VM353:587 SOX:  SOXSETTINGS
VM353:587 SOX:  ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn","Unsorted-showMetaReviewCount"]
VM353:587 SOX:  downvotedPostsEditAlert
VM353:587 SOX:  {}
VM353:587 SOX:  editReasons
VM353:587 SOX:  [["Markdown update","Updated markdown."],["MWE","[minimal working example](http://meta.tex.stackexchange.com/q/228/5764)"]]
VM353:587 SOX:  metaNewQuestionAlert-lastQuestions
VM353:587 SOX:  {"meta.tex":"How to including multimedia files in beamer [Work in progress, please ignor for the moment]"}
VM353:563 SOX:  ----------------end saved variables---------------------
VM353:563 SOX:  initializing SOX dialog
VM353:563 SOX:  injecting features into dialog
VM353:563 SOX:  Object {name: "addAuthorNameToInboxNotifications", desc: "Add the author's name to notifications in the inbox", extended_description: "If you receive a comment/answer/suggested edit not…or of the comment/answer/edit to the notification", meta: "", match: ""…}
VM353:563 SOX:  running addAuthorNameToInboxNotifications
VM353:563 SOX:  observe: .inbox-dialog
VM353:563 SOX:  Object {name: "alignBadgesByClass", desc: "Align badges by their class on user profile pages", meta: "http://meta.stackexchange.com/q/254607/260841", match: "*://*/users/*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "answerTagsSearch", desc: "Show tags for the question an answer belongs to on search pages (for better context)", extended_description: "By default, any search results thar are answers do…e adds the question's tags underneath the result.", meta: "http://meta.stackexchange.com/questions/197874/include-tags-in-answers-entries-on-search-results", match: "*://*.com/search*"…}
VM353:563 SOX:  running answerTagsSearch
VM353:563 SOX:  SOX Access Token: SET
VM353:563 SOX:  Getting From API with URL: https://api.stackexchange.com/2.2/questions/?order=desc&sort=creation&pages…site=meta&key=lL1S1jr2m*DRwOvXMPp26g((&access_token=e2VVaHLYkmc2GEGYEiIyNQ))
VM353:563 SOX:  SOX Access Token: SET
VM353:563 SOX:  Object {name: "colorAnswerer", desc: "Color answerer's comments", extended_description: "Highlight the username of a commenter if they have posted an answer on that page.", meta: "http://meta.stackexchange.com/questions/19574/high…from-answer-author-in-addition-to-question-author", match: "*://*/questions*"…}
VM353:563 SOX:  Object {name: "fixedTopbar", desc: "Fix topbar position", extended_description: "Locks the topbar to the top of the window so you c…buntu due to the different styling of the topbar.", meta: "http://meta.stackexchange.com/questions/101385/should-the-top-navigation-be-frozen-optional", match: ""…}
VM353:563 SOX:  running fixedTopbar
VM353:563 SOX:  observe: #notify-container,#notify--1
VM353:563 SOX:  Object {name: "highlightQuestions", desc: "Change highlighting for questions with favourite tags", extended_description: "Changes the favourite tag question highlighting to be a more subtle, coloured left-border", meta: "http://meta.stackexchange.com/questions/238591/sho…ite-tag-highlighting-in-question-lists-be-changed", match: ""…}
VM353:563 SOX:  running highlightQuestions
VM353:563 SOX:  Object {name: "isQuestionHot", desc: "Add a label on questions which are hot-network questions", extended_description: "If the question you are currently viewing is HOT, a flame icon is added next to the title", meta: "http://meta.stackexchange.com/questions/245390/let-mods-and-10k-know-when-questions-go-hot", match: "*://*/questions*"…}
VM353:563 SOX:  Object {name: "markEmployees", desc: "Add the SO logo after employee names to make them stand out", meta: "http://meta.stackexchange.com/questions/246678/sho…staff-have-a-special-character-in-their-user-name", match: "", exclude: "*://chat.*.com/*,SE1.0"}
VM353:563 SOX:  running markEmployees
VM353:563 SOX:  SOX Access Token: SET
VM353:563 SOX:  Object {name: "scrollToTop", desc: "Add Scroll To Top button", extended_description: "This feature adds a 'scroll to top' button at the …hat will jump to the top of the page when clicked", meta: "", match: ""…}
VM353:563 SOX:  running scrollToTop
VM353:563 SOX:  Object {name: "spoilerTip", desc: "Differentiate spoilers from empty blockquotes", meta: "http://meta.stackexchange.com/questions/104085/differentiate-spoilers-from-empty-block-quotes", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "standOutDupeCloseMigrated", desc: "Add highlighted tags to closed/on hold/duplicate/migrated questions on question lists", extended_description: "Adds a coloured box at the end of a title (that re… more easily tell what the state of a question is", meta: "http://meta.stackexchange.com/questions/257021/pro…ate-closed-and-migrated-in-the-title-more-obvious", match: ""…}
VM353:563 SOX:  running standOutDupeCloseMigrated
VM353:563 SOX:  observe: #user-tab-questions, #question-mini-list
VM353:563 SOX:  Object {name: "tabularReviewerStats", desc: "Display reviewer stats on /review/suggested-edits in table form", meta: "http://meta.stackexchange.com/q/276946/260841", match: "*://*.com/review/suggested-edits/*", exclude: ""}
VM353:563 SOX:  Object {name: "topAnswers", desc: "Improve answer visibility by listing top answers", meta: "", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "unspoil", desc: "Add a link to the bottom of a post to reveal all spoilers in a post", meta: "http://meta.stackexchange.com/questions/249808/add…ay-to-reveal-all-spoiler-blocks-in-a-post-at-once", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "autoShowCommentImages", desc: "View linked images (to imgur) in comments inline", extended_description: "This feature will automatically detect comments with links to imgur and will display them inline", meta: "", match: "*://*/questions*"…}
VM353:563 SOX:  Object {name: "commentReplies", desc: "Add reply links to comments for quick replying (without having to type someone's username)", meta: "http://meta.stackexchange.com/questions/74778/add-…ment-that-pre-populates-comment-box-with-username", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "commentShortcuts", desc: "Use Ctrl+I,B,K (to italicise, bolden and add code backticks) in comments", meta: "http://meta.stackexchange.com/questions/14756/formatting-keyboard-shortcuts-for-comments", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "confirmNavigateAway", desc: "Add a confirmation dialog when navigating away on pages whilst still typing a comment", meta: "http://meta.stackexchange.com/questions/252205/add…-navigate-away-from-this-page-when-writing-a-comm", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "copyCommentsLink", desc: "Copy 'show x more comments' link to the top", meta: "http://meta.stackexchange.com/questions/55020/add-…-comments-button-to-the-top-of-a-list-of-comments", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "moveBounty", desc: "Move the 'start a bounty' link to before the comments", meta: "http://meta.stackexchange.com/questions/234095/can…-move-start-a-bounty-to-a-more-intuitive-location", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "showCommentScores", desc: "Show your comment and comment replies scores in your profile tabs", extended_description: "Adds a button next to comments in your profile's r… when clicked, show you the score of your comment", meta: "http://meta.stackexchange.com/questions/38285/disp…umber-of-comment-upvotes-in-recent-activity-pages", match: "*://*/users/*"…}
VM353:563 SOX:  Object {name: "hiddenCommentsIndicator", desc: "Add a darker border underneath comments if there are some hidden after it", meta: "http://meta.stackoverflow.com/q/296582/3541881", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "addSBSBtn", desc: "Add a button to the editor toolbar to start side-by-side editing", extended_description: "An 'SBS' button is added to the right of the markd… the markdown and the preview appear side-by-side", meta: "http://meta.stackexchange.com/questions/253112/the…iscourse-layout-for-side-by-side-markdown-preview", match: ""…}
VM353:563 SOX:  running addSBSBtn
VM353:563 SOX:  observe: li[id^="wmd-redo-button"], textarea[id^="wmd-input"]
VM353:563 SOX:  observe: .wmd-preview.sbs-on
VM353:563 SOX:  Object {name: "editComment", desc: "Pre-defined edit comment options (checkboxes)", extended_description: "Adds checkboxes to add canned messages for edit re… is added to the Help dropdown menu in the topbar", meta: "http://meta.stackexchange.com/questions/190461/imp…ing-flow-with-predefined-options-for-edit-summary", match: ""…}
VM353:563 SOX:  running editComment
VM353:563 SOX:  Object {name: "editReasonTooltip", desc: "Add a tooltip to posts showing the last revision's…on the word 'edited' in 'edited [date] at [time]'", extended_description: "When a post is edited, the editor is displayed und…d' underneath a post in 'edited [date] at [time]'", meta: "http://meta.stackexchange.com/questions/2315/show-reason-for-edit-without-clicking-through-to-diff", match: "*://*/questions*"…}
VM353:563 SOX:  Object {name: "enhancedEditor", desc: "Add more features to the markdown editor", extended_description: "Adds find/replace, changes the TAB key behaviour, …kGo integration, and basic auto-correct features.", meta: "", match: "*://*/questions*,*://*/review*"…}
VM353:563 SOX:  Object {name: "kbdAndBullets", desc: "Add KBD and list buttons to editor toolbar", extended_description: "Adds a kbd and bullet icon to the markdown editor … with KBD tags or listify's the current selection", meta: "http://meta.stackexchange.com/questions/102841/key-equivalent-for-kbd-kbd", match: "*://*/questions*"…}
VM353:563 SOX:  Object {name: "titleEditDiff", desc: "Make title edits show separately rather than merged in edit suggestions", meta: "http://meta.stackexchange.com/questions/135710/please-show-changed-titles-separately-in-edit-diffs", match: "*://*.com/review/suggested-edits*", exclude: ""}
VM353:563 SOX:  Object {name: "inlineEditorEverywhere", desc: "Inline editor regardless of reputation", extended_description: "Enables the inline editor on all sites, even if yo… yet. Note: this feature may not work on Firefox.", meta: "", match: "*://*/questions*"…}
VM353:563 SOX:  Object {name: "downvotedPostsEditAlert", desc: "Add a notification to your inbox when a question you downvote is edited", meta: "http://meta.stackexchange.com/q/165962/260841", match: "", exclude: ""}
VM353:563 SOX:  running downvotedPostsEditAlert
VM353:563 SOX:  downvotedPostsEditAlert posts to check
VM353:563 SOX:  Object {}
VM353:563 SOX:  downvotedPostsEditAlert notifications
VM353:563 SOX:  Object {}
VM353:563 SOX:  Object {name: "flagOutcomeTime", desc: "Show the flag outcome time when viewing your Flag History", meta: "", match: "", exclude: "*://chat.*.com/*,SE1.0"}
VM353:563 SOX:  running flagOutcomeTime
VM353:563 SOX:  Object {name: "flagPercentages", desc: "Show flagging percentages for each type in the Flag Summary", meta: "", match: "", exclude: "*://chat.*.com/*,SE1.0"}
VM353:563 SOX:  running flagPercentages
VM353:563 SOX:  Object {name: "flagPercentageBar", desc: "Show the total percentage of helpful flags as a coloured bar on the Flag Summary Page", meta: "http://meta.stackoverflow.com/questions/310881/overall-percentage-of-helpful-flags", match: "", exclude: "*://chat.*.com/*,SE1.0"}
VM353:563 SOX:  running flagPercentageBar
VM353:563 SOX:  Object {name: "hideHireMe", desc: "Hide the Looking for a Job module", meta: "", match: "", exclude: "*://chat.*.com/*"}
VM353:563 SOX:  running hideHireMe
VM353:563 SOX:  Object {name: "linkedToFrom", desc: "Add an arrow to linked posts in the sidebar to show whether they are linked to or linked from", meta: "http://meta.stackexchange.com/q/276235/260841", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "chatEasyAccess", desc: "Add buttons to user profiles to change user write access directly from a chat room", meta: "http://meta.stackexchange.com/q/203480/260841", match: "*://chat.*.com/*", exclude: ""}
VM353:563 SOX:  Object {name: "renameChat", desc: "Prepend 'Chat - ' to chat tabs' titles", meta: "http://meta.stackexchange.com/questions/246289/cha…-on-chat-pages-to-chat-sitename-or-chat-room-name", match: "*://chat.*.com/*", exclude: ""}
VM353:563 SOX:  Object {name: "betterCSS", desc: "Add extra CSS for animation actions on voting and favourite buttons", extended_description: "Pulse effect when hovering over the upvote/downvot…urrently only implemented natively on Android.SE.", meta: "http://meta.stackexchange.com/questions/252685/i-w…oting-animations-like-on-android-se-pretty-please", match: "*://*/questions*"…}
VM353:563 SOX:  Object {name: "grayOutVotes", desc: "Gray out deleted vote buttons", meta: "http://meta.stackexchange.com/a/174806/260841", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "stickyVoteButtons", desc: "Make vote buttons next to posts sticky whilst scrolling on that post", meta: "http://meta.stackexchange.com/a/35047/260841", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "disableOwnPostVoteButtons", desc: "Disable vote buttons on your own posts", meta: "", match: "*://*/questions*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "parseCrossSiteLinks", desc: "Parse titles to links cross-SE-sites", extended_description: "Detects links to other questions on SE sites and converts them to their title", meta: "http://meta.stackexchange.com/questions/251183/parse-question-links-from-other-se-sites", match: "*://*/questions*"…}
VM353:563 SOX:  Object {name: "quickAuthorInfo", desc: "Show when the post's author was last seen and whether they are registered", meta: "", match: "*://*/questions*,*://*/review*", exclude: "SE1.0"}
VM353:563 SOX:  Object {name: "shareLinksMarkdown", desc: "Change 'share' link to format of [post-name](url)", extended_description: "When you click 'share' under a post, this will con…lly copies the converted string to your clipboard", meta: "http://meta.stackexchange.com/questions/126544/add…nd-share-button-to-posts-with-comment-ready-links", match: "*://*/questions*"…}
VM353:563 SOX:  Object {name: "warnNotLoggedIn", desc: "Warn you when you are not logged in", meta: "", match: "", exclude: "*://chat.*.com/*,SE1.0"}
VM353:563 SOX:  running warnNotLoggedIn
VM353:563 SOX:  Object {name: "showMetaReviewCount", desc: "Add how many reviews are available on Meta to the main site review page", meta: "", match: "*://*/review", exclude: "*://meta.*.com/*"}
VM353:563 SOX:  observe: .new_comment
kopal-first-ad.png:1 GET http://lh4.ggpht.com/_Er7KBHV51-k/S3wgCl5VKfI/AAAAAAAAAkY/SR1o7vo3Vao/kopal-first-ad.png 403 (Forbidden)
files.quickmediasolutions.com/sopp_ad.png:1 GET http://files.quickmediasolutions.com/sopp_ad.png 404 (Not Found)
keenhead.gif:1 GET http://img682.imageshack.us/img682/609/keenhead.gif 404 (Not Found)
numberonen.jpg:1 GET http://img299.imageshack.us/img299/9724/numberonen.jpg 404 (Not Found)
welbog.homeip.net/~inferno/images/so/atwoodian-conspiracy.png:1 GET http://welbog.homeip.net/~inferno/images/so/atwoodian-conspiracy.png net::ERR_NAME_NOT_RESOLVED

---

### Steps to reproduce

Find any "migrated" post in
  http://meta.stackexchange.com/search?q=closed%3A1
and hover over the standOutDupeClosedMigrated.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn","Unsorted-showMetaReviewCount"]

**Comment by enki-code** [comment]
Nice catch, thank you for reporting this. We'll get it fixed up as soon as possible.

**Comment by shu8** [comment]
@wgrundlingh thanks, fixed [in dev 2.0.4](https://github.com/soscripted/sox/raw/dev/sox.user.js) (we've changed the versioning to numbers now, so no more letters)

I'd only accounted for migrations *away* from the current site; fixed now to take into account the direction :)

@enki-code fixed
