### ISSUE TITLE
Apostrophe in tooltip drops remaining text

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#211]
### Current Behaviour

The standOutDupeCloseMigrated feature grabs the "closed reason" and displays it in the tooltip. However, if the "closed reason" contains a single apostrophe (or quote) ', then all text after it is dropped from the tooltip text.

In the example below, I've used TeX.SE since we have a number of questions closed as being "unclear what you've asked":

![tex-se](https://cloud.githubusercontent.com/assets/1776164/21665315/c3271806-d2a0-11e6-95cf-a74f07c72848.gif)

Note that the "year" is dropped from the text ('14) and that everything after "'ve asked..." as well in the second example.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

Find some examples here:
  http://tex.stackexchange.com/search?q=closed%3A1

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn","Unsorted-showMetaReviewCount"]

**Comment by enki-code** [comment]
Thanks, I'll try to investigate this tomorrow. Should be something simple.

**Comment by shu8** [comment]
@wgrundlingh thanks, fixed [in dev 2.0.4](https://github.com/soscripted/sox/raw/dev/sox.user.js) (we've changed the versioning to numbers now, so no more letters)

@enki-code fixed
