### ISSUE TITLE
Edit comment tooltip doesn't work in review queue

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#212]
### Current Behaviour
I don't recall whether the edit comment tooltip on hover used to work in the review queue (or whether it's intended to work there).  Just discovered that it doesn't, at least in v2.0.5.  If it isn't part of the feature, let me request it, because it's as useful in the review queue as in a regular thread.  If this is a bug and console output would help, let me know.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Comments-autoShowCommentImages","Comments-commentReplies","Comments-confirmNavigateAway","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Sidebar-hideHireMe","Chat-renameChat","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-warnNotLoggedIn","Extras-showMetaReviewCount"]

**Comment by shu8** [comment]
done in [dev 2.0.6](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 Confirmed.
