### ISSUE TITLE
Enter saved token doesn't work

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#213]
### Current Behaviour
I'm pretty sure I mentioned this on another issue, which I can't find now, and it can't be tracked as just a comment, so I'll post it as an actual issue.  A key icon was added to the SOX menu to enable entering a saved token.  This has never worked for me.  The entry window pops up, I paste the token and save, but the entered token is never used as a valid one (features requiring a token continue to not work until I generate a new token).

A recent test seemed to indicate that tokens might be associated with an installation rather than an account.  If that's the case, trying to use a token from a different installation might not work.  Don't know if this feature has worked for others, but I'll post this as input.  If reuse of a token isn't possible, the key could be streamlined to just generate a new token.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Comments-autoShowCommentImages","Comments-commentReplies","Comments-confirmNavigateAway","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Sidebar-hideHireMe","Chat-renameChat","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-warnNotLoggedIn","Extras-showMetaReviewCount"]

**Comment by shu8** [comment]
@fixer1234 yeah, it doesn't look like we actually need to be able to input our own keys now. so I'll change that to just generate a new key asap

**Comment by shu8** [comment]
@fixer1234 done in [dev 2.0.6](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 Nice implementation.
