### ISSUE TITLE
hiddenCommentsIndicator not active in review queue

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#214]
### Current Behaviour

Hidden comments are currently not active within the review queue:

![image](https://cloud.githubusercontent.com/assets/1776164/21733129/b55b5440-d411-11e6-8416-edcfa15261ef.png)

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

If you're able to view the closed review queue on TeX.SE:
  http://tex.stackexchange.com/review/close/112028

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount"]

**Comment by shu8** [comment]
fixed in [dev 2.0.8](https://github.com/soscripted/sox/raw/dev/sox.user.js) -- I'd just not enabled it for review pages :/
