### ISSUE TITLE
No titleEditDiff needed for tag wiki's or excerpts

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#216]
### Current Behaviour

There is no need an active titleEditDiff when reviewing suggested edits on tag wiki's or excerpts, since they don't have a title, nor would the tag change.

![image](https://cloud.githubusercontent.com/assets/1776164/21739746/e58d47a8-d458-11e6-9021-9eb8a71f98a4.png)

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

See
  http://meta.stackexchange.com/review/suggested-edits/48596

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount"]

**Comment by shu8** [comment]
fixed in [dev 2.0.7](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
