### ISSUE TITLE
Review queue count for Meta incorrect

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#217]
### Current Behaviour
Earlier today, there was a post in one of the Meta site review queues, which was reflected on the main site review queue page.  It was reviewed.  Now the Meta site review queues all show zero available reviews.  On the main site Review queues, the new Meta reviews count is still showing as 1.

Update:  ~1/2 hr later, the Meta count is again showing 0, so this feature may be tapping into a cached value or something that is infrequently refreshed.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Comments-autoShowCommentImages","Comments-commentReplies","Comments-confirmNavigateAway","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Sidebar-hideHireMe","Chat-renameChat","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-warnNotLoggedIn","Extras-showMetaReviewCount"]

**Comment by shu8** [comment]
That was probably caching because the script GETs the page exactly like the browser would so it may have cached it. 

If this happens again, try a 'hard refresh' of the review page and see if it still happens :)

**Comment by fixer1234** [comment]
@shu8 I did a page refresh a number of times.  What's a "hard refresh"?

**Comment by shu8** [comment]
@fixer1234 a way to refresh a single page without cache: https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/

seems like it's Ctrl Shift R for FF

**Comment by enki-code** [comment]
@fixer1234  @shu8 The commands to do a hard refresh are different depending on OS. Typically Control + F5 does the trick. Here is a good article on it https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/

**Comment by shu8** [comment]
I'm going to close this. Feel free to comment back if you notice it happen again :)

**Comment by fixer1234** [comment]
@shu8 OK, the problem has recurred continuously and on multiple platforms (for probably the better part of a week).  Meta count always shows 1 even though it has been 0 for days.  Problem includes platform where I just updated SOX from a version that didn't previously have this feature.  Hard refresh didn't affect it.  The platforms all use some version of Firefox, the bane of your existence.
