### ISSUE TITLE
Copy code from code block

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#218]
### Current Behaviour

I currently use [the following script](  https://gist.github.com/kpym/30d90be41ab5c248cdf7/raw/cc21badb01bb8d85f00f257697413e51f85608eb/Copy%2520code%2520from%2520SX%2520v2.user.js) to allow one to copy a code block from a post. It adds a

![image](https://cloud.githubusercontent.com/assets/1776164/21746286/1cfa1cd4-d4f4-11e6-899a-08b12f698792.png)

to the top-right of the code block which changes to

![image](https://cloud.githubusercontent.com/assets/1776164/21746291/386ea016-d4f4-11e6-9a78-26778818e383.png)

once the copy was successful.

This is a very useful feature and seems to be in-line with something that could also be offered a part of SOX. Could it be added?

One could use the [clipboard copy icon from FontAwesome](http://fontawesome.io/icon/clipboard/) in some way.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount"]

**Comment by enki-code** [comment]
Absolutely. Should be available in the next release.

**Comment by shu8** [comment]
done in dev [2.0.9](https://github.com/soscripted/sox/raw/dev/sox.user.js)

![this](https://cloud.githubusercontent.com/assets/8850830/21750575/16c3c71a-d5ae-11e6-8b4b-aed33f55dcb5.gif)

the button appears on hover of the code.

It's the last one in the Extras section. Happy to change any UI-related things about it :)

**Comment by fixer1234** [comment]
@wgrundlingh This feature showed up in SOX.  There isn't yet a wiki entry for it, but I found this feature request that looks like its origination.  What, exactly, does this feature do (why is it needed to copy a code block)?  I've always just used normal copy procedures.  Is the idea here that hovering anywhere in a code block identifies the entire block and copies it to the clipboard in one click?

**Comment by wgrundlingh** [comment]
@fixer1234 On TeX.SE where I contribute most of my time, users often post a minimal example that is a complete set of code. Often this could be a large-ish piece of code that becomes tedious to copy-and-paste using a click-and-drag method. It's easier to copy the entire code in one click to then paste in your coding editor.

I've grown used to this type of usage, and the single-click copy-to-clipboard is *extremely* useful. Perhaps other sites might be less prone to using this feature since code may be posted in one-liners or a very short snippets.

**Comment by wgrundlingh** [comment]
@shu8 Would it be possible to make this feature stick to the top right corner of the code block even if one scrolls up/down so it's always visible?

**Comment by enki-code** [comment]
@wgrundlingh Yes, we can make the button sticky. :)  I will try to work on some stuff this weekend.

**Comment by wgrundlingh** [comment]
@enki-code Here's perhaps another reason for it to be sticky (and stay *on top of the code block*):

![tex-se](https://cloud.githubusercontent.com/assets/1776164/21957597/7a840b12-da4e-11e6-9f8b-683337ea03a9.gif)

Taken from any one-liner of code. Here's one:
  [page number \raggedleft in table of contents](http://tex.stackexchange.com/q/348709/5764)

**Comment by wgrundlingh** [comment]
Another reason for sticky-ness:

![tex-se](https://cloud.githubusercontent.com/assets/1776164/21994618/6c33cf38-dbd5-11e6-8349-b5ebc86b663d.gif)

Wide code blocks have a movable copy-and-paste icon.

**Comment by enki-code** [comment]
As far as placement goes, would you rather have it fixed at the top left corner? Sorry for the delay on getting this done.

**Comment by wgrundlingh** [comment]
@enki-code Yes, fixed in the top-right corner. That makes logical sense.

**Comment by shu8** [comment]
@wgrundlingh this is partially fixed in [dev 2.0.23](https://github.com/soscripted/sox/raw/dev/sox.user.js)... it'll stay visible whilst you scroll down a long code section and will stay visible on one-liners, but the issue where it stays on the original right side when horizontally scrolling remains... (no idea how to fix that)

**Comment by wgrundlingh** [comment]
@shu8 Thanks for this work... If I knew how to code (in whichever language it is you do this), I would help out, but I don't, unfortunately.

Here's a small bug in the meantime: Suggested edits can show two copy-to-clipboard buttons:

![image](https://cloud.githubusercontent.com/assets/1776164/23137155/4c787c84-f755-11e6-946c-a58b8ec45461.png)

See this: http://tex.stackexchange.com/review/suggested-edits/115249

**Comment by shu8** [comment]
@wgrundlingh 😆 no problem! I'll get this one fixed as well soon :)

**Comment by shu8** [comment]
@wgrundlingh that's been fixed in the latest dev version :)

**Comment by Sir-Cumference** [comment]
@shu8 I wrote a solution:

    copyCode: function() {
        // Description: Add a button to code in posts to let you copy it

        //button uses CSS mainly from http://stackoverflow.com/a/30810322/3541881
        function addButton() {
            //https://github.com/soscripted/sox/issues/218#issuecomment-281148327 reason for selector:
            //http://stackoverflow.com/a/11061657/3541881

            $('pre:not(:has(.sox-copyCodeButton))').before('<i class="fa fa-clipboard sox-copyCodeButton" style="display:none; background-color:#eff0f1; margin-left: -15px;"></i>');

            $('pre').hover(function() {
                $(this).prev('.sox-copyCodeButton').show();
            }, function() {
                $(this).prev('.sox-copyCodeButton').hide();
            });

            $('.sox-copyCodeButton').hover(function() {
                $(this).show();
            }, function() {
                $(this).hide();
            });
        }

        addButton();
        $(document).on('sox-new-review-post-appeared', addButton);

        $(document).on('click', '.sox-copyCodeButton', function() {
            try {
                if (!$('.sox-copyCodeTextarea').length) $('body').append('<textarea class="sox-copyCodeTextarea">');
                $('.sox-copyCodeTextarea').val($(this).next('pre').text());
                $('.sox-copyCodeTextarea').select();
                document.execCommand('copy');
                $(this).effect("highlight", {
                    color: 'white'
                }, 3000);
            } catch (e) {
                sox.info('Browser doesn\'t support execComand for copyCode feature');
            }
        });
    },

It might be a bit hacky, but hopefully it works properly. :)

**Comment by shu8** [comment]
@Sir-Cumference thanks! It works great!! :)

@wgrundlingh fixed, completely, in [dev 2.0.26](https://github.com/soscripted/sox/raw/dev/sox.user.js), thanks to @Sir-Cumference! :)
