### ISSUE TITLE
autoShowCommentImages doesn't work for imgur-only images

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#219]
### Current Behaviour

Imgur-only links in comments seems broken:

![image](https://cloud.githubusercontent.com/assets/1776164/21748327/142f79bc-d537-11e6-8aec-50bf2932be57.png)

Perhaps it currently only works for i.stack.imgur.com images...?

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

See [Table does not fit on page](http://tex.stackexchange.com/q/347672/5764) for an imgur-only image link.

See [Doesn't the Winter Bash hat thing promote bad questions and/or answers?](http://meta.stackexchange.com/q/289387/168244) for an i.stack.imgur.com link.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount"]

**Comment by shu8** [comment]
@wgrundlingh it should work for both imgur and stack imgur, but the user posted the link to http://imgur.com/a/XHyJP, which isn't actually the image file, it's the album that imgur creates for the image. the actual image is at http://i.imgur.com/cj5Gl1g.png which the script can't really figure out :/

**Comment by wgrundlingh** [comment]
@shu8 Yes. Would it be possible to distinguish between imgur.com and i.imgur.com images?

**Comment by shu8** [comment]
@wgrundlingh yes, I've added a check in (locally atm) to make sure the link is to a real image URL :)

**Comment by shu8** [comment]
(just pushed it in [dev 2.0.10](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
