### ISSUE TITLE
Advanced Editor issues

### ISSUE THREAD

**Issue by enki-code** [soscripted/sox#22]
### Expected Behavior
- Find and Replace button should toggle the toolbar.
- Insert Code button dialog should have some content.

### Actual Behavior
As of right now it just keeps adding toolbars.
![ace-editor-fr-fail](https://cloud.githubusercontent.com/assets/12533449/13556276/8f00feb2-e38a-11e5-9c73-dcf6b1546bb4.png)

The Insert Code dialog is also having issues, it is being displayed, it just doesn't have any content.
![ace-editor-insert-fail](https://cloud.githubusercontent.com/assets/12533449/13556290/c098f75e-e38a-11e5-8f73-de69688267ba.png)

### Steps to reproduce

- Click the Find & Replace button a few times.

- Open the insert code dialog.

**Comment by shu8** [comment]
@enki-code I've fixed the first issue, but can't repro the second one:

<img width="628" alt="screen shot 2016-03-13 at 11 09 25" src="https://cloud.githubusercontent.com/assets/8850830/13728316/129e1d96-e90c-11e5-8c95-d05661b486b9.png">

Does it still happen? Anything in console?

**Comment by enki-code** [comment]
Yeah, second one still happens.  Dialog is blank.

Console errors

> Uncaught ReferenceError: ace is not defined
>     (anonymous function) @ VM1965:1001
>     g.string.c.(anonymous function) @ VM1949:33
> 
> Uncaught ReferenceError: ace is not defined
>     (anonymous function) @ VM1965:1012
>     n.event.dispatch @ VM1965:8
>     r.handle @ VM1965:8
> 
> Uncaught ReferenceError: ace is not defined
>     (anonymous function) @ VM1965:1017
>     n.event.dispatch @ VM1965:8
>     r.handle @ VM1965:8
>

**Comment by shu8** [comment]
@enki-code try entering `ace` in the console after you get those error message. does it exist?

**Comment by enki-code** [comment]
@shu8 I have an idea for a fix.  When loading a question, an ajaxComplete event fires, you could try wrapping your initialization code in that. I suspect this is a timing issue.

    $(document).ajaxComplete(function(event, request, settings) {
        var url = settings.url;
        if(url.startsWith('/posts/')){
             // try injecting your stuff here.

        }
    });

**Comment by enki-code** [comment]
I use this all the time, it might help you.
```
// ==UserScript==
// @name         ajaxComplete logger
// @description  logs ajaxComplete details to the console for development purposes.
// @namespace    https://stackoverflow.com/users/1454538/
// @author       ᴉʞuǝ
// @match        *://*.askubuntu.com/
// @match        *://*.mathoverflow.net/*
// @match        *://*.serverfault.com/*
// @match        *://*.stackapps.com/*
// @match        *://*.stackexchange.com/*
// @match        *://*.stackoverflow.com/*
// @match        *://*.superuser.com/*
// @exclude      *://api.stackexchange.com/*
// @exclude      *://blog.stackexchange.com/*
// @exclude      *://blog.stackoverflow.com/*
// @exclude      *://data.stackexchange.com/*
// @exclude      *://elections.stackexchange.com/*
// @exclude      *://stackexchange.com/*
// @run-at       document-end
// ==/UserScript==
(function($) {
    $(document).ajaxComplete(function(event, request, settings) {
        console.log(settings);
    });
}(jQuery));
```

**Comment by shu8** [comment]
@enki-code I'll be looking into this again either today or tomorrow :)

**Comment by shu8** [comment]
It seems the ace editor issue is a timing issue... but I can't fix it. To anyone interested, I've tried..:

- `@require`ing the Ace editor files directly from the userscript
- adding various `setTimeout`s
- using the `ajaxComplete` function enki gave

**Comment by shu8** [comment]
ok.. this ace editor is a pain.

Thoughts on getting rid of the ace editor section entirely? @enki-code

**Comment by enki-code** [comment]
@shu8 I honestly wouldn't be bothered by it.  It might be better off on its own, as a strand alone script.

**Comment by shu8** [comment]
@enki-code right. getting rid of the ace editor then. Will do in a bit

**Comment by shu8** [comment]
I've removed the Ace Editor feature.

To anyone who sees this in the future, the feature is available as a separate userscript at Stack Apps:  [Stack Exchange Editor Extra: a userscript to add extra features to the Markdown Editor](http://stackapps.com/q/6508/26088)
