### ISSUE TITLE
Adding an option to hide the chat as well as the "love the site" on the side bar

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [soscripted/sox#223]
### Installed Version: 2.0.10  Environment: Tampermonkey

Feature request: adding an option to hide the chat as well as the "love the site" on the side bar:

![image](https://cloud.githubusercontent.com/assets/15331/21812787/1e8c1fc2-d722-11e6-8cb9-6876c2233710.png)

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-tabularReviewerStats","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-shareLinksMarkdown","Extras-warnNotLoggedIn"]

**Comment by enki-code** [comment]
Another easy one.  I'll look into getting this done as soon as I get some more time.

**Comment by shu8** [comment]
@Franck-Dernoncourt sorry for the delay, but this has been added in [dev 2.0.23](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by Franck-Dernoncourt** [comment]
thanks, it works!
