### ISSUE TITLE
show comment score doesn't seem to work

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [soscripted/sox#224]
### Current Behaviour

show comment score doesn't seem to work

![image](https://cloud.githubusercontent.com/assets/15331/21813090/12dc02cc-d723-11e6-930a-1030f40e034c.png)

---

### SOX Errors logged to the browser console -- F12 (if available)

```
SOX:  SOX Access Token: SET
VM3636:563 SOX:  Getting From API with URL: https://api.stackexchange.com/2.2/comments/487496?order=desc&sort=creation&site=stats&key=lL1S1jr2m*DRwOvXMPp26g((&access_token=[removed]
VM3636:563 SOX:  SOX Access Token: SET
VM3636:8 GET https://api.stackexchange.com/2.2/comments/487496?order=desc&sort=creation&…e=stats&key=lL1S1jr2m*DRwOvXMPp26g((&access_token=[removed] 400 (Bad Request)
send @ VM3636:8
ajax @ VM3636:8
getFromAPI @ VM3636:668
(anonymous) @ VM3636:1960
dispatch @ VM3636:7
r.handle @ VM3636:7
VM3636:581 SOX:  SOX Error: error Bad Request
sox.error @ VM3636:581
error @ VM3636:684
j @ VM3636:6
fireWith @ VM3636:6
x @ VM3636:8
(anonymous) @ VM3636:8
```

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-tabularReviewerStats","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-shareLinksMarkdown","Extras-warnNotLoggedIn"]

**Comment by shu8** [comment]
@Franck-Dernoncourt Can you reset your access token please? Clicking the key icon at the bottom of the dialog should let you recreate one :)

It should work then...

**Comment by Franck-Dernoncourt** [comment]
thanks, good catch, it worked :)
