### ISSUE TITLE
Only reduce comment images inline to fit width

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#225]
### Current Behaviour

autoShowCommentImages are always expanded to the full width of the comments, regardless of the original image size. Here's an example that blows up an image unnecessarily:
  [Bookmark to toggles lower nested levels](http://tex.stackexchange.com/q/348044/5764)

![image](https://cloud.githubusercontent.com/assets/1776164/21824452/5c6b9e64-d734-11e6-9414-8701b399e566.png)

Would it be possible to only *reduce* the image size if it doesn't fit within the comment width, rather than always make it 100% width?

[Original small image](https://i.stack.imgur.com/0sfOy.png)

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode"]

**Comment by shu8** [comment]
@wgrundlingh this *should* be fixed [in dev 2.0.11](https://github.com/soscripted/sox/raw/dev/sox.user.js), but it's annoyingly difficult to find comments with images when you want to... so please tell me if you see any bugs if you see comments with images! :)

**Comment by wgrundlingh** [comment]
Perhaps this query will be of help:
  http://data.stackexchange.com/meta.stackexchange/query/614674/comments-with-image-links-in-them

**Comment by shu8** [comment]
@wgrundlingh thanks! if you know stuff about SEDE, do you know how to get the URL as well? I can't see a URL field :/

**Comment by wgrundlingh** [comment]
You're asking for the comment URL? I've supplied the post URL.

**Comment by shu8** [comment]
Hmmm I can only see the post ID on the query... :/ Should I be able to
click the ID?

**Comment by wgrundlingh** [comment]
Yes, it should be a clickable URL. I edited the previous comment to show a clickable URL, perhaps you still had the old SEDE query; here's the one I have:
  http://data.stackexchange.com/meta.stackexchange/query/614676/comments-with-image-links-in-them

![image](https://cloud.githubusercontent.com/assets/1776164/21868508/e116a626-d807-11e6-8200-d6932b73cc7a.png)
