### ISSUE TITLE
shareLinksMarkdown should remove [closed reason] at the end of the post title

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#226]
### Current Behaviour

With shareLinksMarkdown active, the current, full title is copied, including when the post has been marked a duplicate/closed and contains a trailing '[duplicate]'/'[closed]'/?. This screws up the markdown, since

    [title [stuff]](url)

doesn't parse properly. Could the trailing '[stuff]' be removed? Alternatively, matching [...] pairs should be changed to (...), since some people still use that in their title; here's an example: http://tex.stackexchange.com/q/172914/5764

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

Add a comment to [Formatting Sandbox](http://meta.stackexchange.com/q/3122/168244) of the form

    [test title [duplicate]](http://test.url)

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode"]

**Comment by shu8** [comment]
@wgrundlingh fixed in [dev 2.0.11](https://github.com/soscripted/sox/raw/dev/sox.user.js); any square brackets are replaced with `()` brackets.

I haven't actually removed the question state though -- I think it is often useful when linking to a question to see it's state :/

Should I keep it there? :)

**Comment by wgrundlingh** [comment]
@shu8 True. Keep the state if the update is to change [...] to (...).
