### ISSUE TITLE
latex issue with the share link feature: no $ added

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [soscripted/sox#227]
### Current Behaviour

When a question title contains latex equations,  the share link feature doesn't add `$`. Example, on http://stats.stackexchange.com/q/255486/12359, one gets clicking on `share`:

`[What's the difference between ℓ1ℓ1\ell_1-SVM, ℓ2ℓ2\ell_2-SVM and LS-SVM loss functions?](http://stats.stackexchange.com/q/255486/12359)`

instead of:

`[What's the difference between $\ell_1$-SVM, $\ell_2$-SVM and LS-SVM loss functions?](http://stats.stackexchange.com/q/255486/12359)`

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-tabularReviewerStats","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-shareLinksMarkdown","Extras-warnNotLoggedIn","Extras-copyCode"]

**Comment by shu8** [comment]
@Franck-Dernoncourt thanks, fixed in [dev 2.0.11](https://github.com/soscripted/sox/raw/dev/sox.user.js).

It gets the title from the page title now, so if there's mathjax in the title, the share URL **won't** contain the state of the question eg `[closed]` at the end, for now
