### ISSUE TITLE
No edit comments available in /review

### ISSUE THREAD

**Issue by TuggyNE** [soscripted/sox#228]
### Installed Version
2.0.11  
**Environment**: Pale Moon 26.5.0 x64 Win 10

### Current Behaviour

Predefined edit comments appear only on question pages, not when editing from /review.

### Steps to reproduce

Go to /review on any site you have review privileges. Edit a post from within any queue. No comment checkboxes appear.

### Features Enabled 

    ["Appearance-answerTagsSearch","Appearance-dragBounty","Appearance-highlightQuestions","Appearance-metaChatBlogStackExchangeButton","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Comments-autoShowCommentImages","Comments-commentShortcuts","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Flags-flagOutcomeTime","Flags-flagPercentages","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-quickAuthorInfo","Extras-shareLinksMarkdown"]

**Comment by enki-code** [comment]
Thanks, I'm guess we just need to update the match rules for that feature. :+1:

**Comment by shu8** [comment]
@TuggyNE Thanks for the bug report! :) Fixed in [dev 2.0.11](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
