### ISSUE TITLE
Add the question's state to the title in the Suggested Edit Review Queue

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#229]
### Current Behaviour
Edits to questions that are closed or on hold are supposed to solve the closure issue.  Otherwise, multiple people waste time reviewing it, only to have a prettier or better written closed question.  

The closure status of a question isn't displayed in the Edit review queue, the only place where it is not.  It's easy to focus on reviewing the proposed changes and miss some aspect that was the basis for closure.  So it requires reopening every question from the Edit review queue in another tab just to verify that it isn't closed.

It would be useful to have the same (Hold) or (Closed) label after the title that appears on the main page, question page, search pages, etc..

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Comments-autoShowCommentImages","Comments-commentReplies","Comments-confirmNavigateAway","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Sidebar-hideHireMe","Chat-renameChat","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-warnNotLoggedIn","Extras-showMetaReviewCount"]

**Comment by shu8** [comment]
@fixer1234 just to clarify, we're talking about the suggested edit queue right?

**Comment by fixer1234** [comment]
@shu8 Correct.

**Comment by shu8** [comment]
@fixer1234 I've added this in [dev v2.0.25](https://github.com/soscripted/sox/raw/dev/sox.user.js) -- please give it a go! :)

Sorry for how long this took!

**Comment by fixer1234** [comment]
@shu8 Thanks.  I loaded this several days ago but haven't yet come across an example to test it.  I'll confirm when a case shows up.

**Comment by fixer1234** [comment]
@shu8 Finally came across an example.  Success.
