### ISSUE TITLE
Tags incorrectly translate to inline posts (linkedPostsInline)

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#231]
### Current Behaviour

SE markdown for tags using [tag:<tag>] or [meta-tag:<tag>] translates to the URL http://<site>/questions/tagged/<tag>, which incorrectly looks like a question that SOX interprets as wanting to display inline:

![image](https://cloud.githubusercontent.com/assets/1776164/21952661/c9e36bd4-d9d7-11e6-8638-6991bf0c2584.png)

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

See [privileges for top users](http://meta.stackexchange.com/a/253696/168244).

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode"]

**Comment by shu8** [comment]
@wgrundlingh fixed in [dev 2.0.13](https://github.com/soscripted/sox/raw/dev/sox.user.js)
