### ISSUE TITLE
Strange permalink bug with shareLinksMarkdown active

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#232]
### Current Behaviour

This specific question yields a strange permalink where the title question is TeX and not the actual question title: http://tex.stackexchange.com/q/48301/5764

![tex-se](https://cloud.githubusercontent.com/assets/1776164/21952790/c86ba90e-d9d9-11e6-9c76-3a29ec2c33a8.gif)

Other questions (and answers) have all successfully included the correct question title via the shareLinksMarkdown option.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode"]

**Comment by shu8** [comment]
This was a side effect of #227's fix. Fixed in [dev 2.0.13](https://github.com/soscripted/sox/raw/dev/sox.user.js)
