### ISSUE TITLE
stickyVoteButtons shows glitches at top and bottom

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#235]
### Current Behaviour

The stickyVoteButtons feature shows a minor displacement when scrolling from the top of a post, with an on-off glitch at the bottom of the post:

![tex-se](https://cloud.githubusercontent.com/assets/1776164/21997569/dab85c1c-dbe4-11e6-9dbd-171bf6d538c4.gif)

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode"]

**Comment by enki-code** [comment]
Thanks for reminding me. I've known about this for a while just never got around to fixing it. We will add it to the list of things to get done.

**Comment by shu8** [comment]
@wgrundlingh the shift to the right's been fixed in [dev 2.0.16](https://github.com/soscripted/sox/raw/dev/sox.user.js), but the on off glitch is still there (for now!)

**Comment by IStoleThePies** [comment]
Here's a fix:

    stickyVoteButtons: function() {
        // Description: For making the vote buttons stick to the screen as you scroll through a post
        //https://github.com/shu8/SE_OptionalFeatures/pull/14:
        //https://github.com/shu8/Stack-Overflow-Optional-Features/issues/28: Thanks @SnoringFrog for fixing this!

        stickcells();
        $(document).on('sox-new-review-post-appeared', stickcells);

        $(window).scroll(function() {
            stickcells();
        });

        function stickcells() {
            var $votecells = $(".votecell");
            $votecells.css("width", "46px");

            $votecells.each(function() {
                var $topbar = $('.topbar'),
                    topbarHeight = $topbar.outerHeight(),
                    offset = (sox.location.on('/review') ? 60 : 10);

                if ($topbar.css('position') == 'fixed') offset += topbarHeight;

                var $voteCell = $(this),
                    $vote = $voteCell.find('.vote'),
                    vcOfset = $voteCell.offset(),
                    scrollTop = $(window).scrollTop();

                if (vcOfset.top - scrollTop - offset <= 0) {
                    if ($vote.children().last().length && $vote.length) //These values strangely alternate between being 0 and 1
                        var realHeight = $vote.children().last().offset().top - $vote.offset().top; //Get the original height; the difference between the last child and the first child's position

                    if (vcOfset.top + $voteCell.height() - scrollTop - offset - realHeight > topbarHeight && $vote.height() + topbarHeight < $voteCell.next().height()) {
                        $vote.css({
                            position: 'fixed',
                            left: vcOfset.left,
                            top: offset
                        });
                    } else {
                        $vote.removeAttr("style");
                    }
                } else {
                    $vote.removeAttr("style");
                }
            });
        }
    },

The bug happened because the height of `#vote` changed whenever the stickiness started (the amount it changed by depends on the post). As a result, scrolling far enough (outside of the "sticky zone") will make `#vote` stop being fixed, but its height will immediately decrease as well, meaning it can be in the sticky zone again. I created `realHeight`, which takes the difference between `#vote`'s first and last children's positions (this doesn't change), and used that instead.

I also fixed a bug causing extremely short posts to glitch in the same way. I made it a requirement that the post (`$voteCell.next()`, aka `#answercell`) must at least be bigger than `#vote`. It turns out that the answercell's height also changes when the vote buttons become sticky, so I compared its changing height to `#vote`'s changing height (instead of using `realHeight`).

**Comment by IStoleThePies** [comment]
Completely ignore the solution above, I wrote something better:

    stickyVoteButtons: function() {
        // Description: For making the vote buttons stick to the screen as you scroll through a post
        //https://github.com/shu8/SE_OptionalFeatures/pull/14:
        //https://github.com/shu8/Stack-Overflow-Optional-Features/issues/28: Thanks @SnoringFrog for fixing this!

        stickcells();
        $(document).on('sox-new-review-post-appeared', stickcells);

        $(window).scroll(function() {
            stickcells();
        });

        function stickcells() {
            var $votecells = $('.votecell');
            $votecells.css('width', '46px');

            $votecells.each(function() {
                var $topbar = $('.topbar'),
                    topbarHeight = $topbar.outerHeight(),
                    offset = (sox.location.on('/review') ? 60 : 10);

                if ($topbar.css('position') == 'fixed') offset += topbarHeight;

                var $voteCell = $(this),
                    $vote = $voteCell.find('.vote'),
                    vcOfset = $voteCell.offset(),
                    scrollTop = $(window).scrollTop();

                if ($vote.children().last().length && $vote.length && $voteCell.next().find('.fw').length) { //These values strangely alternate between existing and not existing. This if statement insures we only get their values when they exist, so no errors.
                    var realHeight = $vote.children(':not(:hidden, .message-dismissable)').last().offset().top + $vote.children(':not(:hidden, .message-dismissable)').last().height() - $vote.offset().top; //Get the original height; the difference between the last child and the first child's position
                    var votePos = $vote.offset().top,
                        fwPos = $voteCell.next().find('.fw').offset().top + 17; //I think a bit below .fw (where the "edit", "delete", etc. buttons lie) is a good place to stop the stickiness.
                }

                if (realHeight + vcOfset.top < fwPos && vcOfset.top - scrollTop - offset <= 0) { //Left condition is for scrolling down into the sticky zone from outside. Right condition is to get rid of a sticky zone on extremely short posts
                    if (fwPos - realHeight > votePos || fwPos - scrollTop - realHeight - offset >= 0) { //Left condition marks the bottom limit for the sticky zone. Right condition is for scrolling up into the sticky zone from outisde.
                        $vote.css({
                            position: 'fixed',
                            top: offset
                        });
                    } else {
                        //Stop stickiness when we've scrolled down past the sticky zone.
                        $vote.css({
                            position: 'absolute',
                            top: fwPos - realHeight //Leave the button at its bottommost position
                        });
                    }
                } else {
                    $vote.removeAttr('style');
                }
            });
        }
    },

This should work a lot better.

**Comment by shu8** [comment]
Thanks, I'll get this added in ASAP! :)

**Comment by calebkleveter** [comment]
Will the solution fix this bug?

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/nroqA.png

**Comment by shu8** [comment]
@calebkleveter I can't repro that... how does that bug happen?

**Comment by shu8** [comment]
@Sir-Cumference thanks sooooo much! I've added it into [dev 2.0.22](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

@wgrundlingh it's fixed! :)

**Comment by calebkleveter** [comment]
To do this I am using smart zoom on an Apple Magic Mouse.

Go to any answer that is long enough to enable sticky vote buttons. Then smart zoom at the middle of the answer.

**Comment by shu8** [comment]
Ok thanks, I'll look into it when I get a bit more time :)
