### ISSUE TITLE
standOutDupeCloseMigrated: "on hold", not "onhold"

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#237]
### Current Behaviour

standOutDupeCloseMigrated puts on hold questions as being "onhold", rather than "on hold":

![image](https://cloud.githubusercontent.com/assets/1776164/22010566/e3b4c42c-dc3e-11e6-8ae6-74db124d0732.png)

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

There might be some here: http://stackoverflow.com/search?tab=newest&q=closed%3a1

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode"]

**Comment by shu8** [comment]
@wgrundlingh fixed in [dev 2.0.16](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
