### ISSUE TITLE
editComment: custom edit reason checkboxes leave white background on un-hover

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#238]
### Current Behaviour

Hovering over and then moving away from a custom edit reason leaves the background *white*, regardless of what this site background looks like:

![tex-se](https://cloud.githubusercontent.com/assets/1776164/22082786/0af35e64-dd7e-11e6-8c2d-4aa0d45e086c.gif)

I'd imagine it would be better to revert to whatever the default background was, rather than white.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode"]

**Comment by shu8** [comment]
Thanks! :) sorry for not getting back to you on some other issues as well, been busy with school :(

I'll get this and your other bug report done today though :)

**Comment by wgrundlingh** [comment]
That is not a problem at all! You're providing a free service that (in my opinion) takes up quite a bit of time! I completely understand any and all delays.

**Comment by shu8** [comment]
@wgrundlingh Thanks! ❤️ Fixed this issue in [dev 2.0.16](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
