### ISSUE TITLE
copyCommentsLink is not removed when clicking "add comment"

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#239]
### Current Behaviour

When adding a comment, all hidden comments are shown. However, the copyCommentLink feature doesn't remove the "show X more comments" button:

![tex-se](https://cloud.githubusercontent.com/assets/1776164/22171741/ab6c450a-df49-11e6-98b2-2bec018ec784.gif)

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar"]

**Comment by shu8** [comment]
@wgrundlingh fixed in [dev 2.0.19](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
