### ISSUE TITLE
v1.0.3

### ISSUE THREAD

**Issue by shu8** [soscripted/sox#24]
### v1.0.3  @soscripted/admins 

- [x] Resource URLs are pointing to RawGit CDN
- [x] Tested on supported browsers
- [x] Verify all features working correctly
- [x] Check console for errors
- [x] Update screenshots in the Readme
- [x] Update features list in Features Wiki (_update old descriptions_)
- [x] Update Contributing Wiki to reflect the latest structure
- [x] Update Contributing Wiki to reflect new helper functions

**Comment by shu8** [comment]
### V1.0.3

- [ ] Working on Google Chrome latest?
- [ ] Working on Firefox latest?
- [ ] All features working?
- [ ] No errors in console?

**Comment by enki-code** [comment]
@shu8 The task list progress is no longer being displayed in on the issues page for this, any ideas why? I've tried swapping tags, removing the milestone, rewriting the list.. I'm stuck.

**Comment by shu8** [comment]
v1.0.3 has been pushed to master
