### ISSUE TITLE
The kbd button inserts `<kbd</kbd>`

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [soscripted/sox#240]
### Current Behaviour

The kbd button inserts `<kbd</kbd>` instead of  `<kbd></kbd>`

![se kbd issue](https://cloud.githubusercontent.com/assets/15331/22176469/4af9b744-dfd9-11e6-8b3a-2a53635ce41f.gif)

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-tabularReviewerStats","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-shareLinksMarkdown","Extras-warnNotLoggedIn","Extras-copyCode"]

**Comment by shu8** [comment]
Thanks @Franck-Dernoncourt, it's because of my hacky way of doing #189. I'll get this fixed soon! :)

**Comment by shu8** [comment]
@Franck-Dernoncourt sorry for the delay! fixed in [dev 2.0.20](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by Franck-Dernoncourt** [comment]
Thanks!
