### ISSUE TITLE
Post features don't show up on Review Queue

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#241]
### Installed Version: 2.0.18  Environment: Tampermonkey

Many of the post or comment features don't show up on the Review Queue, like the CSS vote/star button effects, notify on edit, comment reply button, etc.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Extras-parseCrossSiteLinks","Extras-hideCertainQuestions"]

**Comment by shu8** [comment]
@IStoleThePies thanks for telling us about this! we'd forgotten to enable these features in the review sections of the sites!

Fixed in [dev 2.0.20](https://github.com/soscripted/sox/raw/dev/sox.user.js) (and sorry for the delay!) :)

**Comment by IStoleThePies** [comment]
@shu8 Could you also enable notify on edit?
