### ISSUE TITLE
isQuestionHot: question title formatting breaks on SU

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#243]
Windows 7 Home Premium 64 bit
Firefox 51.1.0
Greasmonkey 3.9
SOX 2.0.3 DEV

See this current hot question:

https://superuser.com/questions/1173773/how-do-these-icons-work-%EF%B8%8F

The "Hot" graphic appears on the **left** hand side and the ** question title** appears on the right hand side (the reverse of what it should be).

Broken screenshot:

![screenshot - 01_02_2017 16_28_11](https://cloud.githubusercontent.com/assets/7079224/22515753/7c203404-e89b-11e6-9689-2bb59f2b9716.png)

Normal screenshot:

![screenshot - 01_02_2017 16_29_41](https://cloud.githubusercontent.com/assets/7079224/22515798/aa52d1b0-e89b-11e6-9961-6e5cb1d80dde.png)

**Comment by shu8** [comment]
Hi! Can you update to the latest Dev version and see if this still occurs?
O have a feeling a change we made to the feature is partially working on
the older version but not fully...

The feature has changed to be a flame icon on the left of the title :)

**Comment by DavidPostill** [comment]
Installed SOX 2.0.20. Now I see a flame to the left on all hot questions. I didn't realise you had changed the feature :)

However, some titles are still *right justified*:

![screenshot - 01_02_2017 23_35_08](https://cloud.githubusercontent.com/assets/7079224/22531142/1d669408-e8d7-11e6-9579-426b37486cca.png)

And some *left justified*:

![screenshot - 01_02_2017 23_36_13](https://cloud.githubusercontent.com/assets/7079224/22531161/3fd096b0-e8d7-11e6-8e92-1a47a24d010d.png)

**Comment by shu8** [comment]
@DavidPostill hmm seems to be a Superuser specific issue... have you seen it happen on any other site?

**Comment by DavidPostill** [comment]
No, I haven't - which is why I thought it was some to do with the emojis in the title - I don't recall seeing those anywhere else ...

**Comment by shu8** [comment]
@DavidPostill ok... this should fixed in [dev 2.0.21](https://github.com/soscripted/sox/raw/dev/sox.user.js) now :)

**Comment by DavidPostill** [comment]
Great work! Confirmed as fixed :)
