### ISSUE TITLE
standOutDupeCloseMigrated tag splits across multiple lines for big titles

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#244]
SOX 2.0.20, Windows 7 Home Premium 64 bit, Firefox 51.1.0

The highlighted tags are being split across multiple lines:

![screenshot - 03_02_2017 10_40_55](https://cloud.githubusercontent.com/assets/7079224/22588367/647d0576-e9fd-11e6-9c41-6fc03c85d51e.png)
 

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-showCommentScores","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Flags-flagOutcomeTime","Flags-flagPercentages"]

**Comment by shu8** [comment]
@DavidPostill thanks, fixed in [dev 2.0.21](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

**Comment by DavidPostill** [comment]
Can't test this one, the title has been edited in the example I gave.

**Comment by shu8** [comment]
@DavidPostill no problem, if you see it happen again, please comment back. I tried editing the titles locally using dev tools and it didn't happen, so it *shouldn't*, but there's always a chance it will! :)
