### ISSUE TITLE
Open jsfiddle links in new tab

### ISSUE THREAD

**Issue by ScottBeeson** [soscripted/sox#245]
Just a QOL feature. It would be nice to have a checkbox that automatically handled jsfiddle links.

**Comment by enki-code** [comment]
If we were to implement this, I probably wouldn't target just jsFiddle links but _any_ external link. We'll talk about it and let you know.

**Comment by ScottBeeson** [comment]
Well, I considered that, but fiddles are _always_ in the context of the current question. Other links may not be?  Or at least limit it to links in the body of the question and answers (ie don't include links on the side to other questions, etc).

**Comment by shu8** [comment]
@ScottBeeson just to clarify, this feature request is asking to open all JSFiddle links in a new tab by default right? :)

**Comment by ScottBeeson** [comment]
I personally would love an option so I could set it to automatically open all JSFiddle links in a new tab.

**Comment by shu8** [comment]
Sure, no problem. I'll get this done as soon as I get a bit more time :). I
might add an option to choose other links as well but I'll definitely be
able to get the jsfiddle links working! :)

**Comment by shu8** [comment]
@ScottBeeson added in [dev 2.0.23](https://github.com/soscripted/sox/raw/dev/sox.user.js) :) 

It's a customizable feature, so you can add more sites if you like.

This is what you'll need to do to get it working for JSFiddle..:

![this](https://cloud.githubusercontent.com/assets/8850830/23107382/4b1b558e-f6f4-11e6-925b-24c208a2095e.png)
