### ISSUE TITLE
Displaying linked content inline fails

### ISSUE THREAD

**Issue by enki-code** [soscripted/sox#25]
**Installed Version: 1.0.3 DEV  |  Environment: Chrome/Tampermonkey**

**Expected Behavior**

Display linked content inline when clicking the expansion button

**Actual Behavior**

It doesn't work. :-1:   location protocol defaults to http, this causes errors when viewing the site over https and the URL being requested does not exists. Perhaps switching to the API would be better.

**Comment by shu8** [comment]
@enki-code I can work on this if you want. I'll still use the site's URL but change the protocol accordingly. It will be easier and better than using the API

**Comment by shu8** [comment]
@enki-code does this still happen with the changes you did to the protocol?

(this line: `$.get(location.protocol + '//' + SOHelper.getSiteURL() + '/posts/' + id + '/body', function(d) {`)

**Comment by enki-code** [comment]
@shu8 Not sure exactly what's going on, it appears to be working correctly [here](http://stackoverflow.com/a/33134704/1454538) but not [here](http://stackapps.com/a/4859/36691)

I get an error in the console when attempting to view content inline on Stackapps, possibly other sites.

> GET https://stackapps.com/posts/comment11656_3324/body 404 (Not Found)
> k.cors.a.crossDomain.send @ VM1244:9
> n.extend.ajax @ VM1244:9
> n.(anonymous function) @ VM1244:9
> (anonymous function) @ VM1244:2925
> n.event.dispatch @ VM1244:8
> r.handle @ VM1244:8

**Comment by shu8** [comment]
@enki-code ah, so the http/https problem is solved. that seems to be a bug in the way I get the ID... the link you were trying to view must actually link to a comment, and so the script gets the comment ID... I'll look into that. which post did you view this on?
