### ISSUE TITLE
Hot Network issue

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#250]
### Installed Version: 2.0.20  Environment: Tampermonkey

I just looked at a question [here](https://astronomy.stackexchange.com/questions/19945/is-the-sun-really-burning-and-getting-smaller), which sometimes shows the Hot Network symbol and text "One of the 100 hot network questions!"

<img width="756" alt="screen shot 2017-02-06 at 12 32 22 pm" src="https://cloud.githubusercontent.com/assets/5375326/22658582/9b72215c-ec68-11e6-917c-4ff4d91622d1.png">
<img width="1267" alt="screen shot 2017-02-06 at 12 33 51 pm" src="https://cloud.githubusercontent.com/assets/5375326/22658584/9e209bd6-ec68-11e6-9202-651d07bc86d3.png">

However, once the page loads I sometimes do not see any indication that it is a Hot Network question. It seems to randomly show or hide the HNQ symbol and text. In addition, it does not show up in the [list](https://stackexchange.com/questions?tab=hot) of HNQs.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Extras-parseCrossSiteLinks","Extras-hideCertainQuestions"]

**Comment by shu8** [comment]
@Sir-Cumference thanks for the bug report! This one's a pretty weird one, but I'm going to keep me eye open to see if I see this happen!

If you see it happen again, please do comment back, and I'll try to look at it on the same day, so it stays on the HNQ list! :/

**Comment by Sir-Cumference** [comment]
@shu8 Hmm...the HNQ symbol doesn't seem to appear on [this](https://english.stackexchange.com/questions/384816/does-have-vs-is-having-questions) question, even though it's on the Hot Network.

**Comment by shu8** [comment]
@Sir-Cumference hmmm, it looks like both of those questions were asked very soon after you visited them, and they might not have appeared on the feed that the script uses until a bit later (if they are cached, for example)? Because I can see the HNQ symbol now, but I realised I saw this a bit too late :/

**Comment by Sir-Cumference** [comment]
@shu8 Yeah, I can see the symbol now.

Also, I haven't found any other cases where the HNQ appears on non-HN questions.

**Comment by shu8** [comment]
@Sir-Cumference hmmm, well if that's the case, should I close this issue then? :)

**Comment by Sir-Cumference** [comment]
@shu8 Well, an unrelated note, the flame icon is offset on English questions:

<img width="1186" alt="screen shot 2017-04-23 at 2 20 14 pm" src="https://cloud.githubusercontent.com/assets/5375326/25317581/24573cac-2830-11e7-836c-0c4b0f761c15.png">

**Comment by shu8** [comment]
I'll get that fixed before closing this then! :)

**Comment by shu8** [comment]
@Sir-Cumference I've fixed the English Language issue in [dev 2.0.32](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

**Comment by Sir-Cumference** [comment]
@shu8 Ah, I've figured out why this first issue happened. The [list](https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20json%20where%20url%3D%22http%3A%2F%2Fstackexchange.com%2Fhot-questions-for-mobile%22&format=json) for HNQs actually changes almost every time I reload it. It seems to switch some questions out for others randomly.

Doesn't look like much can be done about that. :/
