### ISSUE TITLE
Sticky voting buttons and post jump within Suggested Edits review

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#253]
### Current Behaviour

While reviewing a suggested edit, scrolling up-and-down causes the post and *sticky* voting buttons to jump:

![tex-se](https://cloud.githubusercontent.com/assets/1776164/22851652/e154de94-efdd-11e6-8134-b3393de52dde.gif)

This happens even when viewing any historical Suggested Edit.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

Visit any previous suggested edit and scroll up-and-down to replicate this behaviour.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar"]

**Comment by shu8** [comment]
@wgrundlingh thanks, fixed in [dev 2.0.22](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
