### ISSUE TITLE
linkedPostsInline repeatedly inserts an error on scrolling within review queue

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#254]
### Current Behaviour

The following occurred while scrolling through a Close Vote review item on [Meta.SE](http://meta.stackexchange.com):

![tex-se](https://cloud.githubusercontent.com/assets/1776164/22851720/f54976e2-efdf-11e6-803d-fc655e35f4b8.gif)

The inline post display arrow is replicated when the floating voting bar starts to follow the scrolling.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

Visit any post that has been closed before where there is an inline post link. Here is one example:
  http://meta.stackexchange.com/review/close/49041

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar"]

**Comment by shu8** [comment]
@wgrundlingh fixed in [dev 2.0.22](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
