### ISSUE TITLE
Hide the review notifications in the redesigned header

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [soscripted/sox#257]
Feature request:  in the redesigned header, hide the review notifications:

![image](https://cloud.githubusercontent.com/assets/15331/22949181/50f47c02-f2cf-11e6-995c-0477334eba42.png)

According to someone on [How can I hide review notifications?](http://meta.stackoverflow.com/q/343816/395857), this can be done by injecting the following CSS: `.indicator-badge.js-unread-count._reviews { display: none }`

**Comment by Franck-Dernoncourt** [comment]
I use the Google Chrome extension [Adblock Plus](https://chrome.google.com/webstore/detail/adblock-plus/cfhdojbkjhnklbpkdaibdccddilifddb?hl=en-US) to remove the icon. It takes around five seconds:

![image](https://cloud.githubusercontent.com/assets/15331/23104355/14d736b4-f69a-11e6-9469-1ebf18f5b5a7.png)


![image](https://cloud.githubusercontent.com/assets/15331/23104325/9843047a-f699-11e6-8e19-24f17110ee15.png)

![image](https://cloud.githubusercontent.com/assets/15331/23104328/a30563bc-f699-11e6-865c-aad998b39f4f.png)

![image](https://cloud.githubusercontent.com/assets/15331/23104353/08811c86-f69a-11e6-92d8-464ee2fb1738.png)

The downside is that it removes the icon instead of just removing the notifications.

**Comment by j-f1** [comment]
@Franck-Dernoncourt Try `stackoverflow.com##._reviews`.

**Comment by shu8** [comment]
@Franck-Dernoncourt I don't think this is needed anymore after [this change](https://meta.stackoverflow.com/questions/252843/posts-awaiting-review-orange-counter-is-way-off/346653#346653):

![this](https://cloud.githubusercontent.com/assets/8850830/24828612/a8087c66-1c58-11e7-8b31-8336a63ff531.jpg)

They've got rid of the number entirely! :)

**Comment by Franck-Dernoncourt** [comment]
Thanks great anyway on my side I simply hide the review button :)
