### ISSUE TITLE
Meta Question Alert function fails

### ISSUE THREAD

**Issue by enki-code** [soscripted/sox#26]
**Installed Version: 1.0.3 DEV  |  Environment: Chrome/Tampermonkey**

**Expected Behavior**

The new meta question alert diamond to display only on main sites that have a child meta site.

**Actual Behavior**

Displays on all main sites and is throwing an error on Stackapps because it does not have a meta site.

**Error Logs**

TypeError: Cannot read property 'split' of undefined(…)

**Comment by shu8** [comment]
I have an idea on how to fix this. I'll look in the topbar and see if there's a meta associated with the site

**Comment by shu8** [comment]
fixed:

        if (SOHelper.getSiteType() != 'main' || !$('.related-site').length) return; //DO NOT RUN ON META OR CHAT OR SITES WITHOUT A META
