### ISSUE TITLE
SOX setting tag doesn't close when clicking on inbox/achievements 

### ISSUE THREAD

**Issue by Gloin1313** [soscripted/sox#260]
Thanks for getting it to work with the new top-bar! Just a small bug:

### Current Behaviour
![screen shot 2017-02-17 at 20 03 48](https://cloud.githubusercontent.com/assets/22625968/23081336/4785f338-f54c-11e6-9c31-082705d00b3e.png)

SOX tab and other SO tags open at the same time.

---

### Steps to reproduce

Click on the SOX (cogs) icon the the top right-hand corner of SO. Then click on inbox/achievements and the SOX tab stays open.

**Comment by shu8** [comment]
Thanks for this bug report, I hadn't noticed it.

I just realised SO have got rid of the hover over buttons thing where it opened the dialog when you hovered over another button -- do you think it's worth adding that? :)

**Comment by Gloin1313** [comment]
They removed it in response to this: http://meta.stackoverflow.com/questions/343103/help-test-the-new-top-nav-phase-3-testing-runs-this-week/343136#343136

**Comment by shu8** [comment]
@Gloin1313 hmmm that's fair enough I guess, but they could have just disabled the hover thing on the SE logo!

I think I'll add a separate feature to add the hover thing for the SOX button, inbox and achievements, leaving out the SE logo one...

**Comment by j-f1** [comment]
@shu8 [This gist](https://gist.github.com/travisjj/3c50be52ce4da566867c624e8777d0a8) from Travis J may be useful.

**Comment by shu8** [comment]
@j-f1 thanks! that's interesting because I never really thought about the mod menu! :/ 

I'll see if I can get a version of it working soon!

**Comment by Gloin1313** [comment]
> they could have just disabled the hover thing on the SE logo!

I don't think so, it would happen with any of the drop-down menus, wouldn't it? I think it just so happened that the person who posted it was a mod.

**Comment by shu8** [comment]
@Gloin1313 I've fixed the bug you reported in [dev 2.0.23](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

I'll look into the other thing as a separate feature soon... :)
