### ISSUE TITLE
The color of first comment is not black

### ISSUE THREAD

**Issue by ooker777** [soscripted/sox#262]
![](http://i64.tinypic.com/21l7uw2.png)

I use Windows 7, with latest Firefox. Disabling SOX makes the comment's color be back to normal. I notice that this is universal, every section of comments in every question or answer in every Stack Exchange site has this behavior.

This is first reported in [meta physics](http://meta.physics.stackexchange.com/q/9685/41634)

**Comment by shu8** [comment]
Looks like the quick author info feature isn't working properly. Have you
got an access token?

Please could you enable debugging in the dialog and then open the console
and copy and paste the log here? It should tell me what's wrong! :)

**Comment by ooker777** [comment]
Yes I have the token.

sox.error file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/sox.common.js:34:13
	init file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/sox.user.js:158:25
	sox.ready/< file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/sox.common.js:70:21
	n.Callbacks/j file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:2:26920
	n.Callbacks/k.fireWith file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:2:27738
	.ready file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:2:29530
	I file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:2:29721

sox.error file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/sox.common.js:34:13
	sox.helpers.getFromAPI/<.error file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/sox.common.js:128:21
	n.Callbacks/j file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:2:26920
	n.Callbacks/k.fireWith file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:2:27738
	x file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:4:11276
	.send/b/< file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:4:14765
	.send file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:4:14951
	.ajax file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:4:10710
	sox.helpers.getFromAPI file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/sox.common.js:116:13
	sox.features.quickAuthorInfo file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/sox.features.js:2075:13
	init file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/sox.user.js:147:29
	sox.ready/< file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/sox.common.js:70:21
	n.Callbacks/j file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:2:26920
	n.Callbacks/k.fireWith file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:2:27738
	.ready file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:2:29530
	I file:///C:/Users/Acer/AppData/Roaming/Mozilla/Firefox/Profiles/zm6hp19k.default/gm_scripts/Stack_Overflow_Extras_(SOX)/jquery-2.1.4.min.js:2:29721

**Comment by shu8** [comment]
@ooker777 you should just be able to copy from the top left to the bottom... if it's not working, you can just screenshot it :)

**Comment by ooker777** [comment]
Yes, the grey color disappears. Thanks for your input :D

Here's the screenshot anyway:
![](http://i64.tinypic.com/juwk5k.png)
