### ISSUE TITLE
Self-reply buttons don't work

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#263]
### Installed Version: 2.0.24  Environment: Tampermonkey

If you go to a chatroom and hover over your posts, you won't see any reply button.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-parseCrossSiteLinks","Extras-hideCertainQuestions"]

**Comment by shu8** [comment]
side effect of #269, fixed in [dev 2.0.25](https://github.com/soscripted/sox/raw/dev/sox.user.js).

Sorry for how long this took! :/

**Comment by Sir-Cumference** [comment]
@shu8 Hmm...still doesn't seem to work. :/

**Comment by shu8** [comment]
@Sir-Cumference The files hadn't pushed yet! sorry -- please could you use that link again and reinstall? :)

**Comment by Sir-Cumference** [comment]
@shu8 Hmm...still doesn't show up.

**Comment by shu8** [comment]
@Sir-Cumference that's weird :/ which chat room are you in?

**Comment by Sir-Cumference** [comment]
@shu8 Right now I'm in physics:

<img width="1000" alt="screen shot 2017-03-30 at 2 47 10 pm" src="https://cloud.githubusercontent.com/assets/5375326/24520806/c6e4699a-1557-11e7-922b-a707432cd51a.png">

**Comment by shu8** [comment]
@Sir-Cumference can you open the console and paste anything there here please?
