### ISSUE TITLE
Show blog posts and "Featured" without "Hot Meta Posts"

### ISSUE THREAD

**Issue by Gloin1313** [soscripted/sox#264]
A feature request that I would use and enjoy would be to be able to hide "Hot Meta Posts" without missing out on announcements in "Featured" and blog posts in the community bulletin. At the moment there is just a generic "Hide the Community Bulletin module".

Thanks.

**Comment by mezmi** [comment]
Seems reasonable. I'll try getting this into the next release.

**Comment by shu8** [comment]
@Gloin1313 I've added the feature "Hide just the 'Hot Meta Posts' sections in the Community Bulletin" in [dev 2.0.31](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :) sorry for the delay!

**Comment by Gloin1313** [comment]
Thanks so much! This is perfect!
