### ISSUE TITLE
SO employee symbol is duplicated

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#265]
### Installed Version: 2.0.24  Environment: Tampermonkey

If you go to a tag page like [this](https://meta.stackexchange.com/questions/tagged/feature-request?sort=newest), you'll notice that SE employees have an extra symbol below their gravatar:

<img width="743" alt="screen shot 2017-03-09 at 6 10 03 pm" src="https://cloud.githubusercontent.com/assets/5375326/23774816/a2acb5c4-04f3-11e7-82d3-ddfafbf11fe5.png">

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-parseCrossSiteLinks","Extras-hideCertainQuestions"]

**Comment by mezmi** [comment]
Thanks for reporting this, I'll look into why this is happening. It'll be the weekend before I can get to it though.

**Comment by shu8** [comment]
@Sir-Cumference fixed in [dev 2.0.26](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
