### ISSUE TITLE
Meta and chat links don't work

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#267]
### Current Behaviour
Meta links often send me to meta.tps//[site].stackexchange.com/, while chat links often send me to https://chat.stackexchange.com/?tab=site&host=tps://[site].stackexchange.com/. [site] refers to the website (for example, on Physics SE you'd just replace that with "physics").

I wrote a fix for this:

    metaChatBlogStackExchangeButton: function() {
        // Description: For adding buttons next to sites under the StackExchange button that lead to that site's meta and chat
        // NOTE: this feature used to have a 'blog' button as well, but it wasn't very useful so was removed

        var link, chatLink;

        $(document).on('mouseenter', '#your-communities-section > ul > li > a', function() {
            var href = $(this).attr('href').split('://').pop(); //Get rid of "http://" or "https://" from url, it only gets in the way
            chatLink = 'http://chat.stackexchange.com?tab=site&host=' + href.split('meta.').pop().split('discuss.').pop().split('/').shift(); //Get rid of "meta." or "discuss." prefixes for the chat links, as well as the "/" at the end of the url

            if (href.indexOf('stackapps') > -1) {
                link = undefined;
            } else if (href.indexOf('area51') > -1 && href.indexOf('discuss.area51') === -1) {
                link = 'http://discuss.area51.stackexchange.com/';
            } else if (href.indexOf('meta.stackexchange.com') > -1) {
                link = undefined;
                chatLink = 'http://chat.meta.stackexchange.com';
            } else if (href.indexOf('meta') > -1 || href.indexOf('discuss.area51') > -1) {
                link = 'http://' + href.split('meta.').pop().split('discuss.').pop();  //Remove "meta." or "discuss." prefixes in the "main" links
            } else {
                link = 'http://meta.' + href;
            }

            if (href.indexOf('stackoverflow.com') > -1 && !href.match(/(pt|ru|es|ja)\.stackoverflow/i)) { //Added Japanese
                chatLink = 'http://chat.stackoverflow.com';
            }

            //All sites have either a chat link or meta link, so no need for a condition
            $(this).find('.rep-score').stop(true).delay(135).fadeOut(20);
            $(this).prepend('<div class="related-links" style="float: right; display: none;">' +
                (link ?
                    (link.indexOf('discuss.area51') > -1 ? '<a href="' + link + '">discuss</a>' : (href.indexOf('meta') > -1 || href.indexOf('discuss.area51') > -1 ? '<a href="' + link + '">main</a>' : '<a href="' + link + '">meta</a>')) :
                    '') +
                (chatLink ? '<a href="' + chatLink + '">chat</a>' : '') +
                '</div>');
            $(this).find('.related-links').delay(135).css('opacity', 0).animate({
                opacity: 1,
                width: 'toggle'
            }, 200);

        }).on('mouseleave', '#your-communities-section > ul > li > a', function() {
            $(this).find('.rep-score').stop(true).fadeIn(110);
            $(this).find('.related-links').remove();
        });
    },

The code also adds "main" and "chat" links to meta sites, as these are on mobile sites:

![screenshot_20170315-144854](https://cloud.githubusercontent.com/assets/5375326/23965586/d27a986c-098e-11e7-978b-90108aad5eb1.png)

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-parseCrossSiteLinks","Extras-hideCertainQuestions"]

**Comment by shu8** [comment]
@Sir-Cumference Sorry for the delay in getting back! Thanks for the fix, I'll get this added in ASAP :)

**Comment by Sir-Cumference** [comment]
@shu8 I've fixed a few more bugs after SE upgraded to https:

    metaChatBlogStackExchangeButton: function() {
        // Description: For adding buttons next to sites under the StackExchange button that lead to that site's meta and chat
        // NOTE: this feature used to have a 'blog' button as well, but it wasn't very useful so was removed

        $(document).on('mouseenter', '#your-communities-section > ul > li > a', function() {
            var link, chatLink, href = $(this).attr('href').split('://').pop(); //Get rid of http:// or https:// from url
            chatLink = 'https://chat.stackexchange.com?tab=site&host=' + href.split('/').shift();

            if (href.indexOf('stackapps') > -1) {

            } else if (href.indexOf('area51') > -1) {
                if (href.indexOf('discuss.area51') === -1) {
                    link = 'https://discuss.area51.stackexchange.com/';
                }
                else {
                    link = 'https://area51.stackexchange.com/';
                }
                chatLink = 'https://chat.stackexchange.com?tab=site&host=area51.stackexchange.com'
            } else if (href === "meta.stackexchange.com") {
                chatLink = 'https://chat.meta.stackexchange.com';
            } else if (href.indexOf('meta') > -1) {
                link = 'https://' + href.split('meta.').pop().split('discuss.').pop();
                chatLink = 'https://chat.stackexchange.com?tab=site&host=' + href.split('meta.').shift() + href.split('meta.').pop().split('/').shift(); //We don't need "meta." in the chat links
            } else if (href.indexOf('.stackexchange.com') > -1 || href.indexOf('.stackoverflow.com') > -1) {
                link = 'https://' + href.split('.').shift() + '.meta' + href.split(href.split('.').shift()).pop();
            } else {
                link = 'https://meta.' + href;
            }

            if (href.indexOf('stackoverflow.com') > -1 && !href.match(/(pt|ru|es|ja)\.stackoverflow/i)) { //Added Japanese
                chatLink = 'http://chat.stackoverflow.com';
            }

            //All sites have either a chat link or meta link
            $(this).find('.rep-score').stop(true).delay(135).fadeOut(20);
            $(this).prepend('<div class="related-links" style="float: right; display: none;">' +
                (link ?
                    (link.indexOf('discuss.area51') > -1 ? '<a href="' + link + '">discuss</a>' : (href.indexOf('meta') > -1 || href.indexOf('discuss.area51') > -1 ? '<a href="' + link + '">main</a>' : '<a href="' + link + '">meta</a>')) :
                    '') +
                (chatLink ? '<a href="' + chatLink + '">chat</a>' : '') +
                '</div>');
            $(this).find('.related-links').delay(135).css('opacity', 0).animate({
                opacity: 1,
                width: 'toggle'
            }, 200);

        }).on('mouseleave', '#your-communities-section > ul > li > a', function() {
            $(this).find('.rep-score').stop(true).fadeIn(110);
            $(this).find('.related-links').remove();
        });
    },

**Comment by shu8** [comment]
@Sir-Cumference thanks! I've added your fix in [dev 2.0.25](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

Apologies for the delay! :/

**Comment by Sir-Cumference** [comment]
@shu8 Sigh, SE just changed the link for Area 51 Discussions. That causes a few conflicts. Here's the fixed code:

    metaChatBlogStackExchangeButton: function() {
        // Description: For adding buttons next to sites under the StackExchange button that lead to that site's meta and chat
        // NOTE: this feature used to have a 'blog' button as well, but it wasn't very useful so was removed
        // Modifications by @Sir-Cumference <https://github.com/soscripted/sox/issues/267>

        $(document).on('mouseenter', '#your-communities-section > ul > li > a', function() {
            var href = $(this).attr('href').split('://').pop(), //Get rid of http:// or https:// from url
                link,
                chatLink = 'https://chat.stackexchange.com?tab=site&host=' + href.split('/').shift();

            if (href.indexOf('stackapps') > -1) {

            } else if (href === "meta.stackexchange.com") {
                chatLink = 'https://chat.meta.stackexchange.com';
            } else if (href.indexOf('meta') > -1) {
                link = 'https://' + href.split('meta.').shift() + href.split('meta.').pop();
                chatLink = 'https://chat.stackexchange.com?tab=site&host=' + href.split('meta.').shift() + href.split('meta.').pop().split('/').shift(); //We don't need "meta." in the chat links
            } else if (href.indexOf('.stackexchange.com') > -1 || href.indexOf('.stackoverflow.com') > -1) {
                link = 'https://' + href.split('.').shift() + '.meta' + href.split(href.split('.').shift()).pop();
            } else {
                link = 'https://meta.' + href;
            }

            if (href.indexOf('stackoverflow.com') > -1 && !href.match(/(pt|ru|es|ja|.meta)/i)) {
                chatLink = 'https://chat.stackoverflow.com';
            }

            //All sites have either a chat link or meta link
            $(this).find('.rep-score').stop(true).delay(135).fadeOut(20);
            $(this).prepend('<div class="related-links" style="float: right; display: none;">' +
                (link ?
                    (link.indexOf('area51.meta') > -1 ? '<a href="' + link + '">discuss</a>' : (href.indexOf('meta') > -1 ? '<a href="' + link + '">main</a>' : '<a href="' + link + '">meta</a>')) :
                    '') +
                (chatLink ? '<a href="' + chatLink + '">chat</a>' : '') +
                '</div>');
            $(this).find('.related-links').delay(135).css('opacity', 0).animate({
                opacity: 1,
                width: 'toggle'
            }, 200);

        }).on('mouseleave', '#your-communities-section > ul > li > a', function() {
            $(this).find('.rep-score').stop(true).fadeIn(110);
            $(this).find('.related-links').remove();
        });
    },

**Comment by shu8** [comment]
@Sir-Cumference finally added this in in [dev 2.0.32](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :) Sorry for the delay again :/
