### ISSUE TITLE
SOX Broken again - NetworkError: 500 Internal Server Error - https://rawgit.com/soscripted/sox/master/sox.css?v=1.0.1a

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#27]
**Installed Version: 1.0.2  |  Environment: Firefox/GreaseMonkey**

Unable to change settings.

![screenshot - 18_03_2016 10_45_46](https://cloud.githubusercontent.com/assets/7079224/13875590/b53490ba-ecf6-11e5-834b-ba244d2e54dc.png)

**Error Logs**

`"NetworkError: 500 Internal Server Error - https://rawgit.com/soscripted/sox/master/sox.css?v=1.0.1a"
`

![screenshot - 18_03_2016 10_48_29](https://cloud.githubusercontent.com/assets/7079224/13875632/fb735a8e-ecf6-11e5-85a0-84cd5bd46bd9.png)

**Comment by enki-code** [comment]
@DavidPostill  This is totally our fault..  RawGit provides two URLs, one for development purposes and one for production. We've been using the development one, and the requests are likely being throttled. 

> If excessive traffic continues after throttling and blacklisting, RawGit may display an error message to users on your site to try to get your attention.

We'll get this taken care of ASAP.

Thanks.

**Comment by enki-code** [comment]
@DavidPostill I've pushed some changes to the master branch, if you could, please reinstall.

I've updated all the URLs to use RawGit's CDN, this should prevent throttling in the future.

**Comment by DavidPostill** [comment]
@enki-code  Reinstall errors as follows:

![screenshot - 18_03_2016 16_57_47](https://cloud.githubusercontent.com/assets/7079224/13885498/a162ba60-ed2a-11e5-98b2-29a83cf9e81a.png)

**Comment by shu8** [comment]
Just saw this... loving the error message though :P 

anyway, I think @enki-code forgot to add the actual filename to the URL so it doesn't exist.

Bit busy for a few hours, but I can change them by tonight if you can't @enki-code :)

Thanks again for the bug report @DavidPostill :D

**Comment by enki-code** [comment]
@shu8  Yes please, I have to leave!

**Comment by shu8** [comment]
fixed by @enki-code in the end
