### ISSUE TITLE
Upvoting comments shifts the text

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#271]
### Installed Version: 2.0.24  Environment: Tampermonkey

If you upvote a comment with a score of 0, the text shifts:
![upvote](https://cloud.githubusercontent.com/assets/5375326/24256872/b57927ba-0fbf-11e7-93f3-4b8f0f5dda3f.gif)

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Extras-parseCrossSiteLinks","Extras-hideCertainQuestions"]

**Comment by shu8** [comment]
@Sir-Cumference thanks for the bug reports! We'll look into them ASAP! :)

**Comment by shu8** [comment]
@Sir-Cumference This seems to be normal with SOX disabled -- it looks like if there are no comments under that post with upvotes, and you upvote the first one, then then comments shift :/

Can you confirm this is correct? :)

**Comment by Sir-Cumference** [comment]
@shu8 Seems right.

**Comment by shu8** [comment]
@Sir-Cumference hmmm, you might be able to post this as a bug/feature-request on Meta then? :/

**Comment by Sir-Cumference** [comment]
@shu8 Yeah, I tried it with SOX disabled on comment that wasn't the first one. It didn't shift, so I assumed it was an SOX bug 😆
