### ISSUE TITLE
SE dialog boxes don't open when hovering from SOX dialog boxes

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#272]
### Installed Version: 2.0.24  Environment: Tampermonkey

If you click on the SE inbox button for the first time on a page, and then (without closing the dialog) hover over the SE reputation button for the first time, it'll open normally:

![screenflow](https://cloud.githubusercontent.com/assets/5375326/24257677/df5b3328-0fc1-11e7-90dd-6457ee5e708b.gif)

The same works vice versa, and it works from one SOX button to another SOX button. However, if you go from an SOX button to either the inbox or reputation, the dialogs won't open.

![screenflow](https://cloud.githubusercontent.com/assets/5375326/24257913/7fa9acec-0fc2-11e7-8b51-9784ef1c4900.gif)

However, going from the inbox or reputation to the SOX buttons *will* the SOX dialogs. The problem only happens when the inbox and reputation dialogs have not been opened before.

Also, I don't know if the same applies when going from the SOX buttons to the official SE moderator inbox.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Extras-parseCrossSiteLinks","Extras-hideCertainQuestions"]

**Comment by shu8** [comment]
@Sir-Cumference fixed in [dev 2.0.29](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

It's a bit of a hacky fix, so there might be a few bugs that I've introduced. Whilst I couldn't see anything weird happening, I've got a track record of adding in bugs :P so please comment here if anything dodgy happens :)

**Comment by Sir-Cumference** [comment]
@shu8 Well, I found something 😄 

If you hover on the SOX settings button and then hover on the Stack Exchange button (without hovering on the inbox or rep buttons), nothing below "More Stack Exchange Communities" will load:

<img width="716" alt="screen shot 2017-04-25 at 6 36 12 pm copy" src="https://cloud.githubusercontent.com/assets/5375326/25410674/393713ce-29e6-11e7-9817-249a44316380.png">

Even weirder, if you hover on the Meta or Notify on Edit questions first and then hover on the SE button, the dialog will completely hide the other buttons (including the SE button):

<img width="716" alt="screen shot 2017-04-25 at 6 36 12 pm copy" src="https://cloud.githubusercontent.com/assets/5375326/25410696/6738c36c-29e6-11e7-8a58-f39a13d5b466.png">
