### ISSUE TITLE
Browser hang/continuous memory leak upon clicking Start Bounty when Make bounty box draggable enabled

### ISSUE THREAD

**Issue by TuggyNE** [soscripted/sox#275]
### Installed Version: / Environment
2.0.12 / Pale Moon 25.6.0 x64, Windows 10

### Current Behaviour
Hangs browser with continuously increasing memory and full CPU utilization.

---

### SOX Errors logged to the browser console -- F12 (if available)
None.

---

### Steps to reproduce
1. Open a question that's eligible for a bounty, e.g. https://space.stackexchange.com/questions/20694/how-well-can-hybrid-motors-be-throttled
2. Click the Start Bounty link

If given feature is not enabled, nothing out of the ordinary happens.

---

### Features Enabled 
(nothing else bounty-related)

**Comment by shu8** [comment]
@TuggyNE hmm, I can't seem to reproduce this -- does it happen on multiple sites or just Space?

**Comment by TuggyNE** [comment]
@shu8 Sorry for the late reply. Yes. Meta SE exhibits the same behavior.

**Comment by shu8** [comment]
@TuggyNE Sorry I took so long to respond! Can you try installing [dev 2.0.30](https://github.com/soscripted/sox/raw/dev/sox.user.js) and see if it fixes it? I still haven't managed to reproduce it unfortunately, but this update might fix it :)
