### ISSUE TITLE
No SOX settings button in 2.0.26 dev

### ISSUE THREAD

**Issue by darkred** [soscripted/sox#276]
### Installed Version: Environment: 

2.0.26 dev
Firefox 52 with Greasemonkey 3.10 and 
Chrome 57 with Tampermonkey 4.2.7

### Current Behaviour

The issue occurs in both Firefox and Chrome. (the following are screenshots from Chrome)
The SOX settings button no longer appears:
![2017-04-01_192029](https://cloud.githubusercontent.com/assets/723651/24580400/60c72a20-1710-11e7-8ec8-8fdf17d9f254.jpg)

In [2.0.24](https://github.com/soscripted/sox/raw/bd6fed747ee357a33cfc9e84efd3baf6b10112ad/sox.user.js) it appeared ok:
![649242fc-1710-11e7-9b6e-e3881e1a073d](https://cloud.githubusercontent.com/assets/723651/24580426/af44dcba-1710-11e7-877b-50dbede8e806.jpg)

### SOX Errors logged to the browser console -- F12 (if available)

From Firefox:
```
- XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.  sox.common.js:74
- SOX:  There was an error loading the feature "Appearance-metaNewQuestionAlert". Please raise an issue on GitHub, and copy the following error log:
TypeError: $(...).position(...) is undefined  sox.common.js:36
- SOX:  There was an error loading the feature "Editing-downvotedPostsEditAlert". Please raise an issue on GitHub, and copy the following error log:
TypeError: $(...).position(...) is undefined
```

### Steps to reproduce

Just install SOX 2.0.26 and then open http://stackoverflow.com/ _(and receive the access token following the instructions)_
For comparison uninstall 2.0.26 and install [2.0.24](https://github.com/soscripted/sox/raw/bd6fed747ee357a33cfc9e84efd3baf6b10112ad/sox.user.js)

### Features Enabled 

All default ones.

**Comment by shu8** [comment]
Thanks for the bug report! Sorry, I completely forgot about the SO new header!

Fixed in [dev 2.0.27](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
