### ISSUE TITLE
Added editor features conflict with firefox's edit link shortcut

### ISSUE THREAD

**Issue by DoS007** [soscripted/sox#278]
### Steps to reproduce
Use Ctrl+L on a superuser.com question while "Add more features to the markdown editor" is enabled. This opens a dialog to insert a link instead of focusing on the address bar (the alternative is F6 which is much slower because of physical distance to the F* Buttons).

The other features of "Add more features to the markdown editor" are great, but CTRL+L is crucial for me. 

Maybe CTRL+ALT+L is an alternative?

**Comment by mezmi** [comment]
Sorry for the delayed response, yes, we can switch this to a different set of hot keys.

**Comment by shu8** [comment]
@DoS007 sorry for how long this took, but I've changed the hotkey to Ctrl Alt L as you suggested in [dev 2.0.30](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

Hope it works for you now! :)
