### ISSUE TITLE
Display review stats as a table displays editor status incorrectly

### ISSUE THREAD

**Issue by KutuluMike** [soscripted/sox#279]
### Current Behaviour

When the setting "Display reviewer stats on /review/suggested-edits in table form" is enabled, the table displays the "Editor stats" incorrectly. With the option off, the page looks like this:

![nosox](https://cloud.githubusercontent.com/assets/15930708/25317052/30a8703e-283f-11e7-94c4-4e8014404fb9.PNG)

When the setting is enabled, the Editor Stats line is pushed into the same table as the Reviewer Stats, but the numbers are wrong:

![review](https://cloud.githubusercontent.com/assets/15930708/25317054/43715c26-283f-11e7-99c3-1747bfcdf944.PNG)

A few things of note:

* The number of accepted edits should be 1. The number shown is, of course, from their username.
* Despite the name, this is a registered user for over 3 years, however, this appears to be their first piece of activity on this specific stack site.

### Steps to Reproduce

The issues appears to occur whenever a user with a default name suggests an edit, e.g. on SF/F:

* https://scifi.stackexchange.com/review/suggested-edits/103923 by user2428118
* https://scifi.stackexchange.com/review/suggested-edits/104008 by user60561

To reproduce, scan the suggested edits list (e.g. https://scifi.stackexchange.com/tools/suggested-edits?page=2&tab=all&filter=week) and look for edits by userXXXXX. Toggle the "review stats as a table" option on/off and refresh.

**Comment by shu8** [comment]
@KutuluMike thanks for spotting and reporting this! I can reproduce it and will get it fixed ASAP! :)

**Comment by shu8** [comment]
@KutuluMike sorry this took soooo long, but I've fixed it in [dev 2.0.30](https://github.com/soscripted/sox/raw/dev/sox.user.js) now! :)
