### ISSUE TITLE
Duplicate closures and edit expansion

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#281]
### Current Behaviour

Only one entry of a  multi-duplicate question shows that it is expandable:

![image](https://cloud.githubusercontent.com/assets/1776164/25554965/74756f1a-2c90-11e7-8e48-867fa61a0045.png)

Source: [LaTeX table cell with a diagonal line and 2 sub cells](https://tex.stackexchange.com/q/27193/5764)

Also, the "edit" option shows that it's expandable when it's not.

![image](https://cloud.githubusercontent.com/assets/1776164/25555080/6a4c7180-2c92-11e7-8d0e-23f12704fbe3.png)

Source: [Problem with footnote in captionof](https://tex.stackexchange.com/q/180195/5764)

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar"]

**Comment by shu8** [comment]
@wgrundlingh I've (finally!) fixed the first issue you mentioned in [dev 2.0.30](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

But I don't see an edit option on the duplicate entries :/ how do you get that option? :)

**Comment by wgrundlingh** [comment]
@shu8 This was implemented for mods and gold badge holders in the question tags. So you'll only see it in some questions - those you have the dupe-hammer capacity.

See [Gold tag-badge holders and moderators can now edit duplicate links](https://meta.stackexchange.com/q/291824/168244).

**Comment by shu8** [comment]
@wgrundlingh that's annoying, I don't have any gold badges! :(

Would it be possible for you to right click on the edit link, click 'inspect element', and screenshot the window that pops up for me so I can try and fix it? :)

**Comment by wgrundlingh** [comment]
@shu8 Would this suffice?

![image](https://cloud.githubusercontent.com/assets/1776164/26475755/8ea6a730-416e-11e7-8931-2dce0c8e4b32.png)

**Comment by shu8** [comment]
thanks, that's perfect! :) I'll get it fixed soon :)

**Comment by shu8** [comment]
@wgrundlingh Thanks, that's perfect! :)

Please could you see if this is fixed for you in [dev 2.0.32](https://github.com/soscripted/sox/raw/dev/sox.user.js)? :)

**Comment by wgrundlingh** [comment]
Works like a charm on both accounts!

![image](https://cloud.githubusercontent.com/assets/1776164/26502410/9aff31f4-41f1-11e7-8ec3-04fd2eb924e4.png)

![image](https://cloud.githubusercontent.com/assets/1776164/26502376/77a9b1e8-41f1-11e7-96b0-e00b847b291d.png)
