### ISSUE TITLE
Move "question eligible for bounty in x hours" link to before the comments

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#282]
### Installed Version: 2.0.29  Environment: Tampermonkey

Small request, but if "Move the 'start a bounty' link to before the comments" is enabled, could you also move the "question eligible for bounty in x hours" link for consistency?

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-hideCertainQuestions","Extras-showMetaReviewCount"]

**Comment by Sir-Cumference** [comment]
@shu8 Done 👍 

    moveBounty: function() {
        // Description: For moving bounty to the top

        $('.bounty-notification').insertAfter('.question .fw'); //$('.bounty-notification').length condition isn't necessary; this line will run only if the element exists
        $("[id='bounty-link bounty']").closest('tr').insertAfter('.question .fw');
    },

**Comment by shu8** [comment]
Thanks again!! I'll get it in soon! :)

**Comment by shu8** [comment]
Thanks @Sir-Cumference. Added in [dev 2.0.30](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by mezmi** [comment]
@Sir-Cumference I've added you as a collaborator so you can push updates. Thank you for all the help.

**Comment by Sir-Cumference** [comment]
@mezmi No problem :)

**Comment by Sir-Cumference** [comment]
@mezmi Quick question. From now on, should I update the code directly if I fix a bug, or create a pull request?

**Comment by shu8** [comment]
You can update the code directly! :)

Thanks for all the help you're giving us! :)


On 30 May 2017 21:38, "Sir-Cumference" <notifications@github.com> wrote:

@mezmi <https://github.com/mezmi> Quick question. From now on, should I
update the code directly if I fix a bug, or create a pull request?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/soscripted/sox/issues/282#issuecomment-305001076>, or mute
the thread

**Comment by Sir-Cumference** [comment]
@shu8 Right. Thanks :)

Admittedly, I really don't have much experience with Github, so I'll have to get used to it :/

**Comment by shu8** [comment]
No problem! :) If you get stuck you can ask either of us or just submit a
pull request and we'll merge it :)

We really appreciate your help :)
