### ISSUE TITLE
Suggestions/bugs for "Color answerer's comments"

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#283]
### Installed Version: 2.0.29  Environment: Tampermonkey

I have two suggestions for the "Color answerer's comments" feature. First, could you add `padding: 1px 5px` to the CSS for those comments, in order to make it look more like the OP's comments? Second, could you change the orange color to something a little lighter and less flashy, like `#f9e2b6`? :)

The end result would look like this:

<img width="683" alt="screen shot 2017-05-17 at 2 51 06 pm" src="https://cloud.githubusercontent.com/assets/5375326/26170689/4b4a9a82-3b10-11e7-9985-a39e717ee679.png">

I also found two bugs. On [this](https://codegolf.stackexchange.com/a/119746) post, you can see that anyone who has answered the question will have a highlighted name on every comment section. Also, you can see [here](https://codegolf.stackexchange.com/a/119759) that if someone edited an answer, their name will be highlighted, not the answerer.

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-hideCertainQuestions","Extras-showMetaReviewCount"]

**Comment by Sir-Cumference** [comment]
Solved :)

    colorAnswerer: function() {
        // Description: For highlighting the names of answerers on comments

        function colour() {
            $('.answercell').each(function(i, obj) {
                var x = $(this).find('.user-details a').last().text();
                $(this).parent().next().find('.comment-user').each(function() {
                    if ($(this).text() == x) {
                        $(this).css({'background-color': '#f9e2b6', 'padding': '1px 5px'});
                    }
                });
            });
        }

        colour();
        $(document).on('sox-new-comment', colour);
    },

**Comment by shu8** [comment]
thanks soooo much!!! :)

I'll try and get this added in ASAP!! :)

On 23 May 2017 at 18:57, Sir-Cumference <notifications@github.com<mailto:notifications@github.com>> wrote:

Solved :)

colorAnswerer: function() {
    // Description: For highlighting the names of answerers on comments

    function colour() {
        $('.answercell').each(function(i, obj) {
            var x = $(this).find('.user-details a').last().text();
            $(this).parent().next().find('.comment-user').each(function() {
                if ($(this).text() == x) {
                    $(this).css({'background-color': '#f9e2b6', 'padding': '1px 5px'});
                }
            });
        });
    }

    colour();
    $(document).on('sox-new-comment', colour);
},

**Comment by shu8** [comment]
@Sir-Cumference thanks for bearing with me! Done in [dev 2.0.30](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
