### ISSUE TITLE
`[postname[([postname](url))` instead of `[postname](url)` 

### ISSUE THREAD

**Issue by ooker777** [soscripted/sox#286]
### Installed Version: 2.0.29  Environment: Firefox
I have two machines, one is Linux Mint 17, and one is Windows 7, both have this problem.

### Current Behaviour

`[What is the mintSources error when installing PPA?]([What is the mintSources error when installing PPA?](https://unix.stackexchange.com/q/366701/60602))`

### SOX Errors logged to the browser console -- F12 (if available)

This is the one taken from my Linux machine:
```
soup injecting fixes SOUP.user.js:1912:23
soup init complete what-is-the-mintsources-error-when-installing-ppa:30:25
url: unix.stackexchange.com/questions/366701/what-is-the-mintsources-error-when-installing-ppa storageName：jVXvmUWKnUnkrALM rule: default %25E7%25BD%2591%25E9%25A1%25B5%25E9%2599%2590%25E5%2588%25B6%25E8%25A7%25A3%25E9%2599%25A4.user.js:229:5
"Please enter an access token. See more details at http://shu8.github.io/Freehand-Circles-Drawing-Tool" freehandCircles.user.js:223:5
soup setup complete what-is-the-mintsources-error-when-installing-ppa:30:25
soup JS fixes applied what-is-the-mintsources-error-when-installing-ppa:30:25
soup subscribed to realtime feed for question 366701 on site 106 what-is-the-mintsources-error-when-installing-ppa:30:25
SOX:  inlineEditorEverywhere error: sox.Stack.using not found sox.common.js:30:13

```
### Steps to reproduce

Just click on the share button

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-displayName","Appearance-dragBounty","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideHireMe","Sidebar-hideChatSidebar","Sidebar-hideLoveThisSite","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-hideCertainQuestions","Extras-showMetaReviewCount","Extras-dailyReviewBar","Extras-openLinksInNewTab","Extras-showQuestionStateInSuggestedEditReviewQueue"]

**Comment by ooker777** [comment]
No, it happens on all sites and all questions in my computer. Here is what is shown on the dev tool:

```
url: english.stackexchange.com/questions/391121/how-does-at-seeing-finer-than-when-seeing storageName：aAaeZepaUomuYNhHW rule: default  %25E7%25BD%2591%25E9%25A1%25B5%25E9%2599%2590%25E5%2588%25B6%25E8%25A7%25A3%25E9%2599%25A4.user.js:229:5
"Please enter an access token. See more details at http://shu8.github.io/Freehand-Circles-Drawing-Tool"  freehandCircles.user.js:223:5
Blocked loading mixed active content “http://www.corsproxy.com/blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.js”[Learn More]  Paste_images_in_SE_sites.user.js:83:2
SOX:  inlineEditorEverywhere error: sox.Stack.using not found  sox.common.js:30:13
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/  jquery-2.1.4.min.js:4:14346
SyntaxError: expected expression, got '<'[Learn More]  how-does-at-seeing-finer-than-when-seeing:1
SOX:  There was an error loading the feature "Extras-openLinksInNewTab". Please raise an issue on GitHub, and copy the following error log:
TypeError: settings.linksToOpenInNewTab is undefined  sox.common.js:36:13

```

**Comment by shu8** [comment]
@ooker777 I've made a small change to the feature in [dev 2.0.33](https://github.com/soscripted/sox/raw/dev/sox.user.js) which might fix this for you.. please could you install this version and see if it still happens? :)

**Comment by ooker777** [comment]
It worsens the problem :(

#Sharing link of question:
`[How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x](https://stackoverflow.com/q/9452108/3416774)))))))))))`

#Sharing link of answer:
[How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x]([How to use string.replace() in python 3.x](https://stackoverflow.com/q/9452108/3416774)))))))))))))))))))))))))

However, in Academia, it follows the Hippocratic Oath:

`[Does your supervisor have to be able to understand your thesis?]([Does your supervisor have to be able to understand your thesis?](https://academia.stackexchange.com/q/90208/14341))`

**Comment by shu8** [comment]
@ooker777 no worries, glad it's working now.

I can reproduce the issue with this specific question and I'm working on a fix :)

**Comment by shu8** [comment]
@ooker777 fixed in [dev 2.0.34](https://github.com/soscripted/sox/raw/dev/sox.user.js) (I think!) Please could you install it and check :)

**Comment by ooker777** [comment]
Thanks, it works. What happened?

**Comment by shu8** [comment]
@ooker777 the 'fix' that I did before didn't really work most of the time! I ended up just reverting the changes and going back to the original 😆

**Comment by ooker777** [comment]
Thanks for your work 😁. Btw, this bug also appears in the wiki 😉
