### ISSUE TITLE
Bug: "Hide just the 'Hot Meta Posts' sections in the Community Bulletin" not always working

### ISSUE THREAD

**Issue by Gloin1313** [soscripted/sox#287]
### Current Behaviour
In #264 "Hide just the 'Hot Meta Posts' sections in the Community Bulletin" was added, but it doesn't always work correctly. Currently there are no featured blog posts in the Community Bulletin, and SOX is only removing one of the "Hot on Meta" posts, and grouping the rest together with "Featured on Meta".

With option turned on:
![screen shot 2017-05-28 at 15 12 21](https://cloud.githubusercontent.com/assets/22625968/26529463/19915106-43b8-11e7-8575-edfc935b5b4b.png)

With option turned off:
![screen shot 2017-05-28 at 15 10 33](https://cloud.githubusercontent.com/assets/22625968/26529455/f3807a78-43b7-11e7-8782-baf8f139ff91.png)

**Comment by shu8** [comment]
Thanks for the bug report, I'll get this fixed as soon as I can :) I must
have missed this when I added the feature! :/

**Comment by shu8** [comment]
@Gloin1313 Fixed in [dev 2.0.33](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by Gloin1313** [comment]
Thank you, this works fine now
