### ISSUE TITLE
Incorrect author associated with comment

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#288]
### Current Behaviour

Incorrect author associated with comment:

![image](https://cloud.githubusercontent.com/assets/1776164/26557620/ac8f0468-4457-11e7-98d8-559e8f152004.png)

Wondering if anyone can reproduce this...? It seems to be only the latest comment. haven't done any other testing, unfortunately.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar"]

**Comment by shu8** [comment]
@wgrundlingh hmm I can't reproduce this. Please could you see what the user ID for the user called egreg and the Joris Meys in the screenshot you posted? if they turn out to be the same ID then it's probably because the script is getting the username from a different ID site and it's getting confused.

**Comment by wgrundlingh** [comment]
@shu8 They are different users with completely different user IDs: [Joris Meys](https://tex.stackexchange.com/users/1463/joris-meys) and [egreg](https://tex.stackexchange.com/users/4427/egreg). However, my inbox doesn't always show the user name added to the comment. Not sure why that's the case. I'm trying different scenarios to recreate/replicate the behaviour.

![image](https://cloud.githubusercontent.com/assets/1776164/26558255/37ca67bc-445c-11e7-8093-899a250e0c09.png)

**Comment by shu8** [comment]
@wgrundlingh i have a feeling you've been throttled now because you were probably opening the inbox a lot in a very short period of time which the API wouldn't have liked :/ please could you check the console to see if there are any error messages in it? :)

**Comment by wgrundlingh** [comment]
@shu8 Indeed being throttled. I should look at the console more often. :-|

![image](https://cloud.githubusercontent.com/assets/1776164/26558461/cc4026ce-445d-11e7-97ec-2ca232227b72.png)

One thing I noticed: The script seems to (attempt to) grab the comment authors when you click on the inbox *and* when it's closed. Is this necessary? Either when you click the inbox and then click it again to close it, or move away and it's closed automatically.

![latex_stuff](https://cloud.githubusercontent.com/assets/1776164/26558544/701f8848-445e-11e7-9a7c-71d4c99e0f67.gif)

**Comment by shu8** [comment]
@wgrundlingh hmm you're right it does. I think I originally did that because I wanted to make sure it caught any *new* notifications without a page refresh, but the solution I've done is definitely not ideal.

Thanks for bringing it up, it needs to be fixed! 

Is the wrong author still being added? :)

**Comment by wgrundlingh** [comment]
@shu8 At the moment, the incorrect author display is on-and-off. Having tagged this thread with **confirmed**, are you able to confirm this?

**Comment by shu8** [comment]
@wgrundlingh I haven't reproduced it, I added 'confirmed' for the fact that the script fetches the info too much :/

I'll add some console debugging in for you soon though so I can figure this out! :)

**Comment by shu8** [comment]
@wgrundlingh I've added some debugging in for you in [dev 2.0.36](https://github.com/soscripted/sox/raw/dev/sox.user.js).

Please can you install this version and then enable debugging from bottom of the settings dialog and paste the console contents here? And please could you also screenshot your inbox so I can see how the console log relates to the actual inbox (you can blur out the messages if you want to!) 
Thanks! :)

**Comment by wgrundlingh** [comment]
@shu8 I install dev 2.0.36; don't know whether the below information is sufficient.

Image of inbox/comment ([egreg](https://tex.stackexchange.com/users/4427/egreg) is user 4427; [Joris Meys](https://tex.stackexchange.com/users/1463/joris-meys) is user 1463):

![image](https://cloud.githubusercontent.com/assets/1776164/26655051/eee34326-460d-11e7-94f3-006c8ae2ebd1.png)

Here is the console:

```
DevTools failed to parse SourceMap: https://tex.stackexchange.com/questions/372083/how-to-convert-roman-into-arabic-numeral/jquery.timeago.min.js.map
VM1520:589 SOX:  logging sox stored values --- 
VM1520:589 SOX:  access token set
VM1520:589 SOX:  SOX-debug
VM1520:589 SOX:  true
VM1520:589 SOX:  SOXSETTINGS
VM1520:589 SOX:  ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar"]
VM1520:589 SOX:  downvotedPostsEditAlert
VM1520:589 SOX:  {"347192":{"questionId":"347192","addedDate":1483602847263,"sitename":"tex","lastCheckedTime":1484368203293},"347197":{"questionId":"347192","addedDate":1483602833281,"sitename":"tex","lastCheckedTime":1484368203396},"347487":{"questionId":"347484","addedDate":1483740886378,"sitename":"tex","lastCheckedTime":1484368203507}}
VM1520:589 SOX:  editReasons
VM1520:589 SOX:  [["updated markdown","updated markdown"],["retag","retag"]]
VM1520:589 SOX:  metaNewQuestionAlert-lastQuestions
VM1520:589 SOX:  {"meta.tex":"How to including multimedia files in beamer [Work in progress, please ignor for the moment]"}
VM1520:8 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ VM1520:8
ajax @ VM1520:8
getFromAPI @ VM1520:670
getIdsAndAddDetails @ VM1520:3582
quickAuthorInfo @ VM1520:3607
init @ VM1520:4412
(anonymous) @ VM1520:622
j @ VM1520:6
fireWith @ VM1520:6
ready @ VM1520:6
I @ VM1520:6
(anonymous) @ VM1498:2
b @ VM1498:2
t @ VM1506:47
VM1520:589 SOX:  SOX does not currently support get author information for type: code edited on answer
2VM1520:589 SOX:  SOX does not currently support get author information for type: answer edited
5VM1520:589 SOX:  SOX does not currently support get author information for type: code edited on answer
```

**Comment by shu8** [comment]
@wgrundlingh sorry for taking a while to respond!

It looks like a recent Chrome update disabled full console debugging :(

Please could you change the debugging level to 'Verbose'? (there's an option of 'info', 'warnings', or 'errors' otherwise) :)

**Comment by shu8** [comment]
@wgrundlingh does this still happen? Sorry for the inactivity these past few months :/

**Comment by wgrundlingh** [comment]
@shu8 Not that I can see. We can close it in the meantime, until it pops up again... *if* it pops up again.
