### ISSUE TITLE
Suggestion for "Show when the post's author was last seen and whether they are registered"

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#290]
Just wondering what you thought of this. I tried making the "last seen" text resemble the rest of the user's info:

<img width="200" alt="screen shot 2017-05-31 at 11 10 53 am" src="https://cloud.githubusercontent.com/assets/5375326/26642259/248676aa-45fb-11e7-8450-ff6ebf04683b.png">

You can see that the text's color now matches the rest of the info, it's a bit smaller, and it's shifted a bit. Should we implement it?

**Comment by j-f1** [comment]
What about putting it between the user info and the timestamp?

> asked Feb 10 '16 at 10:00 am
> [clock] about 7 hours ago, registered
> `[  top of avatar ]` McGafter
> `[bottom of avatar]` 133  • 6

**Comment by Sir-Cumference** [comment]
@j-f1 Hmm...maybe it's just me, but this:
<img width="200" alt="screen shot 2017-05-31 at 12 52 19 pm" src="https://cloud.githubusercontent.com/assets/5375326/26643666/1135bd54-4600-11e7-81a4-05bddbbb0776.png">
seems a bit awkward, imo. 😕

**Comment by j-f1** [comment]
Also, maybe it should only show if the user is unregistered: most are registered, and it’s pretty easy to tell if someone’s a moderator.

**Comment by shu8** [comment]
@Sir-Cumference it looks good! :)

@j-f1 I think that sounds reasonable -- we could make it only show 'unregistered'?

**Comment by Sir-Cumference** [comment]
@shu8 @j-f1 Done. It's a bit hacky, but it should work :)
