### ISSUE TITLE
Feature request: Optional [] conversion to ()

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#292]
### Current Behaviour

It seems that, by default, `[` and `]` are switched to `(` and `)` as part of the "share" button. Can this be turned into an *option* rather?

![image](https://cloud.githubusercontent.com/assets/1776164/26698971/e4c3dad0-46cc-11e7-8cc6-8a8487da8155.png)

Reference: [Why is \( ... \) preferable to $$ ... $$?](https://tex.stackexchange.com/q/503/5764)

Motivation: `\[` and `\]` have special meaning which is different `\(` and `\)` in the world of LaTeX.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar"]

**Comment by j-f1** [comment]
It should probably escape `\[` to `\\\[`.

**Comment by wgrundlingh** [comment]
@j-f1 I usually escape the code-related content in a title using backticks, so changing `\[` to `\\\[` wouldn't help *me*. Not sure whether I'm just a special case in my usage. Don't think so though.

**Comment by j-f1** [comment]
```markdown
[test \[ link](https://stackoverflow.com)  
[test \\\[ link](https://stackoverflow.com)
```
renders as:

> [test \[ link](https://stackoverflow.com)  
> [test \\\[ link](https://stackoverflow.com)

**Comment by shu8** [comment]
This sounds reasonable; I'll look into it ASAP and if there's no real reason it's doing what it is, I can get this done :)

**Comment by shu8** [comment]
@wgrundlingh [dev 2.0.39](https://github.com/soscripted/sox/raw/dev/sox.user.js) doesn't replace them anymore :)
