### ISSUE TITLE
Regional (or 12-hour) timestamps

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#293]
I wrote a [script](https://stackapps.com/questions/7379/regional-12-hour-timestamps) that displays timestamps based on your timezone, in 12-hour format. It's based on [another script](https://stackapps.com/questions/2528/display-absolute-timestamps-in-local-time), so if it's OK with you, I could ask him for permission and then implement it.

I've already written the code to implement it into SOX, which would make the 12-hour format optional:

<img width="539" alt="screen shot 2017-06-05 at 12 30 33 pm" src="https://cloud.githubusercontent.com/assets/5375326/26793124/d860f04a-49ea-11e7-8953-c475a2ad9a99.png">

What do you think? :)

**Comment by shu8** [comment]
@Sir-Cumference looks really good! If the author gives permission, let's add it! :)

**Comment by Sir-Cumference** [comment]
@shu8 He said "no problem". We should probably credit him in the changelog for writing a good chunk of it, since he says "Do whatever you want, as long as you don't sell it or claim you wrote it." in his license.

**Comment by Sir-Cumference** [comment]
@shu8 Added to [dev 2.0.37](https://github.com/soscripted/sox/raw/dev/sox.user.js) 👍

**Comment by Sir-Cumference** [comment]
@shu8 Just wanted to apologize for being inactive for so long. College is incredibly time consuming 😩, but I'll try and work on it when I can.

**Comment by shu8** [comment]
Don't worry about it! I'm in exactly the same boat 😂 this is just a side
project so it's fine! :)
