### ISSUE TITLE
Autocorrect incorrectly removes extensions

### ISSUE THREAD

**Issue by SathyaBhat** [soscripted/sox#294]
### Current Behaviour

Clicking the "Autocorrect" option incorrectly removes the extensions from text - ie, for ex `.log` becomes `. og` . Have a look at this revision

https://superuser.com/posts/1235710/revisions

Ideally it should ignore whatever is in codeblock completely. 

There's a much better autocorrect/edit project by @astrocb ( https://github.com/AstroCB/Stack-Exchange-Editor-Toolkit ) which I'd suggest using for the Autocorrect features

---

### SOX Errors logged to the browser console -- F12 (if available)

None
---

### Steps to reproduce

1. Go to any post which has extension in its text ( ex `.py` etc
2. Click on Auto correct
---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-displayName","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-linkedPostsInline","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-sortByBountyAmount","Unsorted-warnNotLoggedIn"]

**Comment by shu8** [comment]
@SathyaBhat Thanks! I'll see if I can get this fixed when I get back after a few weeks :) and I'll look into that toolkit too! :)

**Comment by shu8** [comment]
So, I'm removing the autocorrect feature; the userscript you linked to is much better and I'd literally be cloning it if I were to add it in SOX! 

to anyone who sees this: use  https://github.com/AstroCB/Stack-Exchange-Editor-Toolkit!
