### ISSUE TITLE
[title](linklink)

### ISSUE THREAD

**Issue by ooker777** [soscripted/sox#295]
### Current Behaviour
`[How can I protect my eyesight when using computers?](https://health.stackexchange.comhttps://health.stackexchange.com/q/52/99)`

### SOX Errors logged to the browser console -- F12 (if available)
```
"Please enter an access token. See more details at http://shu8.github.io/Freehand-Circles-Drawing-Tool"  freehandCircles.user.js:223:5
SOX:  inlineEditorEverywhere error: sox.Stack.using not found  sox.common.js:30:13
SOX:  There was an error loading the feature "Extras-openLinksInNewTab". Please raise an issue on GitHub, and copy the following error log:
TypeError: settings.linksToOpenInNewTab is undefined  sox.common.js:36:13
```

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideHireMe","Sidebar-hideChatSidebar","Sidebar-hideLoveThisSite","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-hideCertainQuestions","Extras-showMetaReviewCount","Extras-dailyReviewBar","Extras-openLinksInNewTab","Extras-showQuestionStateInSuggestedEditReviewQueue"]

**Comment by shu8** [comment]
@ooker777 thanks for the bug report, I'll get this fixed ASAP! :)

(sorry for the delay in replying! :/ )

**Comment by shu8** [comment]
@ooker777 I only just got round to looking at this, and I can't seem to reproduce the issue -- does this still happen for you? :)

**Comment by Franck-Dernoncourt** [comment]
I use V2.0.38 and  it works well on my side. I use this feature several times per day on average, it's very convenient :-)

**Comment by ooker777** [comment]
This bug has disappeared. Thanks
