### ISSUE TITLE
Feature request: custom magic links available on posts 

### ISSUE THREAD

**Issue by ooker777** [soscripted/sox#296]
Most of the time, when I go to a child meta site to ask if a question is on-topic on it or not, I usually need to manually go to its help section to link the "What topics can I ask about here?" page. There are [magic links](https://meta.stackexchange.com/a/94000/260800), but they only work in comments, except `[tag:tag-name]` and `[meta-tag:tag-name]`.

Would it be possible to make them available on posts as well? If no, what hinders this?

**Comment by shu8** [comment]
@ooker777 this is an interesting suggestion! I'll look into whether the way I'm doing it right now will be easy to modify to work in posts and if it is, I'll get it done in this version :)

**Comment by ooker777** [comment]
I advertise this request [here](https://meta.stackexchange.com/a/320281/260800)

**Comment by shu8** [comment]
Thanks for that :)

I'm considering rewriting [this userscript](https://meta.stackexchange.com/questions/274240/adding-magic-link-for-meta-stack-overflow/278421#278421) I made to work for both comments and answers (and clean up the code too). Do you think that would be useful?

**Comment by ooker777** [comment]
I think I don't need too much of that; just a shortcut for a frequent use is enough. But if you already have a script for that, then why not?

**Comment by shu8** [comment]
@ooker777 Done in [dev 2.3.21](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

It's a slightly adapted version of my other userscript https://stackapps.com/q/6650.

Please give it a shot and let me know how it works. I need to improve the extended description I've added to the dialog, but in short this is how to use it:

- set your magic links via the link added to the Help dropdown at the top-right of the page
- use the placeholders `$BASEURL`, `$METABASEURL`, `$QUESTIONID`, and `$ANSWERID` in the URL

It's in the Extras section in the settings dialog

e.g.:

![this](https://user-images.githubusercontent.com/8850830/50495573-ee511300-0a21-11e9-92fd-df1a5b76e534.gif)

---

Note this does require you to define your own magic links, so the ones already available in comments will need to be manually added if you want to use them in posts! I can make these part of it as default but I wanted to get a working version ready for you to try using first! 

I haven't had much time to test it so would appreciate if you told me of any bugs. I am away for a few days so won't be able to get to them straight away. Have a great new year :)
