### ISSUE TITLE
Add option to allow side-by-side editor to be enabled by default

### ISSUE THREAD

**Issue by codygray** [soscripted/sox#297]
### Current Behaviour

When you wish to use the side-by-side editing mode, you must click the "Toggle SBS?" link in the editor toolbar. This setting is not remembered, and you must do so each time you enter the post editor.

### Desired Behaviour

The user should be able to configure (as part of the features) whether she wants the side-by-side editor to be used by default. This way, the side-by-side editing mode can be used automatically, every time the post editor is invoked, thus saving time.

### Features Enabled 

    ["Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-isQuestionHot","Appearance-tabularReviewerStats","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Voting-grayOutVotes","Voting-stickyVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-quickAuthorInfo","Extras-showQuestionStateInSuggestedEditReviewQueue"]

**Comment by shu8** [comment]
@codygray thanks, this sounds like a reasonable suggestion, I'll try getting this added in ASAP! :)

**Comment by shu8** [comment]
@codygray added an option in the dialog in [dev 2.0.39](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
