### ISSUE TITLE
Preview Question/Answer expands but does not hide preview

### ISSUE THREAD

**Issue by cullub** [soscripted/sox#3]
I'm on FF 44.  This is a bug for links to questions/answers in questions, answers, or comments.

Example:

![commentexpandbug](https://cloud.githubusercontent.com/assets/7533931/13161891/6a4909d8-d666-11e5-80d4-af9d3406b7ce.gif)

**Comment by shu8** [comment]
lol whoops! I think I forgot to actually hide it :/ I'll look at that today as well :) thanks

**Comment by shu8** [comment]
@cullub fixed :) (in dev)
