### ISSUE TITLE
"Add bunch of features to editor" option cannot be disabled on question pages

### ISSUE THREAD

**Issue by SeinopSys** [soscripted/sox#30]
**Installed Version: 1.0.2  |  Environment: Chrome/Tampermonkey**

**Expected Behavior**

When I open the settings dialog **while I'm on a question's page**, there should be a checkbox in front of the "Add a bunch of features to the standard markdown editor (autocorrect, find+replace, Ace editor, and more!)" option that I can un-check and then save my settings. From what I've seen, this only seems to happen on question pages.

**Actual Behavior**

There is no checkbox.
>![](http://i.imgur.com/NgRIANi.png)

**Error Logs**

```
Uncaught ReferenceError: ace is not defined (anonymous function) @ ext-language_tools.js:1
Uncaught ReferenceError: ace is not defined (anonymous function) @ theme-github.js:1
Uncaught ReferenceError: ace is not defined (anonymous function) @ mode-javascript.js:1
Uncaught ReferenceError: ace is not defined (anonymous function) @ javascript.js:1
```

**Steps to reproduce**

Visit any question page with the aforementioned option enabled and witness the checkbox's ascension from its original place.

**Comment by shu8** [comment]
Thanks @SeinopSys. I can repro and I have a feeling it's because the checkbox's ID is the same as something (haven't checked yet) on the toolbar that the enhanced editor creates.

I'll look into it and push a fix ASAP :)

**Comment by shu8** [comment]
fixed in https://github.com/soscripted/sox/commit/01221c8a49f6d504b6f33a022dfc8b27a0d84f68
