### ISSUE TITLE
Feature loading errors

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#300]
### Installed Version: 2.0.38  

Windows 7 Home Premium 64 bit, Firefox 55.0.3

---

### SOX Errors logged to the browser console -- F12 (if available)

SOX:  There was an error loading the feature "Editing-downvotedPostsEditAlert". Please raise an issue on GitHub, and copy the following error log:
ReferenceError: siteCodes is not defined

SOX:  There was an error loading the feature "Extras-openLinksInNewTab". Please raise an issue on GitHub, and copy the following error log:
TypeError: settings.linksToOpenInNewTab is undefined

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-showCommentScores","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Extras-alwaysShowImageUploadLinkBox","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-showMetaReviewCount","Extras-openLinksInNewTab","Extras-showQuestionStateInSuggestedEditReviewQueue"]

**Comment by shu8** [comment]
@DavidPostill should be fixed in [dev 2.0.39](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
