### ISSUE TITLE
"Window that has been opened for you to receive your access token" Doesn't exist

### ISSUE THREAD

**Issue by rifuso** [soscripted/sox#301]
### Installed Version: 1.X.X  Environment: Chrome/Tampermonkey

Safari Version 11.0 (12604.1.38.1.7) / Tampermonkey

### Current Behaviour

To complete the SOX installation please follow the instructions in the window that has been opened for you to receive your access token.

This message keeps popping up even though there is no window that has been opened and no apparent "access token"

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

- Click on icon for Sox Settings
- Click on Save Changes

**Comment by shu8** [comment]
@rifuso sorry for the really late response, however if you're still interested, please try installing the latest dev version and see if it works for you? unfortunately I don't have access to safari atm, but hopefully it'll work!

https://github.com/soscripted/sox/raw/dev/sox.user.js
