### ISSUE TITLE
Unable to change SOX settings

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#303]
### Current Behaviour

There used to be a small cog where one could change the SOX settings. This is not visible in the new top bar navigation.

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar"]

**Comment by AdrianTP** [comment]
Not sure if this is related, but none of the SOX features seem to work at all, despite Tampermonkey insisting that the userscript is running.

`VM504:3934 Uncaught SOX: There was an error while attempting to initialize the SOX Settings Dialog, please report this on GitHub.
TypeError: Cannot read property 'left' of undefined`

**Comment by shu8** [comment]
Thanks guys, I'm aware of this and will fix as soon as I get some time!
I've been really busy recently unfortunately :(( sorry for how long this is
taking!

**Comment by Franck-Dernoncourt** [comment]
Note that http://area51.stackexchange.com/ still has the old bar, which is handy to change the settings  through the small cog.

**Comment by shu8** [comment]
@Franck-Dernoncourt @AdrianTP @wgrundlingh sorry for the incredibly late response, i've been really busy. this is fixed in the latest dev version.

https://github.com/soscripted/sox/raw/dev/sox.user.js

**Comment by DavidPostill** [comment]
Excellent. Working for me :)

**Comment by shu8** [comment]
@DavidPostill great!! thanks for sticking with it whilst I've not been working on it!
