### ISSUE TITLE
Several known bugs

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#308]
This is basically a TODO, which I'll try to patch when I get the time (unfortunately, I don't know how long that'll take).

- [x] Meta diamond and notify-on-edit buttons are not shown
- [x] SOX features dialog box is offset horizontally from its button, and is offset vertically from the topbar on SO and Server Fault (note, the last two have topbars that are smaller than other sites, which usually are 50px in height. The dialog box is placed 50px below the top, so we need to change its position to `$('.top-bar').height` or something)
- [x] "Add display name before gravatar in topbar" doesn't work on stackexchange.com or Area 51
- [x] SOX is disabled on Area 51 Discussions
- [x] In the SOX features dialog box, clicking the "reset" button will cause some glitches when you've entered text.
- [x] If you search for a feature and nothing shows up (e.g. due to a typo), you need to completely erase the word and retype it. In contrast, if features do show up, you only need to delete a few characters to fix the typo.
- [x] "Copy 'show x more comments' link to the top" doesn't seem to work; clicking the text will only scroll you up, and doesn't show the comments.
- [x] SOX buttons are placed in between inbox and achievement buttons when logged out, rather than to the left of them
- [x] Topbar disappears on Area 51 when "Fix topbar position" is enabled (I think we might as well disable SOX on Area 51, but keep it enabled on Discussions) (deprecated fixed topbar)
- [x] The Notify on Edit button suddenly shows up on [Area 51's chat](https://chat.stackexchange.com/?tab=site&host=area51.stackexchange.com) (and is shifted), rather than being absent like for every other site's chat (deprecated notify on edit feature)
- [x] Notify on edit doesn't work on Area 51 Discussions (deprecated notify on edit feature)
- [x] On Area 51 Discussions only, the SOX settings button has the color #858c93, rather than #9fa6ad like the other SE buttons.

**Comment by Sir-Cumference** [comment]
@shu8 Thought I'd mention, I just found out about the "sticky" property of CSS, which became supported by most browsers somewhat recently. This is 100x better than what we had for the sticky vote buttons, since it's way smoother and faster.

I've just put that in, and I'll try and get to the rest of these when I find the time.

**Comment by shu8** [comment]
@Sir-Cumference sorry, the 'show x more comments' bug is my fault from the last change I made, I'll fix that ASAP!

**Comment by Sir-Cumference** [comment]
@shu8 Should probably specify what my previous edits did. The main change was that they made the page calculate where to put the dialog boxes for the SOX and Meta buttons. This prevented the boxes from being disjoint on sites like Meta SE, where the topbar is wider than on most sites.

The notify on edit button may shift the Meta dialog a bit, but I figured since we were already getting rid of it the problem should be resolved.

On another note, I slightly edited the way the buttons were placed on screen, so that they appear before the inbox when you are logged out.

**Comment by shu8** [comment]
Thanks, that's great! I'll be moving the notify on edit feature out to a separate userscript soon! And if we get rid of the fixed topbar the A51 bug should go too!

**Comment by shu8** [comment]
I think all of these are now fixed/no longer a problem! (I still need to make the separate notify on edit userscript!)
