### ISSUE TITLE
Setting icon showing 3 times on top bar!

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#310]
### Installed Version: 2.1.2 DEV  Environment: Violentmonkey

Setting icon showing 3 times on top bar!

![screenshot - 11_03_2018 22_56_54](https://user-images.githubusercontent.com/7079224/37259552-ac958a5e-257f-11e8-93ec-b50e7071ceec.png)

Note, I'm also running [script - Top-navigation choices - Stack Apps](https://stackapps.com/questions/7603/top-navigation-choices)

If I disable that script I still see 2 setting Icons!

![screenshot - 11_03_2018 22_58_58](https://user-images.githubusercontent.com/7079224/37259579-f2b0f1d6-257f-11e8-9eef-dd7e2b2a0fed.png)

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-warnNotLoggedIn"]

**Comment by Sir-Cumference** [comment]
Hmm, that's strange. What browser are you using?

**Comment by DavidPostill** [comment]
Windows 7 Home Premium 64 bit, Firefox 58.0.2

**Comment by Sir-Cumference** [comment]
@DavidPostill I believe I've figured it out. Could you try [the new version](https://github.com/soscripted/sox/raw/dev/sox.user.js) to see if it's fixed? :)

**Comment by DavidPostill** [comment]
Confirmed as fixed. Single setting icon now showing at right end of top nav bar.
