### ISSUE TITLE
Comments being formatted wrongly

### ISSUE THREAD

**Issue by JohnKNess** [soscripted/sox#312]
### Installed Version: 1.X.X  Environment: Chrome/Tampermonkey
SOX: Version 2.1.0
Chrome: Version 64.0.3282.186 (Official Build) (64-bit)
Tapermonkey: v4.5

### Current Behaviour

When looking at the comments in the DBA.SE question "[How can I improve the performance of a sorted join?](https://dba.stackexchange.com/q/199945/15356)" then some of them are elongated.

If I turn off the SOX userscript then comments are back to normal.

---

### SOX Errors logged to the browser console -- F12 (if available)

**Errors**
```
userscript.html?id=f50b667d-c5eb-4146-a2e6-5c613ae6bfd2:583 SOX:  There was an error loading the feature "Editing-downvotedPostsEditAlert". Please raise an issue on GitHub, and copy the following error log:
TypeError: Cannot read property 'left' of undefined
sox.error @ userscript.html?id=f50b667d-c5eb-4146-a2e6-5c613ae6bfd2:583
```

```
userscript.html?id=f50b667d-c5eb-4146-a2e6-5c613ae6bfd2:583 SOX:  There was an error loading the feature "Voting-stickyVoteButtons". Please raise an issue on GitHub, and copy the following error log:
TypeError: Cannot read property 'top' of undefined
sox.error @ userscript.html?id=f50b667d-c5eb-4146-a2e6-5c613ae6bfd2:583
```

```
userscript.html?id=f50b667d-c5eb-4146-a2e6-5c613ae6bfd2:583 SOX:  There was an error loading the feature "Extras-openLinksInNewTab". Please raise an issue on GitHub, and copy the following error log:
TypeError: Cannot read property 'replace' of undefined
sox.error @ userscript.html?id=f50b667d-c5eb-4146-a2e6-5c613ae6bfd2:583
```

```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at Window.eval (userscript.html?id=f50b667d-c5eb-4146-a2e6-5c613ae6bfd2:1420)
    at <anonymous>:2:120
    at T.e.string.f.function.c.(anonymous function) (eval at exec_fn (:1:108), <anonymous>:51:390)
```

**Warnings**

```
userscript.html?id=f50b667d-c5eb-4146-a2e6-5c613ae6bfd2:8 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

---

### Steps to reproduce

Browse to "[How can I improve the performance of a sorted join?](https://dba.stackexchange.com/q/199945/15356)" with SOX and SOUP userscripts activated.

**Comment by JohnKNess** [comment]
This might be because of this:

[2018 monthly product team updates](https://meta.stackexchange.com/a/307770/202162)

> ## March 2018
> ### Done
> Responsive design pt1: Implemented question pages and question list pages. **One of the first steps was to remove the tables from the comments on question pages. Comments are now list items. Sorry if the rapid changes break userscripts** but it's for the better.

**Comment by shu8** [comment]
@JohnKNess thanks for the bug report! I can't seem to see this -- do you mind posting a screenshot of the comments section so I can see where to look? :)

thanks for the link to the march update too! I'll try updating any features using table specific selectors!

**Comment by JohnKNess** [comment]
I'm unable to upload from work. Will send from home. Thanks for the feedback. Funny thing is I don't have the problem at home and/or only with long comments. I'll do some more research.

**Comment by JohnKNess** [comment]
Ok. Here we go. This is what it looks like when SOX and SOUP are activated and I open a question which contains long comments:

![Picture of elongated comments in a DBA.SE question](https://user-images.githubusercontent.com/13273624/37680827-571a203c-2c85-11e8-940d-f41f14994b5e.png)

If I turn off SOX then everything is back to normal. Turning off SOUP has no impact.

**Comment by calebkleveter** [comment]
I am also experiencing this issue:
- SOX 2.1.0
- Tampermonkey: 4.5
- Google Chrome:  65.0.3325.162 (Official Build) (64-bit)

**Comment by JohnKNess** [comment]
I might have found the culprit. 

With certain comments (e.g. one of the comments in the question [ORDER BY gives ERROR: function array_position(text[], character varying) does not exist](https://dba.stackexchange.com/questions/201837/order-by-gives-error-function-array-positiontext-character-varying-does-no)) if I turn on the option **Add reply links to comments for quick replying (without having to type someone's username)** then the comment will become elongated. If I turn this option off, then the comment behaves normally.

**Comment by shu8** [comment]
@JohnKNess @calebkleveter I couldn't reproduce this :( but I've changed the location the reply button is added in [v2.1.6 dev](
https://github.com/soscripted/sox/raw/dev/sox.user.js) which might just fix this -- please could you give it a go and tell me if it works? :)

**Comment by calebkleveter** [comment]
Fixed 👍!

**Comment by JohnKNess** [comment]
Seems to work in v2.1.6 dev. Thanks for fixing it.
