### ISSUE TITLE
Dialog box problems

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#313]
Currently, for a large enough window, the buttons and text at the bottom of the dialog box will actually leave the box:

<img width="550" alt="screen shot 2018-03-15 at 7 45 18 pm" src="https://user-images.githubusercontent.com/5375326/37496540-7fe0b332-2889-11e8-8a78-27ad13522699.png">

These are solved if we remove the "achievements-dialog" class from the dialog (since it adds a problematic min-height to the box). I noticed it was added to the code [here](https://github.com/soscripted/sox/commit/9a615953f543c8056f7d667433a4374f80926cbd#diff-204f1b5847048af3721b9c54d3ac6220). Do we still need it?

**Comment by shu8** [comment]
@Sir-Cumference I think we might have added it for the old topbar? I don't remember 😆 but removing it doesn't seem to anything ATM so I'll get rid of it and hope for the best 🤞
