### ISSUE TITLE
Issue #160 is back :(

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#317]
See https://meta.stackexchange.com/questions/309246/to-be-logged-in-or-not-to-be-logged-in-that-is-the-question for the gory details.

Windows 7 Home Premium 64 bit, Firefox 59.0.2

SOX version 2.1.3 DEV

**Comment by shu8** [comment]
@DavidPostill sorry, that's annoying! I'll try getting it fixed as soon as I get some time!

**Comment by shu8** [comment]
@DavidPostill sorry for the delay, I've fixed it in [2.1.8 DEV](
https://github.com/soscripted/sox/raw/dev/sox.user.js) and added a 'SOX:' at the beginning in case it happens in future!
