### ISSUE TITLE
Add timeline and revision links

### ISSUE THREAD

**Issue by polyluxus** [soscripted/sox#318]
### Current Behaviour
 n/a

### Feature request

I am hoping the functionality of [this script by Brock Adams](https://gist.github.com/BrockA/5761948) or [View Post Timeline on stackapps](https://stackapps.com/a/4150/27677) could be added to SOX.

It adds links to the timeline 
```https://*.stackexchange.com/posts/<id>/timeline```
and revisions 
```https://*.stackexchange.com/posts/<id>/revisions```
page to the bottom of the post (next to flag, edit, ..., notify on edit.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-showQuestionStateInSuggestedEditReviewQueue"]

**Comment by shu8** [comment]
@polyluxus thanks for the suggestion, I'll try getting this added soon! :)

**Comment by shu8** [comment]
@polyluxus added in [dev 2.0.10](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
