### ISSUE TITLE
SOX settings topbar icon doesn't appear

### ISSUE THREAD

**Issue by Quincunx271** [soscripted/sox#319]
### Installed Version: 2.1.0  Environment: Tampermonkey

SOX: Version 2.1.0 (also on v2.1.7DEV)
Chrome: Version 66.0.3359.139 (Official Build) (64-bit)
Tapermonkey: v4.5

### Current Behaviour

Upon visiting any Stack Exchange site, there is nothing for opening SOX settings. The gear icon simply doesn't appear

### SOX Errors logged to the browser console -- F12 (if available)

None. The log is empty

### Steps to reproduce

I downloaded SOX from clicking on [this link](https://github.com/soscripted/sox/raw/v2.1.0/sox.user.js). After authorizing, the gear icon never appeared.

**Comment by shu8** [comment]
@Quincunx271 thanks for raising this! seems like they changed their topbar markup -- this should be fixed now in [2.1.8 DEV](
https://github.com/soscripted/sox/raw/dev/sox.user.js).

Please could you confirm? :)

**Comment by DavidPostill** [comment]
Confirmed as fixed on latest FF

**Comment by Quincunx271** [comment]
I can confirm that fixes it

**Comment by Quincunx271** [comment]
Weird... it's gone again

**Comment by DavidPostill** [comment]
Still displaying for me.

**Comment by shu8** [comment]
Even weirder.. is anything showing up in the console?

**Comment by Quincunx271** [comment]
Nothing at all.

**Comment by shu8** [comment]
Please could you 'enable debugging' from the SOX dialog and paste
everything that shows here?

**Comment by Quincunx271** [comment]
How do I do that? What's the SOX dialog?

**Comment by Quincunx271** [comment]
I just restarted chrome, and it's back! No idea what happened...

**Comment by shu8** [comment]
Great! Probably some sort of cache of the old version?

Glad it's sorted!
