### ISSUE TITLE
That's no employee!

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#32]
**Installed Version: 1.0.3DEV  |  Environment: Chrome/Tampermonkey**

Go to http://stackoverflow.com/questions/5223/length-of-a-javascript-object-that-is-associative-array. Scroll down... then some more. Note how nearly every name has a SO icon beside it, marking nearly every user as employee.

**Expected Behavior**

Mark only employees as such.

**Actual Behavior**

Marking (nearly) every username on http://stackoverflow.com/questions/5223/length-of-a-javascript-object-that-is-associative-array as an employee, when most / all of them aren't. 

**Error Logs**

None.

**Steps to reproduce**

Loaded http://stackoverflow.com/questions/5223/length-of-a-javascript-object-that-is-associative-array with the "Mark employees with SO icon" option. Doesn't seem to occur with (m)any? other pages.

**Comment by enki-code** [comment]
Thanks. I'll look into this tomorrow. We're fetching this data using the api and reading the is_employee property so maybe something is up with the if statement.

**Comment by catb0t** [comment]
Closing this as fixed, sweet! :D

**Comment by enki-code** [comment]
I've actually opened a post on Meta Stack Exchange about this, the API shouldn't be reporting Jeff Atwood as an employee, he left the company 4 years ago, March 2012.

https://meta.stackexchange.com/questions/277818/api-results-employee-status
