### ISSUE TITLE
Does not work - no gear button appearing

### ISSUE THREAD

**Issue by Eddcapone** [soscripted/sox#321]
### Current Behaviour

Gear Button not showing

### SOX Errors logged to the browser console -- F12 (if available)

no errors are logged, only the string "asd"
### Steps to reproduce

install

### Features Enabled 

    undefined

**Comment by shu8** [comment]
@Eddcapone thanks for the bug report -- is this in Chrome or Firefox? :)

**Comment by shu8** [comment]
@LunarWatcher thanks! I think I might push the dev version to master then

**Comment by Eddcapone** [comment]
I was using Chrome 64bit as of version Version 67.0.3396.79

**Comment by Jake-Symons** [comment]
Just an update the DEV version works fine now

**Comment by shu8** [comment]
Great! I'll get this pushed to the main branch ASAP as it's a big bug

**Comment by shu8** [comment]
I've pushed the main version to the master branch now.
