### ISSUE TITLE
Ability to export and import user preferences

### ISSUE THREAD

**Issue by GaurangTandon** [soscripted/sox#322]
Installed Version: 2.1.13DEV  Environment: Tampermonkey

I wish to share my user preferences with another user. Is there a way to do so?

**Comment by shu8** [comment]
@GaurangTandon It's been on my [todo list](https://github.com/soscripted/sox/projects/1#card-625590) for a very long time, I just haven't gotten round to do it yet unfortunately :(

If you want I can guide you through steps you/they can manually do to save them till then?

**Comment by GaurangTandon** [comment]
In which JSON object are the settiings stored? What do I type in the console to access them?

**Comment by shu8** [comment]
@GaurangTandon it's a stringifed JSON in the `SOXSETTINGS` GM Value 

`console.log(GM_getValue('SOXSETTINGS'))` on your computer should get the settings as a string and 

`GM_setValue('SOXSETTINGS', <settings>)` should save them on the other one :)

**Comment by shu8** [comment]
@GaurangTandon I've implemented this in [v2.2.7 DEV](https://github.com/soscripted/sox/raw/dev/sox.user.js) -- hopefully it should work!
