### ISSUE TITLE
Integrate a better comment keyboard shortcuts userscript in SOX

### ISSUE THREAD

**Issue by GaurangTandon** [soscripted/sox#323]
Wrt your "Use Ctrl+I,B,K (to italicise, bolden and add code backticks) in comments" option in SOX, I made a userscript that neatly integrates keyboard shortcuts in chat.SE, chat.SO, as well as comment boxes on all SE sites. 

Here's [the StackApps entry.](https://stackapps.com/questions/7923/comment-keyboard-shortcuts)

I'll be more than happy to help you integrate my code with your SOX. I've tried to write my code in the most descriptive manner possible so the integration shouldn't be an issue.

What do you think?

**Comment by shu8** [comment]
@GaurangTandon that sounds awesome! Please feel free to submit a pull request to the DEV branch if you like! :)

**Comment by GaurangTandon** [comment]
Sure, I'd be glad to! Can you point me to the specific part of your `sox` file where I am required to make changes?

**Comment by shu8** [comment]
Great! You basically only really need to edit the `sox.features.js` file -- [find the current `commentShortcuts` feature](https://github.com/soscripted/sox/blob/dev/sox.features.js#L520) and change it it implement the feature!

You could also update the description in `sox.features.info.json` file if you like :)

Please do have a look at [Contributing](https://github.com/soscripted/sox/wiki/Contributing) -- I think it's mostly up to date, though I will be updating it soon when I get some time!

Thanks for the help!

**Comment by mezmi** [comment]
Closing, will accept a push request if one comes in.
