### ISSUE TITLE
Enabling "Always show the 'Link from the web' box when uploading an image" disables pasting of clipboard images

### ISSUE THREAD

**Issue by GaurangTandon** [soscripted/sox#328]
**Reproduce:**

1. Enable "Always show the 'Link from the web' box when uploading an image"
2. Copy an image 
3. Open the image insertion dialog and press Ctrl-V

**Expected:** image should be pasted
**Actual:** nothing happens because the focus is on input textbox. **Moreover, clicking outside the textbox still retains the focus on the textbox.** This is a major issue, 

**Suggested fix:** clicking outside the textbox should not retain the focus on the textbox. 

_I'll try do a pull request when I've some time_

**Comment by shu8** [comment]
@GaurangTandon I just tried it and it doesn't seem to keep the textbox in focus when you click outside? Do you have anything extra installed?

**Comment by GaurangTandon** [comment]
Sorry! I miswrote stuff. Here's the corrected version:

**Reproduce:** same as before  
**Expected**: image should be pasted  
**Actual**: nothing happens because the focus is on the textbox. While clicking outside the textbox removes its focus, pressing Ctrl-V again focuses back on the textbox. Pressing the Cancel button does not remove the textbox, rather focuses on it again. These are the two major issues that make it impossible to Ctrl-V an image into the imgur dialog.  
**Suggested fix**: the opposite of what is mentioned in Actual should happen  

I hope it's clear now!

**Comment by shu8** [comment]
@GaurangTandon Here's what I see (I press Ctrl+V before and after, it only works after)

![this](https://user-images.githubusercontent.com/8850830/41497287-2c3573a8-714a-11e8-9fcc-481cd758cae7.gif)

**Comment by GaurangTandon** [comment]
Sorry, you're right. I tried SOX on a clean slate and it worked. Don't know which extension/userscript was causing the issue :/

Sorry for the disturbance! :(

**Comment by shu8** [comment]
No problem! Glad it's sorted!
