### ISSUE TITLE
"View linked images (to imgur) in comments inline" should be anchored to (and remove the trailing text of) imgur link

### ISSUE THREAD

**Issue by GaurangTandon** [soscripted/sox#329]
Currently, if I write a new comment with the a URL like: `i.stack.imgur.com/ABCDE.png`, the image is embedded but the URL remains in the comment.

I think it is pretty pointless to let the text of the URL remain in the comment as no one would click it. A better way would be instead to anchor the image itself to that link. Sort of:

    <a href="i.stack.imgur.com/gNbkP.png"><img src="i.stack.imgur.com/gNbkP.png"/></a>

so clicking it would directly take us to that link.

_Will do a PR soon!_

**Comment by shu8** [comment]
@GaurangTandon I agree, not sure why we ever left it there TBH 😆 

If you don't manage to submit a pull request, I'll fix it when I next change stuff! :)

**Comment by shu8** [comment]
done in v2.2.0.
