### ISSUE TITLE
Broken SOX Dialog

### ISSUE THREAD

**Issue by enki-code** [soscripted/sox#33]
**Installed Version: 1.0.3DEV  |  Environment: Tampermonkey/Chrome**

The SOX settings dialog is showing two scrollbars and looks pretty awful.

![twobars](https://cloud.githubusercontent.com/assets/12533449/14227629/e22db27e-f8b6-11e5-90b8-9f29c1e6d12b.png)

The features div has an scroll overflow which is causing the second scroll bar and a few other CSS adjustments are needed.

**Comment by catb0t** [comment]
I noticed this and I thought it was kinda clunky but I assumed it was the cause of either another userscript I have installed, or my default zoom level, so I didn't bother opening it.

To add to your initial thoughts, the "Save changes" button doesn't appear until the outer scroll bar or both scrollbars are all the way to the bottom, which made me very confused when I wanted to save my changes after first opening it.

**Comment by shu8** [comment]
@catb0t and @enki-code this is really weird. This is what I see:

![this](https://cloud.githubusercontent.com/assets/8850830/14227737/26eae7b6-f8fc-11e5-87f6-42e17619a6f3.png)

**Comment by enki-code** [comment]
@shu8 Can you push your files and I'll reinstall?  @catb0t Thanks for confirming this.

**Comment by shu8** [comment]
@enki-code the 'commit changes' button is disabled for me.. presumably because there is no change... weird!

**Comment by enki-code** [comment]
@shu8 add a superfluous comment and we'll just remove it

**Comment by shu8** [comment]
@enki-code what do you mean....??

**Comment by enki-code** [comment]
@shu8 just add a comment 'fdkjghdfkjhgfdkhgfdklglkdfhg' so there is a change and you can make a commit.

**Comment by shu8** [comment]
@enki-code oh I just diffed it, it's exactly the same! there's no point.

Can you go to https://rawgit.com/soscripted/sox/dev/sox.css?v=1.0.3a and copy/paste the first few CSS rules so I know it's up-to-date?

**Comment by shu8** [comment]
@catb0t to help in debugging this -- could you tell us which browser and version you're using? thanks! :)

**Comment by catb0t** [comment]
@shu8 This is Chrome 49.0.2623.110 on Linux (X11) amd64. 
![blargh](https://cloud.githubusercontent.com/assets/3238748/14227849/3befbc18-f8d4-11e5-96f5-a370875adc50.png)

**Comment by shu8** [comment]
@catb0t thanks! we're all on chrome it seems...

**Comment by enki-code** [comment]
I pushed some changes to the css file to hopefully solve the phantom scroll bar.

There are still a few other issues to work out, the Save button should be fixed at the bottom of the dialog so it is always visible.  The version number is no longer being injected into the dialog to show users what version they're running. The category headings are still a bit too large as well.

We'll get all these sorted out here shortly.

Thanks

**Comment by catb0t** [comment]
This is fixed for me, so it now looks like it does for @shu8 :D If I want to be pedantic, I'll say the settings box as a whole is now less tall than it was before, and there are a lot of tickboxes to scroll though.

**Comment by enki-code** [comment]
@catb0t I'll increase the height.

**Comment by shu8** [comment]
@catb0t yeah it is... we'll look into making it close to the window's height -- it's just that something to do with the browser's height was causing this bug, so we'll have to use a different way...

@enki-code a small 'todo' list :):

- [ ] make dialog taller -- use `height: calc(100%-200px)`?
- [ ] re-add the `#sox-settings-dialog-version` div (it seems I accidentally deleted that :/)
- [ ] fix the save button div

I can do the first 2, but could you do the last one enki? Not sure how to do it :/

**Comment by enki-code** [comment]
@catb0t  @shu8  Okay, I've made some adjustments to the dialog height, the save button, ect, can you two try the latest changes and verify that everything is displaying as it should.

**Comment by enki-code** [comment]
I moved the Meta Question Diamond to the right of the SOX Settings button and this is how the dialog should display now.  View Height - 100px;

![newdialog](https://cloud.githubusercontent.com/assets/12533449/14229058/bc31a270-f8dd-11e5-9f50-fa257f2efb53.png)

**Comment by enki-code** [comment]
Not quite done yet, but, this is a preview of what the finished dialog will look like.

![newdialog](https://cloud.githubusercontent.com/assets/12533449/14229631/d8d0bba0-f8ec-11e5-9c80-1dc586319b43.png)

**Comment by enki-code** [comment]
@catb0t @shu8 This should be fixed now.

**Comment by catb0t** [comment]
Yaay, it's fixed, it's so pretty! :D

**Comment by shu8** [comment]
@enki-code I've pushed an update to make it close on click off of it :)

**Comment by enki-code** [comment]
@catb0t @shu8 Glad you two like the changes, it was a bit of work getting it to look how I wanted but well worth it. I added spacing between each feature so things weren't so cluttered and the extra 50px wide makes things a bit easier on the eyes. I'm not a fan of the two line descriptions myself, but hey, can't win em' all.

I'll be testing this in other browsers today to confirm that is really is working. I appreciate the patience and feedback while getting this resolved.

Also, if you see anything else that needs to be changed in the dialog let me know, Thanks. :+1:

**Comment by shu8** [comment]
@enki-code we can change those descriptions to be a bit shorter I think!

BTW did you know you can do multiple 'reactions' to comments? ;) ^^

**Comment by shu8** [comment]
How about...:

---

>Add an extra mod diamond to the topbar that alerts you if there is a new question posted on the child-meta of the current site

to

>Add a mod diamond to the topbar to alert you of new questions on the site's child-meta

---

>Add colourful, more apparent signs to questions that are on hold, duplicates, closed or migrated on question lists

to

>Add coloured, more obvious signs to closed/on hold/duplicate/migrated questions on question lists

---

>Add a bunch of features to the standard markdown editor (autocorrect, find+replace, Ace editor, and more!)

to

>Add more features to the markdown editor (autocorrect, find+replace, Ace editor, and more!)

---

>Add a confirmation dialog before navigating away on pages whilst you are still typing a comment

to

>Add a confirmation dialog when navigating away on pages whilst you are still typing a comment

---

TBH I think we could probably remove the 'Add a button in the editor toolbar to insert a hyperlink to a post and add the author automatically' -- it's use is very limited and I'm not sure it even works anymore :P 

what do you think about these changes and the feature removal??

**Comment by catb0t** [comment]
@shu8 I definitely like all of those being terser and more expressive! I never really got the point of the 'Add a button in the editor toolbar to insert a hyperlink to a post and add the author automatically', so I won't miss it. :)

**Comment by shu8** [comment]
@catb0t that's great! And yeah, I wrote that feature for a question on meta, so it was useful to that person, but I think not many people know about it and they wouldn't really need it tbh... We'll see what enki says and we'll go from there :)

**Comment by enki-code** [comment]
@shu8 Those look good to me! As far as the sorting goes, looks like we're going to be doing it manually.  I'll start by alphabetizing the categories and we'll see how it looks. Also, some of the features that are in the Unsorted section could be graduated to Appearance, most of them in fact.

**Comment by shu8** [comment]
@enki-code lol, it came from a standalone userscript: http://meta.stackexchange.com/a/252095/260841 :P We can get rid of it. I'll add it to the deprecated features and remove it from the JSON.

**Comment by shu8** [comment]
@enki-code do you have any local changes to the JSON? I haven't updated it yet incase I overwrite something...

**Comment by enki-code** [comment]
@shu8 No, go ahead and push your changes.

**Comment by enki-code** [comment]
@shu8 The SOX Dialog closes when the page is clicked but does not close when any of the other dialogs are opened.  Think you can take care of that, pleeeease? :+1:

**Comment by shu8** [comment]
@enki-code sure! :) will do some time today, and I'll push my JSON changes as well.

**Comment by shu8** [comment]
@enki-code I've shortened those descriptions now :)
