### ISSUE TITLE
Feature request: colored signs on duplicate and closed questions should be more interesting

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#34]
![colorbox](https://cloud.githubusercontent.com/assets/3238748/14234832/24589664-f9bb-11e5-94c8-721a093c6301.png)

I think it would be nice for the duplicate and closed labels to show the same text as in the dupe/close banner when hovered
>**marked** as duplicate by Shadow Wizard 5 hours ago
>**closed** as not constructive by Jon Ericson ♦ Mar 19 '13 at 17:11

etc, and for the duplicate label itself to be a link to the question of which this one is a duplicate. Or would loading each question that has a label and searching for that data be more work than it's worth?

**Comment by shu8** [comment]
This is a cool idea. 

I'll make it so that the close reason is there as a tooltip on the sign. 

It's definitely not more work than its worth and would actually be pretty handy!!

**Comment by shu8** [comment]
I can't assign myself or add tags to this caeca use I'm on my phone, but I'll get this done tomorrow :)

**Comment by shu8** [comment]
@catb0t @enki-code 

for duplicates, how would you feel about the orange 'duplicate' sign actually linking to the dupe??

just asking, because there's a chance you accidentally click the sign when you want to go to the quesiton...

**Comment by catb0t** [comment]
@shu8 I'd enjoy it since I'm used to thinking of the label being a separate entity, and so I don't click it to go to the question itself.

Perhaps the "duplicate" sign linking to the dupe, and the close information being a tooltip on the sign, could be different options in the dropdown, so they can be enabled individually?

**Comment by shu8** [comment]
@catb0t I've done all that now^^ you can reinstall the dev userscript to see the changes.

Could you test it and give any feedback so I can fix it completely? Thanks! :D 

---

>Perhaps the "duplicate" sign linking to the dupe, and the close information being a tooltip on the sign, could be different options in the dropdown, so they can be enabled individually?

I was thinking we could possibly add a control panel specifically for features, but right now, that just won't work. 

@enki-code is it worth looking into for v1.0.4?? It could be pretty cool -- features could have toggle-able features.

**Comment by catb0t** [comment]
@shu8 I just reinstalled and the tooltips don't seem to work, nor do the dupe links. They have HTML like:
```html
<span class="standOutDupeCloseMigrated-migrated">&nbsp;migrated&nbsp;</span>
```
which should probably be
```html
<span class="standOutDupeCloseMigrated-migrated" title="migrated to meta.politics.stackexchange by blah at blah on blah">&nbsp;migrated&nbsp;</span>
```
Essentially, nothing seems to have changed, or at least I can't get it to work.

**Comment by shu8** [comment]
@catb0t whoops! Sorry!! I forgot to update the resource URLs on github.. :/

I've done it now, so reinstalling should work.

sorry again :/

**Comment by catb0t** [comment]
@shu8 It works, it's damn beautiful! :D [status-completed](http://meta.stackexchange.com/questions/tagged/status-completed)!

**Comment by shu8** [comment]
@catb0t great!! :D If you see any bugs or extra feature requests, please do comment :)

**Comment by IStoleThePies** [comment]
@shu8 Could you add the colored signs to questions when viewing them from a user's profile?

**Comment by shu8** [comment]
@IStoleThePies sure, I'll look into it :)

**Comment by shu8** [comment]
@IStoleThePies done in [dev aq](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
