### ISSUE TITLE
Does color answerer's comments work?

### ISSUE THREAD

**Issue by GaurangTandon** [soscripted/sox#343]
### Current Behaviour

![image](https://user-images.githubusercontent.com/6308683/42367962-67fcaa9e-8123-11e8-87c1-53d97cfa6c2b.png)

Unless I am misunderstanding something, the answerer's comments are not at all colored below their posts. You can see this behavior anywhere, for example, [here](https://chemistry.stackexchange.com/a/71689/5026). They're the same as they used to be before and after enabling this feature.

**Expected behavior:** some coloring should be there:

I'll look into this issue right now.

---

### Features Enabled 

    ["Appearance-colorAnswerer","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-tabularReviewerStats","Appearance-addTimelineAndRevisionLinks","Comments-autoShowCommentImages","Comments-confirmNavigateAway","Editing-addSBSBtn","Editing-inlineEditorEverywhere","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-hideChatSidebar","Sidebar-hideLoveThisSite","Sidebar-hideHotNetworkQuestions","Chat-replyToOwnChatMessages","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-showQuestionStateInSuggestedEditReviewQueue"]

**Comment by shu8** [comment]
@GaurangTandon you're right, I never noticed it stop working!

Changing `$(this).parent().next()` to `$(this).next()` fixes it :)

**Comment by GaurangTandon** [comment]
Hmm, great, wait a second though, I think I have a few more optimizations. Sending in ten minutes.
