### ISSUE TITLE
Convert timestamps on chat transcript pages to local time

### ISSUE THREAD

**Issue by GaurangTandon** [soscripted/sox#346]
On any `https://chat.stackexchange.com/transcript/ROOM_ID` page, for example, the transcript for [Charcoal HQ](https://chat.stackexchange.com/transcript/11540), the message timestamps are shown in UTC time, as opposed to the [actual room](https://chat.stackexchange.com/rooms/11540) where timestamps are in local time.

I propose a new feature to convert the timestamps on the transcript page to the user's local time as well.

**Edge case:** in cases where the user is in the morning of a day, and the message was posted in the night of the previous day, the date that is shown on the right side of the chat transcript would be off-by-one. The only way to fix it is by: a) checking which timestamps cross the midnight on conversion to local time b) append the new date directly to them. Relevant demo:

![image](https://user-images.githubusercontent.com/6308683/42452012-85c148fc-83a6-11e8-86b5-b069a4b677c2.png)

**Comment by shu8** [comment]
@GaurangTandon nice idea, we could could extend the current 'Convert timestamps to your local time' feature to do this? It could even have a per-feature setting to enable in chat or not?

**Comment by GaurangTandon** [comment]
I never actually tried out the "Convert timestamps to your local time" because... timestamps have always been in local time for me already!?...unless I really missed something

**Comment by shu8** [comment]
@GaurangTandon ah sorry, that feature changes the tooltip from the UTC time to relative time!

**Comment by GaurangTandon** [comment]
Yeah, I guess we could reuse some of the functionality from that code too.

**Comment by samliew** [comment]
I have a similar userscript here https://github.com/samliew/SO-mod-userscripts/blob/master/ChatTranscriptHelper.user.js

**Comment by GaurangTandon** [comment]
@shu8 @samliew has actually got dozens of userscripts right there --> https://github.com/samliew/SO-mod-userscripts, some of them are so good that it's hard to resist making a new issue for each one of them  for inclusion in SOX :P 

You wanna go in there and push them directly into master @shu8? (with due credits by [MIT License](https://github.com/samliew/SO-mod-userscripts/blob/master/LICENCE))

**Comment by shu8** [comment]
Nice! They all look really useful! 

I'm not sure if I should add them into SOX if they're already available as separate userscripts though; they're all quite major and deserve their own script!

If you have any thoughts @samliew I'd be happy to hear them! :)

**Comment by samliew** [comment]
I'm okay if you want to have any of my userscripts included in SOX if you find them useful, although you might want to check for updates occasionally.

**Comment by mezmi** [comment]
Closing this as there is maintained option available from @samliew.
