### ISSUE TITLE
Make author name display consistent with existing SE display

### ISSUE THREAD

**Issue by GaurangTandon** [soscripted/sox#347]
![image](https://user-images.githubusercontent.com/6308683/42466179-cd2f7806-83cb-11e8-82a0-d21ec494f72d.png)

As you can see above, the display is not consistent. I think the for the sake of consistency, SOX should display author names the same way they are displayed by SE for chat replies. Reading through your inbox and seeing half of the author names as `author: ...` and the other half as `...by author` makes it inconsistent.

If you are okay with this quick change, I can make it while I am doing the refactor I mentioned in #345.

**Comment by shu8** [comment]
@GaurangTandon hmm, I like the SOX method better :/ it seems more obvious when it's at the top.

If anyone else sees this, we need a vote! 😆

**Comment by shu8** [comment]
@GaurangTandon sure, that seems fair! I'll do it ASAP :)

**Comment by shu8** [comment]
@GaurangTandon should be working in [dev 2.2.18](https://github.com/soscripted/sox/raw/dev/sox.user.js), please try it out! :)

**Comment by GaurangTandon** [comment]
Great! Except that I am not sure if you really needed the extra work. I mean: the SE guys just take a shortcut and prepend the author name to `span.item-summary` directly, alongside the rest of the text, I wouldn't have minded if you too did the same instead of creating new css, etc. :P Nvm though, great work :D
