### ISSUE TITLE
Should we drop support for the old topbar?

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#349]
Pretty much every site uses the new topbar. Server Fault and SO are a bit different, but they still have the same topbar class as the other sites.

Right now, SOX is pretty broken on sites with the old topbar, e.g. Area 51 and chatroom pages, and those sites are becoming a bit of a hassle to keep up with considering SOX isn't very useful there. We'd also probably clear up a lot of code if we removed the if statements that check whether the topbar is the new one or old one. 

What do you think?

EDIT: Just noticed SE implemented a vanilla sticky topbar: https://meta.stackexchange.com/questions/311213/can-i-please-have-the-option-to-sticky-my-top-bar-wherever-i-want?noredirect=1&lq=1

**Comment by shu8** [comment]
I think we should also remove the fixed topbar feature as well as they support it natively now?

**Comment by Sir-Cumference** [comment]
@shu8 Sounds good, or we could at least change it to "Add fixed topbar on Ask Ubuntu".

**Comment by shu8** [comment]
Perfect, and once the redesign is done we can get rid of it altogether :)

**Comment by shu8** [comment]
I've just pushed an update to remove the fixedTopbar feature because Ask Ubuntu's site design has now been updated so the feature is natively supported!
