### ISSUE TITLE
Task List progress not being displayed

### ISSUE THREAD

**Issue by enki-code** [soscripted/sox#35]
- [ ] task one
- [x] task two
- [ ] task three
- [ ] task four

**Comment by enki-code** [comment]
@shu8 The task list progress is no longer being displayed on the issues page for any issues, any ideas why? I've tried swapping tags, removing the milestone, rewriting the lists.. I'm stuck.  Maybe GitHub made some changes?

**Comment by shu8** [comment]
@enki-code hmmm I don't see it either. can't find anything about this on google...

**Comment by enki-code** [comment]
@shu8 I emailed GitHub, waiting for a response now.

**Comment by enki-code** [comment]
For reference:

From: Rachel Berry (GitHub Staff)

Hi Enki,

Thanks for letting us know! Our engineering team is looking into why that went missing, and I'll be in touch once I know more. Appreciate your help!

All the best,
Rachel

**Comment by enki-code** [comment]
Update:

Hi Matthew,  <--- yes that's my name

> Any updates on this?

Thanks for following up. We're still working on a fix, but we were able to determine that this only affects issues/PRs where there is text in the body of the comment that comes *before* the task list. So a workaround while we're still getting a fix out is to move the tasklist to the top of your issue content. I know that's not at all ideal, and we're working on a solution. I'll be in touch once a fix goes out!

All the best,
Rachel
