### ISSUE TITLE
Path attribute error in metaNewQuestionAlert

### ISSUE THREAD

**Issue by GaurangTandon** [soscripted/sox#352]
The stack trace is pretty long, but here's the relevant part.

![image](https://user-images.githubusercontent.com/6308683/42736488-cd2507c2-8885-11e8-81ab-ada949ee762f.png)

Redirects to this line:

    $diamond.html($diamond.html()); // Reloads...

To reproduce, just visit any SO or SE page, for example, stackoverflow.com

Latest dev build.

(I'm sorry I have zero experience with SVGs, so no PRs this time!)

**Comment by shu8** [comment]
Thanks, I'll look into it.

**Comment by shu8** [comment]
@Sir-Cumference I was looking at the SVG path data:

    M8.4.78c.33-.43.87-.43 1.3 0l5.8 7.44c.33.43.33 1.13 0 1.56l-5.8 7.44c-.33.43-.87.43-1.2 0L2.6 9.78a1.34 1.34 0 0 1 0-0.156L8.478z

and was wondering -- did you get that from an SE site or make a diamond from scratch? (I only just realised that all the other topbar icons are SVGs!)

I removed the line `L8.478z`, which I didn't understand (I don't get what the coordinates are!) and the error stopped appearing :/

**Comment by Sir-Cumference** [comment]
@shu8 I got it from a moderator, so it matches what is actually used on SE sites. Not too sure about that line, but I know it appeared in the real button's code. :/

**Comment by shu8** [comment]
@Sir-Cumference weird :/ I can't see the diamond looking different without the line, so I'll remove it for now (I'll keep it in a comment in case we need it in the future), and see how it goes for a while. 

FWIW, it seems like Chrome just completely ignores it anyway:

![image](https://user-images.githubusercontent.com/8850830/42737998-3ad86604-8874-11e8-8b25-7c13544be358.png)

**Comment by Sir-Cumference** [comment]
Wow, I realize I made a typo while copying the code. That last line should be "L8.4.78z". I've checked that the rest matches the code correctly.

**Comment by shu8** [comment]
@Sir-Cumference ah! that makes sense -- it'll be going to (8.4, 0.78) I think! I'll just change it now :)
