### ISSUE TITLE
"HTTP-Based Public Key Pinning is deprecated" warning for isQuestionHot

### ISSUE THREAD

**Issue by GaurangTandon** [soscripted/sox#353]
![image](https://user-images.githubusercontent.com/6308683/42736633-8bf649cc-8886-11e8-902f-6565bb37a2dc.png)

> HTTP-Based Public Key Pinning is deprecated. Chrome 69 and later will ignore HPKP response headers. (Host: query.yahooapis.com)

On the line:

    if (sox.location.on('/questions') || $('.question-summary').length) {
        $.ajax({

I am not sure how to fix it :/

Considering I'm on version 67 already, I think you need to act fact on this one!

**Comment by shu8** [comment]
Thanks. I'll look into it.

**Comment by j-f1** [comment]
That doesn’t seem like a big issue. HPKP is basically the server telling the browser to only accept a certain certificate when connecting to that sever via HTTPS. Since Chrome will ignore the header, everything will work OK.

**Comment by shu8** [comment]
@j-f1 Thanks! 
I've still removed the YQL use though because it seems like they've changed it a few times recently and it's probably going to break soon anyway 😆

**Comment by GaurangTandon** [comment]
@j-f1  Ah, so it's an issue from `query.yahooapis.com`'s side and not from ours?

**Comment by j-f1** [comment]
Yep! That’s correct.
