### ISSUE TITLE
Fix for comment flagging and upvoting options appearing permanently in the new UI

### ISSUE THREAD

**Issue by GaurangTandon** [soscripted/sox#356]
[SE recently decided](https://meta.stackexchange.com/questions/312794/why-are-the-comment-upvote-and-flag-options-always-appearing-now) to feature flag and upvote buttons on every single comment permanently. [I'm not the only one who finds it a bit too weird.](https://meta.stackoverflow.com/questions/371260/comment-icons-always-visible-a-new-feature-or-a-bug)

Meanwhile, moderator Samuel on StackOverflow [created a neat userscript to bring back the old behavior](https://meta.stackexchange.com/a/312800/256391). (under which I've also commented)

Please include this in SOX :)

**Comment by shu8** [comment]
Sure! It does look weird being so different now 😂

**Comment by shu8** [comment]
Done in [dev 2.2.28](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
