### ISSUE TITLE
updateurl of the dev branch script points to master branch

### ISSUE THREAD

**Issue by GaurangTandon** [soscripted/sox#357]
[updateurl of the dev branch script points to master branch](github.com/soscripted/sox/blob/dev/sox.user.js). This results in users of the dev branch not getting updates automatically. Please fix.

**Comment by shu8** [comment]
nice catch, thanks! I'll fix it ASAP :)

On Wed, 25 Jul 2018 at 03:22, Gaurang Tandon <notifications@github.com<mailto:notifications@github.com>> wrote:

updateurl of the dev branch script points to master branch<http://github.com/soscripted/sox/blob/dev/sox.user.js>. This results in users of the dev branch not getting updates automatically. Please fix.

**Comment by shu8** [comment]
Done :)
