### ISSUE TITLE
KBD button missing

### ISSUE THREAD

**Issue by polyluxus** [soscripted/sox#364]
### Current Behaviour

I am missing the <kbd>KBD</kbd> button in the editor, the list button &bullet; is present though.

![unbenannt3](https://user-images.githubusercontent.com/19774680/45171006-976cc700-b201-11e8-8dd5-dda3b2e7d7b7.PNG)

The feature is enabled: `Add KBD and list buttons to editor toolbar`

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-pasteImagesDirectly","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-showQuestionStateInSuggestedEditReviewQueue"]

**Comment by shu8** [comment]
Thanks for the bug report. I recently changed something in the last dev
version that probably broke this! :/ I'll only be able to look at it next
week -- you could install the main master version until then if you want? :)

Sorry it can't be sooner!

**Comment by shu8** [comment]
@polyluxus Please could you check if this is now working in [dev 2.3.4](https://github.com/soscripted/sox/raw/dev/sox.user.js)? :)

**Comment by polyluxus** [comment]
@shu8 It works, thank you.
