### ISSUE TITLE
Fixed-position top-bar nowhere to be found on Skeptics.SE

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#37]
**Installed Version: 1.0.3DEV  |  Environment: Tampermonkey/Chrome**

**Expected Behavior**

Topbar position on Skeptics.SE should reflect that of all other sites, rather than hiding itself.

**Actual Behavior**

**Only on Skeptics.SE**, if the `Fix topbar position` option is checked, then the top-bar will not display at all and you will need to uncheck the option from another page. 

![part1](https://cloud.githubusercontent.com/assets/3238748/14286113/f6dc1230-fb1b-11e5-928d-78e7aa720c33.png)

If the option is unchecked then it will display as usual, anchored annoyingly to the top of the page.
![part2](https://cloud.githubusercontent.com/assets/3238748/14286104/f07ef27c-fb1b-11e5-9c1f-fccb32ddea0c.png)

**Error Logs**

I don't think this is relevant, but I'll add it anyways.

![hereugo](https://cloud.githubusercontent.com/assets/3238748/14285937/513329d6-fb1b-11e5-9e74-802f8a1f68e7.png)

**Steps to reproduce**

Loaded http://skeptics.stackexchange.com today. Not sure if this bug was introduced recently, since I never noticed it before...?

**Comment by enki-code** [comment]
@catb0t  We've encountered this before on different sites. It's the `margin-top: -34px` rule that we use, I'll look into a different way of handling this today, something a little more cross site friendly.

Thanks for bringing this to our attention.

**Comment by enki-code** [comment]
This should be fixed now in the DEV branch.

**Comment by shu8** [comment]
Can confirm it's fixed @enki-code :)

**Comment by catb0t** [comment]
Fixed! :D
