### ISSUE TITLE
Add highlighted tags to closed/on hold/duplicate/migrated questions on question lists not working on meta.so

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#372]
v2.3.11 dev
Windows 7 Home Premium 64 bit, Firefox 63.0.1, Violentmonkey 2.9.10

Example:

[This](https://meta.stackoverflow.com/questions/376305/i-cant-post-a-java-code-int-he-body-section-while-i-am-asking-question-it-ask) question is closed as a duplicate but doesn't have the coloured duplicate tag:

![screenshot - 07_11_2018 21_14_39](https://user-images.githubusercontent.com/7079224/48161376-4c8b3080-e2d2-11e8-8adc-b0d9e7003368.png)

**Comment by shu8** [comment]
[Fixed in dev 2.3.13](https://github.com/soscripted/sox/raw/dev/sox.user.js) :) 

It was a slightly broken regex, I don't think it would have been working on meta.so for a while!
