### ISSUE TITLE
Click the help button to go to https://example.stackexchange.com/help/on-topic

### ISSUE THREAD

**Issue by ooker777** [soscripted/sox#374]
The only reason I visit the help center is to go to https://example.stackexchange.com/help/on-topic. Therefore I suggest to change the link in this button to the corresponding page of the site.

![](https://i.imgur.com/42vq1F5.png)

**Comment by shu8** [comment]
Sounds reasonable! I'll get this done, I may rename the link to `on-topic` too if it fits in the space there!

**Comment by shu8** [comment]
@ooker777 done in [dev 2.3.15](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by ooker777** [comment]
is there a reason to add another button instead of changing the link? Go to the help page is pretty useless for power users I think. 

If there is such a reason, I think we can add a sub-option to remove the help
