### ISSUE TITLE
Make the hot meta posts diamond redirect to meta.

### ISSUE THREAD

**Issue by Ethan-JK** [soscripted/sox#376]
Can you make it so **clicking** a button that appears when you click the "hot meta posts" diamond that redirects you to the meta site? You could make a go-to meta button at the bottom/top, or both.

**Comment by shu8** [comment]
I can make the title of the dialog a link :)

**Comment by shu8** [comment]
Done in [dev 2.3.22](https://github.com/soscripted/sox/raw/dev/sox.user.js) @Ethan-JK :)
