### ISSUE TITLE
The View/Remove Edit Reasons box needs change.

### ISSUE THREAD

**Issue by Ethan-JK** [soscripted/sox#377]
### No margin between the delete button and the text.
Just see for yourself: ![bad stuff][1]
Can you add a `margin-right`/`-left`?

### No edit button.
*Please* add a button to the left of the delete one to edit it.

### No way to reorder.
Can not change the order in which options appear without deleting all of them and reading in a different order. Can you make a drag & drop interface or up and down buttons?

### Needes two more default reasons: title & retag.

- title - Change title
  - This one isn't needed really, but I find this might be useful.
- retag - Changed tags
  - Okay, this one is **needed**. Please add this default.

### Make the delete button red, not blue.
If the edit button is added, that one should still be blue.

### The window opens by default position blocked by the top bar.
See the image.
![noooooooo!][2]

  [1]: https://i.stack.imgur.com/eDbZT.png
  [2]: https://i.stack.imgur.com/jiAgv.png

**Comment by shu8** [comment]
Thanks, revamping that modal's UI is on my todo list, to make it look like SE's modals. See the custom magic links feature's modal for an idea of how it will soon look!

Thanks for the other suggestions on functionality, I'll see what I can do about them :)

On Wed, 9 Jan 2019 at 00:55, Ethan K <notifications@github.com<mailto:notifications@github.com>> wrote:
A few things:
No margin between the delete button and the text.

Just see for yourself: [bad stuff] <https://camo.githubusercontent.com/f9dc4bc00bc768f87bf14599198395bfc553af2d/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f6544625a542e706e67>
Can you add a margin-right/-left?

No edit button.

Please add a button to the left of the delete one to edit it.

No way to reorder.

Can not change the order in which options appear without deleting all of them and reading in a different order. Can you make a drag & drop interface or up and down buttons?

Needes two more default reasons: title & retag.

  *   title - Change title
     *   This one isn't needed really, but I find this might be useful.
  *   retag - Changed tags
     *   Okay, this one is needed. Please add this default.

Make the delete button red, not blue.

If the edit button is added, that one should still be blue.

**Comment by shu8** [comment]
@Ethan-JK I've done all the _design_ change in [dev 2.3.27](https://github.com/soscripted/sox/raw/dev/sox.user.js). I didn't get round to the edit/reorder functionality (it's slightly more involved than design changes!) so will try getting that done at a later date.

Looking at the SOX code, _a lot_ of features' code can be improved, so I may rewrite this entirely instead!

Please let me know if the design changes are what you were thinking of!

**Comment by Ethan-JK** [comment]
@shu8 **Wow! Thank looks *really* good!**

One thing: The delete button is a little *too* bold. Could you make the button less bold or the text next to it bolder?

**Comment by shu8** [comment]
Sure, I'll get that done soon :)

**Comment by shu8** [comment]
@Ethan-JK How's the delete button now in [dev 2.3.29](https://github.com/soscripted/sox/raw/dev/sox.user.js)?

**Comment by Ethan-JK** [comment]
@shu8 Nice! I was kind of thinking of something plain like this:

<img width="297" alt="so edit custon reasons" src="https://user-images.githubusercontent.com/44984953/52171497-ac537500-2723-11e9-8da2-e09a6be2b1e5.png">

With the delete button being the same as the <kbd>discard</kbd> button for a question/answer.

**Comment by shu8** [comment]
@Ethan-JK Thanks for the mockup!

How's it now in [dev 2.3.30](https://github.com/soscripted/sox/raw/dev/sox.user.js)?

I've also added the edit option :) 

![image](https://user-images.githubusercontent.com/8850830/52177385-0aca3300-27b8-11e9-9487-253b9353c6ef.png)

**Comment by Ethan-JK** [comment]
@shu8 Cool! That looks and works great! One thing - are there any plans to move around the order of the reasons?

Other than that, this looks **awesome**!

**Comment by shu8** [comment]
@Ethan-JK glad you like it!

To be honest, I'm not sure how useful people would find re-ordering the reasons -- could I ask whether your main use case would be for the dialog where it lists all your reasons or for the actual checkboxes when editing?
