### ISSUE TITLE
Don't have all posts go away in the "top meta posts" when I click one.

### ISSUE THREAD

**Issue by Ethan-JK** [soscripted/sox#378]
Right now, when I click the top meta posts diamond and click one, all of them go away. Would it be possible to have them all stay (but the notification goes away) so I can re-read some and read others that may be interesting? The item could be styled differently when you click on it so you know that you read it, but you can still refer back to it. The questions would disappear still when the question is not "hot", or you can make it stay for a few days or until more posts come in to fill its place. Also keep the diamond on the meta sites as well so you don't have to go *back* to the main site to keep looking at hot meta posts.

**Comment by shu8** [comment]
@Ethan-JK thanks for the suggestion! This sounds pretty reasonable, I'll let you know when I get round to doing it! :)

**Comment by shu8** [comment]
@Ethan-JK Done in [dev 2.3.26](https://github.com/soscripted/sox/raw/dev/sox.user.js) :) 

I've also cleaned up the styles in the dropdown dialog, adding some more whitespace!

**Comment by Ethan-JK** [comment]
Thanks!

**Comment by Ethan-JK** [comment]
@Shu8 What do you think of this part of my issue?

> Also keep the diamond on the meta sites as well so you don't have to go back to the main site to keep looking at hot meta posts.

I find it annoying to have to toggle back to the main site to keep looking.

**Comment by shu8** [comment]
@Ethan-JK I tried to make the feature as similar to the real mod diamond which AFAIK doesn't show on meta sites (I may be wrong!). The feature only shows the latest 5 posts, so if you're on the meta site, you can just go to the '/questions' page on the meta site to see the same posts!

**Comment by Ethan-JK** [comment]
@shu8 I guess that works. I just feel that the nav bar should stay the same everywhere, but I really don't care. I guess your view on it makes sense!
