### ISSUE TITLE
Improve Community profile

### ISSUE THREAD

**Issue by Ethan-JK** [soscripted/sox#381]
Currently, SOX has the [recommended community standards](https://opensource.guide/) `Description`, `README`, and `License` in its [Community profile](https://github.com/soscripted/sox/community), but does not have `Code of conduct`, `Contributing`, `Issue templates` (this would be very nice, and could be set up to auto-add tags), and `Pull request template` (same deal). It may be a good idea to add some/all of these.

**Comment by shu8** [comment]
@Ethan-JK Thanks for that link, I never even knew the community profile was a thing! I'll definitely get that done, hopefully by the weekend!

FWIW, we do have a [Contributing wiki](https://github.com/soscripted/sox/wiki/Contributing) but I guess making it in the more standard form would help it get seen more easily!

**Comment by Ethan-JK** [comment]
@shu8 Your welcome!

By the way, thanks for sharing with **me** the Contributing wiki. **I** didn't know about that!

**Comment by Ethan-JK** [comment]
Also, a bit of a request:

When you add `Issue templates`, could you add `Bug` and `Feature-Request` templates and match both templates to the corresponding labels. If you do that, I would also like it if SOX only filled in debug information in the bug dialog, if possible.

Though you do whatever you want. `:)`

**Comment by shu8** [comment]
Added a link to the contributing wiki, templates for pull requests, bugs, and feature requests.

The environment details will also only be injected for bug issues :) (you'll need [v2.4.1 dev](https://github.com/soscripted/sox/raw/dev/sox.user.js) for the injection to work!)

**Comment by Ethan-JK** [comment]
@shu8 SOX seems to add features enabled no matter what issue template I use. Is this normal behavior? If so, this doesn't seem needed, but if not I believe I found a bug.

**Comment by shu8** [comment]
That shouldn't happen, thanks for mentioning it! I'll look into it :) @Ethan-JK

**Comment by shu8** [comment]
Fixed in [dev 2.4.3](https://github.com/soscripted/sox/raw/dev/sox.user.js). Thanks again for pointing this out, not sure how I missed it before!

**Comment by Ethan-JK** [comment]
@shu8 Just checked again: Yep, you fixed it.
