### ISSUE TITLE
Remove dependency on RawGit, which is EOL

### ISSUE THREAD

**Issue by AfroThundr3007730** [soscripted/sox#382]
RawGit is expected to [shutdown after October 2019](https://rawgit.com/), after which, a new CDN would be needed for the update URL of this script. One of the alternatives recommended is [jsDelivr](https://www.jsdelivr.com/), which provides equivalent functionality to RawGit.

There are currently two locations revealed by code search to be using RawGit, which would need to be updated to use the new site:

https://github.com/soscripted/sox/blob/179ff9be304b1d30c3f4c09ef33b7a698699c981/sox.user.js#L12

https://github.com/soscripted/sox/blob/179ff9be304b1d30c3f4c09ef33b7a698699c981/sox.features.js#L1084

**Comment by shu8** [comment]
Thanks for pointing this out! I've merged your pull request :)
