### ISSUE TITLE
Duplicated 'top answers' feature row

### ISSUE THREAD

**Issue by ooker777** [soscripted/sox#388]
Sorry, I don't know what is this line called, but in [How can I say I am an outstanding leader without sounding arrogant?](https://interpersonal.stackexchange.com/q/12415/86) it is duplicated:

![](https://i.imgur.com/8ulh9wR.png)

I refresh it and it's gone, so I guess there is no need to worry about it. But you may want to take notice. 

(Stupid me for not trying refreshing it first. After drafting the post already, I don't want to waste my effort of screenshoting :P) 

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-highlightQuestions","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Appearance-showTagWikiLinkOnTagPopup","Appearance-hideWelcomeBackMessage","Appearance-hideHowToAskWhenZoomed","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideJustHotMetaPosts","Sidebar-hideHireMe","Sidebar-hideLoveThisSite","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-copyCode","Extras-dailyReviewBar","Extras-openLinksInNewTab","Extras-showQuestionStateInSuggestedEditReviewQueue","Extras-addOnTopicLinkToSiteSwitcher","Extras-customMagicLinks"]

**Comment by shu8** [comment]
Thanks @ooker777, I'll try finding the cause of this! :)

**Comment by shu8** [comment]
Was the row duplicated from the first time you loaded the page, or did you perform some other action on the page in between it being duplicated? 

I can add a check to make sure SOX doesn't add the row if it already exists but I can't see (yet!) how the feature could even run twice! 

You don't happen to have two different SOX installations installed (different userscript managers maybe?) do you?

**Comment by ooker777** [comment]
Yes, it's duplicated from the first time the page is loaded. And yes I only have one installation installed.

**Comment by shu8** [comment]
I've added a check in to make sure it doesn't add a duplicate again in [dev 2.4.5](https://github.com/soscripted/sox/raw/dev/sox.user.js). Thanks again for the bug report! Hopefully it won't happen again :)
