### ISSUE TITLE
Sidebar arrow linked to/from wrong for commented links.

### ISSUE THREAD

**Issue by davidcllee** [soscripted/sox#389]
Sidebar "add arrow to linked to or linked from" the links come exclusively from the comments in the current post is not captured correctly. The direction is reversed: should be linked to ">" but as of now are displayed as linked from "<".

My system and browser specification:
OS Mojave 10.14.10
Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)

---

### Features Enabled 

    ["Appearance-colorAnswerer","Appearance-localTimestamps","Appearance-addTimelineAndRevisionLinks","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-copyCommentsLink","Comments-showCommentScores","Editing-addSBSBtn","Editing-editComment","Editing-findAndReplace","Flags-flagPercentageBar","Sidebar-linkedToFrom","Extras-quickAuthorInfo","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-openLinksInNewTab"]

**Comment by shu8** [comment]
Thanks for the bug report @davidcllee!

I've fixed this in [dev 2.4.6](https://github.com/soscripted/sox/raw/dev/sox.user.js) -- please give it a shot!
