### ISSUE TITLE
2.4.8DEV not working

### ISSUE THREAD

**Issue by ooker777** [soscripted/sox#390]
It simply doesn't run. There is nothing in the console. I use FF 67.0b12 (32-bit), Tampermonkey  4.9.5921

**Comment by shu8** [comment]
@ooker777 I can't reproduce when I'm using the exact same versions :( 

Does the last main version work ([2.4.0 from here](https://github.com/soscripted/sox/blob/master/sox.user.js))?

Could you check there aren't any conflicting extensions installed, and that the userscript does show as active in Tampermonkey's dialog when you click it on an SE site?

**Comment by ooker777** [comment]
oops, restarting the computer make it works. 

The reason I update to the latest one is because the previous version (2.4.x dev) suddenly stops working. I guess it happened because I removed a bunch of addons

**Comment by shu8** [comment]
Glad it's working again! :)

**Comment by ooker777** [comment]
As I see this happens once in a while, maybe you want to put this issue as
an FAQ?

**Comment by shu8** [comment]
Sure, I think this is related to https://github.com/Tampermonkey/tampermonkey/issues/477 which mentions that sometimes scripts seem to run at the wrong time, and it only seems to affect FF. 

I'll add a note to the readme that on FF restarting the browser/computer should fix the script not loading :)
