### ISSUE TITLE
https://sitename.com/questions/ask is considered as a question!

### ISSUE THREAD

**Issue by double-beep** [soscripted/sox#392]
**Describe the bug**
It is well-known that SOX has an awesome feature(!) to quickly-view questions and answer, e.g.:

![image](https://user-images.githubusercontent.com/38133098/58343419-9648fc00-7e5b-11e9-8e0e-1c54fa71e214.png)

However, when there is a link, e.g. https://stackoverflow.com/questions/ask, then SOX interprets this as a question and...:

![image](https://user-images.githubusercontent.com/38133098/58343501-d6a87a00-7e5b-11e9-9b19-e1b24d7fee8a.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go and see a random comment which contains https://sitename.com/questions/ask
2. Press the button.
3. Saw thee result? Nothing happens

**Expected behaviour**
SOX shouldn't at all consider https://sitename.com/questions/ask as a question!

I haven't dug into the code, but I suppose that it should use a regex to understand if it is a question or not, right? How about `whatever.com/questions/[0-9]*` or whatever possible.

**Comment by shu8** [comment]
Thanks for the bug report! (and I'm glad you find the feature awesome!)

I'll get this fixed ASAP -- probably using your regex! :P

**Comment by shu8** [comment]
@double-beep It's surprisingly hard to find a comment like that (probably because the post ends up being deleted!) -- do you mind posting the link you saw that on, so I can test the fix works?

**Comment by double-beep** [comment]
Yyyyyyep! [Here](https://stackoverflow.com/a/56296578) is one!

**Comment by shu8** [comment]
Should be fixed in [dev 2.4.15](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by double-beep** [comment]
Cheers!
