### ISSUE TITLE
Image lengthens on review page

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#397]
**Describe the bug**
Image lengthens and shows the user name  above on all images

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://stackoverflow.com/review

**SOX errors logged in console**
None

**Expected behaviour**
Username should not be displayed

**Screenshots/GIFs**
![image](https://user-images.githubusercontent.com/7231077/58940553-5822d500-8797-11e9-980a-ce679e577372.png)

![image](https://user-images.githubusercontent.com/7231077/58940527-4b9e7c80-8797-11e9-9dfb-c41a8cf4c8a3.png)

**Environment**
Tampermonkey V2.4.31DEV Chrome

**Comment by shu8** [comment]
Thanks for the bug report :)

I suspect this will be something to do with the 'show your username next to
your avatar in the topbar' (but could be something completely else!)

I'll have a look as soon as I can :)

**Comment by SmartManoj** [comment]
Yes ,`Add display name before gravatar in topbar' ; That's the one

**Comment by shu8** [comment]
@SmartManoj I've fixed this in [dev 2.5.1](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
