### ISSUE TITLE
Revisions and timeline similar for both question and answer

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#398]
**Describe the bug**
Revisions and timeline similar for both question and answer

**To Reproduce**
Steps to reproduce the behaviour:
https://stackoverflow.com/questions/16405601/remove-characters-before-and-including-in-python-2-7

**Comment by shu8** [comment]
Thanks for the bug report @SmartManoj. I have reproduced this and will get a fix out ASAP!

**Comment by shu8** [comment]
@SmartManoj fixed in [dev 2.5.2](https://github.com/soscripted/sox/raw/dev/sox.user.js) :) 

Seems like this feature never worked for answers, it was always using the question ID!

**Comment by SmartManoj** [comment]
We can get id from share option
