### ISSUE TITLE
Comments shift left when vote dial switches to floating along the side of post

### ISSUE THREAD

**Issue by cullub** [soscripted/sox#4]
This may or may not be a separate issue, but I'll list it here anyways.  

I'll use the same example, as well.  Just note the comments rather than the vote div.

![bug](https://cloud.githubusercontent.com/assets/7533931/13162329/e367ca2c-d669-11e5-8b98-4412a4cc6e2d.gif)

**Comment by cullub** [comment]
Suggested Fix:

 - Set the CSS width for all elements with class `votecell` to `62px`
 - Stop adding `left: 45px;` to the `style` of `answercell`

**Comment by enki-code** [comment]
@cullub  Thanks, I'll try and look into this today.

**Comment by enki-code** [comment]
This should be fixed now.

**Comment by shu8** [comment]
@enki-code yep fixed! :)

btw, `removeAttr('style')` is very clever! :D
