### ISSUE TITLE
Open links to images as an enlarged modal instead of a new tab

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#404]
Like this https://codepen.io/ongtiffany/pen/BoOeQV?editors=0100

**Comment by shu8** [comment]
I've implemented this in [dev 2.5.15](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

"Open imgur images as larger modals on click" under "Appearance" in the SOX settings dialog:

![openImagesAsModals feature](https://user-images.githubusercontent.com/8850830/60756948-f951b500-9ffb-11e9-8f42-5d67ee6279ed.gif)

**Comment by SmartManoj** [comment]
> Appearance

Appears in comment section

**Comment by shu8** [comment]
Whoops! Fixed in [dev 2.5.16](https://github.com/soscripted/sox/raw/dev/sox.user.js) :) 

(you will probably need to re-enable the feature again!)
