### ISSUE TITLE
Dark theme Support

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#406]
Compatible with https://github.com/StylishThemes/StackOverflow-Dark

**Comment by shu8** [comment]
@SmartManoj Thanks for the feature request.

Please could you follow the [feature-request template](https://github.com/soscripted/sox/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=) when making feature requests? In particular:

>A clear and concise description of what you would like to see SOX implement.

For example, which features are you finding are currently incompatible with the dark mode? And do you have any ideas on what could be done to make them compatible? (e.g. is it just the styling that needs tweaking, or is there a functional problem?)

**Comment by SmartManoj** [comment]
Yes just the styling that needs tweaking.  Some buttons' text are not visible

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/60157457-6b601800-980c-11e9-944f-b4ba8c8a282e.png)

**Comment by shu8** [comment]
Before this has any real chance of being implemented, it would be helpful to produce a list of SOX's UI elements that conflict with the dark theme.

**Comment by SmartManoj** [comment]
reopen

**Comment by shu8** [comment]
Could you post which UI elements would need changing? Unfortunately without feedback from you this feature request has little chance of being completed!

**Comment by SmartManoj** [comment]
sox-settings-dialog-feature-pack 
#sox-settings-dialog-features .modal-content div:hover

**Comment by shu8** [comment]
Thanks, this is done in [dev 2.5.25](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
