### ISSUE TITLE
Merge AutoReviewComments

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#409]
https://github.com/Benjol/SE-AutoReviewComments/issues/171#issuecomment-473685289

**Comment by shu8** [comment]
Thanks for the feature request. Something similar has come up before (but I can't find the link!) -- I don't want to include extremely large scripts that already exist into SOX. My aim is to be able to maintain SOX as best I can, but including large scripts such as this one would make that much harder.

AutoReviewComments is incredibly useful but it's also got a lot going on in it. IMO it's better off as it's own script/extension, sorry!
