### ISSUE TITLE
Black/Green Eye (downvoted post edit notification): add tooltip and cursor

### ISSUE THREAD

**Issue by cullub** [soscripted/sox#41]
**Installed Version: 1.0.3  |  Environment: Firefox/Greasemonkey**

**Expected Behavior**

Could you make the cursor be a pointer to show that it can be clicked?
Also, could you add a tooltip showing what it does when you click it?

**Steps to reproduce**
![greeneye](https://cloud.githubusercontent.com/assets/7533931/14323350/d2b53024-fbe5-11e5-94f0-f18afb832463.gif)

**Comment by shu8** [comment]
@cullub sure, will do asap

**Comment by cullub** [comment]
By the way, what is it anyways?  :)

**Comment by catb0t** [comment]
@cullub it gives you a notification if that post gets edited, it's pretty cool

**Comment by enki-code** [comment]
@cullub I use it for tracking edits on posts that I have downvoted. That way if I feel the post has been improved I can remove my downvote and possibly give an upvote.  It's nice, it's opt in so you only get notified on posts you wish to be notified about.   

We've discussed removing that icon and placing a link inside the post menu (share, edit, flag). This will likely happen over the next few days.

**Comment by cullub** [comment]
Ok, cool - nice to know!

**Comment by shu8** [comment]
@cullub @enki-code I've changed the eye to this:

![this](https://cloud.githubusercontent.com/assets/8850830/14391083/e6aa7076-fdb1-11e5-913a-b07e05403433.png)

looks a bit less odd now... and fixes a bug with bounty indicators :)

It's in the latest DEV 1.0.4 version.

(I might do something about the spacing there...)
