### ISSUE TITLE
Add Stars to Features

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#411]
**Describe the feature you'd like**
There are plenty of features in wiki. Add some rating to each of it would be nice

**Use case**
I just installed to copy snippets.So, somebody like me miss some really cool features.

**Comment by shu8** [comment]
Thanks, this is a cool idea. My aim with the 'feature packs' was something similar -- to bring more useful features to people's attention.

I'm open to more ideas on how to show the features to users better! I think some sort of 'rating' system _could_ work, but it's very hard to objectively give a feature a rating, even if it's just something like a 5-star based system.

Do you have any ideas on how we could give features 'scores'?

**Comment by SmartManoj** [comment]
It should contain two ratings as Author and User Ratings.

**Comment by shu8** [comment]
I can imagine this working as having some sort of 'usefulness' property in the [features JSON](https://github.com/soscripted/sox/blob/master/sox.features.info.json) file, and adding a sort option to the settings dialog that sorts by the rating (and that could also be shown in the wiki).

However, I'm still unsure on a nice way to give meaningful 'ratings' to features.

**Comment by mezmi** [comment]
Personally, I'd leave this out.

'Usefulness' or 'Scores' would be hard to metric without knowing who is using what.  What I find useful, others do not. 

I am going to close this for now, if we feel the need to come back to it later then we can discuss it further.
