### ISSUE TITLE
Share link breaks - url is missing

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#412]
**Describe the bug**
Share link breaks

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://stackoverflow.com/questions/34740438/the-program-cant-start-because-api-ms-win-crt-runtime-l1-1-0-dll-is-missing-whi/35119972#35119972
2. Click on Share
You will get `[The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing while starting Apache server on my computer]()`

**SOX errors logged in console**
Please click 'enable debugging' in the SOX settings dialog; hit F12 on a Stack Exchange site; and copy & paste the contents of the 'console' here

**Expected behaviour**

**Screenshots/GIFs**
If applicable, please add screenshots/GIFs (you can use something like [LICEcap](https://www.cockos.com/licecap/) to make one!) to help explain the problem.

**Environment**
SOX version: 2.5.13DEV
Platform: Tampermonkey

If this is not auto-populated, please state your full browser version, SOX version number, and userscript manager (e.g. Tampermonkey)

---

### Features Enabled 

    ["Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideJustHotMetaPosts","Sidebar-hideHireMe","Sidebar-hideChatSidebar","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksPrivacy","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-hideCertainQuestions","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-openLinksInNewTab","Extras-showQuestionStateInSuggestedEditReviewQueue"]

**Comment by SmartManoj** [comment]
How to disable this setting currently?

**Comment by SmartManoj** [comment]
Got in Extras
`Change 'share' link to format of [post-name](url)`

**Comment by SmartManoj** [comment]
> How to disable this setting currently?

After disable , there is empty box when clicking share

**Comment by shu8** [comment]
I've fixed this in [dev 2.5.14](https://github.com/soscripted/sox/raw/dev/sox.user.js)

Thanks again for reporting the bug!
