### ISSUE TITLE
Flame icon on hot-network questions seems to cause the 'Ask Question' button to move out of its proper position

### ISSUE THREAD

**Issue by AmperAndSand** [soscripted/sox#414]
**Describe the bug**
The flame icon on questions which are hot-network questions seems to cause the 'Ask Question' button which is normally on the upper right side of the screen to be below the question title.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://gaming.stackexchange.com/q/354243/4797 (currently a hot network question)
2. Notice that the 'Ask Question' button is below the question title instead of at its normal position at the upper right side of the screen.

**Screenshots/GIFs**
'Add a label on questions which are hot-network questions' enabled:
![screenshot 1](https://user-images.githubusercontent.com/1404745/61029358-6fd02780-a3ed-11e9-94e3-55e7e59c1a63.png)
'Add a label on questions which are hot-network questions' disabled:
![screenshot 2](https://user-images.githubusercontent.com/1404745/61029606-fe44a900-a3ed-11e9-8f22-cc97396b80ba.png)

**Environment**
SOX version: 2.5.0
Platform: Tampermonkey
Browser: Chrome Version 75.0.3770.100 (Official Build) (64-bit)

If this is not auto-populated, please state your full browser version, SOX version number, and userscript manager (e.g. Tampermonkey)

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-copyCommentsLink","Comments-showCommentScores","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-kbdAndBullets","Editing-titleEditDiff","Flags-flagOutcomeTime","Flags-flagPercentages","Sidebar-linkedToFrom","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-warnNotLoggedIn"]

**Comment by shu8** [comment]
Thanks for the bug report!

I think this was recently fixed in a dev version. I see you're using v2.5.0 -- please could you try [installing the latest dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js) to see if this is fixed for you? :)

**Comment by AmperAndSand** [comment]
@shu8 I've just tried the dev version. On the sites I've tested, this issue does not happen. It seems to now work fine now. Thanks!
