### ISSUE TITLE
Shortcut to copy code

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#416]
**Describe the feature you'd like**
A clear and concise description of what you would like to see SOX implement.

pressing c inside code will copy ; Currently c is mapped to comments

**Use case**
A short example of where this feature could be used 

**Suggested descriptions**
If you have suggestions for a short concise description (to include in the settings dialog), please mention them!

**Comment by shu8** [comment]
There is already a feature as part of SOX that lets you copy code blocks to the clipboard ("Add a button to code in posts to let you copy it" under "Extras"). 

Is this what you're looking for?

**Comment by SmartManoj** [comment]
Yep but with a shortuct

**Comment by shu8** [comment]
How should the shortcut know which code block on the page to copy?

On Sat, 13 Jul 2019, 04:13 SmartManoj, <notifications@github.com<mailto:notifications@github.com>> wrote:

Yep but with a shortuct

**Comment by SmartManoj** [comment]
copy when hovering the snippet

**Comment by shu8** [comment]
I'm not sure if this would be very useful then, because if you have to hover over the code block, you're already using your mouse -- it's probably easier to just click the button using the existing feature at that point!

On Sat, 13 Jul 2019 at 08:30, SmartManoj <notifications@github.com<mailto:notifications@github.com>> wrote:

copy when hovering the snippet

**Comment by SmartManoj** [comment]
The button is too small and hard to click

**Comment by SmartManoj** [comment]
Kinda like https://chrome.google.com/webstore/detail/copy-link-address/kdejdkdjdoabfihpcjmgjebcpfbhepmh?hl=en

**Comment by shu8** [comment]
I can make the button bigger if that's the issue you find with it?

**Comment by SmartManoj** [comment]
> click the button

Harder to move the cursor to corner

**Comment by SmartManoj** [comment]
> There is already a feature as part of SOX that lets you copy code blocks to the clipboard ("Add a button to code in posts to let you copy it" under "Extras").
> 
> Is this what you're looking for?

Not working

**Comment by shu8** [comment]
@SmartManoj again, please could you post another issue with more details, and steps to reproduce, otherwise comments on closed issues tend to get buried!
