### ISSUE TITLE
Sox Reply Link Not working

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#418]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://android.stackexchange.com/questions/214837/adb-shell-input-text-with-space-not-working?noredirect=1#comment275252_214837
2. Click on reply to user

**SOX errors logged in console**
Please click 'enable debugging' in the SOX settings dialog; hit F12 on a Stack Exchange site; and copy & paste the contents of the 'console' here

**Expected behaviour**

**Screenshots/GIFs**
If applicable, please add screenshots/GIFs (you can use something like [LICEcap](https://www.cockos.com/licecap/) to make one!) to help explain the problem.

**Environment**
SOX version: 2.5.18DEV
Platform: Tampermonkey

If this is not auto-populated, please state your full browser version, SOX version number, and userscript manager (e.g. Tampermonkey)

---

### Features Enabled 

    ["Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Appearance-openImagesAsModals","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideJustHotMetaPosts","Sidebar-hideHireMe","Sidebar-hideChatSidebar","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksPrivacy","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-hideCertainQuestions","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-openLinksInNewTab","Extras-showQuestionStateInSuggestedEditReviewQueue"]

**Comment by shu8** [comment]
I can't reproduce. Please could you follow the steps in the bug report template to help debugging?

**Comment by SmartManoj** [comment]
Works in 2.5.19DEV
