### ISSUE TITLE
Favourite tag colors on SO are a bit hard on the eyes

### ISSUE THREAD

**Issue by SeinopSys** [soscripted/sox#42]
**Installed Version: 1.0.3  |  Environment: Chrome/Tampermonkey**

**Expected Behavior**

The tags should have an easily legible background & text color combination.

**Actual Behavior**

The tags are slightly hard to read due to lack of enough contrast. According to [contrast-ratio](http://leaverou.github.io/contrast-ratio/#%2339739d-on-%23c3dafa) the colors used are considered acceptable if they are above 18pt in size, however, tags have a `font-size` of `12px` on SO.
>[![](http://i.imgur.com/EMGBqRi.png)](http://stackoverflow.com/q/36483876/1344955)

**Comment by shu8** [comment]
I don't think it would be a good idea to increase the size, so do you have
any ideas on a different colour?

The font-color could be a bit darker...? Or do you think it should be a
different background-color altogether?

**Comment by SeinopSys** [comment]
I think `#D7E6FB` would fit as the new background, with the border it puts enough emphasis on the tag:
>![](http://i.imgur.com/UqugfIZ.png)

**Comment by enki-code** [comment]
There is actually a few issues with that feature that I'd like to take care of. It doesn't work with tag wildcards, like html* should catch html, html4, html5, ect.. but, it's not.

I agree, the colors could be a little better. We'll try to come up with something that'll be a little easier on the eyes.

**Comment by enki-code** [comment]
After a little bit of digging, it appears as though there is some CSS already in place but not being used for favorite tags.

```
.favorite-tag {
    padding-right: 1.8em
}

.favorite-tag:after {
    position: absolute;
    display: inline-block;
    content: "";
    margin-top: -6px;
    top: 50%;
    right: .4em;
    width: 12px;
    height: 12px;
    background-image: url("../../img/share-sprite-new.png?v=f82a7459e9d3");
    background-image: url("../../img/share-sprite-new.svg?v=698e8b939ec0"), none;
    background-repeat: no-repeat;
    background-position: -158px 0
}
```

Which produces
![tag-colors](https://cloud.githubusercontent.com/assets/12533449/14364245/d795c13a-fcbc-11e5-9b4c-a937dc8bf319.png)

We could add a border to that and have something like this.
![tag-colors-borders](https://cloud.githubusercontent.com/assets/12533449/14364262/e2b856e0-fcbc-11e5-8442-7eb02898846b.png)

Thoughts??

**Comment by shu8** [comment]
@enki-code looking good! :)

**Comment by SeinopSys** [comment]
Might be just me, but I think having the star half the `font-size` with `line-height` matching the `height` might look a bit better than a full-sized star.

**Comment by shu8** [comment]
@SeinopSys Could you install the latest DEV (again, sorry!) and see whether it's any better.

![this](https://cloud.githubusercontent.com/assets/8850830/14394386/e7ecf2f8-fdc3-11e5-877b-232f6c39170a.png)

It also fixes the problem @enki-code said about wildcards.

The star might be a bit too dark on second thoughts...

**Comment by enki-code** [comment]
@shu8  Yeah, the colors need some work.

**Comment by SeinopSys** [comment]
@shu8 That star color does not fit whatsoever

**Comment by enki-code** [comment]
@SeinopSys We're already changing it. 

We'll be using:
★	Dark Star	`&#9733;`

**Comment by shu8** [comment]
@SeinopSys lol yeah... I'm pretty bad at anything UI-related :P

**Comment by enki-code** [comment]
Okay, so... I made a few changes and had to make a judgement call. 

I removed the borders.  Messing with the borders screws up the tags on a few sites.

I didn't like the star that we were using or the one that I had planned on using; the one I mentioned in my previous comment. They just didn't look **good**.

So... This is what I came up with.

![tag-highlighting](https://cloud.githubusercontent.com/assets/12533449/14510341/dd070c28-0185-11e6-947c-15971b8546f3.png)

I added a little tag icon to the favorited post tags and added a visual indicator to the left side of the question summary.

This works on all sites, doesn't break the tag borders on sites that have tag borders and it doesn't have that ugly little star. 

Thoughts??

Hopefully you guys don't hate it. LOL.

**Comment by SeinopSys** [comment]
Looks good to me.

**Comment by enki-code** [comment]
I've pushed a fix for this.   Still working on the rest of the function itself, trying to eliminate the timeout and get it to properly match the *favorited* tags.

**Comment by shu8** [comment]
@enki-code looking really nice!! :D

**Comment by enki-code** [comment]
@shu8 I was able to remove the timeout. :)

![fav-highlighting](https://cloud.githubusercontent.com/assets/12533449/14533578/7633c5e6-021a-11e6-99e7-3533497e288e.gif)

**Comment by enki-code** [comment]
@SeinopSys I posted a feature request on Meta SE regarding the favorited tag highlighting.
https://meta.stackexchange.com/questions/278354/favorite-tag-highlighting
