### ISSUE TITLE
Issue template automatic version number injection broken

### ISSUE THREAD

**Issue by SeinopSys** [soscripted/sox#43]
**Installed Version: 1.0.3  |  Environment: Chrome (49.0.2623.110)/Tampermonkey**

**Expected Behaviour**

When reporting an issue, the `1.X.X` should [change to the installed version number](https://github.com/soscripted/sox/issues/31).

**Actual Behaviour**

The value is left unchanged.

**Steps to reproduce**

 1. Try creating a [new issue](/soscripted/sox/issues/new)
 2. Notice the default generic version number string in the field

**Comment by enki-code** [comment]
Yeah, this is actually a bit of an issue. I noticed this earlier today.

We might have to change the way we're doing this or drop it all together now that the version number is included in the dialog.   The problem is the way GitHub is loading content, we're having some timing issues.

**Comment by SeinopSys** [comment]
Can't you just use some placeholder text like `Click/focus to generate template` and bind a delegated `focus` handler somewhere, so when the input is focused the template is added with no race conditions?

**Comment by shu8** [comment]
@SeinopSys That's a great idea! If the fix I have in mind doesn't work, I think we'll go with that :)

**Comment by shu8** [comment]
@enki-code and @SeinopSys I think I've fixed it. Could you please install the DEV version and confirm?

**Comment by SeinopSys** [comment]
There's a slight network delay:
![](http://i.imgur.com/6ZXjZC2.gif)

I'd suggest adding a `Checking…` in there until the request either finishes or fails and disabling the input while that's happening, if possible.

**Comment by enki-code** [comment]
I'll be pushing a change to this here shortly that should solve the polling, timing and delay issues.

![version-inject](https://cloud.githubusercontent.com/assets/12533449/14370483/864b5b2e-fce3-11e5-91e0-f8200d2a5c44.gif)

**Comment by enki-code** [comment]
@SeinopSys An update as to why this was such an issue. GitHub uses pjax for loading content, so if navigating to the new issue page from any other page none of our code was being executed. I spent some time digging, found out they were using pjax, not ajax, and wired up an event for that and everything seems to be working fine now with little to no delay.

If you're curious, this is the code that solved it.
```
$(document).on('pjax:complete', function() {
    if (location.href.indexOf('/issues/new') > -1) {
        inject();
    }
});
```
