### ISSUE TITLE
Feature Request: Make SOX settings panel behave similar to other panels in the topbar

### ISSUE THREAD

**Issue by SeinopSys** [soscripted/sox#44]
**Installed Version: 1.0.3  |  Environment: Chrome/Tampermonkey**

**Expected Behaviour**

While having a "native" panel open and hovering over a different "native" icon, that menu is opened automatically. I think for the menu to look properly integrated this behaviour should be retained in the script.

**Actual Behaviour**

Moving the mouse over the SOX icon in the header does nothing while keeping the last opened menu open.

**Steps to reproduce**

![](http://i.imgur.com/8EYraaY.gif)

**Comment by enki-code** [comment]
Ahhh!!  You're finding everything!  Again, I noticed this earlier today, and will work on getting that sorted out.

**Comment by shu8** [comment]
@enki-code This is how SE does this:

    showOnMouseOver: function () {
            // http://meta.stackexchange.com/questions/210177/dont-require-a-click-to-switch-between-sites-inbox-and-achievements-on-the-ne
            var shouldShow = false;
            
            // find out if any buttons/dialogs are visible
            for (var i = 0; i < buttons.length; i++) {
                var b = buttons[i];
                if (b != this && b.showsOnMouseOver && b.isOn()) {
                    shouldShow = true;
                    break;
                }
            }
            
            if (shouldShow) {
                // quickly moving between button/dialog pairs shouldn't clear unread indicators
                this.toggle(true, /*preventMarkAsRead*/true);
            }
        },

(https://dev.sstatic.net/Js/full.en.js)

Seems like we could replicate this...

**Comment by shu8** [comment]
@enki-code @SeinopSys I've done this now :) Please could you test it in the DEV version (just pushed it)

![this](https://cloud.githubusercontent.com/assets/8850830/14365912/0e292eee-fd08-11e5-9e97-798b673e2dfa.gif)

I've tried to test all possible transitions and it seems to work^^, but if there's a bug please tell me!

Next step: do the same to the mod diamond! :D

**Comment by SeinopSys** [comment]
It is indeed working.

**Comment by shu8** [comment]
@SeinopSys great! :D
