### ISSUE TITLE
Add scrolling to chat room lists

### ISSUE THREAD

**Issue by LunarWatcher** [soscripted/sox#442]
**Describe the feature you'd like**

Being in too many rooms hides user info, or hides the full room list along with the actions. There's a bug report on [MSE](https://meta.stackexchange.com/q/183479) for this. However, it's currently ignored and probably won't be fixed any time soon. The problem is still real.

My FR: add a scrollbar to the chat room list in user cards and, if possible, in the right nav bar (see the bug report on MSE)

**Use case**

Mainly to avoid not being able to take some actions against specific users who happen to have a long room list.

**Suggested descriptions**

> Enable scrolling in the room list within usercards and in the navbar when there's a significant amount of rooms in the list

**Comment by shu8** [comment]
@LunarWatcher I've added this in [dev 2.6.5](https://github.com/soscripted/sox/raw/dev/sox.user.js)!

Please could you confirm it works? It should look like this:

![usercard](https://user-images.githubusercontent.com/8850830/64950391-2a0f5f80-d873-11e9-91c5-417ec33559c5.png)

![sidebar](https://user-images.githubusercontent.com/8850830/64950392-2a0f5f80-d873-11e9-90e6-4bca5839ff3f.png)

**Comment by LunarWatcher** [comment]
Looks good! There's a couple problems though. From the user list on the right:

![bilde](https://user-images.githubusercontent.com/29489988/64959000-89c83380-d890-11e9-9ee8-498753e4f5b7.png)

The list is partially hidden. From the chat log, clicking on the username on messages still causes some overflow (but significantly less than before):

![bilde](https://user-images.githubusercontent.com/29489988/64959066-aebca680-d890-11e9-84f3-3653a8a9d373.png)

And

![bilde](https://user-images.githubusercontent.com/29489988/64959120-c98f1b00-d890-11e9-995d-10f7195a0845.png)

(depending on how far I've scrolled and where it opens relative to the line)

Maybe restrict height a bit more? Aside that, from the profile pic the full list of own rooms, it works perfectly fine. (If it matters, I'm using FF. Mentioning this in case it works for you in some other browser)

**Comment by shu8** [comment]
Ah, forgot that our own usercards are in other places :P 

I've just pushed an update in [dev 2.6.6](https://github.com/soscripted/sox/raw/dev/sox.user.js) that just reduces the height a bit more.

If that works for you I think we're safe to leave it at that because it's still not too small, but if it doesn't I'll try adding some sort of JS that calculates a better height instead. 

Let me know if it works! :)

**Comment by LunarWatcher** [comment]
Looks like it works now. Thanks ^^
