### ISSUE TITLE
Unchecking pre-defined edit comment options (checkboxes) doesn't remove semicolon

### ISSUE THREAD

**Issue by jfcorbett** [soscripted/sox#45]
**Installed Version: 1.0.3  |  Environment: Firefox/Greasemonkey**

**Expected Behavior**

When checking a second comment option, a semicolon is automatically added after comment from the first option. If you then uncheck the second option, the comment gets removed, and you would also expect the semicolon delimiter to be removed as well. 

**Actual Behavior**

When unchecking the second option, the comment gets removed, but not the semicolon delimiter. If you keep checking and unchecking further options, the semicolons just pile up. 

**Steps to reproduce**

1. Check one option. 
2. Check a second one. Then uncheck that second one. Semicolon is still there. 
Repeat step 2; semicolons pile up.

**Comment by shu8** [comment]
@jfcorbett thanks! I can reproduce this and will work on a fix.

**Comment by shu8** [comment]
@jfcorbett I've fixed this in the latest DEV version. Please could you install that and confirm it is fixed for you?

**Comment by jfcorbett** [comment]
It's fixed!
