### ISSUE TITLE
remove "Welcome back message "  not working

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#455]
**Describe the bug**
Not working 
**To Reproduce**
Steps to reproduce the behaviour:

**SOX errors logged in console**
Please click 'enable debugging' in the SOX settings dialog; hit F12 on a Stack Exchange site; and copy & paste the contents of the 'console' here

is this really need?

SOX: logging sox stored values --- 
userscript.html?id=39f6f996-693e-43bf-a59f-4f7879b515e1:68 SOX: access token set
userscript.html?id=39f6f996-693e-43bf-a59f-4f7879b515e1:68 SOX: SOX-lastVersionInstalled
userscript.html?id=39f6f996-693e-43bf-a59f-4f7879b515e1:68 SOX: 2.6.16DEV
userscript.html?id=39f6f996-693e-43bf-a59f-4f7879b515e1:68 SOX: SOX-debug
userscript.html?id=39f6f996-693e-43bf-a59f-4f7879b515e1:68 SOX: true

**Expected behaviour**
SOX: logging sox stored values --- 
userscript.html?id=39f6f996-693e-43bf-a59f-4f7879b515e1:68 SOX: access token set
userscript.html?id=39f6f996-693e-43bf-a59f-4f7879b515e1:68 SOX: SOX-lastVersionInstalled
userscript.html?id=39f6f996-693e-43bf-a59f-4f7879b515e1:68 SOX: 2.6.16DEV
userscript.html?id=39f6f996-693e-43bf-a59f-4f7879b515e1:68 SOX: SOX-debug
userscript.html?id=39f6f996-693e-43bf-a59f-4f7879b515e1:68 SOX: true
**Screenshots/GIFs**
If applicable, please add screenshots/GIFs (you can use something like [LICEcap](https://www.cockos.com/licecap/) to make one!) to help explain the problem.

**Environment**
SOX version: 2.6.16DEV
Platform: Tampermonkey

If this is not auto-populated, please state your full browser version, SOX version number, and userscript manager (e.g. Tampermonkey)

---

### Features Enabled 

    undefined

**Comment by shu8** [comment]
@SmartManoj I never managed to reproduce this but looking at the code I can see a case where this might have happened so hopefully it should be working for you now in [dev 2.6.17](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/73588881-a1791f00-44f4-11ea-8c6d-7d9dda55b5b2.png)
still in 2.6.25 DEV
