### ISSUE TITLE
Discovered nice unmentioned feature: "Join internal structures"

### ISSUE THREAD

**Issue by KoolKeith** [soscripted/sox#458]
Hi.
Actually this was the only thing I was looking for, and SOX does it! When saving a thread with Wallabag (with the Addon Wallbagger), everything gets saved, all posts ! TYVM

PS: If somebody wants to reproduce (see for yourself), be aware that Wallabag needs quite a bit of time to setup locally.
PPS: Could we have a custum date format inputbox? For all of Europe its 19.01.20 today :)
---

### Features Enabled 

    ["Appearance-alignBadgesByClass","Appearance-colorAnswerer","Appearance-displayName","Appearance-dragBounty","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Appearance-showTagWikiLinkOnTagPopup","Appearance-hideWelcomeBackMessage","Appearance-hideHowToAskWhenZoomed","Appearance-openImagesAsModals","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-hiddenCommentsIndicator","Comments-onlyShowCommentActionsOnHover","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideJustHotMetaPosts","Sidebar-hideHireMe","Sidebar-hideChatSidebar","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Sidebar-addTagsToHNQs","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-linkedPostsInline","Extras-shareLinksPrivacy","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-hideCertainQuestions","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-openLinksInNewTab","Extras-addOnTopicLinkToSiteSwitcher","Extras-customMagicLinks"]

**Comment by shu8** [comment]
Hi there! Sorry if I've misunderstood your post, but I don't think SOX should be doing anything extra for any other extensions to work! Please could you clarify what you mean? :)

**Comment by KoolKeith** [comment]
Hi.
There are many tools which first prepare (simplify) and then let you read or store web pages in a clean, raw manner. Live webpages are often super bloated with CSS, JS, and deeply nested divs. I guess web developer etiquette should do the opposite (using modern tags like <article>). Well, they don't. Some examples for the counter-measure tools and webservices  are Pocket, Instapaper, printfriendly.com and 100 more.

One of those is wallabag. But it has problems on almost all Forum-Like-Pages. It cannot determine which is the main area of interest. So it often saves nothing, or just the first post, at best. And SOX - magically - changes something in the DOM - willingly or by accident - so that wallabag can now indeed recognize and harvest the whole page. Every post mashed together in one super block! And that's totally cool.
