### ISSUE TITLE
GitHub "New Issue" box isn't editable

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#46]
The autofill feature being discussed in #43 makes the version number show up properly (yay!) but has the side effect of the text box into which I am currently typing being not editable, (boo!) meaning I have to go disable SOX before writing an issue.

**Steps to repro**: Update to 1.0.4DEV and try to make a new issue here at https://github.com/soscripted/sox/issues/new.

**Comment by catb0t** [comment]
It has HTML like:

```html
<textarea name="issue[body]" tabindex="1" id="issue_body" placeholder="Leave a comment" aria-label="Comment body" class="form-control input-contrast comment-form-textarea js-comment-field js-improved-comment-field js-task-list-field js-quick-submit js-size-to-fit js-suggester-field js-quote-selection-target js-session-resumable" style="max-height: 712px; height: 622.222px;" disabled>
```

Not editable:

![notedit](https://cloud.githubusercontent.com/assets/3238748/14393348/905145f0-fd94-11e5-8661-1e1b208cf24f.png)


if you remove the `disabled` at the end of that tag, it magically becomes editable!

![editable](https://cloud.githubusercontent.com/assets/3238748/14393354/9a223940-fd94-11e5-954b-d4c1bd2f77ed.png)

**Comment by shu8** [comment]
@catb0t weird! But repro'ed and looking into it. 

We missed it because we were just looking at the version being added!!

Thanks, again :)

**Comment by shu8** [comment]
@catb0t fixed in latest DEV :+1:
