### ISSUE TITLE
Score of other answers not showing

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#463]
**Describe the bug**
![image](https://user-images.githubusercontent.com/7231077/73518597-c2723f00-4424-11ea-9cb3-9b194d943a4b.png)

Also underline last active answer and accepted answers

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://stackoverflow.com/questions/45552141/configure-autohotkey-to-edit-scripts-with-notepad

**SOX errors logged in console**
Please click 'enable debugging' in the SOX settings dialog; hit F12 on a Stack Exchange site; and copy & paste the contents of the 'console' here

**Expected behaviour**

**Screenshots/GIFs**
If applicable, please add screenshots/GIFs (you can use something like [LICEcap](https://www.cockos.com/licecap/) to make one!) to help explain the problem.

**Environment**
SOX version: 2.6.25DEV
Platform: Tampermonkey

If this is not auto-populated, please state your full browser version, SOX version number, and userscript manager (e.g. Tampermonkey)

---

### Features Enabled 

    undefined

**Comment by double-beep** [comment]
Which feature are you talking about?

**Comment by SmartManoj** [comment]
#375

**Comment by double-beep** [comment]
I am unable to reproduce this bug - scores are showing just fine for me, even in the 'active' tab. Can you try disabling all the other scripts running in the page and see if the bug persists?

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/73585547-3285d100-44c8-11ea-86e8-fdd4ccd5aa8f.png)
Still

**Comment by double-beep** [comment]
Can you also try disabling dark mode? Perhaps it's also related to this one.

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/73590273-9d55fd00-4506-11ea-9ed3-0eeed944899e.png)
still

**Comment by double-beep** [comment]
Huh, that doesn't seem right. What features are you using? And are there any errors in console (press F12)?

**Comment by SmartManoj** [comment]
Default features only ; No errors;

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/73591093-553bd800-4510-11ea-8f5f-01c410aece57.png)
tried stable version too

**Comment by shu8** [comment]
I too am unable to reproduce this.

Please could you enable debugging mode from the SOX settings panel, and then refresh a question page and copy/paste the entire console output in a comment here?

**Comment by SmartManoj** [comment]
> Please could you enable debugging mode from the SOX settings panel, and then refresh a question page and copy/paste the entire console output in a comment here?

Exactly did like that
https://github.com/soscripted/sox/issues/463#issuecomment-581018633

Could you provide a working screenshot in incognito mode?

Since many features are broken, created a support group
https://t.me/joinchat/AAAAAEVKCNt-j8K1acK2hg

**Comment by shu8** [comment]
It works in incognito:

![image](https://user-images.githubusercontent.com/8850830/76255814-bf017d00-6246-11ea-9cfb-01b93e870405.png)

The screenshot you posted earlier of the console doesn't show the full log when debugging mode is enabled. Has the page loaded fully and have any messages been cleared?

I'm looking for something like:

![image](https://user-images.githubusercontent.com/8850830/76255900-e2c4c300-6246-11ea-94cf-6c26eaae3c13.png)

that should come up in the console.

---

Please could you use the SOX Gitter chat: https://gitter.im/soscripted/sox to talk about SOX instead of Telegram.

**Comment by SmartManoj** [comment]
> . Has the page loaded fully and have any messages been cleared?

Yes and No

**Comment by SmartManoj** [comment]
> loaded

**Comment by SmartManoj** [comment]
After a reset, works fine

**Comment by SmartManoj** [comment]
All features were not worked at the time.

**Comment by SmartManoj** [comment]
Clicking save changes works maybe not reset

**Comment by SmartManoj** [comment]
Test
