### ISSUE TITLE
Daily review bar is misaligned

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#466]
The location of the "daily review bar" `Extras-dailyReviewBar` is misaligned:

![image](https://user-images.githubusercontent.com/1776164/74575994-fb8ad300-4f3d-11ea-91a9-925516ed7470.png)

![image](https://user-images.githubusercontent.com/1776164/74576043-28d78100-4f3e-11ea-8e9a-13f47fb11205.png)

Using Google Chrome Version 79.0.3945.130 (Official Build) (32-bit). Performs similarly in Firefox 72.0.2 (64-bit). Running V2.6.25DEV of SOX.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-displayName","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Appearance-showTagWikiLinkOnTagPopup","Appearance-hideWelcomeBackMessage","Appearance-hideHowToAskWhenZoomed","Appearance-openImagesAsModals","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Comments-onlyShowCommentActionsOnHover","Comments-copyCommentMarkdown","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideJustHotMetaPosts","Sidebar-hideHireMe","Sidebar-hideChatSidebar","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Sidebar-addTagsToHNQs","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Chat-scrollChatRoomsList","Voting-betterCSS","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-hideCertainQuestions","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-openLinksInNewTab","Extras-showQuestionStateInSuggestedEditReviewQueue","Extras-addOnTopicLinkToSiteSwitcher","Extras-customMagicLinks"]

**Comment by double-beep** [comment]
SE changed their HTML again - fixed 2 days ago in https://github.com/soscripted/sox/pull/464/commits/f0144dd77fade98de2b996a1468486cedd225542 - install from [here](https://github.com/double-beep/sox/raw/improve_dailyReviewBar/sox.user.js).

**Comment by wgrundlingh** [comment]
That fixed it, thanks!

**Comment by shu8** [comment]
I just merged @double-beep's pull request! Thanks for the bug report too :)
