### ISSUE TITLE
showQuestionStateInSuggestedEditReviewQueue is now natively implemented - Should it be removed?

### ISSUE THREAD

**Issue by double-beep** [soscripted/sox#469]
`showQuestionStateInSuggestedEditReviewQueue` is a feature that uses the API and shows the question's state in the suggested edits queue. However, looks like this is now implemented natively:

![image](https://user-images.githubusercontent.com/38133098/79448588-55655300-7fea-11ea-8006-d48c16d2e334.png)

Should the feature be removed completely or just changed to something like this?

    $(document).on('sox-new-review-post-appeared', () => {
        const $anchor = $('.summary h2 a');
        const $aText = $anchor.html()
        if ($('[class^="standOutDupeCloseMigrated"]').length || !$anchor.length || !$aText.match(/closed|duplicate/)) return;

        $anchor.html($aText.replace(/ \[(closed|duplicate)\]/, ''));
        $anchor.after(`&nbsp;<span class="standOutDupeCloseMigrated-${$aText.match(/closed|duplicate/)[0]}">${$aText.match(/closed|duplicate/)[0]}</span></a>`);
      });

**Comment by shu8** [comment]
Thanks for raising this issue! I think we should remove it and update the `standOutDupeCloseMigrated` feature to now work on /review too!

**Comment by shu8** [comment]
Removed thanks to @double-beep! :)
