### ISSUE TITLE
Example screenshot on README is not as cool as it could be

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#47]
**Installed Version: 1.0.4DEV  |  Environment: Chrome/Tampermonkey**

The screenshot on the README's really out of date. I'd provide one right here to be a nice person, but at least one of the developers has  Mac that takes pretty screenshots with shadowing and stuff.

**Expected Behavior**

The README should have a screenshot that shows the beautiful amazingness that is the current, searchable, lexicographically-sorted options box.

**Actual Behavior**

The screenshot on the README's like, 10 millenia old. Show off your cool project!

**Comment by shu8** [comment]
@catb0t lol, it is on the master branch:

![](https://cloud.githubusercontent.com/assets/12533449/14296194/c732b1b2-fb2d-11e5-9563-1e34b12eada9.png)

... but not on the DEV. will change ASAP

**Comment by shu8** [comment]
@catb0t done :+1:

**Comment by shu8** [comment]
@catb0t BTW none of us uses Macs for our screenshots... :P

**Comment by enki-code** [comment]
I just had to google *lexicographically*.   I took that screen shot, cropped it in ms paint and opened it in pixlr to do the box blur. :)
