### ISSUE TITLE
Employee flag is sometimes added twice on intial page load

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#475]
Windows 7 Home Premium 64 bit, Firefox 78.0.2

Example:

![Screenshot - 15_07_2020 , 20_54_54](https://user-images.githubusercontent.com/7079224/87589944-f0e78c00-c6dd-11ea-9026-279e8c1cfcfa.png)

Hovering over the flags shows that both have been added by SOX.

Refreshing the page  removes the duplicate flag.

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-displayName","Appearance-dragBounty","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Appearance-showTagWikiLinkOnTagPopup","Appearance-hideWelcomeBackMessage","Appearance-hideHowToAskWhenZoomed","Appearance-openImagesAsModals","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Comments-onlyShowCommentActionsOnHover","Comments-copyCommentMarkdown","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-hideChatSidebar","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Sidebar-addTagsToHNQs","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-scrollChatRoomsList","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksPrivacy","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-copyCode","Extras-dailyReviewBar","Extras-openLinksInNewTab","Extras-showQuestionStateInSuggestedEditReviewQueue","Extras-addOnTopicLinkToSiteSwitcher","Extras-customMagicLinks"]

**Comment by double-beep** [comment]
Have you clicked "show more comments"? This is when I've seen this happen, although it shouldn't. It would benefit from a rewrite...

**Comment by shu8** [comment]
Thanks for the bug report! Do you have an example post this happens on?

**Comment by shu8** [comment]
I haven't reproduced this, but did @double-beep's PR in #477 fix this?

That change was released in v.2.6.35 (https://github.com/soscripted/sox/raw/dev/sox.user.js)
