### ISSUE TITLE
Hover text overlaps with quote bar

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#476]
Here is a view of the hover text around the voting buttons when not using SOX:

![hover text over quote without SOX](https://user-images.githubusercontent.com/1776164/87809199-d7466180-c80f-11ea-8d4e-eaf2489fccb8.gif)

Here is a view of the hover text around the voting buttons when SOX is enabled:

![hover text over quote with SOX](https://user-images.githubusercontent.com/1776164/87809365-22607480-c810-11ea-9699-bc9af79b64a7.gif)

I'm using Google Chrome 83.0.4103.116 (Official Build) (32-bit) with Tampermonkey 4.10.

Answer that can be used to replicate this:
  [MWEs and their wrongly assumed place in the question](https://tex.meta.stackexchange.com/a/8609/5764)

**Comment by double-beep** [comment]
What version of SOX are you using? What are the features you have enabled?

**Comment by shu8** [comment]
Thanks for the bug report! I can reproduce this and will try to get a fix out ASAP :)

**Comment by wgrundlingh** [comment]
> What version of SOX are you using? What are the features you have enabled?

Sorry, should have added that: 2.6.29 DEV

**Comment by shu8** [comment]
Should be fixed in [2.6.36 dev](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
