### ISSUE TITLE
Tooltips should be displayed on top, always

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#482]
**Describe the bug**
Tooltip balloons are displayed under tags.

**Expected behaviour**
It would make sense that tooltips are displayed on top (of everything).

**Screenshots/GIFs**
![temp](https://user-images.githubusercontent.com/1776164/97204507-66e69f00-1773-11eb-9f83-7ca8e3b759db.gif)

**Environment**
SOX version: 2.7.0DEV
Platform: Tampermonkey

If this is not auto-populated, please state your full browser version, SOX version number, and userscript manager (e.g. Tampermonkey)

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-displayName","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Appearance-showTagWikiLinkOnTagPopup","Appearance-hideWelcomeBackMessage","Appearance-openImagesAsModals","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Comments-onlyShowCommentActionsOnHover","Comments-copyCommentMarkdown","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideJustHotMetaPosts","Sidebar-hideHireMe","Sidebar-hideChatSidebar","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Chat-scrollChatRoomsList","Voting-betterCSS","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-hideCertainQuestions","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-openLinksInNewTab","Extras-addOnTopicLinkToSiteSwitcher","Extras-customMagicLinks"]

**Comment by shu8** [comment]
Thanks a lot for the bug report! I've reproduced this and will get a fix out ASAP :)

**Comment by shu8** [comment]
Should be fixed in [dev 2.7.2](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
