### ISSUE TITLE
Add mention links for answer

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#484]
**Use case**
https://stackoverflow.com/a/12141511/5033247 -> it mentioned the highest voted answer
So no need to open a new tab.

append an option under every answer using the scores button link

**Comment by shu8** [comment]
Thanks for the feature request. I'm not sure I understand what exactly the feature you're asking for is -- please could you elaborate a bit more?

Please follow the new issue ["Feature Request" template](https://github.com/soscripted/sox/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=) template when making feature requests.

**Comment by SmartManoj** [comment]
To mention one answer in another for the same question

**Comment by shu8** [comment]
I'm sorry, I still don't quite understand what this feature should be.

Please could you open a new issue, following the **[Feature Request template](https://github.com/soscripted/sox/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=)** with more details as prompted by the template?
