### ISSUE TITLE
Remove Diamond on site for mods, keep diamond on other sites

### ISSUE THREAD

**Issue by timaroberts82** [soscripted/sox#488]
The diamond notification for meta posts is handy. However, if a user is a mod on a site, then you get two diamonds. So far as I can tell, options are to either disable it and not use it or have the second diamond.It would be nice to see only one on the mod site and the SOX diamond on non mod sites.

**Use case**
Any site where a user is _not_ a mod

**Comment by shu8** [comment]
@timaroberts82 Thanks for the feature request, and sorry for the extremely delayed response.

If you're still interested in this, would you mind typing `StackExchange.options.user.userType` into your browser console (hit F12 to open it) on a site where you are a moderator and telling me what the number it shows is?

I'm hoping it will be different for moderators, which might make it easier to do this in the userscript! For reference, for me it is `3` on a normal registered user account!

**Comment by shu8** [comment]
It seems like `StackExchange.options.user.isModerator` might also be set for moderators -- please could you try pasting this in too?

**Comment by Timaroberts** [comment]
@shu8 for me `StackExchange.options.user.userType` returns `4` for me on a site where I am a moderator, where elsewhere `userType` returns` 3 `. I installed the update, and it seems to be working fine for me :)   Thanks!

**Comment by shu8** [comment]
That's great! Thanks for letting me know the type!
