### ISSUE TITLE
Settings menu gone

### ISSUE THREAD

**Issue by VulumeCode** [soscripted/sox#494]
**Describe the bug**
The button to open the settings is gone. Noticed it after the april 1 joke page update.

**To Reproduce**
open a stackxxx page 

**SOX errors logged in console**
none

**Expected behaviour**
see a config button to open the menu

**Screenshots/GIFs**
![image](https://user-images.githubusercontent.com/2590984/162482373-9810cab5-b37a-48f5-861c-a6a9c19f1b9c.png)

**Environment**
SOX version: 2.7.0
Platform: Tampermonkey

If this is not auto-populated, please state your full browser version, SOX version number, and userscript manager (e.g. Tampermonkey)

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-displayName","Appearance-dragBounty","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Appearance-showTagWikiLinkOnTagPopup","Appearance-hideWelcomeBackMessage","Appearance-openImagesAsModals","Comments-autoShowCommentImages","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Comments-onlyShowCommentActionsOnHover","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideJustHotMetaPosts","Sidebar-hideHireMe","Sidebar-hideChatSidebar","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Sidebar-addTagsToHNQs","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Chat-scrollChatRoomsList","Voting-betterCSS","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksPrivacy","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-hideCertainQuestions","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-openLinksInNewTab","Extras-addOnTopicLinkToSiteSwitcher","Extras-customMagicLinks"]

**Comment by AmperAndSand** [comment]
Can confirm on Brave 1.37.111 Chromium: 100.0.4896.79 (Official Build) (64-bit) with Violentmonkey and Firefox 99.0 (64-bit) and Tampermonkey.

**Comment by shu8** [comment]
Thanks for reporting this! I can reproduce this and am working on a fix!

**Comment by shu8** [comment]
This should now be fixed in [dev 2.7.12](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)
