### ISSUE TITLE
Mod diamond in the topbar that has notifications of new questions on a site's meta is missing

### ISSUE THREAD

**Issue by AmperAndSand** [soscripted/sox#496]
**Describe the bug**
The mod diamond in the topbar that has notifications of new questions on a site's meta is now missing. Happens in both Chrome & Violentmonkey, and Firefox & Tampermonkey. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any SE site
2. Notice that the mod diamond in the topbar that has notifications of new questions on a site's meta is now missing.

**SOX errors logged in console**
doesn't seem to be any errors

**Expected behaviour**
The mod diamond in the topbar that has notifications of new questions on a site's meta should appear.

**Environment**
SOX version: 2.7.12 DEV
Platform: Chrome & Violentmonkey, and Firefox & Tampermonkey

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-copyCommentsLink","Comments-showCommentScores","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-kbdAndBullets","Flags-flagOutcomeTime","Flags-flagPercentages","Sidebar-linkedToFrom","Voting-disableVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-warnNotLoggedIn","Extras-showMetaReviewCount"]

**Comment by shu8** [comment]
Thanks for the bug report, I can reproduce this. All features related to the topbar are likely broken after SE's changes :/ 

I'll get this fixed ASAP but am unfortunately quite busy over the next few days.

**Comment by shu8** [comment]
This should be fixed now in [dev 2.7.13](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :) 

Sorry for the delay!
