### ISSUE TITLE
No SOX features applied, only settings icon visible

### ISSUE THREAD

**Issue by VulumeCode** [soscripted/sox#498]
Stopped working for a while now. I reinstalled and tried different browser profiles.

Firefox 102.0.1

Tampermonkey 4.17.6161

**Comment by shu8** [comment]
Hi @VulumeCode, thanks for the bug report! I can't reproduce this on FF or Chrome with Tampermonkey.

Can you check to see if you have any other extensions installed? Can you confirm the SOX version you are using? If you 'enable debugging' in the SOX dialog, and then press F12 for the browser console, do you see any errors? 

Thanks for your help!

**Comment by VulumeCode** [comment]
Using SOX 2.8.0

Tried on my home computer Firefox 103.0 (some addons) and Chrome 103.0.5060.134 (only tampermonkey). Both have the same issue. I did see the features appear a few times, but they're gone after page reload. Only happens when I'm not trying, hitting F5 a few dozen times doesn't cause it to reappear once. 

No errors in the console.

**Comment by not-a-ethan** [comment]
@shu8 I am experiencing this also on FF developer edition on v104.0b9. I just tested this with all other extensions and user scripts disabled. The user script version is v2.8.0. I also did not get any errors in the browser console.

**Comment by shu8** [comment]
Would you be able to take a screenshot of the SOX settings dialog?

**Comment by not-a-ethan** [comment]
@shu8 Sure. Let me do that now

**Comment by not-a-ethan** [comment]
@shu8 Just took a screenshot of it in a private window with only this one user script running
![image](https://user-images.githubusercontent.com/92686703/186987695-1a3fe716-21d3-4a1e-a646-29f231dfb51b.png)

**Comment by shu8** [comment]
Thanks @not-a-ethan! Please could you click "Enable debugging" at the bottom, open the browser console (F12), and take a screenshot of anything showing in the console? (or if there's too much stuff, copy/paste instead?)

**Comment by not-a-ethan** [comment]
@shu8 
![image](https://user-images.githubusercontent.com/92686703/186988030-8359b9f2-c6c9-4d9b-85fd-cb3d0228a612.png)

**Comment by shu8** [comment]
Thanks! Hmm, it does seem to be running :/

I see you have the 'add highlighted tags to closed/on hold/...' feature enabled. if you go to https://meta.stackexchange.com right now, do you see this question with the added highlighted orange 'duplicate' tag?

![image](https://user-images.githubusercontent.com/8850830/186988285-1b684a2c-7677-4599-bb0c-65ac252ed71f.png)

**Comment by not-a-ethan** [comment]
@shu8 Dont see anything. I enabled all settings just to see if only some things are broken
![image](https://user-images.githubusercontent.com/92686703/186988555-8f88f022-8ecc-4c1d-a218-91dde5c8e32b.png)

**Comment by shu8** [comment]
Are there any more logs in the console lower down?

**Comment by not-a-ethan** [comment]
![image](https://user-images.githubusercontent.com/92686703/186988694-c28cf4ac-35bd-458f-9584-f15fc9a29fff.png)

**Comment by shu8** [comment]
There should be an option somewhere that seems to be filtering some of the logs -- do you see something like this anywhere? I think 'verbose' might be disabled in your console

![image](https://user-images.githubusercontent.com/8850830/186989392-c7fff455-1be1-4ae2-aa14-89193e7b9a15.png)

**Comment by not-a-ethan** [comment]
Don't see any of that since I'm on Firefox dev edition

![image](https://user-images.githubusercontent.com/92686703/186989613-95d07e6a-c791-4ff2-8f55-9019576fdf4d.png)
![image](https://user-images.githubusercontent.com/92686703/186989626-29d1fc00-6a51-49a3-bf1a-97115ad51a67.png)

**Comment by shu8** [comment]
Hmm, thanks a lot for your help! I'm not sure why this is happening :/ I'll try debugging this a bit more and try to repro it -- thanks for being patient, I'll get back to you ASAP!

**Comment by shu8** [comment]
I just pushed a quick change, please could you try the latest dev version (v2.8.2 dev)? https://github.com/soscripted/sox/raw/dev/sox.user.js

**Comment by not-a-ethan** [comment]
@shu8 Its working now!
![image](https://user-images.githubusercontent.com/92686703/186992233-6636520a-b693-4409-b44d-77c01b76181b.png)
![image](https://user-images.githubusercontent.com/92686703/186992256-9b892e1e-f977-4491-a10c-92fa0a014e87.png)

**Comment by shu8** [comment]
@not-a-ethan That's awesome, thank you so much for bearing with me whilst I debugged this! It turns out this was only affecting FF and the original bug report mentioned it not working in FF and Chrome so I must have overlooked checking in FF as well.

**Comment by shu8** [comment]
@VulumeCode please could you check if the latest dev version is now working for you on FF?

You mentioned it wasn't working in Chrome as well -- is that still the case?

**Comment by VulumeCode** [comment]
It works with FF. Chrome still has the same issue. 

Console dump in Chrome (updated to latest version)

![image](https://user-images.githubusercontent.com/2590984/188227238-69e3ffc0-c9e9-4153-8e2e-ee61ab5612ea.png)

**Comment by shu8** [comment]
@VulumeCode Thanks! It seems like your settings aren't actually saved for some reason. Could you click 'Reset' in the dialog and try getting a new access token when it prompts you and then re-selecting your options (being sure to click 'Save Changes' after choosing your options)?

**Comment by VulumeCode** [comment]
That worked! Since all options were already selected I first unselected all, save changes, reload, select all, save changes, fixed!
