### ISSUE TITLE
Convert Stackoverflow answers link in another answer into bookmarks

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#503]
**Describe the feature you'd like**
In the [answer](https://stackoverflow.com/a/70641605)
Change https://stackoverflow.com/a/70632872/10749567 to "#10749567" in the link.  and a button to the previous position like (Alt + -) in editors.
Or show the answer when hover.

**Use case**
Quick navigation

Related issue: #484

**Comment by shu8** [comment]
Thanks for the feature request.

> Or show the answer when hover.

I believe this is essentially accomplished by the existing "Display linked posts inline by clicking on an arrow" feature:

!["Display linked posts inline by clicking on an arrow" feature demo](https://github.com/soscripted/sox/assets/8850830/a568bd6f-c073-4581-9cc2-d973ea6708f6)
