### ISSUE TITLE
AJAX listeners may be run multiple times for the same event

### ISSUE THREAD

**Issue by yut23** [soscripted/sox#504]
**Describe the bug**
`sox.helpers.addAjaxListener` calls `sox.helpers.runAjaxHooks`, which wraps and replaces `XMLHttpRequest.prototype.open`. This works fine the first time `runAjaxHooks` is called, but upon following calls, it re-wraps itself recursively. Each time this happens, all the listeners will be run one more time when triggered. I first noticed this when tag wiki links started getting duplicated in the tag mouseover popup.

**To reproduce**
1. Enable `Appearance-showTagWikiLinkOnTagPopup` and another feature that uses an AJAX listener on a question page (e.g. `Appearance-dragBounty`, `Appearance-standOutDupeCloseMigrated`)
2. Go to a question
3. Mouse over a tag
4. See multiple tag wiki links (N = number of `addAjaxListener` calls)

**Expected behaviour**
`runAjaxHooks` should remember if it's been run before, and do nothing if so.

**Screenshots/GIFs**
![multiple tag wiki links](https://user-images.githubusercontent.com/522590/233725386-9e57fd0e-ca22-44e4-99d9-90f41d5904b1.png)
![recursive stack trace in devtools](https://user-images.githubusercontent.com/522590/233726984-fd842f7c-10aa-464a-aee9-ba72439da501.png)

**Environment**
Chrome 111.0.5563.146, SOX 2.8.4 DEV, Tampermonkey

**Comment by shu8** [comment]
Thanks for the bug report, and for the detailed investigation!

I'm a bit busy at the moment but will get this fixed as soon as I can!

**Comment by shu8** [comment]
This should now be fixed in [dev 2.8.6](https://github.com/soscripted/sox/raw/dev/sox.user.js) -- thanks again for the detailed investigation! :)
