### ISSUE TITLE
"All settings" checkbox is misaligned

### ISSUE THREAD

**Issue by miken32** [soscripted/sox#506]
This checkbox is out of line in Firefox:

<img width="641" alt="Screenshot 2023-12-20 at 4 33 29 PM" src="https://github.com/soscripted/sox/assets/1329102/aa6bea39-d664-4c72-9450-21b797c24888">

Using Firefox 121.0, and latest dev version of SOX.

**Comment by mezmi** [comment]
I have been out of the loop here for a bit but will try to look at this next week and get it sorted. Will take me bit to get caught back up with everything.
