### ISSUE TITLE
Reply-to-comment button does nothing

### ISSUE THREAD

**Issue by jfcorbett** [soscripted/sox#51]
**Installed Version: 1.0.4 DEV  |  Windows 7/GreaseMonkey/Firefox**

**Expected Behavior**

Clicking reply-to-comment button should open comment dialog and start comment with "@username".

**Actual Behavior**

Clicking reply-to-comment has no detectable effect. 

**Error Logs**

`TypeError: $(...).parents(...).find(...).first(...).find(...).attr(...) is undefined sox.features.js:576:34
`

**Steps to reproduce**

Just clicking the thing.

**Comment by shu8** [comment]
@jfcorbett thanks! will look into it

**Comment by shu8** [comment]
@jfcorbett this should be fixed now. Please can you reinstall v1.0.4 DEV and confirm it is working for you? :)

**Comment by jfcorbett** [comment]
Hereby confirmed!
