### ISSUE TITLE
Canned comment view/edit/delete dialog opens in a weird place

### ISSUE THREAD

**Issue by jfcorbett** [soscripted/sox#52]
**Installed Version: 1.0.4 DEV  |  Environment: Windows 7/Firefox/GreaseMonkey**

**Expected Behavior**

Alt-O opens pre-defined comment view/edit/delete dialog .

**Actual Behavior**
Dialog opens at a semi-sensible place for some page zooms, but:

- At  larger zoom (which I usually use): Dialog opens at top of page, which is usually completely outside the visible area when page is scrolled down to comments section. I initially thought Alt-O did not work at all, because I couldn't see the dialog!

- At smaller zoom: Dialog extends horizontally beyond the screen; more so the smaller the zoom is. 

(Also, would expect pressing Alt-O again to toggle off that dialog. )

**Error Logs**

Nothing of note.

**Steps to reproduce**
Alt-O in comment textbox. Zoom in and out to see effects.

**Comment by enki-code** [comment]
I'm working on rewriting this feature. It has some functional issues as well as UI issues.

**Comment by jfcorbett** [comment]
Note that this has the same target functionality as the existing AutoReviewComments script: http://stackapps.com/questions/2116/autoreviewcomments-pro-forma-comments-for-se

**Comment by enki-code** [comment]
Thanks again for raising this issue, after some discussion we decided to deprecate this feature. 

Sorry if that causes any inconvenience.
