### ISSUE TITLE
Tabular reviewer stats should really get in shape

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#53]
**Installed Version: 1.0.4DEV  |  Environment: Tampermonkey/Chrome**

Tabular reviewer stats aren't very tabular.

**Expected Behavior**

Like this:

![](http://i.stack.imgur.com/exlYN.png)

**Actual Behavior**

Like this:

![stats](https://cloud.githubusercontent.com/assets/3238748/14481575/57c1d9b8-0102-11e6-90c2-d6090d48186a.png)

**Error Logs**

yay, error logs, for once.

```
SOX error: There was an error loading the feature "Appearance-tabularReviewerStats". Please raise an issue on GitHub, and copy the following error log.
VM541:3856 TypeError: Cannot read property '0' of null(…)
content.js:9 content: detected DOMContentLoaded 208efcd9-1c08-4ee5-9407-88132c3f25c3
https://api.stackexchange.com/2.2/posts/undefined?order=desc&sort=activity&…dnSEBb8&key=)2kXF9IR5OHnfGRPDahCVg((&access_token=XXXXXXXX)) Failed to load resource: the server responded with a status of 400 (Bad Request)
https://api.stackexchange.com/2.2/posts/undefined?order=desc&sort=activity&…dnSEBb8&key=)2kXF9IR5OHnfGRPDahCVg((&access_token=XXXXXXXX)) Failed to load resource: the server responded with a status of 400 (Bad Request)
```
I'm not actually sure if I accurately XXX'd the XXX-worthy content in there (pls no hax).

**Steps to reproduce**

Loaded a page like http://stackoverflow.com/review/suggested-edits/11980890, and clicked "more".

**Comment by shu8** [comment]
Think I know why... I'll push a fix ASAP

**Comment by shu8** [comment]
@catb0t should be fixed now. please can you install the latest dev version to confirm?

**Comment by catb0t** [comment]
Yay! It's fixed :D
