### ISSUE TITLE
"Linked" arrows should be deterministic

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#54]
**Installed Version: 1.0.4DEV  |  Environment: Tampermonkey/Chrome**

Feature request: arrow direction shouldn't be chosen by cryptographically secure RNG

**Expected Behavior**

"Linked" arrows shouldn't imply a link in a certain direction when there is none. This isn't a side effect of #40 as it only seems to happen when there's a link in exactly one direction.

**Actual Behavior**

![magic](https://cloud.githubusercontent.com/assets/3238748/14492413/1123ff68-014d-11e6-88c3-43436339cc7d.png)

I linked **to** the "Linked" quesition; the "Linked" question doesn't link **here**.

**Error Logs**

None.

**Steps to reproduce**

The example I have on hand is http://meta.stackexchange.com/q/278270, but it seems to happen with a lot of questions all over the SE network. 

Unfortunately, it's not fully clear to me *how* to reproduce this specifically -- I've only noticed from browsing SE a lot and reading linked questions that it sometimes doesn't match up. (It's a heisenbug -- try to quantify it and it runs away.)

**Comment by shu8** [comment]
that feature is in the process of being rewritten for the other feature-request. so this should be fixed with that.. bit busy atm but should be done by the weekend

**Comment by catb0t** [comment]
@shu8 cool! you needn't rush; sorry if you felt overwhelmed by my slew of bugs, I had been building evidence :P

**Comment by shu8** [comment]
@catb0t should be fixed now... I'm almost done with the rewrite, but this should fix this issue. can you confirm? :)

**Comment by catb0t** [comment]
Yesss, it's fixed! :D
