### ISSUE TITLE
Favourite tags highlight more than I bargained for 

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#55]
**Installed Version: 1.0.4DEV  |  Environment: Tampermonkey/Chrome**

This is the corollary to #48: I don't have any `wildcards*` in my favourite tags, but it's still too greedy.

**Expected Behavior**

Only favourite-highlight and star tags that I've actually favourited.

**Actual Behavior**

Like this:

![greedy2](https://cloud.githubusercontent.com/assets/3238748/14492725/3cd04b4c-014f-11e6-9d7d-def0dcc42378.png)

`[exception-handling]` isn't in my favourite tags, but a lot of questions with that tag also have `[python-3.x]`

Or this:

![greedy](https://cloud.githubusercontent.com/assets/3238748/14492745/610fa30e-014f-11e6-98a7-05f0e74acdfd.png)

`[racket-faq]` isn't in my favourite tags (and no longer exists), but `[racket]` is.

**Error Logs**

None.

**Steps to reproduce**

It's... not really clear what I did to reproduce this exactly; I just screenshotted the ocassions I noted. It doesn't happen all the time, and it's far from an urgent problem, but I thought I'd introduce it anyways.

**Comment by catb0t** [comment]
Here are more examples of this going wrong. I didn't do anything special, just scrolled http://stackoverflow.com.

In this one, `[sicp]` is not a favourite tag but is strongly related to `[scheme]` and `[racket]`.

![greedy3](https://cloud.githubusercontent.com/assets/3238748/14494128/37a4a214-0157-11e6-99cd-216f1344b229.png)

Here, `[csv]`, `[pyenchant]` and `[enchant]` are not in my favourite tags, but are again related to tags in my favourites.
![greedy4](https://cloud.githubusercontent.com/assets/3238748/14494165/66f5743a-0157-11e6-90e9-4356f42b9299.png)

I never noticed behaviour like this before SOX; maybe SO has changed something and this bug report should go to them instead? Or SOX could counteract it, since I don't want tags I haven't favourited to show as favourites.

**Comment by enki-code** [comment]
It's us. I will look into getting this resolved today, if I have time. Looks like we have a lot to work on.

**Comment by shu8** [comment]
@enki-code think I need a word boundary in the regex :/

btw can you check for errors for the other issue with this feature? (see the comment there)

**Comment by enki-code** [comment]
@shu8  I would check to see if the tag has a wild card if it does, then do indexOf, if not, just compare strings and make sure they match.

**Comment by shu8** [comment]
@enki-code I think we could just add a `\b` to the regex:

           for(var i = 0; i<len; i++) {
                if(interesting[i].indexOf('*') != -1) {
                    interesting[i] = interesting[i].replace('*', '.*'); //replace wildcards with regex equivalents
                }
            }
            
            $('.tagged-interesting > .summary > .tags > .post-tag').filter(function(index) {
                for(var i = 0; i<len; i++) {
                    if ($(this).text().match(new RegExp('\b' + interesting[i]))) { //check if it matches the regex (ie. the tag)
                        $(this).append('<i class="fa fa-star" style="margin-left: 5px;display: inline;color: darkblue;"></i>');
                        return true;
                    }
                }        
            }).addClass(highlightClass);

**Comment by shu8** [comment]
ok... so I just read this issue properly... 

I can't actually repro this and see that you said it happened at a random time but i don't think a word boundary regex would actually help in this case...

It's a weird bug though! Maybe try installing the latest dev version and see if anything has (unintentionally) fixed it? ;)

**Comment by catb0t** [comment]
@shu8 Yaaay, it's fiiixed! Also, I *really* love the current styling:

![sidebar](https://cloud.githubusercontent.com/assets/3238748/14565644/110bebd6-02fa-11e6-8d5f-1a95991f90f1.png)

That orange highlight on the left side is literal perfection -- you guys rock :P

**Comment by enki-code** [comment]
@catb0t I found the previous styling for favorites extremely hard for me to read.. Any text on that yellow background and I find my self squinting and reaching for a giant magnifying glass.  

Glad you like the new style.  

I thought about making a formal feature request on meta to ask that the favorite question styling be changed.

**Comment by shu8** [comment]
@enki-code I think you could actually make a feature request for that... I'm pretty sure I've seen posts complaining about the extreme orangeness on SO... I'll see if I can find one

**Comment by catb0t** [comment]
@enki-code  I'd back it with a bounty, as I so often do. :D

**Comment by enki-code** [comment]
@catb0t @shu8 Posting to Meta SE. Some support would be much appreciated :+1: 

https://meta.stackexchange.com/questions/278354/favorite-tag-highlighting
