### ISSUE TITLE
Notifications shouldn't mangle contributors' names

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#56]
**Installed Version: 1.0.4DEV  |  Environment: Tampermonkey/Chrome**

SOX: the latest technology in C++ name-mangling

**Expected Behavior**

The names in the inbox should be the commenters' names :P

**Actual Behavior**

Names in notifications are... wrong. The **top three notifications** were all made by one user, [Alex A. ♦](http://meta.codegolf.stackexchange.com/users/20469/alex-a).

![namemangle](https://cloud.githubusercontent.com/assets/3238748/14535556/6498e04c-023c-11e6-9cc2-eccbb0368dba.png)

The names below those top three are correct.

**Error Logs**

Not errors, but the console logs notification names, which match the rendered content:

```
sox does not currently support get author information for typechat reply
VM904:3005 Asaf R
VM904:3005 P Daddy
VM904:3005 OscarRyz
VM904:3005 derobert
VM904:3005 Antti Haapala
VM904:3005 Geobits
VM904:3005 Filip Haglund
VM904:3005 Patrick Hofman
VM904:3005 Digital Trauma
content.js:9 content: detected DOMContentLoaded 375729dc-d4a3-4e55-9129-1cf2d88cab78
VM904:3005 Joel Harmon
VM904:3005 QPaysTaxes
VM904:3005 downrep_nation
VM904:3005 Dennis
VM904:3005 Won&#39;t
VM904:3005 mbomb007
VM904:3005 msh210
VM904:3005 Digital Trauma
```

**Steps to reproduce**

Not sure. I opened my inbox a few minutes ago and was a little confused. Reloading the page and re-installing SOX don't change anything; moreover I do not recognise these as names that have ever been in my inbox.

**Comment by shu8** [comment]
@catb0t seems to be a problem with the API lookup -- `meta` is Meta SE... will fix by weekend!

**Comment by enki-code** [comment]
@shu8 Is that feature using the API param helper?

**Comment by shu8** [comment]
@enki-code no, I'm actually working on it now. should be able to do it today. 

@catb0t Which site is that notification for?

**Comment by shu8** [comment]
@catb0t can you please reinstall and check whether this is fixed? :)

**Comment by catb0t** [comment]
Fixed! :D

**Comment by catb0t** [comment]
@shu8 it's Code Golf, not that it matters since it's fixed
