### ISSUE TITLE
Favorite tag highlighting when changing pages

### ISSUE THREAD

**Issue by enki-code** [soscripted/sox#57]
**Installed Version: 1.0.4DEV  |  Environment: Tampermonkey/Chrome**

**Expected Behavior**

When the highlight favorite tags feature is enabled the tags should be highlighted when the page loads, when new questions are loaded and when moving to different pages.

**Actual Behavior**

Favorite tags are not being highlighted when transitioning to a different page.

** Info

The questions are likely being loaded via web sockets, I cannot see any active ajax requests when changing pages.  This might be tricky to solve.

![fav-highlighting-pages](https://cloud.githubusercontent.com/assets/12533449/14535724/117c2d6e-0224-11e6-88a4-e889709d5954.gif)

**Comment by shu8** [comment]
@enki-code seems like a GET request to `http://stackoverflow.com/?page=2&pagesize=15&layout=compact&_=1460652389388` is sent, try adding an ajaxComplete() wrap around it..?

**Comment by enki-code** [comment]
I tried running my ajax complete script and it wasn't coming up with anything. Will try again now.

**Comment by shu8** [comment]
@enki-code hmm the ajaxComplete event is fired if you put it in the *console*.

It just doesn't work when we put it in the userscript...

**Comment by enki-code** [comment]
@shu8 I've got it :)

**Comment by enki-code** [comment]
@shu8 I think I may know why.

> If $.ajax() or $.ajaxSetup() is called with the global option set to false, the .ajaxComplete() method will not fire.

**Comment by shu8** [comment]
@enki-code lol yeah I'd checked that already :/

**Comment by shu8** [comment]
@enki-code This should be fixed now. Can you install the latest dev version and confirm? :)

**Comment by enki-code** [comment]
really!  moving the mutation observer to the document!! grrr!! why didn't I think of that!?  

confirmed working.

nicely done!!

**Comment by enki-code** [comment]
I gotta say... that looks really good :)  I really hope they adopt this feature.
