### ISSUE TITLE
Best way to check for complete page load?

### ISSUE THREAD

**Issue by shu8** [soscripted/sox#58]
Is the best method we have for checking whether the page is completely loaded either:

```
$(document).ajaxComplete(function() {

});
```

or...

```

StackExchange.ready(function() {

});
```

or something else?

We need to create a helper function in the form of:

    SOHelper.onPageReady(function() {
         //code to be ran when page is ready
     });

but I'm not sure which of those methods we should use..

**Comment by enki-code** [comment]
StackExchange.ready seems to be working the best for me.  A combination of both is required for some things to work so I don't think we'll really be able to refactor that much.

**Comment by shu8** [comment]
@enki-code that's annoying.. we really need an accurate usable way for everything!! I'll see if I can find anything...

**Comment by catb0t** [comment]
The way it works currently seems pretty nice from *my* end, but I'm also not building the thing.

**Comment by enki-code** [comment]
@catb0t  Feel free to submit pull requests :)

**Comment by enki-code** [comment]
@shu8 I'm not sure we're going to need a helper for this.

Having something like this in the user.js file would solve the problem. 

```
$(function() {
    // document ready
    
    function init(){
        // init
        
        // execute feature functions here
    }

    StackExchange.ready(init());

});
```

Now, any features that require hooking the ajaxComplete can do so from within the feature function and not have to worry about the ready state of the document.

**Comment by shu8** [comment]
@enki-code ah! great idea! SOX itself can load the features after the document is ready!

**Comment by enki-code** [comment]
@shu8 Also, I found that we don't need window.eval for helpers in Greasemonkey if you wait to call them until StackExchange.ready

I'd have to do some more checking, but, we might be able to get rid of those eval statements.

**Comment by shu8** [comment]
@enki-code in Firefox as well? I thought the problem with FF was that all the userscripts run in a sandbox so it can't access window variables...?

**Comment by enki-code** [comment]
Run this in FireFox Greasemonkey, it works. 

```
// ==UserScript==
// @name        Test
// @namespace   test
// @match     *://*.stackoverflow.com/*
// @version     1
// @grant       none
// ==/UserScript==

(function(notify, $, undefined) {
    
    function init() {
        
      alert(StackExchange.options.site.id);
    
    }
    
    StackExchange.ready(init());
    
    

}(window.notify = window.notify || {}, jQuery));
```

**Comment by shu8** [comment]
@enki-code cool! seems like that should work... I'll test it with a modified version of the functions and see if it works properly

**Comment by shu8** [comment]
@enki-code hmm I can't get the StackExchange.ready() to fire in the userscript. I'm trying:

```
StackExchange.ready(function() {
    console.log('ready!');
});
```

just before the `if(isAvailable()) {`, but nothing gets logged...

any ideas?
