### ISSUE TITLE
Eye icon doubles for posts that had been awarded a bounty

### ISSUE THREAD

**Issue by SeinopSys** [soscripted/sox#59]
**Installed Version: 1.0.3  |  Environment: Chrome/Tampermonkey**

**Expected Behavior**

Only one icon should appear.

**Actual Behavior**

2 icons appear instead:
>![](http://i.imgur.com/Rdusg37.png)

**Steps to reproduce**

Visit http://stackoverflow.com/a/8923753/1344955

**Comment by shu8** [comment]
@SeinopSys The eye icon has been replaced with a link next to the flag links called 'notify on edit' in v1.0.4 DEV. so it has been fixed already (unintentionally :P)
