### ISSUE TITLE
Inline comment images

### ISSUE THREAD

**Issue by enki-code** [soscripted/sox#61]
When the *View linked images (to imgur) in comments inline* feature is enabled images should not break the text of the comment but should be displayed after the text.

**Comment by shu8** [comment]
@enki-code the images should, currently, be shown after the link if there is some text in the link, or it replaces the link if the link text is just the URL.

Do you have anywhere where this happens? Because it sounds like a bug..?

**Comment by enki-code** [comment]
If the <link> is placed in the middle of the content, the image would be placed after the link, which in turn breaks the comment.  Not a bug, just a design issue, we just need to detect if there is an image, if so, find the end of the comment, and inject the image there. :)

I'll see if I can find an example.

**Comment by shu8** [comment]
@enki-code ahh ok I get you. I was thinking you were saying something else! no need for an example any more :)

**Comment by shu8** [comment]
fixed in v2.0.0
