### ISSUE TITLE
Contribution workflow

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#65]
Suppose I want to add a feature to SOX.

Here's what I'd do:

1. Fork to http://github.com/catb0t/sox
2. `git clone http://github.com/catb0t/sox`
3. `git checkout dev`
4. \<make changes to sox.features.js\>
5. `git add .`
6. `git commit -m "add new feature: ..."`
7. `git push -u origin master`
8. visit https://github.com/catb0t/sox/raw/dev/sox.user.js to be prompted for a test installation
9. click install, and... nope.

These lines in `sox.user.js`:
```
// @require      https://cdn.rawgit.com/soscripted/sox/v1.0.3/sox.helpers.js
// @require      https://cdn.rawgit.com/soscripted/sox/v1.0.3/sox.enhanced_editor.js
// @require      https://cdn.rawgit.com/soscripted/sox/v1.0.3/sox.features.js
```
are obviously the issue.

The changes I made to the `sox.features.js`  in my repo in step 4 won't be present in the main repo.

Should I change these lines in *my* repo so I can install the script from my own copy for testing? But then I *have* to remember to revert the lines if / when I make a pull request to http://github.com/soscripted/sox, and I'm quite human and I don't think I'd remember consistently and... it just seems messy. 

Am I missing something obvious, or should I just deal with changing the URLs?

**Comment by enki-code** [comment]
@catb0t Sorry about that, yes, it is extremely annoying and will be fixed in the next build.  Simple lack of understanding in the GM documentation :-1:. 

For now, just use local urls for testing. I doubt we'll have time to handle any PR's until after v2.0 is released.

**Comment by shu8** [comment]
@catb0t also, I'm working on rewriting the contributing docs to make it simpler to follow. it will be much easier in v2.0.0 :)

**Comment by shu8** [comment]
@catb0t I've just published the new [Contributing Guidelines](https://github.com/soscripted/sox/wiki/Contributing). Do they clarify how to contribute a bit better now? :) 

V2.0.0 has made it a bit less of a pain to add new features and I hope these notes help! :)

**Comment by enki-code** [comment]
To build upon what @shu8 said: 
**v2.0** solves this completely, we are now using relative URLs for all SOX files. External dependencies will still require a full path. Hope that helps.
