### ISSUE TITLE
 Topbar position is broken on http://meta.askubuntu.com.

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#66]
sox 1.03, Windows 7 64 bit, Firefox 46.0.1, greasemonkey

Topbar position is broken on http://meta.askubuntu.com.

With sox enabled:

![screenshot - 20_05_2016 09_09_45](https://cloud.githubusercontent.com/assets/7079224/15421458/53bd6fa4-1e6b-11e6-8d26-2a58b3c5fd7a.png)

With sox disabled:

![screenshot - 20_05_2016 09_09_16](https://cloud.githubusercontent.com/assets/7079224/15421437/275f22ae-1e6b-11e6-8f0d-641296b29bb8.png)

**Comment by shu8** [comment]
@DavidPostill thanks! will fix in next version :)

**Comment by enki-code** [comment]
@DavidPostill Just to reiterate what @shu8 said, I'll be completely rewriting this feature, it'll work correctly on all sites now and will fix any padding issues.

**Comment by enki-code** [comment]
I've completed the fix for this, it'll be available in the next release.
