### ISSUE TITLE
Layout Bug in Settings

### ISSUE THREAD

**Issue by hinneLinks** [soscripted/sox#67]
**Installed Version: 1.0.3  |  Environment: Firefox 46.0.1 / Greasmonkey 3.8**

**Expected Behavior**
Settings Usable

**Actual Behavior**
Settings not usable, some Settings (Row with Checkbox) is over the Main Site (no Background), some is behind it.
Main Icon is mixed Up with other Icons.
See Screenshot:
![se-sox-bug](https://cloud.githubusercontent.com/assets/15357388/15528186/d3203298-2241-11e6-8d6e-9d66690dcd76.png)

**Error Logs**
I can see two Errors:

https://api.stackexchange.com/2.2/posts/322657?order=desc&sort=activity&site=meta&filter=<<LONG STRING>>&key=<<LONG STRING>>&access_token=undefined
{"error_id":403,"error_message":"`key` is not valid for passed `access_token`, token not found.","error_name":"access_denied"}

Firefox kann keine Verbindung zu dem Server unter wss://qa.sockets.stackexchange.com/ aufbauen.
...h(c){}if(!L){try{L="WebSocket"in window?new WebSocket(s):new MozWebSocket(s)}cat...

(Last Message means, that Firefox couldn't create a connection)

![se-sox-bug-console](https://cloud.githubusercontent.com/assets/15357388/15528326/351bb49e-2243-11e6-9f9d-f2ab025a3d06.png)

**Steps to reproduce**
Install Greasmonkey on FF 46.0.1, Install SOX 1.0.3

Btw, i wasn't able to install the Development/Experimantal Version, Greasemonkey says "Error downloading URL [...URL...] Unkown error"

**Comment by enki-code** [comment]
Looks like the CSS isn't being injected for some reason.

Would you mind installing the following version and see if that works?
https://github.com/soscripted/sox/raw/v1.0.3/sox.user.js

**Comment by hinneLinks** [comment]
Installing from that link didn't work either.
But you mentioning being a CSS Problem, i checked the Network-Panel, it seems my company's proxy is blocking https://rawgit.com/soscripted/sox/dev/sox.css?v=1.0.3d , i guess that's the css thats missing?

I'll talk to my admins to get that site unblocked, hopefully it will work then.
