### ISSUE TITLE
Settings layout shows up as jumbled - getting a 403 error from rawgit.com when accessing CSS

### ISSUE THREAD

**Issue by AmperAndSand** [soscripted/sox#68]
**Installed Version: 1.0.3  |  Environment: Vivaldi 1.2.490.43 64-bit on Windows / Tampermonkey**

**Expected Behavior**
The settings UI should show up properly.

**Actual Behavior**
>How is the feature currently behaving?

The settings layout is all jumbled up (some parts of the page intentionally blurred by me to hide details on the profile):
(thumbnail below links to higher-resolution, original image)
[![screencapture-soxsettingslayoutjumbled](http://i.imgur.com/I92b85Tl.jpg)](http://i.imgur.com/I92b85T.jpg)

Error log (below) is saying that I'm getting a 403 error from rawgit.com when attempting to access a CSS file for SOX. I believe this is a block by CloudFlare. I tried doing the CloudFlare CAPTCHA on rawgit.com and then refreshing my profile page, but the issue persists.

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

`https://rawgit.com/soscripted/sox/dev/sox.css?v=1.0.3d Failed to load resource: the server responded with a status of 403 ()`

**Steps to reproduce**
>What steps did you take to reproduce the issue?
Install SOX 1.0.3, go to profile page on an SE site and have the SOX settings UI load.

**Comment by catb0t** [comment]
This is an issue related to incomplete page loads, I get it sometimes too. Does it always happen? Are you using a VPN / proxy / Tor or something? Do you have some anti-cross-domain-resource-resolvency browser extensions?

**Comment by AmperAndSand** [comment]
I'm currently not able to reproduce the issue. I checked rawgit.com and it appears that my IP address is currently not CloudFlare-blocked. I disabled SOX back then when the issue kept on happening. I just tried it again. Back then, I wasn't using any VPN or proxy nor anti-cross-domain-resource-resolvency browser extensions, AFAIK.

**Comment by shu8** [comment]
it is a problem to do with the CSS not loading properly. In the next version, we've cached the CSS so it should work then. I'll ping you again later today or tomorrow when we release v2.0.0 :)

**Comment by shu8** [comment]
should be fixed in [v2.0.0](https://github.com/soscripted/sox/raw/master/sox.user.js). Please could you install it and try? @AmperAndSand
