### ISSUE TITLE
Warn me when I'm not logged in

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#69]
Sometimes SE randomly logs me out after I've been logged in for a day or two. 

SOX presenting me with a little warning box in the corner like 

> You are **not logged in**. You should **log in** to continue enjoying SE.

would be helpful so I don't have to go through the pain of trying to submit my question / answer / comment and then being redirected to a login page and losing the thing I was writing. SOX could ping SE every 5 minutes or something to see if I am still in session, and warn me if not.

**Comment by shu8** [comment]
Sounds good, I'll see what I can do :)

**Comment by shu8** [comment]
added in [v2.0.0](https://github.com/soscripted/sox/raw/master/sox.user.js). Please install it for more features and loads of bug fixes! :)
