### ISSUE TITLE
Links to job offers getting a unrelated title

### ISSUE THREAD

**Issue by hinneLinks** [soscripted/sox#70]
**Installed Version: 1.0.3  |  Environment: Firefox 47.0.1/Greasemonkey 3.8**

**Expected Behavior**
The rendering of links (parse cross site links) to job offers on stackoverflow.com/jobs don't change at all or shows the title of the job offer:

![so-jobs-link-title-right](https://cloud.githubusercontent.com/assets/15357388/16513142/7d4783ec-3f62-11e6-9ac2-fdab5b7a314e.png)

**Actual Behavior**
Links to jobs have a totally unrelated title:
![so-jobs-link-title-wrong](https://cloud.githubusercontent.com/assets/15357388/16513141/7d4580ba-3f62-11e6-8a86-8c0acf090566.png)

**Error Logs**
None

**Steps to reproduce**
Go to this Question on meta.so and watch the Links with/without sox:

https://meta.stackoverflow.com/questions/316527/can-the-jobs-careers-team-explain-to-employers-the-purpose-of-the-remote-optio?rq=1

**Comment by shu8** [comment]
@hinneLinks thanks, reproduced and fixed. I'll ping you again when this is released (v2.0.0) which should be within the next few days :)

**Comment by shu8** [comment]
fixed in [v2.0.0](https://github.com/soscripted/sox/raw/master/sox.user.js). Please install it for more features and loads of bug fixes! :)
