### ISSUE TITLE
Access Token not working ("not logged in" error)

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#71]
**Installed Version: 2.0.0  |  Environment: undefined**

**Expected Behavior**
>Go to SO to get access token, log in, get access token

**Actual Behavior**
>Go to SO, log in, screen shows that I'm logged in as fixer1234, small message window lower right says I need to log in, no action on access token
Also, every time SU is refreshed, SOX is reloaded and a warning pops up to go to SO to get the access token.  This basically makes SOX unusable.  Had to disable it.

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

```
SOX:  initializing SOX dialog sox.common.js:54:17
SOX:  injecting features into dialog sox.common.js:54:17
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:3:6598
ReferenceError: waitForKeyElements is not defined sox.features.js:1021:17
SOX:  initializing SOX dialog sox.common.js:54:17
SOX:  injecting features into dialog sox.common.js:54:17
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:3:6598
SOX:  Please go to stackoverflow.com to get your access token for certain SOX features sox.common.js:54:17
vwof plugin, exception in ScreenWaveMedia: TypeError: video_data is undefined vwof.js:67:0
ReferenceError: waitForKeyElements is not defined sox.features.js:1021:17
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead. <unknown>
Content Security Policy: The page's settings blocked the loading of a resource at about:blank ("base-uri https://github.com"). <unknown>
Empty string passed to getElementById(). github-06ce76d6a7511ce3a2095752c3575119026281a84f0c9ca9fe739b7317c949c5.js:6:26892
vwof plugin, exception in ScreenWaveMedia: TypeError: video_data is undefined vwof.js:67:0
Empty string passed to getElementById(). frameworks-f2de4c863a487a877150989f965232bacfde178abf9c1963d9f84c5c19916f0c.js:9:20031
Key event not available on GTK2: key="u" modifiers="accel,shift" browser.xul
Key event not available on GTK2: key="u" modifiers="accel shift" browser.xul
Key event not available on GTK2: key="u" modifiers="control shift" browser.xul
Key event not available on some keyboard layouts: key="c" modifiers="accel,alt" browser.xul
Key event not available on some keyboard layouts: key="i" modifiers="accel,alt,shift" browser.xul
Key event not available on some keyboard layouts: key="z" modifiers="accel, alt, shift" browser.xul
TypeError: NetworkError when attempting to fetch resource. <unknown>
TypeError: $node.find(...).eq(...).attr(...) is undefined sox.features.js:1038:32
TypeError: keyset is null bootstrap.js:34:5
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
```

**Steps to reproduce**
>What steps did you take to reproduce the issue?
included above

![so login error](https://cloud.githubusercontent.com/assets/10065766/16542055/3d058626-4066-11e6-8ee0-4af27bf90cc5.png)

**Comment by enki-code** [comment]
@fixer1234 What browser are you using?  I'll look into this today and see what I can figure out. I was unable to repo this ATM.

**Comment by fixer1234** [comment]
@enki-code  same behavior in Firefox 45.2 ESR and Firefox 47.0

**Comment by fixer1234** [comment]
Additional info: thought if I disable features that rely on a token, that might stop the token nagging.  No such luck.  I disabled everything and it still nags for a token on every screen refresh.  So it isn't being driven by a specific feature that needs it.

**Comment by enki-code** [comment]
Thanks for the update. I am working on this now. 
As for the configuration retention, we currently use the GM_ storage which can be a bit tricky.  Each user script has it's own specific settings so when the script is reinstalled the settings get wiped.

The reason we are using the GM_ storage is that the settings are retained after cleaning the local storage and cookies.

I will look into this as well.

**Comment by enki-code** [comment]
Okay, so, I have some updates regarding this issue.

I think I've come up with a solution that should work for everyone.

When the script is installed and ran for the first time it'll redirect the user OR open a new tab to stackexchange.com (if not already there) and present the user with the OAuth dialog, after having been granted access we gather and store the access token (which we are currently doing) and further use of the script will not require any oauth authentication.

We were having trouble trying to figure out the correct flow, and completely forgot about it before releasing. Again, this is our fault, piss poor planning to say the least.

I've got a mockup of the code working right now, just needs a bit more tweaking and I'll get it pushed to v2.0.1, just wanted you to know that I am actively working on this.

**Comment by fixer1234** [comment]
@enki-code, cool!  Looking forward to the next version.  But don't go nuts with some arbitrary, self-imposed deadline.  Include yourself in your priorities.  Just saying.

BTW, was that erroneous "not logged in" message on every page related to this problem or was that something else?

**Comment by enki-code** [comment]
Thank you, I appreciate that. I try to do as much as I can, when I can, this is just a hobby for me. 

In regards to the erroneous  _not logged in_ message, that was something else, it is a new feature that was introduced in 2.0 and is not working correctly.

StackExchange sites have a JavaScript object exposed that we utilize, it exposes variables about the user and the site. I wrote a wrapper around that object to make things easier for us, one of the properties of that wrapper is misbehaving. Basically, in the UserScript we have a `sox.user` object with a property `loggedIn`, this is what is causing that issue and I am investigating this as well.

**Comment by enki-code** [comment]
Sorry this is taking so long, I've been extremely busy at home.  I'll do my best to spend some time working on all these issues this weekend.

**Comment by shu8** [comment]
I may have some time this weekend as well, I do hope I can help get this sorted!

**Comment by shu8** [comment]
@fixer1234 Sorry, again, for the extremely long wait; we've both had other things on our hands.

Please could you try installing [the new file in the `fix` branch](https://github.com/soscripted/sox/raw/fix/sox.user.js) and delete any other `sox.user.js` files you may have. This should hopefully work on FF now.

What should happen:

- you install the script
- go on an SE site
- if you're not on SO, it will open SO in a new tab for me (popup blocker may block this, please allow it)
- you click on the cogs button on SO.com
- a popup will ask you to authorise SOX
- you click confirm and then it should close and no more alerts should come

I'm in the process of fixing other features, but hopefully this fix will at least make the script usable once  more.

Sorry for the time this is taking!

**Comment by fixer1234** [comment]
Moving the information from #85 to here by request.  It relates to the same feature, but the nature of the problem is very different.  I'll leave #85 there and you can delete either this post or #85 as you think appropriate.

**Installed Version: 1.X.X  |  Environment: Chrome/Tampermonkey**
Note: the auto-detection system identified Chrome, but I'm using Firefox (on this system, FF ESR 45.3.0).

**Expected Behavior**
>How do you expect the feature to work?
Not return an error message.


**Actual Behavior**
>How is the feature currently behaving?
It opened a dialog on SO to get a token.  The dialog appeared to work.  When the process was done, it displayed the error message attached below.  The process did log me into SO, and I haven't tested features yet, so I don't know whether there's actually an operational problem.  But the error message looks like SOX thinks so.


**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.



**Steps to reproduce**
>What steps did you take to reproduce the issue?
Followed the steps presented to get a token.
![se error message](https://cloud.githubusercontent.com/assets/10065766/17644899/ee3ef702-6162-11e6-9a5f-5e693ab18736.png)

**Comment by shu8** [comment]
@fixer1234 try to do all this when you are already logged in; this is a known error in the SE API: [Resurfacing bug: “could not parse proxy url” error message](http://stackapps.com/q/6166/26088).

**Comment by fixer1234** [comment]
@shu8, it looks like you fixed the nag problem too well.  Now I can't get it to ask me again to create the token.  I assume the token was not created originally.  Is there a way to verify whether it was or wasn't (and to retrigger signup)?

**Comment by fixer1234** [comment]
@shu8, Tried this again with the new version and being logged into SO.  I started the session after SOX installation at SO (SU was already an open tab when Firefox was reloaded).  I reselected the SOX options from SO.  When I clicked Save Changes, it didn't trigger any token signup activity.

I left SO open and switched to the SU tab.  There, I got the notice about getting the token on SO.  I clicked the consent box and the OK.  The message box closed, but nothing happened.  I went to the SO tab and there was no token-related activity there.  

So I'm assuming I don't have a token at this point (and if the previous v2.0.1 managed to create a token, that didn't survive the SOX removal and re-installation).

**Comment by fixer1234** [comment]
@shu8, Tried this again with the new version and being logged into SO.  I started the session after SOX installation at SO (SU was already an open tab when Firefox was reloaded).  I reselected the SOX options from SO.  When I clicked Save Changes, it didn't trigger any token signup activity.

I left SO open and switched to the SU tab.  There, I got the notice about getting the token on SO.  I clicked the consent box and the OK.  The message box closed, but nothing happened.  I went to the SO tab and there was no token-related activity there.  

Given all of the finicky conditions, (SO open and logged in, no ad blockers on either site, etc.), I just did the whole process from scratch to ensure every condition was met (uninstalled SOX, closed and restarted Firefox, reloaded SOX, opened and logged into both sites, verified no ad blocker, reloaded sites to bring up SOX icons, reselected and saved SOX options).  Got the same behavior described above regarding the token.

So I'm assuming I don't have a token at this point.  Is the token stored with SOX, so removing SOX wipes it (if it's stored separately, any chance the old v2.0.1 stored some corrupted token or flag that's preventing the new version from creating one)?

**Comment by shu8** [comment]
Can you please reinstall [this new version](https://github.com/soscripted/sox/raw/fix/sox.user.js) and go to a question and check the console; you should see a `SOX Access Token: **********************` log there. does it give a token or does it say `false` or `0`?

**Comment by fixer1234** [comment]
@shu8, interesting.  When I loaded the new and improved new SOX, a popup window the size of the token dialog appeared momentarily, I didn't do anything to actually create a token.  I checked the console output, and it gives a long string as a token ID, so I assume that means I magically have a token?  There is no more nag popup or SO tabs being opened, so that's great.

**Comment by shu8** [comment]
@fixer1234 yeah, if you are already logged in and you have previously clicked the 'approve application' button, the popup automatically closes because it knows you've already given permission.

So now this issue should be fixed! :tada: 

The inbox notification issue now seems to be separate :/

**Comment by geekyi** [comment]
Wow, this fixes everything! No more nag dialogs! Why isn't this released as 2.0.1 at least? This is a vital fix.
(Firefox 50.0b3)

**Comment by shu8** [comment]
@geekyi that was my plan last month when this was fixed, but then I got really busy with school work again :( so I couldn't work on it. I've made a few more pushes today with the intention of making this an official release before Monday. 

Hope you understand that both of us don't really have much time so we work on SOX wherever we get some free time! :)

**Comment by geekyi** [comment]
I can understand. Wow lot's of activity here! I'm pretty new to SO and to this userscript. 

From a newbie perspective, the number of features is a bit overwhelming! So I've left things at the defaults (all on). Will see if I can get the time to understand and contribute 😛. Thanks again!

**Comment by shu8** [comment]
@geekyi hehe yeah... we get that a lot :P 

To make it a bit easier, we have a [features wiki page here](https://github.com/soscripted/sox/wiki/Features) which lists all the features. Most of them have a link to a meta question where that feature was requested, so if you're unsure of any features, those links should explain them. Feel free to raise issues here or chat with us [on Gitter in our chat room](https://gitter.im/soscripted/sox?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge), where we'll try our best to get any issues sorted :)

Hopefully you will find SOX really useful when you get to grips with the features! :)
