### ISSUE TITLE
Add a mod diamond to the topbar to alert you of new questions on the site's child-meta

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#76]
**Installed Version: 2.0.0  |  Environment: undefined**

**Expected Behavior**
>How do you expect the feature to work?
Was working in previous version.

**Actual Behavior**
>How is the feature currently behaving?
No diamond in the top bar with this version.

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

**Steps to reproduce**
>What steps did you take to reproduce the issue?
Looked at the top bar.

**Comment by catb0t** [comment]
Which browser? The `Environment: undefined` thing is also a bug, I think

**Comment by fixer1234** [comment]
@catb0t, for me, this is on several versions of Firefox.  I reported a number of issues with v2.0.0 in separate posts and probably should have made each one more complete.

**Comment by catb0t** [comment]
Reproduced on Firefox 47.

**Comment by shu8** [comment]
@fixer1234 @catb0t please could you try installing the [new user.js file in the `fix` branch](https://github.com/soscripted/sox/raw/fix/sox.user.js) and test whether it is now working for you now? thanks :)

**Comment by fixer1234** [comment]
The feature is working in v2.0.1.
