### ISSUE TITLE
Blur or transparentize the top bar's background

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#77]
https://stackapps.com/questions/6968/blur-the-topbar-s-background

This simple little thing is IMO *really* cool and I think it might be cool to have in SOX since we could possibly have adjustable values for blurriness and opaqueness.

**Comment by shu8** [comment]
@catb0t Seems like a cool feature, I'll look into making this one of the custom settings features in SOX :)

**Comment by enki-code** [comment]
@catb0t We've decided to reject this for now and focus on getting things stable.
