### ISSUE TITLE
Add a dropdown of search stuff when I click the "Search Q & A" button

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#78]
> Sometimes I come up with feature ideas in my head and think I should post them here, and then I think, "Hmm, instead of making enki and shu8 do all the work, I should implement it myself" except a) I am a lot busier than I think I am and b) I am a lot less skilled at this browser-DOM thing than I think I am, so I'll leave this here. :)

Perhaps when I click the "Search Q & A" there could be a box drop down from the top bar, sorta like

![searchbox](https://cloud.githubusercontent.com/assets/3238748/16845190/0cfb7f54-49b6-11e6-91e5-560524ccf6fb.png)

<sup>unfinished mockup made possible by the cool software that is [pencil](https://github.com/prikhi/pencil)</sup>
And other stuff from the advanced search tips. 

> tags	[tag]
> exact	"words here"
> author	user:1234
> user:me (yours)
> score	score:3 (3+)
> score:0 (none)
> answers	answers:3 (3+)
> answers:0 (none)
> isaccepted:yes
> hasaccepted:no
> inquestion:1234
> views	views:250
> sections	title:apples
> body:"apples oranges"
> url	url:"*.example.com"
> favorites	infavorites:mine
> infavorites:1234
> status	closed:yes
> duplicate:no
> migrated:no
> wiki:no
> types	is:question
> is:answer
> exclude	-[tag]
> -apples
> 

SE's search is rather lame at times, (can't search for questions with <= n votes, only >= n, etc) but I still think this could be cool. 

Or, instead of buttons and stuff, just make the dropdown have two boxes, one for "Search this SE site" and one for "Search all of Stack Exchange", and the advanced search tips in a reference box (not clickable, just for humans to read) which would be equally as useful with less work.

Thoughts?

**Comment by enki-code** [comment]
I like this idea!! If I were to implement it, it would be as a separate userscript. Thanks for sharing this, I'll see if I can make this happen some time soon. Still a lot going on here, I need to get all the v2.0 issues sorted out.

**Comment by shu8** [comment]
@catb0t by button, are we talking about the search field at the top right of every page?

Sounds like a really cool idea and when I get time I might look into this a bit more :)

**Comment by catb0t** [comment]
Yes, that's what I meant, sorry :D

**Comment by enki-code** [comment]
@catb0t So, @shu8 and I were talking and we've decided to reject this for now. 

Basically, with the current state of SOX adding a feature this large would be a bit unrealistic for us right now.  However, like I said in my first comment, I do like the idea and would like to implement it as its own script.   

Once we got SOX all sorted out and working how we want I will make this for you.
