### ISSUE TITLE
Android.SE-style vote buttons cause blurring / tearing on Chromium + Blink on Skeptics

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#79]
**Installed Version: 2.0.0  |  Environment: Tampermonkey on Vivaldi, Chromium, Google Chrome, any Blink-based rendering engine, *not Firefox***

**Expected Behavior**

> How do you expect the feature to work?

On https://skeptics.stackexchange.com, rolling over vote buttons causes the same animations as on other sites and doesn't cause weird blurring and tearing.

**Actual Behavior**

> How is the feature currently behaving?

Rolling over causes blurring and tearing on the left half of the answer and question post text divs. It's extremely hard to get a screenshot of and my GIF recording software does not like Chrome or Vivaldi very much, but it is quite noticeable to humans.

Look really close right in the center, some letters are cut off because of the tearing:

Not torn:
![screenshot from 2016-07-14 15-16-34](https://cloud.githubusercontent.com/assets/3238748/16853264/ac0a7c94-49d9-11e6-96c7-746327fab13a.png)
Torn:
![screenshot from 2016-07-14 15-16-41](https://cloud.githubusercontent.com/assets/3238748/16853265/ac135efe-49d9-11e6-80c3-fd760b82cec8.png)
Not torn:
![screenshot from 2016-07-14 15-22-44](https://cloud.githubusercontent.com/assets/3238748/16853266/ac226a2a-49d9-11e6-89ab-0a48ca481c1e.png)
Torn:
![screenshot from 2016-07-14 15-22-46](https://cloud.githubusercontent.com/assets/3238748/16853267/ac30895c-49d9-11e6-97e8-c29de0f208c1.png)

**Error Logs**

> SOX errors are logged to the browser console, if possible, please post those here.

None.

**Steps to reproduce**

> What steps did you take to reproduce the issue?
1. Get a Blink-based (or?) Chromium-derived browser. Google Chrome, Chromium, Vivaldi, Opera, etc will suffice.
2. Install SOX, and ensure the "Add extra CSS for voting signs and favourite button (currently only on Android SE)" is checked 
3. Go to https://skeptics.stackexchange.com and click any question
4. Rollover the vote buttons on the question and answers. 
5. Notice the blurring and shifting of the space between the vote buttons and the center of the answer text div

It's highly likely this is actually a bug in Blink or Chromium, but I'll put it here anyways.

_Only on Skeptics_. I don't know what's up with this, I've never seen anything quite like it.

**Comment by shu8** [comment]
@catb0t thanks, it's very weird that it only happens on skeptics.

Skeptics must have *something* different because #83 also only applied to skeptics.

I'll try to see if I can find a reason :/

**Comment by IStoleThePies** [comment]
@shu8 This works, but please don't ask me why:

    betterCSS: function() {
            // Description: For adding the better CSS for the voting buttons and favourite button

            $('.vote-down-off, .vote-down-on, .vote-up-off, .vote-up-on, .star-off, .star-on').addClass('sox-better-css');
            $('head').append('<link rel="stylesheet" href="https://rawgit.com/shu8/SE-Answers_scripts/master/coolMaterialDesignCss.css">');
            $('#hlogo').css({"-webkit-transform": "translate3d(0,0,0)"});
        },

I literally only solved this by fiddling around for two hours and desperately adding whatever CSS properties I could to whatever elements were potentially involved. The result is a working solution that I don't understand at all.

**Comment by shu8** [comment]
@IStoleThePies 😮 I love you. :P 

Done in [dev al](https://github.com/soscripted/sox/raw/dev/sox.user.js)

cc/ @catb0t It's fixed! :D

**Comment by IStoleThePies** [comment]
@shu8 Actually, this might be a better solution, since the current one shifts the logo a bit:

    $('#header').css({'-webkit-transform': 'translateZ(0)'});

**Comment by Sir-Cumference** [comment]
@shu8 Sigh, new problem. If you go to a question on any SE site and zoom in, the logo flickers:

![problem](https://cloud.githubusercontent.com/assets/5375326/24384640/6262f20a-1333-11e7-84a1-e8cbe79065aa.gif)

I think it should be fixed if you replace my solution with `$('#hmenus').css('-webkit-transform', 'translateZ(0)');`. Not actually sure why this works, I just stumbled on it when testing the line of code on other elements. 😆

**Comment by shu8** [comment]
@Sir-Cumference I must have missed this when you posted it!

Thanks for spotting it and fixing it! I'll get this added in ASAP :)

and btw, I find this issue baffling myself as well! random CSS seems to fix it every time 😆

**Comment by shu8** [comment]
@Sir-Cumference added in [dev 2.0.29](https://github.com/soscripted/sox/raw/dev/sox.user.js). Thanks again for the fix! :)
