### ISSUE TITLE
<kbd> tags are being inserted in wrong textarea

### ISSUE THREAD

**Issue by MarcinOrlowski** [soscripted/sox#80]
**Installed Version: 2.0.0  |  Environment: Tampermonkey**

`<kbd>` tags are being inserted in wrong input.

1. go to random question on stackoverflow.com
2. open question for editing and leave it opened
3. scroll down to answer textarea
4. click "kbd" on on its toolbar
5. `<kbd>` will be inserted in question edit text area instead of answer one

**Comment by shu8** [comment]
@MarcinOrlowski Thank you, I have reproduced this and will work on a fix.

I'm really sorry for the time it's taken for me to respond, I've not had much time recently.

**Comment by shu8** [comment]
@MarcinOrlowski I've fixed this in v2.0.1. Please delete the old version you have and reinstall it [using this link](https://github.com/soscripted/sox/raw/fix/sox.user.js) :)
