### ISSUE TITLE
HNQ Attribute filter terms aren't persistent at all

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#81]
**Installed Version: 2.0.0  |  Environment: Tampermonkey**

**Expected Behavior**
>How do you expect the feature to work?

When I set the "Filter the hot network questions by their attributes" terms, tick the box and hit "save", the terms will be in effect and be there next time I open the settings

**Actual Behavior**
>How is the feature currently behaving?

Filters are not saved across refreshes.

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

None.

**Steps to reproduce**
>What steps did you take to reproduce the issue?

Add any text to any of the boxes in "Filter the hot network questions by their attributes" and hit save. The text is gone. If it isn't gone, fully reload the page or browse to a different SE site.

**Comment by shu8** [comment]
@catb0t I don't know whether this was unintentionally fixed in [the new `fix` version](https://github.com/soscripted/sox/raw/fix/sox.user.js), but I can't repro it... can you try installing the new version and testing again please?

**Comment by shu8** [comment]
@catb0t Does this still happen? :)
