### ISSUE TITLE
"Get token" problem

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#85]
**Installed Version: 1.X.X  |  Environment: Chrome/Tampermonkey**
Note: the auto-detection system identified Chrome, but I'm using Firefox (on this system, FF ESR 45.3.0).

**Expected Behavior**
>How do you expect the feature to work?
Not return an error message.

**Actual Behavior**
>How is the feature currently behaving?
It opened a dialog on SO to get a token.  The dialog appeared to work.  When the process was done, it displayed the error message attached below.  The process did log me into SO, and I haven't tested features yet, so I don't know whether there's actually an operational problem.  But the error message looks like SOX thinks so.

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

**Steps to reproduce**
>What steps did you take to reproduce the issue?
Followed the steps presented to get a token.
![se error message](https://cloud.githubusercontent.com/assets/10065766/17644899/ee3ef702-6162-11e6-9a5f-5e693ab18736.png)

**Comment by shu8** [comment]
Seen as this is still part of #71, please could you post an update there and close this please. Too many issues starts getting hard to handle :)
