### ISSUE TITLE
Display linked posts inline with arrow

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#92]
**Installed Version: 1.X.X  |  Environment: Chrome/Tampermonkey**
Note: Firefox not Chrome

**Expected Behavior**
>How do you expect the feature to work?
Not sure if this is working as intended.  Don't remember if this previously was limited to links to the local site.  It does work for local links.

**Actual Behavior**
>How is the feature currently behaving?
Links to posts or users on other SE sites don't get the arrow treatment.  If this is not part of the design behavior, it would be useful to add it to the future features list.

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

**Steps to reproduce**
>What steps did you take to reproduce the issue?

**Comment by shu8** [comment]
This always worked on local links only.

There are no plans to make it work for external links because the use is generally small because if an external link is posted, the context is often different.
