### ISSUE TITLE
Add author's name to notifications in inbox

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#93]
**Installed Version: 1.X.X  |  Environment: Chrome/Tampermonkey**
Note: environment is Firefox (V48.0 in Windows in this case), not Chrome

**Expected Behavior**
>How do you expect the feature to work?
This feature used to work.

**Actual Behavior**
>How is the feature currently behaving?
No author's name included now in inbox notifications.

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

**Steps to reproduce**
>What steps did you take to reproduce the issue?

**Comment by shu8** [comment]
Are there no errors in the console? Please make sure the 'net' tab is enabled as well :)

**Comment by fixer1234** [comment]
@shu8, I was just so excited to see a new version that I jumped in and started testing stuff.  :-)  When I spotted a problem, I used the built-in reporting link.  I assumed that since this was a new version and reflects changes to a lot of stuff, that you would want reporting to start fresh.  But if you want to keep old issues in their old threads, I'll go back and move stuff.  I'll also check the issues you pinged.  

On the console errors, I'll have to find your previous instructions on how to bring that up.  I figured that some of these issues might be things you were already aware of, so additional console errors might not be needed.  Can you just leave a comment on any of the issues where errors would be useful?

BTW, one of the issues I reported doesn't appear in the list.  Maybe someone else reported it (or I did earlier), and it got moved.  It was the feature where the last-seen time of the author is displayed in comments.  I came across a thread where the information did appear, so this looks like another erratic one (works sometimes and not others).  If I spot that issue in the list somewhere, I'll add that information.

**Comment by fixer1234** [comment]
@shu8 , Just went to record me some error messages and lo and behold, the author names are back on the notifications.  Maybe wiping the previous version and installing the new on cleared something and the inbox was waiting to be refreshed.  I'll mark this as closed.

**Comment by fixer1234** [comment]
I installed the newest, newer, new version and the author names are missing again.  Is this something that requires some type of system refresh for them to appear?  If they do reappear, it might be something to advise users about so they don't think it's a bug.  Here's the console output:

```
bg on Updatedbg.js:333:2
Object { status: "loading" }bg.js:334:2
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
bg on Updatedbg.js:333:2
Object { status: "loading", url: "http://superuser.com/questions" }bg.js:334:2
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
bg runtime Object { action: "check_shortcuts" }bg.js:75:5
bg runtime Object { id: 2, index: 1, windowId: 0, selected: true, highlighted: true, active: true, pinned: false, status: "loading", incognito: false, width: 1411, 6 more… }bg.js:76:5
sendRequest:  tab 2 Object { action: "update_shortcuts", msObj: "{"visible":{"enable":true,"key":"V"…" }bg.js:762:3
request end:  check_shortcutsbg.js:307:5
bg on Updatedbg.js:333:2
Object { status: undefined }bg.js:334:2
content script runtime.onMessage:  update_shortcutscontent_script.js:91:2
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.sox.common.js:18
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
SOX:  initializing SOX dialogsox.common.js:63:17
SOX:  injecting features into dialogsox.common.js:63:17
observe: .inbox-dialogsox.common.js:70:13
observe: .commentsox.common.js:70:13
SOX Access Token: CZFS8gYq1CSv9OYdwT7tiw))sox.common.js:46:13
observe: #wmd-redo-buttonsox.common.js:70:13
observe: [id^="wmd-redo-button"]sox.common.js:70:13
observe: .image-upload formsox.common.js:70:13
SOX Access Token: CZFS8gYq1CSv9OYdwT7tiw))sox.common.js:46:13
Array [ "superuser-139892", "superuser-1115827" ]sox.features.js:1326:17
observe: .share-tipsox.common.js:70:13
http://superuser.com/questions : Unable to run script because scripts are blocked internally.(unknown)
not well-formed(unknown)
bg on Updatedbg.js:333:2
Object { status: "complete" }bg.js:334:2
bg on Updatedbg.js:333:2
Object { status: undefined }bg.js:334:2
bg runtime Object { action: "enable_selected" }bg.js:75:5
bg runtime Object { id: 2, index: 1, windowId: 0, selected: true, highlighted: true, active: true, pinned: false, status: "complete", incognito: false, width: 1411, 6 more… }bg.js:76:5
request end:  enable_selectedbg.js:307:5
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.jquery.min.js:3:6598
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/panel.js:3525:3
not well-formedmessages.json:1:1
Error: Could not establish connection. Receiving end does not exist.(unknown)
TypeError: $node.find(...).eq(...).attr(...) is undefinedsox.features.js:1037:32
fire: .inbox-dialogsox.common.js:77:29
bg on Updatedbg.js:333:2
Object { status: undefined }bg.js:334:2
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/panel.js:3525:3
not well-formedmessages.json:1:1
```

The last 7 lines were added after I clicked on the inbox icon to view messages.

**Comment by shu8** [comment]
@fixer1234 Can't see why this should happen, and I can't repro it, however I have made a slight change in  [this v2.0.1a version](https://github.com/soscripted/sox/raw/fix/sox.user.js), so please try installing this.

If it still doesn't work, please paste the console log when 'net' is enabled and also could you add screenshots of the network tab

**Comment by fixer1234** [comment]
Loaded v2.0.1a.  Authors weren't there initially, but I rechecked an hour or two later and they were there.  Maybe needed to wait for some cache to refresh?  Anyway, looks like you fixed it.

**Comment by fixer1234** [comment]
Loaded v2.0.1b and again, the authors don't appear.  It's been probably 5 hr, and unlike the previous installation, they didn't eventually show up.  I tried various things like closing and reopening FF, and refreshing the page, but no effect.  Any way to capture diagnostics?

**Comment by fixer1234** [comment]
Well it's about damn time!  OK, the names magically started appearing in the inbox, again, around 6 hr after installing v2.0.1b.  Will close issue again.
