### ISSUE TITLE
Align badges by their class on user profile pages

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#94]
**Installed Version: 1.X.X  |  Environment: Chrome/Tampermonkey**
Note: Firefox, not Chrome

**Expected Behavior**
>How do you expect the feature to work?
No idea what this new feature is intended to do.

**Actual Behavior**
>How is the feature currently behaving?
The feature doesn't appear to change any behavior.  There was always a selection of sorting/grouping options, one of which was class.  Everything still appears the same.

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

**Steps to reproduce**
>What steps did you take to reproduce the issue?

**Comment by shu8** [comment]
BTW, all features are listed on https://github.com/soscripted/sox/wiki/Features, and they usually have a link to a meta post that describes how they work/what they do.

Does what is described in [this post](http://meta.stackexchange.com/questions/254607/align-badges-by-class) not happen?

**Comment by fixer1234** [comment]
@shu8, thanks for the link.  I never would have guessed that that's what the feature referred to.  So this applies only the user's network profile page?  To answer your question, no.  The badge information is all centered in the column (assuming I'm looking in the right place). 

![soxnetwork profile badges](https://cloud.githubusercontent.com/assets/10065766/17646119/2045bf62-6189-11e6-86a7-42deef259780.png)

**Comment by shu8** [comment]
No, it's supposed to be on a user's per-site profile. eg. http://meta.stackexchange.com/users/811/shog9?tab=topactivity, or http://meta.stackexchange.com/users/260841:

![](http://i.stack.imgur.com/i7F69.png)

Although it might be useful to also do it on the page you screenshotted, but that won't happen until the next few weeks or so :(

**Comment by fixer1234** [comment]
OK.  It isn't quite that neat on mine.

![capture](https://cloud.githubusercontent.com/assets/10065766/17652276/2bcc0158-6246-11e6-86d9-8c8e5f4e564f.PNG)

This isn't a feature that's important to me, I was just reporting what I thought might be an issue.  I don't really care whether it gets fixed, and it could even be just a local quirk.  I'll leave it up to you whether you want to just close this or leave it open and fix it so SOX is more perfect.  If you want to pursue it, I'll be happy to run diagnostics.

**Comment by shu8** [comment]
@fixer1234 lol, I've been a bit *too* trigger-happy closing some of these issues.

I'll keep this open for now, and investigate it a bit more when I get some time :)

**Comment by enki-code** [comment]
@shu8 Looks like an easy fix, a min-width rule on whatever element you're element you're using to separate the badge counts. :)

**Comment by shu8** [comment]
@fixer1234 fixed in v2.0.2 DEV :)
