### ISSUE TITLE
New navigation for StackOveflow(beta feature) - Support

### ISSUE THREAD

**Issue by darkred** [soscripted/sox#97]
**Installed Version: 2.0.0  |  Environment: Firefox 48.0/Greasemonkey 3.8**

I've been testing the [New Navigation for StackOverflow](http://meta.stackexchange.com/questions/256814/new-navigation-for-stack-overflow-is-in-alpha-testing) (beta feature) some months now.
Does SOX (partially) support this feature?
Would it be ok if I reported any issues I notice with the new-nav?

**Comment by shu8** [comment]
@darkred It doesn't officially support it, but we would like to support it so yes, if you see any issues then please do report them! :) It would really help us prepare it for when new-nav gets released to all sites.

However, it may not be at the very top of our list right now (you can see the issues backlog :P)
